// Module ID: 6868
// Function ID: 54362
// Name: AgeRestrictionSource
// Dependencies: [2]

// Module 6868 (AgeRestrictionSource)
const result = require("set").fileFinishedImporting("../discord_common/js/shared/shared-constants/AgeRestrictionSource.tsx");

export const AgeRestrictionSource = { NO_CLASSIFICATION: 0, [0]: "NO_CLASSIFICATION", MANUAL_CLASSIFICATION: 1, [1]: "MANUAL_CLASSIFICATION", AUTOMATED_CLASSIFICATION: 2, [2]: "AUTOMATED_CLASSIFICATION", AGENCY_CLASSIFICATION_ESRB: 3, [3]: "AGENCY_CLASSIFICATION_ESRB", AGENCY_CLASSIFICATION_PEGI: 4, [4]: "AGENCY_CLASSIFICATION_PEGI", DISCORD_CLASSIFICATION: 5, [5]: "DISCORD_CLASSIFICATION", AGENCY_CLASSIFICATION_GOP: 6, [6]: "AGENCY_CLASSIFICATION_GOP", AGENCY_CLASSIFICATION_IGDB: 7, [7]: "AGENCY_CLASSIFICATION_IGDB" };
