// Module ID: 8257
// Function ID: 65114
// Name: BadgeId
// Dependencies: [284214097]

// Module 8257 (BadgeId)
const _module = require(dependencyMap[0]);
const result = _module.fileFinishedImporting("../discord_common/js/shared/shared-constants/BadgeId.tsx");

export const BadgeId = { PREMIUM_TENURE: 1, [1]: "PREMIUM_TENURE", PARTNER: 2, [2]: "PARTNER", CERTIFIED_MODERATOR: 3, [3]: "CERTIFIED_MODERATOR", HYPESQUAD: 4, [4]: "HYPESQUAD", HYPESQUAD_HOUSE_1: 5, [5]: "HYPESQUAD_HOUSE_1", HYPESQUAD_HOUSE_2: 6, [6]: "HYPESQUAD_HOUSE_2", HYPESQUAD_HOUSE_3: 7, [7]: "HYPESQUAD_HOUSE_3", BUG_HUNTER_LEVEL_1: 8, [8]: "BUG_HUNTER_LEVEL_1", BUG_HUNTER_LEVEL_2: 9, [9]: "BUG_HUNTER_LEVEL_2", VERIFIED_DEVELOPER: 10, [10]: "VERIFIED_DEVELOPER", EARLY_SUPPORTER: 11, [11]: "EARLY_SUPPORTER", GUILD_BOOSTER: 12, [12]: "GUILD_BOOSTER", LEGACY_USERNAME: 13, [13]: "LEGACY_USERNAME", QUEST_COMPLETED: 14, [14]: "QUEST_COMPLETED", APRIL_FOOLS_2026: 15, [15]: "APRIL_FOOLS_2026", ORB_PROFILE: 16, [16]: "ORB_PROFILE", GIFTING: 17, [17]: "GIFTING", ACCOUNT_AGE: 18, [18]: "ACCOUNT_AGE", STREAMING: 19, [19]: "STREAMING", GAME_TIME: 20, [20]: "GAME_TIME", GAME_VARIETY: 21, [21]: "GAME_VARIETY", STAFF: 22, [22]: "STAFF" };
