// Module ID: 486
// Function ID: 6305
// Name: set
// Dependencies: []

// Module 486 (set)
const obj = { ACTION_GENRES: new Set([]) };
const set = new Set([]);
obj.ADVENTURE_GENRES = new Set([]);
const set1 = new Set([]);
obj.DRIVING_RACING_GENRES = new Set([]);
const set2 = new Set([]);
obj.MASSIVELY_MULTIPLAYER_GENRES = new Set([]);
const set3 = new Set([]);
obj.ROLE_PLAYING_GENRES = new Set([]);
const set4 = new Set([]);
obj.SHOOTER_GENRES = new Set([]);
const set5 = new Set([]);
obj.SIMULATION_GENRES = new Set(["<string:1862271004>", "<string:1946157084>", "SDG", "gwSn4I", "TiLCgw"]);
const set6 = new Set(["<string:1862271004>", "<string:1946157084>", "SDG", "gwSn4I", "TiLCgw"]);
obj.SPORTS_GENRES = new Set([]);
const set7 = new Set([]);
obj.STRATEGY_GENRES = new Set([false, false, false, false, false, false, false]);
const set8 = new Set([false, false, false, false, false, false, false]);
obj.MISCELLANEOUS_GENRES = new Set([]);
const set9 = new Set([]);
obj.ALL = new Set([]);
const _module = require(dependencyMap[0]);
const result = _module.fileFinishedImporting("../discord_common/js/shared/shared-constants/GameGenres.tsx");

export const GameGenres = { ACTION: 1, [1]: "ACTION", ACTION_RPG: 2, [2]: "ACTION_RPG", BRAWLER: 3, [3]: "BRAWLER", HACK_AND_SLASH: 4, [4]: "HACK_AND_SLASH", PLATFORMER: 5, [5]: "PLATFORMER", STEALTH: 6, [6]: "STEALTH", SURVIVAL: 7, [7]: "SURVIVAL", ADVENTURE: 8, [8]: "ADVENTURE", ACTION_ADVENTURE: 9, [9]: "ACTION_ADVENTURE", METROIDVANIA: 10, [10]: "METROIDVANIA", OPEN_WORLD: 11, [11]: "OPEN_WORLD", PSYCHOLOGICAL_HORROR: 12, [12]: "PSYCHOLOGICAL_HORROR", SANDBOX: 13, [13]: "SANDBOX", SURVIVAL_HORROR: 14, [14]: "SURVIVAL_HORROR", VISUAL_NOVEL: 15, [15]: "VISUAL_NOVEL", DRIVING_RACING: 16, [16]: "DRIVING_RACING", VEHICULAR_COMBAT: 17, [17]: "VEHICULAR_COMBAT", MASSIVELY_MULTIPLAYER: 18, [18]: "MASSIVELY_MULTIPLAYER", MMORPG: 19, [19]: "MMORPG", ROLE_PLAYING: 20, [20]: "ROLE_PLAYING", DUNGEON_CRAWLER: 21, [21]: "DUNGEON_CRAWLER", ROGUELIKE: 22, [22]: "ROGUELIKE", SHOOTER: 23, [23]: "SHOOTER", LIGHT_GUN: 24, [24]: "LIGHT_GUN", SHOOT_EM_UP: 25, [25]: "SHOOT_EM_UP", FPS: 26, [26]: "FPS", DUAL_JOYSTICK_SHOOTER: 27, [27]: "DUAL_JOYSTICK_SHOOTER", SIMULATION: 28, [28]: "SIMULATION", FLIGHT_SIMULATOR: 29, [29]: "FLIGHT_SIMULATOR", TRAIN_SIMULATOR: 30, [30]: "TRAIN_SIMULATOR", LIFE_SIMULATOR: 31, [31]: "LIFE_SIMULATOR", FISHING: 32, [32]: "FISHING", SPORTS: 33, [33]: "SPORTS", BASEBALL: 34, [34]: "BASEBALL", BASKETBALL: 35, [35]: "BASKETBALL", BILLIARDS: 36, [36]: "BILLIARDS", BOWLING: 37, [37]: "BOWLING", BOXING: 38, [38]: "BOXING", FOOTBALL: 39, [39]: "FOOTBALL", GOLF: 40, [40]: "GOLF", HOCKEY: 41, [41]: "HOCKEY", SKATEBOARDING_SKATING: 42, [42]: "SKATEBOARDING_SKATING", SNOWBOARDING_SKIING: 43, [43]: "SNOWBOARDING_SKIING", SOCCER: 44, [44]: "SOCCER", TRACK_FIELD: 45, [45]: "TRACK_FIELD", SURFING_WAKEBOARDING: 46, [46]: "SURFING_WAKEBOARDING", WRESTLING: 47, [47]: "WRESTLING", STRATEGY: 48, [48]: "STRATEGY", FOUR_X: 49, [49]: "FOUR_X", ARTILLERY: 50, [50]: "ARTILLERY", RTS: 51, [51]: "RTS", TOWER_DEFENSE: 52, [52]: "TOWER_DEFENSE", TURN_BASED_STRATEGY: 53, [53]: "TURN_BASED_STRATEGY", WARGAME: 54, [54]: "WARGAME", MOBA: 55, [55]: "MOBA", FIGHTING: 56, [56]: "FIGHTING", PUZZLE: 57, [57]: "PUZZLE", CARD_GAME: 58, [58]: "CARD_GAME", EDUCATION: 59, [59]: "EDUCATION", FITNESS: 60, [60]: "FITNESS", GAMBLING: 61, [61]: "GAMBLING", MUSIC_RHYTHM: 62, [62]: "MUSIC_RHYTHM", PARTY_MINI_GAME: 63, [63]: "PARTY_MINI_GAME", PINBALL: 64, [64]: "PINBALL", TRIVIA_BOARD_GAME: 65, [65]: "TRIVIA_BOARD_GAME", TACTICAL: 66, [66]: "TACTICAL", INDIE: 67, [67]: "INDIE", ARCADE: 68, [68]: "ARCADE", POINT_AND_CLICK: 69, [69]: "POINT_AND_CLICK" };
export const GameGenresSets = obj;
