// Module ID: 663
// Function ID: 8031
// Name: set
// Dependencies: [2]

// Module 663 (set)
import set from "set";

const obj = {};
let set = new Set([1, 2, 3, 4, 5, 21, 35, 56, 57, 64, 68]);
obj.UNDELETABLE = set;
obj.GUILD_DISCOVERY_STATUS = new Set([14, 15, 16, 17]);
const set1 = new Set([14, 15, 16, 17]);
obj.USER_MESSAGE = new Set([0, 19, 20, 23, 26, 41, 45, 47, 68]);
const set2 = new Set([0, 19, 20, 23, 26, 41, 45, 47, 68]);
obj.NOTIFIABLE_SYSTEM_MESSAGE = new Set([7, 22, 35, 46, 64]);
const set3 = new Set([7, 22, 35, 46, 64]);
obj.REPLYABLE = new Set([0, 7, 19, 20, 23, 24, 25, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 45, 46]);
const set4 = new Set([0, 7, 19, 20, 23, 24, 25, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 45, 46]);
obj.FORWARDABLE = new Set([0, 19, 20, 23, 35]);
const set5 = new Set([0, 19, 20, 23, 35]);
obj.REFERENCED_MESSAGE_AVAILABLE = new Set([19, 21, 23]);
const set6 = new Set([19, 21, 23]);
obj.AVAILABLE_IN_GUILD_FEED = new Set([0, 19]);
const set7 = new Set([0, 19]);
obj.DEADCHAT_PROMPTS = new Set([40, 42]);
const set8 = new Set([40, 42]);
obj.NON_COLLAPSIBLE = new Set([24]);
const set9 = new Set([24]);
obj.NON_PARSED = new Set([4, 12, 18, 27, 28, 31]);
const set10 = new Set([4, 12, 18, 27, 28, 31]);
obj.AUTOMOD_INCIDENT_ACTIONS = new Set([36, 37, 38, 39]);
const set11 = new Set([36, 37, 38, 39]);
obj.SELF_MENTIONABLE_SYSTEM = new Set([46]);
const set12 = new Set([46]);
obj.SCHEDULABLE = new Set([0, 19]);
const set13 = new Set([0, 19]);
obj.SILENTLY_CREATABLE = new Set([67]);
const result = set.fileFinishedImporting("../discord_common/js/shared/shared-constants/MessageTypes.tsx");

export const MessageTypes = { DEFAULT: 0, [0]: "DEFAULT", RECIPIENT_ADD: 1, [1]: "RECIPIENT_ADD", RECIPIENT_REMOVE: 2, [2]: "RECIPIENT_REMOVE", CALL: 3, [3]: "CALL", CHANNEL_NAME_CHANGE: 4, [4]: "CHANNEL_NAME_CHANGE", CHANNEL_ICON_CHANGE: 5, [5]: "CHANNEL_ICON_CHANGE", CHANNEL_PINNED_MESSAGE: 6, [6]: "CHANNEL_PINNED_MESSAGE", USER_JOIN: 7, [7]: "USER_JOIN", GUILD_BOOST: 8, [8]: "GUILD_BOOST", GUILD_BOOST_TIER_1: 9, [9]: "GUILD_BOOST_TIER_1", GUILD_BOOST_TIER_2: 10, [10]: "GUILD_BOOST_TIER_2", GUILD_BOOST_TIER_3: 11, [11]: "GUILD_BOOST_TIER_3", CHANNEL_FOLLOW_ADD: 12, [12]: "CHANNEL_FOLLOW_ADD", GUILD_STREAM: 13, [13]: "GUILD_STREAM", GUILD_DISCOVERY_DISQUALIFIED: 14, [14]: "GUILD_DISCOVERY_DISQUALIFIED", GUILD_DISCOVERY_REQUALIFIED: 15, [15]: "GUILD_DISCOVERY_REQUALIFIED", GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING: 16, [16]: "GUILD_DISCOVERY_GRACE_PERIOD_INITIAL_WARNING", GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING: 17, [17]: "GUILD_DISCOVERY_GRACE_PERIOD_FINAL_WARNING", THREAD_CREATED: 18, [18]: "THREAD_CREATED", REPLY: 19, [19]: "REPLY", CHAT_INPUT_COMMAND: 20, [20]: "CHAT_INPUT_COMMAND", THREAD_STARTER_MESSAGE: 21, [21]: "THREAD_STARTER_MESSAGE", GUILD_INVITE_REMINDER: 22, [22]: "GUILD_INVITE_REMINDER", CONTEXT_MENU_COMMAND: 23, [23]: "CONTEXT_MENU_COMMAND", AUTO_MODERATION_ACTION: 24, [24]: "AUTO_MODERATION_ACTION", ROLE_SUBSCRIPTION_PURCHASE: 25, [25]: "ROLE_SUBSCRIPTION_PURCHASE", INTERACTION_PREMIUM_UPSELL: 26, [26]: "INTERACTION_PREMIUM_UPSELL", STAGE_START: 27, [27]: "STAGE_START", STAGE_END: 28, [28]: "STAGE_END", STAGE_SPEAKER: 29, [29]: "STAGE_SPEAKER", STAGE_RAISE_HAND: 30, [30]: "STAGE_RAISE_HAND", STAGE_TOPIC: 31, [31]: "STAGE_TOPIC", GUILD_APPLICATION_PREMIUM_SUBSCRIPTION: 32, [32]: "GUILD_APPLICATION_PREMIUM_SUBSCRIPTION", PRIVATE_CHANNEL_INTEGRATION_ADDED: 33, [33]: "PRIVATE_CHANNEL_INTEGRATION_ADDED", PRIVATE_CHANNEL_INTEGRATION_REMOVED: 34, [34]: "PRIVATE_CHANNEL_INTEGRATION_REMOVED", PREMIUM_REFERRAL: 35, [35]: "PREMIUM_REFERRAL", GUILD_INCIDENT_ALERT_MODE_ENABLED: 36, [36]: "GUILD_INCIDENT_ALERT_MODE_ENABLED", GUILD_INCIDENT_ALERT_MODE_DISABLED: 37, [37]: "GUILD_INCIDENT_ALERT_MODE_DISABLED", GUILD_INCIDENT_REPORT_RAID: 38, [38]: "GUILD_INCIDENT_REPORT_RAID", GUILD_INCIDENT_REPORT_FALSE_ALARM: 39, [39]: "GUILD_INCIDENT_REPORT_FALSE_ALARM", GUILD_DEADCHAT_REVIVE_PROMPT: 40, [40]: "GUILD_DEADCHAT_REVIVE_PROMPT", CUSTOM_GIFT: 41, [41]: "CUSTOM_GIFT", GUILD_GAMING_STATS_PROMPT: 42, [42]: "GUILD_GAMING_STATS_PROMPT", PURCHASE_NOTIFICATION: 44, [44]: "PURCHASE_NOTIFICATION", VOICE_HANGOUT_INVITE: 45, [45]: "VOICE_HANGOUT_INVITE", POLL_RESULT: 46, [46]: "POLL_RESULT", CHANGELOG: 47, [47]: "CHANGELOG", NITRO_NOTIFICATION: 48, [48]: "NITRO_NOTIFICATION", CHANNEL_LINKED_TO_LOBBY: 49, [49]: "CHANNEL_LINKED_TO_LOBBY", GIFTING_PROMPT: 50, [50]: "GIFTING_PROMPT", IN_GAME_MESSAGE_NUX: 51, [51]: "IN_GAME_MESSAGE_NUX", GUILD_JOIN_REQUEST_ACCEPT_NOTIFICATION: 52, [52]: "GUILD_JOIN_REQUEST_ACCEPT_NOTIFICATION", GUILD_JOIN_REQUEST_REJECT_NOTIFICATION: 53, [53]: "GUILD_JOIN_REQUEST_REJECT_NOTIFICATION", GUILD_JOIN_REQUEST_WITHDRAWN_NOTIFICATION: 54, [54]: "GUILD_JOIN_REQUEST_WITHDRAWN_NOTIFICATION", HD_STREAMING_UPGRADED: 55, [55]: "HD_STREAMING_UPGRADED", CHAT_WALLPAPER_SET: 56, [56]: "CHAT_WALLPAPER_SET", CHAT_WALLPAPER_REMOVED: 57, [57]: "CHAT_WALLPAPER_REMOVED", REPORT_TO_MOD_DELETED_MESSAGE: 58, [58]: "REPORT_TO_MOD_DELETED_MESSAGE", REPORT_TO_MOD_TIMEOUT_USER: 59, [59]: "REPORT_TO_MOD_TIMEOUT_USER", REPORT_TO_MOD_KICK_USER: 60, [60]: "REPORT_TO_MOD_KICK_USER", REPORT_TO_MOD_BAN_USER: 61, [61]: "REPORT_TO_MOD_BAN_USER", REPORT_TO_MOD_CLOSED_REPORT: 62, [62]: "REPORT_TO_MOD_CLOSED_REPORT", EMOJI_ADDED: 63, [63]: "EMOJI_ADDED", PREMIUM_GROUP_INVITE: 64, [64]: "PREMIUM_GROUP_INVITE", VOICE_SESSION: 65, [65]: "VOICE_SESSION", GUILD_BOOST_UPSELL: 66, [66]: "GUILD_BOOST_UPSELL", FRIEND_REQUEST_ACCEPTED: 67, [67]: "FRIEND_REQUEST_ACCEPTED", MEDIA_MENTION_MESSAGE: 68, [68]: "MEDIA_MENTION_MESSAGE" };
export const MessageTypesSets = obj;
