// Module ID: 672
// Function ID: 8272
// Name: SKUFlags
// Dependencies: [284214097]

// Module 672 (SKUFlags)
const _module = require(dependencyMap[0]);
const result = _module.fileFinishedImporting("../discord_common/js/shared/shared-constants/SKUFlags.tsx");

export const SKUFlags = { PREMIUM_PURCHASE: 1, [1]: "PREMIUM_PURCHASE", HAS_FREE_PREMIUM_CONTENT: 2, [2]: "HAS_FREE_PREMIUM_CONTENT", AVAILABLE: 4, [4]: "AVAILABLE", PREMIUM_AND_DISTRIBUTION: 8, [8]: "PREMIUM_AND_DISTRIBUTION", STICKER: 16, [16]: "STICKER", GUILD_ROLE: 32, [32]: "GUILD_ROLE", AVAILABLE_FOR_SUBSCRIPTION_GIFTING: 64, [64]: "AVAILABLE_FOR_SUBSCRIPTION_GIFTING", APPLICATION_GUILD_SUBSCRIPTION: 128, [128]: "APPLICATION_GUILD_SUBSCRIPTION", APPLICATION_USER_SUBSCRIPTION: 256, [256]: "APPLICATION_USER_SUBSCRIPTION", CREATOR_MONETIZATION: 512, [512]: "CREATOR_MONETIZATION", GUILD_PRODUCT: 1024, [1024]: "GUILD_PRODUCT", AVAILABLE_FOR_APPLICATION_GIFTING: 2048, [2048]: "AVAILABLE_FOR_APPLICATION_GIFTING", AVAILABLE_ON_ANDROID: 4096, [4096]: "AVAILABLE_ON_ANDROID", AVAILABLE_ON_IOS: 8192, [8192]: "AVAILABLE_ON_IOS", STAFF_CREATE_SUBSCRIPTION_GROUP_LISTING_MASK: 384, [384]: "STAFF_CREATE_SUBSCRIPTION_GROUP_LISTING_MASK", STOREFRONT_UPDATE_MASK: 12288, [12288]: "STOREFRONT_UPDATE_MASK" };
