// Module ID: 682
// Function ID: 683
// Dependencies: [683, 685, 717, 725, 721, 705, 731, 722, 727, 733, 726, 704, 728, 734, 713, 712, 706, 690, 710, 708, 737, 740, 741, 756, 760, 743, 761, 762, 752, 763, 736, 735, 759, 720, 764, 732, 766, 767, 684, 709, 701, 768, 769, 770, 771, 772, 723, 773, 774, 775, 776, 778, 780, 783, 786, 787, 788, 790, 791, 792, 793, 794, 796, 797, 798, 799, 800, 814, 745, 815, 816, 750, 818, 819, 820, 822, 827, 829, 834, 836, 838, 839, 842, 844, 845, 846, 795, 777, 848, 693, 702, 849, 686, 784, 850, 714, 716, 715, 692, 852, 689, 695, 853, 730, 687, 789, 742, 785, 855, 698, 856, 697, 851, 738, 703, 699, 854, 729, 754, 744, 700, 765, 758, 857, 858, 694, 859, 860, 691, 739, 779, 861, 696]

// Module 682
import _mod683 from "module_683" /* 683 */;
import spanToJSON from "spanToJSON" /* 684 */;
import unwrapScopeFromWeakRef from "unwrapScopeFromWeakRef" /* 685 */;
import _mod686 from "module_686" /* 686 */;
import _mod687 from "module_687" /* 687 */;
import consoleSandbox from "consoleSandbox" /* 689 */;
import _mod690 from "module_690" /* 690 */;
import SDK_VERSION from "SDK_VERSION" /* 691 */;
import _mod692 from "module_692" /* 692 */;
import _htmlElementAsString from "_htmlElementAsString" /* 693 */;
import generateSpanId from "generateSpanId" /* 694 */;
import uuid4 from "uuid4" /* 695 */;
import safeDateNow from "safeDateNow" /* 696 */;
import _mod697 from "module_697" /* 697 */;
import _mod698 from "module_698" /* 698 */;
import _mod699 from "module_699" /* 699 */;
import MAX_BAGGAGE_STRING_LENGTH from "MAX_BAGGAGE_STRING_LENGTH" /* 700 */;
import _mod701 from "module_701" /* 701 */;
import _mod702 from "module_702" /* 702 */;
import dateTimestampInSeconds from "dateTimestampInSeconds" /* 703 */;
import SEMANTIC_ATTRIBUTE_CACHE_HIT from "SEMANTIC_ATTRIBUTE_CACHE_HIT" /* 704 */;
import SPAN_STATUS_ERROR from "SPAN_STATUS_ERROR" /* 705 */;
import _mod706 from "module_706" /* 706 */;
import Scope from "Scope" /* 708 */;
import _getSpanForScope from "_getSpanForScope" /* 709 */;
import closeSession from "closeSession" /* 710 */;
import _mod712 from "module_712" /* 712 */;
import _mod713 from "module_713" /* 713 */;
import instrumentError from "instrumentError" /* 714 */;
import _mod715 from "module_715" /* 715 */;
import instrumentUnhandledRejection from "instrumentUnhandledRejection" /* 716 */;
import TRACING_DEFAULTS from "TRACING_DEFAULTS" /* 717 */;
import _mod720 from "module_720" /* 720 */;
import SentryNonRecordingSpan from "SentryNonRecordingSpan" /* 721 */;
import _mod722 from "module_722" /* 722 */;
import DEFAULT_ENVIRONMENT from "DEFAULT_ENVIRONMENT" /* 723 */;
import _mod725 from "module_725" /* 725 */;
import logSpanEnd from "logSpanEnd" /* 726 */;
import timedEventsToMeasurements from "timedEventsToMeasurements" /* 727 */;
import _enhanceEventWithSdkInfo from "_enhanceEventWithSdkInfo" /* 728 */;
import forEachEnvelopeItem from "forEachEnvelopeItem" /* 729 */;
import normalize from "normalize" /* 730 */;
import _mod731 from "module_731" /* 731 */;
import _mod732 from "module_732" /* 732 */;
import sampleSpan from "sampleSpan" /* 733 */;
import captureCheckIn from "captureCheckIn" /* 734 */;
import applyClientOptions from "applyClientOptions" /* 735 */;
import mergeScopeData from "mergeScopeData" /* 736 */;
import _notifyEventProcessors from "_notifyEventProcessors" /* 737 */;
import SyncPromise from "SyncPromise" /* 738 */;
import _mod739 from "module_739" /* 739 */;
import _mod740 from "module_740" /* 740 */;
import _mod741 from "module_741" /* 741 */;
import SENTRY_BUFFER_FULL_ERROR from "SENTRY_BUFFER_FULL_ERROR" /* 742 */;
import DEFAULT_TRANSPORT_BUFFER_SIZE from "DEFAULT_TRANSPORT_BUFFER_SIZE" /* 743 */;
import disabledUntil from "disabledUntil" /* 744 */;
import _INTERNAL_captureSerializedLog from "_INTERNAL_captureSerializedLog" /* 745 */;
import _INTERNAL_captureSerializedMetric from "_INTERNAL_captureSerializedMetric" /* 750 */;
import setupIntegration from "setupIntegration" /* 752 */;
import _mod754 from "module_754" /* 754 */;
import _mod756 from "module_756" /* 756 */;
import exceptionFromError from "exceptionFromError" /* 758 */;
import _mod759 from "module_759" /* 759 */;
import _mod760 from "module_760" /* 760 */;
import MIN_DELAY from "MIN_DELAY" /* 761 */;
import eventFromEnvelope from "eventFromEnvelope" /* 762 */;
import _INTERNAL_clearAiProviderSkips from "_INTERNAL_clearAiProviderSkips" /* 763 */;
import _mod764 from "module_764" /* 764 */;
import _mod765 from "module_765" /* 765 */;
import parameterize from "parameterize" /* 766 */;
import _mod767 from "module_767" /* 767 */;
import applySdkMetadata from "applySdkMetadata" /* 768 */;
import _mod769 from "module_769" /* 769 */;
import _mod770 from "module_770" /* 770 */;
import _mod771 from "module_771" /* 771 */;
import winterCGHeadersToDict from "winterCGHeadersToDict" /* 772 */;
import _mod773 from "module_773" /* 773 */;
import _mod774 from "module_774" /* 774 */;
import _mergeOptions from "_mergeOptions" /* 775 */;
import linkedErrorsIntegration from "linkedErrorsIntegration" /* 776 */;
import aggregateExceptionsFromError from "aggregateExceptionsFromError" /* 777 */;
import moduleMetadataIntegration from "moduleMetadataIntegration" /* 778 */;
import _mod779 from "module_779" /* 779 */;
import requestDataIntegration from "requestDataIntegration" /* 780 */;
import captureConsoleIntegration from "captureConsoleIntegration" /* 783 */;
import instrumentConsole from "instrumentConsole" /* 784 */;
import severityLevelFromString from "severityLevelFromString" /* 785 */;
import _shouldDropEvent from "_shouldDropEvent" /* 786 */;
import _extractErrorData from "_extractErrorData" /* 787 */;
import generateIteratee from "generateIteratee" /* 788 */;
import resolve from "resolve" /* 789 */;
import markAsInstrumented from "markAsInstrumented" /* 790 */;
import flattenIssue from "flattenIssue" /* 791 */;
import thirdPartyErrorFilterIntegration from "thirdPartyErrorFilterIntegration" /* 792 */;
import _mod793 from "module_793" /* 793 */;
import featureFlagsIntegration from "featureFlagsIntegration" /* 794 */;
import _INTERNAL_FLAG_BUFFER_SIZE from "_INTERNAL_FLAG_BUFFER_SIZE" /* 795 */;
import growthbookIntegration from "growthbookIntegration" /* 796 */;
import profiler from "profiler" /* 797 */;
import _addTracingHeadersToFetchRequest from "_addTracingHeadersToFetchRequest" /* 798 */;
import trpcMiddleware from "trpcMiddleware" /* 799 */;
import _mod800 from "module_800" /* 800 */;
import captureFeedback from "captureFeedback" /* 814 */;
import fmt from "fmt" /* 815 */;
import consoleLoggingIntegration from "consoleLoggingIntegration" /* 816 */;
import count from "count" /* 818 */;
import _mod819 from "module_819" /* 819 */;
import _mod820 from "module_820" /* 820 */;
import convertPromptToMessages from "convertPromptToMessages" /* 822 */;
import extractRequestAttributes from "extractRequestAttributes" /* 827 */;
import INSTRUMENTED_METHODS from "INSTRUMENTED_METHODS" /* 829 */;
import instrumentAnthropicAiClient from "instrumentAnthropicAiClient" /* 834 */;
import ANTHROPIC_AI_INSTRUMENTED_METHODS from "ANTHROPIC_AI_INSTRUMENTED_METHODS" /* 836 */;
import _mod838 from "module_838" /* 838 */;
import CHATS_CREATE_METHOD from "CHATS_CREATE_METHOD" /* 839 */;
import _mod842 from "module_842" /* 842 */;
import LANGCHAIN_INTEGRATION_NAME from "LANGCHAIN_INTEGRATION_NAME" /* 844 */;
import instrumentLangGraph from "instrumentLangGraph" /* 845 */;
import LANGGRAPH_INTEGRATION_NAME from "LANGGRAPH_INTEGRATION_NAME" /* 846 */;
import _mod848 from "module_848" /* 848 */;
import _mod849 from "module_849" /* 849 */;
import _resolveResponse from "_resolveResponse" /* 850 */;
import _isFetchSupported from "_isFetchSupported" /* 851 */;
import dynamicRequire from "dynamicRequire" /* 852 */;
import _mod853 from "module_853" /* 853 */;
import _mod854 from "module_854" /* 854 */;
import replaceExports from "replaceExports" /* 855 */;
import filenameIsInApp from "filenameIsInApp" /* 856 */;
import callFrameToStackFrame from "callFrameToStackFrame" /* 857 */;
import LRUMap from "LRUMap" /* 858 */;
import vercelWaitUntil from "vercelWaitUntil" /* 859 */;
import flushWithTimeout from "flushWithTimeout" /* 860 */;
import escapeStringForRegex from "escapeStringForRegex" /* 861 */;

Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

export const registerSpanErrorInstrumentation = _mod683.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = unwrapScopeFromWeakRef.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = unwrapScopeFromWeakRef.setCapturedScopesOnSpan;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = _mod725.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = SPAN_STATUS_ERROR.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = SPAN_STATUS_ERROR.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = SPAN_STATUS_ERROR.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = SPAN_STATUS_ERROR.getSpanStatusFromHttpCode;
export const setHttpStatus = SPAN_STATUS_ERROR.setHttpStatus;
export const continueTrace = _mod731.continueTrace;
export const startInactiveSpan = _mod731.startInactiveSpan;
export const startNewTrace = _mod731.startNewTrace;
export const startSpan = _mod731.startSpan;
export const startSpanManual = _mod731.startSpanManual;
export const suppressTracing = _mod731.suppressTracing;
export const withActiveSpan = _mod731.withActiveSpan;
export const getDynamicSamplingContextFromClient = _mod722.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = _mod722.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = _mod722.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = _mod722.spanToBaggageHeader;
export const setMeasurement = timedEventsToMeasurements.setMeasurement;
export const timedEventsToMeasurements = timedEventsToMeasurements.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_PREVIOUS_TRACE_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_ATTRIBUTE_URL_FULL;
export const SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE = SEMANTIC_ATTRIBUTE_CACHE_HIT.SEMANTIC_LINK_ATTRIBUTE_LINK_TYPE;
export const createEventEnvelope = _enhanceEventWithSdkInfo.createEventEnvelope;
export const createSessionEnvelope = _enhanceEventWithSdkInfo.createSessionEnvelope;
export const createSpanEnvelope = _enhanceEventWithSdkInfo.createSpanEnvelope;
export const addEventProcessor = captureCheckIn.addEventProcessor;
export const captureCheckIn = captureCheckIn.captureCheckIn;
export const captureEvent = captureCheckIn.captureEvent;
export const captureException = captureCheckIn.captureException;
export const captureMessage = captureCheckIn.captureMessage;
export const captureSession = captureCheckIn.captureSession;
export const close = captureCheckIn.close;
export const endSession = captureCheckIn.endSession;
export const flush = captureCheckIn.flush;
export const isEnabled = captureCheckIn.isEnabled;
export const isInitialized = captureCheckIn.isInitialized;
export const lastEventId = captureCheckIn.lastEventId;
export const setContext = captureCheckIn.setContext;
export const setExtra = captureCheckIn.setExtra;
export const setExtras = captureCheckIn.setExtras;
export const setTag = captureCheckIn.setTag;
export const setTags = captureCheckIn.setTags;
export const setUser = captureCheckIn.setUser;
export const startSession = captureCheckIn.startSession;
export const withMonitor = captureCheckIn.withMonitor;
export const getClient = _mod713.getClient;
export const getCurrentScope = _mod713.getCurrentScope;
export const getGlobalScope = _mod713.getGlobalScope;
export const getIsolationScope = _mod713.getIsolationScope;
export const getTraceContextFromScope = _mod713.getTraceContextFromScope;
export const withIsolationScope = _mod713.withIsolationScope;
export const withScope = _mod713.withScope;
export const getDefaultCurrentScope = _mod712.getDefaultCurrentScope;
export const getDefaultIsolationScope = _mod712.getDefaultIsolationScope;
export const setAsyncContextStrategy = _mod706.setAsyncContextStrategy;
export const getGlobalSingleton = _mod690.getGlobalSingleton;
export const getMainCarrier = _mod690.getMainCarrier;
export const closeSession = closeSession.closeSession;
export const makeSession = closeSession.makeSession;
export const updateSession = closeSession.updateSession;
export const Scope = Scope.Scope;
export const notifyEventProcessors = _notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = _mod740.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = _mod740.getReportDialogEndpoint;
export const Client = _mod741.Client;
export const ServerRuntimeClient = _mod756.ServerRuntimeClient;
export const initAndBind = _mod760.initAndBind;
export const setCurrentClient = _mod760.setCurrentClient;
export const createTransport = DEFAULT_TRANSPORT_BUFFER_SIZE.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const MULTIPLEXED_TRANSPORT_EXTRA_KEY = eventFromEnvelope.MULTIPLEXED_TRANSPORT_EXTRA_KEY;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const installedIntegrations = setupIntegration.installedIntegrations;
export const _INTERNAL_clearAiProviderSkips = _INTERNAL_clearAiProviderSkips._INTERNAL_clearAiProviderSkips;
export const _INTERNAL_shouldSkipAiProviderWrapping = _INTERNAL_clearAiProviderSkips._INTERNAL_shouldSkipAiProviderWrapping;
export const _INTERNAL_skipAiProviderWrapping = _INTERNAL_clearAiProviderSkips._INTERNAL_skipAiProviderWrapping;
export const applyScopeDataToEvent = mergeScopeData.applyScopeDataToEvent;
export const getCombinedScopeData = mergeScopeData.getCombinedScopeData;
export const mergeScopeData = mergeScopeData.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = _mod759.createCheckInEnvelope;
export const hasSpansEnabled = _mod720.hasSpansEnabled;
export const isSentryRequestUrl = _mod764.isSentryRequestUrl;
export const handleCallbackErrors = _mod732.handleCallbackErrors;
export const fmt = parameterize.fmt;
export const parameterize = parameterize.parameterize;
export const addAutoIpAddressToSession = _mod767.addAutoIpAddressToSession;
export const addAutoIpAddressToUser = _mod767.addAutoIpAddressToUser;
export const addChildSpanToSpan = spanToJSON.addChildSpanToSpan;
export const convertSpanLinksForEnvelope = spanToJSON.convertSpanLinksForEnvelope;
export const getActiveSpan = spanToJSON.getActiveSpan;
export const getRootSpan = spanToJSON.getRootSpan;
export const getSpanDescendants = spanToJSON.getSpanDescendants;
export const getStatusMessage = spanToJSON.getStatusMessage;
export const spanIsSampled = spanToJSON.spanIsSampled;
export const spanTimeInputToSeconds = spanToJSON.spanTimeInputToSeconds;
export const spanToJSON = spanToJSON.spanToJSON;
export const spanToTraceContext = spanToJSON.spanToTraceContext;
export const spanToTraceHeader = spanToJSON.spanToTraceHeader;
export const updateSpanName = spanToJSON.updateSpanName;
export const _INTERNAL_setSpanForScope = _getSpanForScope._setSpanForScope;
export const parseSampleRate = _mod701.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = _mod769.getTraceData;
export const getTraceMetaTags = _mod770.getTraceMetaTags;
export const debounce = _mod771.debounce;
export const extractQueryParamsFromUrl = winterCGHeadersToDict.extractQueryParamsFromUrl;
export const headersToDict = winterCGHeadersToDict.headersToDict;
export const httpHeadersToSpanAttributes = winterCGHeadersToDict.httpHeadersToSpanAttributes;
export const httpRequestToRequestData = winterCGHeadersToDict.httpRequestToRequestData;
export const winterCGHeadersToDict = winterCGHeadersToDict.winterCGHeadersToDict;
export const winterCGRequestToRequestData = winterCGHeadersToDict.winterCGRequestToRequestData;
export const DEFAULT_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEFAULT_ENVIRONMENT;
export const DEV_ENVIRONMENT = DEFAULT_ENVIRONMENT.DEV_ENVIRONMENT;
export const addBreadcrumb = _mod773.addBreadcrumb;
export const functionToStringIntegration = _mod774.functionToStringIntegration;
export const eventFiltersIntegration = _mergeOptions.eventFiltersIntegration;
export const inboundFiltersIntegration = _mergeOptions.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = _extractErrorData.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const instrumentSupabaseClient = markAsInstrumented.instrumentSupabaseClient;
export const supabaseIntegration = markAsInstrumented.supabaseIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const consoleIntegration = _mod793.consoleIntegration;
export const featureFlagsIntegration = featureFlagsIntegration.featureFlagsIntegration;
export const growthbookIntegration = growthbookIntegration.growthbookIntegration;
export const profiler = profiler.profiler;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const wrapMcpServerWithSentry = _mod800.wrapMcpServerWithSentry;
export const captureFeedback = captureFeedback.captureFeedback;
export const _INTERNAL_captureLog = _INTERNAL_captureSerializedLog._INTERNAL_captureLog;
export const _INTERNAL_captureSerializedLog = _INTERNAL_captureSerializedLog._INTERNAL_captureSerializedLog;
export const _INTERNAL_flushLogsBuffer = _INTERNAL_captureSerializedLog._INTERNAL_flushLogsBuffer;
export const logger = fmt;
export const consoleLoggingIntegration = consoleLoggingIntegration.consoleLoggingIntegration;
export const _INTERNAL_captureMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureMetric;
export const _INTERNAL_captureSerializedMetric = _INTERNAL_captureSerializedMetric._INTERNAL_captureSerializedMetric;
export const _INTERNAL_flushMetricsBuffer = _INTERNAL_captureSerializedMetric._INTERNAL_flushMetricsBuffer;
export const metrics = count;
export const createConsolaReporter = _mod819.createConsolaReporter;
export const addVercelAiProcessors = _mod820.addVercelAiProcessors;
export const _INTERNAL_cleanupToolCallSpan = convertPromptToMessages._INTERNAL_cleanupToolCallSpan;
export const _INTERNAL_getSpanForToolCallId = convertPromptToMessages._INTERNAL_getSpanForToolCallId;
export const instrumentOpenAiClient = extractRequestAttributes.instrumentOpenAiClient;
export const OPENAI_INTEGRATION_NAME = INSTRUMENTED_METHODS.OPENAI_INTEGRATION_NAME;
export const instrumentAnthropicAiClient = instrumentAnthropicAiClient.instrumentAnthropicAiClient;
export const ANTHROPIC_AI_INTEGRATION_NAME = ANTHROPIC_AI_INSTRUMENTED_METHODS.ANTHROPIC_AI_INTEGRATION_NAME;
export const instrumentGoogleGenAIClient = _mod838.instrumentGoogleGenAIClient;
export const GOOGLE_GENAI_INTEGRATION_NAME = CHATS_CREATE_METHOD.GOOGLE_GENAI_INTEGRATION_NAME;
export const createLangChainCallbackHandler = _mod842.createLangChainCallbackHandler;
export const LANGCHAIN_INTEGRATION_NAME = LANGCHAIN_INTEGRATION_NAME.LANGCHAIN_INTEGRATION_NAME;
export const instrumentLangGraph = instrumentLangGraph.instrumentLangGraph;
export const instrumentStateGraphCompile = instrumentLangGraph.instrumentStateGraphCompile;
export const LANGGRAPH_INTEGRATION_NAME = LANGGRAPH_INTEGRATION_NAME.LANGGRAPH_INTEGRATION_NAME;
export const _INTERNAL_FLAG_BUFFER_SIZE = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_FLAG_BUFFER_SIZE;
export const _INTERNAL_MAX_FLAGS_PER_SPAN = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_MAX_FLAGS_PER_SPAN;
export const _INTERNAL_addFeatureFlagToActiveSpan = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_addFeatureFlagToActiveSpan;
export const _INTERNAL_copyFlagsFromScopeToEvent = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_copyFlagsFromScopeToEvent;
export const _INTERNAL_insertFlagToScope = _INTERNAL_FLAG_BUFFER_SIZE._INTERNAL_insertFlagToScope;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const getBreadcrumbLogLevelFromHttpStatusCode = _mod848.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = _mod702.dsnFromString;
export const dsnToString = _mod702.dsnToString;
export const makeDsn = _mod702.makeDsn;
export const SentryError = _mod849.SentryError;
export const GLOBAL_OBJ = _mod686.GLOBAL_OBJ;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = _mod715.addHandler;
export const maybeInstrument = _mod715.maybeInstrument;
export const resetInstrumentationHandlers = _mod715.resetInstrumentationHandlers;
export const triggerHandlers = _mod715.triggerHandlers;
export const isDOMError = _mod692.isDOMError;
export const isDOMException = _mod692.isDOMException;
export const isElement = _mod692.isElement;
export const isError = _mod692.isError;
export const isErrorEvent = _mod692.isErrorEvent;
export const isEvent = _mod692.isEvent;
export const isInstanceOf = _mod692.isInstanceOf;
export const isParameterizedString = _mod692.isParameterizedString;
export const isPlainObject = _mod692.isPlainObject;
export const isPrimitive = _mod692.isPrimitive;
export const isRegExp = _mod692.isRegExp;
export const isString = _mod692.isString;
export const isSyntheticEvent = _mod692.isSyntheticEvent;
export const isThenable = _mod692.isThenable;
export const isVueViewModel = _mod692.isVueViewModel;
export const isBrowser = dynamicRequire.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const debug = consoleSandbox.debug;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const addContextToFrame = uuid4.addContextToFrame;
export const addExceptionMechanism = uuid4.addExceptionMechanism;
export const addExceptionTypeValue = uuid4.addExceptionTypeValue;
export const checkOrSetAlreadyCaught = uuid4.checkOrSetAlreadyCaught;
export const getEventDescription = uuid4.getEventDescription;
export const parseSemver = uuid4.parseSemver;
export const uuid4 = uuid4.uuid4;
export const isNodeEnv = _mod853.isNodeEnv;
export const loadModule = _mod853.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = _mod687.addNonEnumerableProperty;
export const convertToPlainObject = _mod687.convertToPlainObject;
export const dropUndefinedKeys = _mod687.dropUndefinedKeys;
export const extractExceptionKeysForMessage = _mod687.extractExceptionKeysForMessage;
export const fill = _mod687.fill;
export const getOriginalFunction = _mod687.getOriginalFunction;
export const markFunctionWrapped = _mod687.markFunctionWrapped;
export const objectify = _mod687.objectify;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const SENTRY_BUFFER_FULL_ERROR = SENTRY_BUFFER_FULL_ERROR.SENTRY_BUFFER_FULL_ERROR;
export const makePromiseBuffer = SENTRY_BUFFER_FULL_ERROR.makePromiseBuffer;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const replaceExports = replaceExports.replaceExports;
export const UNKNOWN_FUNCTION = _mod698.UNKNOWN_FUNCTION;
export const createStackParser = _mod698.createStackParser;
export const getFramesFromEvent = _mod698.getFramesFromEvent;
export const getFunctionName = _mod698.getFunctionName;
export const stackParserFromStackParserOptions = _mod698.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = _mod698.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = _mod697.isMatchingPattern;
export const safeJoin = _mod697.safeJoin;
export const snipLine = _mod697.snipLine;
export const stringMatchesSomePattern = _mod697.stringMatchesSomePattern;
export const truncate = _mod697.truncate;
export const isNativeFunction = _isFetchSupported.isNativeFunction;
export const supportsDOMError = _isFetchSupported.supportsDOMError;
export const supportsDOMException = _isFetchSupported.supportsDOMException;
export const supportsErrorEvent = _isFetchSupported.supportsErrorEvent;
export const supportsFetch = _isFetchSupported.supportsFetch;
export const supportsHistory = _isFetchSupported.supportsHistory;
export const supportsNativeFetch = _isFetchSupported.supportsNativeFetch;
export const supportsReferrerPolicy = _isFetchSupported.supportsReferrerPolicy;
export const supportsReportingObserver = _isFetchSupported.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const browserPerformanceTimeOrigin = dateTimestampInSeconds.browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = dateTimestampInSeconds.dateTimestampInSeconds;
export const timestampInSeconds = dateTimestampInSeconds.timestampInSeconds;
export const TRACEPARENT_REGEXP = _mod699.TRACEPARENT_REGEXP;
export const extractTraceparentData = _mod699.extractTraceparentData;
export const generateSentryTraceHeader = _mod699.generateSentryTraceHeader;
export const generateTraceparentHeader = _mod699.generateTraceparentHeader;
export const propagationContextFromHeaders = _mod699.propagationContextFromHeaders;
export const shouldContinueTrace = _mod699.shouldContinueTrace;
export const getSDKSource = _mod854.getSDKSource;
export const isBrowserBundle = _mod854.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = _mod754.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = disabledUntil.DEFAULT_RETRY_AFTER;
export const disabledUntil = disabledUntil.disabledUntil;
export const isRateLimited = disabledUntil.isRateLimited;
export const parseRetryAfterHeader = disabledUntil.parseRetryAfterHeader;
export const updateRateLimits = disabledUntil.updateRateLimits;
export const MAX_BAGGAGE_STRING_LENGTH = MAX_BAGGAGE_STRING_LENGTH.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = MAX_BAGGAGE_STRING_LENGTH.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = MAX_BAGGAGE_STRING_LENGTH.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.dynamicSamplingContextToSentryBaggageHeader;
export const objectToBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.objectToBaggageHeader;
export const parseBaggageHeader = MAX_BAGGAGE_STRING_LENGTH.parseBaggageHeader;
export const getHttpSpanDetailsFromUrlObject = _mod765.getHttpSpanDetailsFromUrlObject;
export const getSanitizedUrlString = _mod765.getSanitizedUrlString;
export const getSanitizedUrlStringFromUrlObject = _mod765.getSanitizedUrlStringFromUrlObject;
export const isURLObjectRelative = _mod765.isURLObjectRelative;
export const parseStringToURLObject = _mod765.parseStringToURLObject;
export const parseUrl = _mod765.parseUrl;
export const stripDataUrlContent = _mod765.stripDataUrlContent;
export const stripUrlQueryAndFragment = _mod765.stripUrlQueryAndFragment;
export const _INTERNAL_enhanceErrorWithSentryInfo = exceptionFromError._enhanceErrorWithSentryInfo;
export const eventFromMessage = exceptionFromError.eventFromMessage;
export const eventFromUnknownInput = exceptionFromError.eventFromUnknownInput;
export const exceptionFromError = exceptionFromError.exceptionFromError;
export const parseStackFrames = exceptionFromError.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generateSpanId = generateSpanId.generateSpanId;
export const generateTraceId = generateSpanId.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const flushIfServerless = flushWithTimeout.flushIfServerless;
export const SDK_VERSION = SDK_VERSION.SDK_VERSION;
export const getDebugImagesForResources = _mod739.getDebugImagesForResources;
export const getFilenameToDebugIdMap = _mod739.getFilenameToDebugIdMap;
export const getFilenameToMetadataMap = _mod779.getFilenameToMetadataMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const _INTERNAL_safeDateNow = safeDateNow.safeDateNow;
export const _INTERNAL_safeMathRandom = safeDateNow.safeMathRandom;
export const _INTERNAL_withRandomSafeContext = safeDateNow.withRandomSafeContext;
