// Module ID: 14509
// Function ID: 14510
// Name: UserSettingsText
// Dependencies: [19, 17, 1874, 3907, 1303, 1304, 676, 21, 4255, 712, 698, 3928, 8175, 3959, 589, 3901, 1480, 7502, 1297, 9790, 4251, 1236, 7765, 4664, 5620, 5621, 7783, 7782, 2]
// Exports: default, setDataSavingMode, setImageDescriptions, setLowQualityImageMode, setStickerAutocomplete, setVideoUploadQuality

// Module 14509 (UserSettingsText)
import "registerAsset";
import { View } from "dispatcher";
import mergeGuildAvatar from "mergeGuildAvatar";
import reset from "reset";
import initialize from "initialize";
import CHANNEL_SIDEBAR_WIDTH from "CHANNEL_SIDEBAR_WIDTH";
import { VideoQualitySettings } from "CHANNEL_SIDEBAR_WIDTH";
import ME from "ME";
import jsxProd from "getSystemLocale";
import createCacheKey from "createCacheKey";

let c10;
let c9;
let closure_12;
let closure_14;
let map1;
let unpackModuleId;
const require = arg1;
({ AnalyticEvents: c9, AnalyticsSections: c10, UserSettingsSections: unpackModuleId } = ME);
({ jsx: closure_12, jsxs: map1, Fragment: closure_14 } = jsxProd);
createCacheKey = { flex: { flex: 1 }, nitroUpsell: { flexDirection: "row", alignItems: "center" }, nitroIcon: null };
createCacheKey = { width: 16, height: 16, tintColor: require("Themes").unsafe_rawColors.PRIMARY_400 };
createCacheKey[2] = createCacheKey;
createCacheKey = createCacheKey.createStyles(createCacheKey);
let result = require("mergeGuildAvatar").fileFinishedImporting("modules/user_settings/chat/native/UserSettingsText.tsx");

export default function UserSettingsText() {
  let require;
  let videoUploadQuality;
  let obj = require(dataSavingMode[13]);
  const token = obj.useToken(videoUploadQuality(dataSavingMode[9]).modules.mobile.TABLE_ROW_PADDING);
  const tmp5 = createCacheKey();
  const InlineAttachmentMedia = require(dataSavingMode[11]).InlineAttachmentMedia;
  const setting = InlineAttachmentMedia.useSetting();
  const InlineEmbedMedia = require(dataSavingMode[11]).InlineEmbedMedia;
  const setting1 = InlineEmbedMedia.useSetting();
  const RenderEmbeds = require(dataSavingMode[11]).RenderEmbeds;
  const setting2 = RenderEmbeds.useSetting();
  const RenderReactions = require(dataSavingMode[11]).RenderReactions;
  const setting3 = RenderReactions.useSetting();
  let obj1 = require(dataSavingMode[14]);
  const items = [CHANNEL_SIDEBAR_WIDTH];
  const stateFromStoresObject = obj1.useStateFromStoresObject(items, () => ({ lowQualityImageMode: CHANNEL_SIDEBAR_WIDTH.dataSavingMode, videoUploadQuality: CHANNEL_SIDEBAR_WIDTH.videoUploadQuality, dataSavingMode: CHANNEL_SIDEBAR_WIDTH.dataSavingMode }));
  ({ lowQualityImageMode: require, videoUploadQuality } = stateFromStoresObject);
  dataSavingMode = stateFromStoresObject.dataSavingMode;
  let obj2 = require(dataSavingMode[14]);
  const items1 = [reset];
  const stateFromStores = obj2.useStateFromStores(items1, () => premiumTypeSubscription.getPremiumTypeSubscription());
  let obj3 = require(dataSavingMode[14]);
  const items2 = [mergeGuildAvatar];
  const stateFromStores1 = obj3.useStateFromStores(items2, () => arr.getCurrentUser());
  let obj4 = require(dataSavingMode[15]);
  let result = obj4.hasPremiumSubscriptionToDisplay(stateFromStores1, stateFromStores);
  let obj5 = require(dataSavingMode[14]);
  const items3 = [initialize];
  const stateFromStores2 = obj5.useStateFromStores(items3, () => initialize.shouldSync("text"));
  let ViewImageDescriptions = require(dataSavingMode[11]).ViewImageDescriptions;
  const setting4 = ViewImageDescriptions.useSetting();
  let obj6 = require(dataSavingMode[16]);
  mergeGuildAvatar = obj6.useNavigation();
  obj = { style: tmp5.flex, children: null };
  obj = { spacing: null, style: null, children: null };
  obj[0] = videoUploadQuality(dataSavingMode[9]).space.PX_24;
  obj[1] = { paddingHorizontal: token };
  obj1 = { children: null };
  obj2 = { title: null, description: null, hasIcons: false, children: null };
  const intl = require(dataSavingMode[21]).intl;
  obj2[0] = intl.string(require(dataSavingMode[21]).t["9nyle0"]);
  const intl2 = require(dataSavingMode[21]).intl;
  obj2[1] = intl2.format(require(dataSavingMode[21]).t.qjjvqO, { maxSize: 8 });
  obj3 = { label: null, value: null, onValueChange: null };
  const intl3 = require(dataSavingMode[21]).intl;
  obj3[0] = intl3.string(require(dataSavingMode[21]).t.U47N1p);
  obj3[1] = setting1;
  obj3[2] = require(dataSavingMode[11]).InlineEmbedMedia.updateSetting;
  const items4 = [callback(require(dataSavingMode[25]).TableSwitchRow, obj3), ];
  obj4 = { label: null, value: null, onValueChange: null };
  const intl4 = require(dataSavingMode[21]).intl;
  obj4[0] = intl4.string(require(dataSavingMode[21]).t.VP11No);
  obj4[1] = setting;
  obj4[2] = require(dataSavingMode[11]).InlineAttachmentMedia.updateSetting;
  items4[1] = callback(require(dataSavingMode[25]).TableSwitchRow, obj4);
  obj2[3] = items4;
  const items5 = [callback2(require(dataSavingMode[24]).TableRowGroup, obj2), ];
  obj5 = { description: null, hasIcons: false, children: null };
  const intl5 = require(dataSavingMode[21]).intl;
  obj5[0] = intl5.string(require(dataSavingMode[21]).t.T0rbtM);
  obj6 = { label: null, value: null, onValueChange: null };
  const intl6 = require(dataSavingMode[21]).intl;
  obj6[0] = intl6.string(require(dataSavingMode[21]).t["w8j+yW"]);
  obj6[1] = setting4;
  obj6[2] = function updateImageDescriptions(image_descriptions) {
    let obj = videoUploadQuality(dataSavingMode[10]);
    obj = { video_upload_quality: videoUploadQuality, image_descriptions, low_quality_image_mode: closure_0, data_saving_mode: dataSavingMode, updated_setting: "image_descriptions" };
    obj.track(outer1_9.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, obj);
    const ViewImageDescriptions = outer1_0(dataSavingMode[11]).ViewImageDescriptions;
    ViewImageDescriptions.updateSetting(image_descriptions);
  };
  obj5[2] = callback(require(dataSavingMode[25]).TableSwitchRow, obj6);
  items5[1] = callback(require(dataSavingMode[24]).TableRowGroup, obj5);
  obj1[0] = items5;
  const items6 = [callback2(closure_14, obj1), , , , , ];
  const obj7 = { title: null, value: null, onChange: null, description: null, hasIcons: false, children: null };
  const intl7 = require(dataSavingMode[21]).intl;
  obj7[0] = intl7.string(require(dataSavingMode[21]).t.PXq9f1).toUpperCase();
  obj7[1] = videoUploadQuality;
  obj7[2] = function updateVideoUploadQuality(videoUploadQuality) {
    let obj = videoUploadQuality(dataSavingMode[10]);
    obj = { video_upload_quality: videoUploadQuality, image_descriptions: setting4, low_quality_image_mode: closure_0, data_saving_mode: dataSavingMode, updated_setting: "video_upload_quality" };
    obj.track(outer1_9.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, obj);
    obj = { videoUploadQuality };
    const result = videoUploadQuality(dataSavingMode[12]).updatedUnsyncedSettings(obj);
  };
  const intl8 = require(dataSavingMode[21]).intl;
  obj7[3] = intl8.format(require(dataSavingMode[21]).t["Up+hSO"], { supportURL: "https://support.discord.com/hc/articles/9665451164951" });
  const obj8 = { label: null, value: null };
  const intl9 = require(dataSavingMode[21]).intl;
  obj8[0] = intl9.string(require(dataSavingMode[21]).t.cWGW5d);
  obj8[1] = VideoQualitySettings.BEST;
  const items7 = [callback(require(dataSavingMode[27]).TableRadioRow, obj8), , ];
  const obj9 = { label: null, value: null };
  const intl10 = require(dataSavingMode[21]).intl;
  obj9[0] = intl10.string(require(dataSavingMode[21]).t["5hKnyC"]);
  obj9[1] = VideoQualitySettings.STANDARD;
  items7[1] = callback(require(dataSavingMode[27]).TableRadioRow, obj9);
  const obj10 = { label: null, value: null };
  const intl11 = require(dataSavingMode[21]).intl;
  obj10[0] = intl11.string(require(dataSavingMode[21]).t.y5k4ZJ);
  obj10[1] = VideoQualitySettings.DATA_SAVER;
  items7[2] = callback(require(dataSavingMode[27]).TableRadioRow, obj10);
  obj7[5] = items7;
  const items8 = [callback2(require(dataSavingMode[26]).TableRadioGroup, obj7), ];
  let tmp18Result = !result;
  if (!result) {
    const obj11 = { style: null, children: null };
    obj11[0] = tmp5.nitroUpsell;
    const obj12 = { source: null, size: null, style: null };
    obj12[0] = videoUploadQuality(tmp2[19]);
    obj12[1] = tmp(tmp2[18]).Icon.Sizes.SMALL;
    obj12[2] = tmp5.nitroIcon;
    const items9 = [tmp16(tmp(tmp2[18]).Icon, obj12), ];
    const obj13 = { variant: "text-sm/medium", color: "text-muted", style: null, children: null };
    obj13[2] = { marginLeft: 4 };
    const intl12 = tmp(tmp2[21]).intl;
    const obj14 = { onClick: null };
    obj14[0] = function onClick() {
      videoUploadQuality(dataSavingMode[17]).setSection(outer1_11.PREMIUM);
      const obj = videoUploadQuality(dataSavingMode[17]);
    };
    obj13[3] = intl12.format(tmp(tmp2[21]).t.uW1zul, obj14);
    items9[1] = tmp16(tmp(tmp2[20]).Text, obj13);
    obj11[1] = items9;
    tmp18Result = tmp18(tmp17, obj11);
  }
  const obj15 = { children: null };
  items8[1] = tmp18Result;
  function handleSync(shouldSync) {
    const result = videoUploadQuality(dataSavingMode[12]).setShouldSyncTextSettings(shouldSync);
  }
  function toggleDataSavingMode(dataSavingMode) {
    let obj = videoUploadQuality(dataSavingMode[10]);
    obj = { video_upload_quality: videoUploadQuality, image_descriptions: setting4, low_quality_image_mode: closure_0, data_saving_mode: dataSavingMode, updated_setting: "data_saving_mode" };
    obj.track(outer1_9.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, obj);
    obj = { dataSavingMode };
    const result = videoUploadQuality(dataSavingMode[12]).updatedUnsyncedSettings(obj);
  }
  items6[1] = callback2(setting4, { children: items8 });
  const obj16 = { title: null, description: null, hasIcons: false, children: null };
  const intl13 = tmp(tmp2[21]).intl;
  obj16[0] = intl13.string(require(dataSavingMode[21]).t.fyG8t2);
  const intl14 = tmp(tmp2[21]).intl;
  obj16[1] = intl14.string(require(dataSavingMode[21]).t["wC0+Ph"]);
  const obj17 = { label: null, value: null, onValueChange: null };
  const intl15 = tmp(tmp2[21]).intl;
  obj17[0] = intl15.string(require(dataSavingMode[21]).t.ix8XIj);
  obj17[1] = dataSavingMode;
  obj17[2] = toggleDataSavingMode;
  obj16[3] = callback(require(dataSavingMode[25]).TableSwitchRow, obj17);
  items6[2] = callback(require(dataSavingMode[24]).TableRowGroup, obj16);
  const obj18 = { title: null, hasIcons: false, children: null };
  const intl16 = tmp(tmp2[21]).intl;
  obj18[0] = intl16.string(require(dataSavingMode[21]).t.PWZOn4);
  const obj19 = { label: null, value: null, onValueChange: null };
  const intl17 = tmp(tmp2[21]).intl;
  obj19[0] = intl17.string(require(dataSavingMode[21]).t["5bK9vw"]);
  obj19[1] = setting2;
  obj19[2] = require(dataSavingMode[11]).RenderEmbeds.updateSetting;
  obj18[2] = callback(require(dataSavingMode[25]).TableSwitchRow, obj19);
  items6[3] = callback(require(dataSavingMode[24]).TableRowGroup, obj18);
  const obj20 = { title: null, hasIcons: false, children: null };
  const intl18 = tmp(tmp2[21]).intl;
  obj20[0] = intl18.string(require(dataSavingMode[21]).t.sMOuuS);
  const obj21 = { label: null, value: null, onValueChange: null };
  const intl19 = tmp(tmp2[21]).intl;
  obj21[0] = intl19.string(require(dataSavingMode[21]).t["zge/fP"]);
  obj21[1] = setting3;
  obj21[2] = require(dataSavingMode[11]).RenderReactions.updateSetting;
  obj20[2] = callback(require(dataSavingMode[25]).TableSwitchRow, obj21);
  items6[4] = callback(require(dataSavingMode[24]).TableRowGroup, obj20);
  const obj22 = { title: null, description: null, hasIcons: false, children: null };
  const intl20 = tmp(tmp2[21]).intl;
  obj22[0] = intl20.string(require(dataSavingMode[21]).t.BkuOO6);
  const intl21 = tmp(tmp2[21]).intl;
  obj22[1] = intl21.string(require(dataSavingMode[21]).t.p4IKE9);
  const obj23 = { label: null, value: null, onValueChange: null };
  const intl22 = tmp(tmp2[21]).intl;
  obj23[0] = intl22.string(require(dataSavingMode[21]).t["3340dY"]);
  obj23[1] = false !== stateFromStores2;
  obj23[2] = handleSync;
  obj22[3] = callback(require(dataSavingMode[25]).TableSwitchRow, obj23);
  items6[5] = callback(require(dataSavingMode[24]).TableRowGroup, obj22);
  obj[2] = items6;
  obj15[0] = callback2(require(dataSavingMode[23]).Stack, obj);
  obj[1] = callback(require(dataSavingMode[22]).Form, obj15);
  return callback(setting4, obj);
};
export const setStickerAutocomplete = function setStickerAutocomplete(enabled) {
  let obj = importDefault(698);
  obj = { enabled, location: obj };
  obj = { section: constants2.SETTINGS_TEXT_AND_IMAGES };
  obj.track(constants.STICKERS_IN_AUTOCOMPLETE_TOGGLED, obj);
  const IncludeStickersInAutocomplete = require(3928) /* explicitContentFromProto */.IncludeStickersInAutocomplete;
  IncludeStickersInAutocomplete.updateSetting(enabled);
};
export const setLowQualityImageMode = function setLowQualityImageMode(lowQualityImageMode) {
  let dataSavingMode;
  let videoUploadQuality;
  let viewImageDescriptions;
  lowQualityImageMode = lowQualityImageMode.lowQualityImageMode;
  ({ videoUploadQuality, viewImageDescriptions, dataSavingMode } = lowQualityImageMode);
  importDefault(698).track(constants.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, { video_upload_quality: videoUploadQuality, image_descriptions: viewImageDescriptions, low_quality_image_mode: lowQualityImageMode, data_saving_mode: dataSavingMode, updated_setting: "low_quality_image_mode" });
  const obj = importDefault(698);
  const result = importDefault(8175).updatedUnsyncedSettings({ lowQualityImageMode });
};
export const setDataSavingMode = function setDataSavingMode(dataSavingMode) {
  let lowQualityImageMode;
  let videoUploadQuality;
  let viewImageDescriptions;
  dataSavingMode = dataSavingMode.dataSavingMode;
  ({ videoUploadQuality, viewImageDescriptions, lowQualityImageMode } = dataSavingMode);
  importDefault(698).track(constants.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, { video_upload_quality: videoUploadQuality, image_descriptions: viewImageDescriptions, low_quality_image_mode: lowQualityImageMode, data_saving_mode: dataSavingMode, updated_setting: "data_saving_mode" });
  const obj = importDefault(698);
  const result = importDefault(8175).updatedUnsyncedSettings({ dataSavingMode });
};
export const setVideoUploadQuality = function setVideoUploadQuality(videoUploadQuality) {
  let dataSavingMode;
  let lowQualityImageMode;
  let viewImageDescriptions;
  videoUploadQuality = videoUploadQuality.videoUploadQuality;
  ({ viewImageDescriptions, lowQualityImageMode, dataSavingMode } = videoUploadQuality);
  importDefault(698).track(constants.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, { video_upload_quality: videoUploadQuality, image_descriptions: viewImageDescriptions, low_quality_image_mode: lowQualityImageMode, data_saving_mode: dataSavingMode, updated_setting: "video_upload_quality" });
  const obj = importDefault(698);
  const result = importDefault(8175).updatedUnsyncedSettings({ videoUploadQuality });
};
export const setImageDescriptions = function setImageDescriptions(viewImageDescriptions) {
  let dataSavingMode;
  let lowQualityImageMode;
  let videoUploadQuality;
  viewImageDescriptions = viewImageDescriptions.viewImageDescriptions;
  ({ videoUploadQuality, lowQualityImageMode, dataSavingMode } = viewImageDescriptions);
  importDefault(698).track(constants.IMAGE_VIDEO_DATA_SETTINGS_UPDATED, { video_upload_quality: videoUploadQuality, image_descriptions: viewImageDescriptions, low_quality_image_mode: lowQualityImageMode, data_saving_mode: dataSavingMode, updated_setting: "image_descriptions" });
  const ViewImageDescriptions = require(3928) /* explicitContentFromProto */.ViewImageDescriptions;
  ViewImageDescriptions.updateSetting(viewImageDescriptions);
};
