// Module ID: 1188
// Function ID: 1189
// Name: native
// Dependencies: [1189, 1190, 2, 1191, 13900, 13140, 13901, 13904, 13905, 13906, 13907, 13908, 13909, 5714, 13910, 13912, 9237, 13913, 13914, 13916, 13917, 13918, 13919, 13920, 5596, 12851, 13929, 13931, 13911, 13933, 13935, 13936, 13937, 13938, 13939, 13940, 13941, 8912, 13942, 13943, 13944, 13945, 13946, 13947, 8911, 8895, 5909, 13272, 9442, 10079]

// Module 1188 (native)
import StatusConstants from "StatusConstants" /* 1189 */;
import BadgeConstants from "BadgeConstants" /* 1190 */;
import Button_Button from "Button/Button" /* 1191 */;
import Icon from "Icon" /* 5596 */;
import OverlayView from "OverlayView" /* 5714 */;
import Pressables from "Pressables" /* 5909 */;
import Form from "Form" /* 8895 */;
import CardSectionDefault from "CardSection" /* 8911 */;
import LegacyText_LegacyTextDefault from "LegacyText/LegacyText" /* 8912 */;
import void_TextInput_TextInputDefault from "void/TextInput/TextInput" /* 9237 */;
import TouchableHitBoxDefault from "TouchableHitBox" /* 9442 */;
import RoleLabel from "RoleLabel" /* 10079 */;
import CutoutableAvatarImage from "CutoutableAvatarImage" /* 12851 */;
import BetaTag from "BetaTag" /* 13140 */;
import IconButton_IconButton from "IconButton/IconButton" /* 13272 */;
import ShinyButton_ShinyButtonDefault from "ShinyButton/ShinyButton" /* 13900 */;
import Checkbox_CheckboxDefault from "Checkbox/Checkbox" /* 13901 */;
import CloseIconDefault from "CloseIcon" /* 13904 */;
import EllipsisDefault from "Ellipsis" /* 13905 */;
import GradientBorderDefault from "GradientBorder" /* 13906 */;
import HelpMessage from "HelpMessage" /* 13907 */;
import IconPillDefault from "IconPill" /* 13908 */;
import NewTagDefault from "NewTag" /* 13909 */;
import RadioGroup from "RadioGroup" /* 13910 */;
import CollapsibleDefault from "Collapsible" /* 13911 */;
import SummarizedIconRow from "SummarizedIconRow" /* 13912 */;
import ThemedIconDefault from "ThemedIcon" /* 13913 */;
import ThumbnailImageDefault from "ThumbnailImage" /* 13914 */;
import Tooltip_Tooltip from "Tooltip/Tooltip" /* 13916 */;
import WarningCircleDefault from "WarningCircle" /* 13917 */;
import Status_StatusUtils from "Status/StatusUtils" /* 13918 */;
import getStatusContainerStyleDefault from "getStatusContainerStyle" /* 13919 */;
import Status from "Status" /* 13920 */;
import Avatar from "Avatar" /* 13929 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 13931 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 13933 */;
import Easing from "Easing" /* 13935 */;
import SpacerDefault from "Spacer" /* 13936 */;
import LiveTagDefault from "LiveTag" /* 13937 */;
import RoleDot from "RoleDot" /* 13938 */;
import Shadows from "Shadows" /* 13939 */;
import NitroWheelDefault from "NitroWheel" /* 13940 */;
import EmptyStateDefault from "EmptyState" /* 13941 */;
import Atoms from "Atoms" /* 13942 */;
import Badge_Badge from "Badge/Badge" /* 13943 */;
import CarouselPaginationDefault from "CarouselPagination" /* 13944 */;
import InputView from "InputView" /* 13945 */;
import Badges_Badges from "Badges/Badges" /* 13946 */;
import RefreshEmptyState from "RefreshEmptyState" /* 13947 */;
import size from "module_2" /* 2 */;

const Button_ButtonDefault = Button_Button;
const IconDefault = Icon;
const OverlayViewDefault = OverlayView;
const CutoutableAvatarImageDefault = CutoutableAvatarImage;
const BetaTagDefault = BetaTag;
const HelpMessageDefault = HelpMessage;
const RadioGroupDefault = RadioGroup;
const SummarizedIconRowDefault = SummarizedIconRow;
const Tooltip_TooltipDefault = Tooltip_Tooltip;
const StatusDefault = Status;
const AvatarDefault = Avatar;
const Badge_BadgeDefault = Badge_Badge;
const InputViewDefault = InputView;
const RefreshEmptyStateDefault = RefreshEmptyState;

const STATUS_PADDING = StatusConstants.STATUS_PADDING;
const StatusSizes = StatusConstants.StatusSizes;
const BADGE_SIZE = BadgeConstants.BADGE_SIZE;
const BADGE_SIZE_UNREAD = BadgeConstants.BADGE_SIZE_UNREAD;
const BADGE_PADDING = BadgeConstants.BADGE_PADDING;
const BADGE_MASK_SIZE = BadgeConstants.BADGE_MASK_SIZE;
const BADGE_MASK_UNREAD_SIZE = BadgeConstants.BADGE_MASK_UNREAD_SIZE;
const result = size.fileFinishedImporting("design/void/native.tsx");
const BetaTag_export = BetaTagDefault;
const HelpMessage_export = HelpMessageDefault;
const OverlayView_export = OverlayViewDefault;
const RadioGroup_export = RadioGroupDefault;
const SummarizedIconRow_export = SummarizedIconRowDefault;
const Status_export = StatusDefault;
const Icon_export = IconDefault;
const CutoutableAvatarImage_export = CutoutableAvatarImageDefault;
const Avatar_export = AvatarDefault;
const RoleDot_export = RoleDot.RoleDot;
const InputView_export = InputViewDefault;
const RefreshEmptyState_export = RefreshEmptyStateDefault;
const Form_export = Form.Form;
const RoleLabel_export = RoleLabel.RoleLabel;

export const Button = Button_ButtonDefault;
export const BUTTON_CORNER_RADIUS = Button_Button.BUTTON_CORNER_RADIUS;
export const useButtonStyles = Button_Button.useButtonStyles;
export const ButtonLooks = Button_Button.ButtonLooks;
export const ButtonColors = Button_Button.ButtonColors;
export const ButtonSizes = Button_Button.ButtonSizes;
export const getButtonStyles = Button_Button.getButtonStyles;
export const ButtonText = Button_Button.ButtonText;
export const getRedesignVariant = Button_Button.getRedesignVariant;
export const getRedesignSize = Button_Button.getRedesignSize;
export const ShinyButton = ShinyButton_ShinyButtonDefault;
export { BetaTag_export as BetaTag };
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = Checkbox_CheckboxDefault;
export const CloseIcon = CloseIconDefault;
export const Ellipsis = EllipsisDefault;
export const GradientBorder = GradientBorderDefault;
export { HelpMessage_export as HelpMessage };
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export { OverlayView_export as OverlayView };
export const TransitionGroupOverlayView = OverlayView.TransitionGroupOverlayView;
export const NonExpandingOverlayView = OverlayView.NonExpandingOverlayView;
export { RadioGroup_export as RadioGroup };
export const RadioIndicator = RadioGroup.RadioIndicator;
export const RadioItem = RadioGroup.RadioItem;
export { SummarizedIconRow_export as SummarizedIconRow };
export const OverflowText = SummarizedIconRow.OverflowText;
export const OverflowTextSmall = SummarizedIconRow.OverflowTextSmall;
export const OverflowCircle = SummarizedIconRow.OverflowCircle;
export const TextInput = void_TextInput_TextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = ThumbnailImageDefault;
export const Tooltip = Tooltip_TooltipDefault;
export const TooltipArrowDirections = Tooltip_Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip_Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export { STATUS_PADDING };
export { StatusSizes };
export const getAnimatedTypingTranslateX = Status_StatusUtils.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = Status_StatusUtils.getMobileStatusContainerRect;
export const getStatusTypingDimensions = Status_StatusUtils.getStatusTypingDimensions;
export const getStatusContainerStyle = getStatusContainerStyleDefault;
export { Status_export as Status };
export const StatusWithTyping = Status.StatusWithTyping;
export { Icon_export as Icon };
export const IconSizes = Icon.IconSizes;
export const getIconSize = Icon.getIconSize;
export const getIconStyle = Icon.getIconStyle;
export { CutoutableAvatarImage_export as CutoutableAvatarImage };
export const AvatarSizes = CutoutableAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = CutoutableAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = CutoutableAvatarImage.styles;
export const CutoutDirection = CutoutableAvatarImage.CutoutDirection;
export const CutoutType = CutoutableAvatarImage.CutoutType;
export { Avatar_export as Avatar };
export const getStatusSize = Avatar.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export { BADGE_SIZE };
export { BADGE_SIZE_UNREAD };
export { BADGE_PADDING };
export { BADGE_MASK_SIZE };
export { BADGE_MASK_UNREAD_SIZE };
export const STANDARD_EASING = Easing.STANDARD_EASING;
export const DECELERATED_EASING = Easing.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export { RoleDot_export as RoleDot };
export const generateBoxShadowStyle = Shadows.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = Shadows.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = Shadows.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = Shadows.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = Shadows.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = LegacyText_LegacyTextDefault;
export const RNTextInput = Atoms.RNTextInput;
export const Badge = Badge_BadgeDefault;
export const MaskedBadge = Badge_Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export { InputView_export as InputView };
export const ClearButtonVisibility = InputView.ClearButtonVisibility;
export const BadgeColors = Badges_Badges.BadgeColors;
export const TextBadge = Badges_Badges.TextBadge;
export { RefreshEmptyState_export as RefreshEmptyState };
export const ThemedEmptyState = RefreshEmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export { Form_export as Form };
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = Pressables.PressableOpacity;
export const PressableHighlight = Pressables.PressableHighlight;
export const SquareIconButton = IconButton_IconButton.SquareIconButton;
export const CircularIconButton = IconButton_IconButton.CircularIconButton;
export const TouchableHitBox = TouchableHitBoxDefault;
export { RoleLabel_export as RoleLabel };
