// Module ID: 1177
// Function ID: 1178
// Name: native
// Dependencies: [1178, 1179, 2, 1180, 13628, 12875, 13629, 13632, 13633, 13634, 13635, 13636, 13637, 5210, 13638, 13640, 9038, 13641, 13642, 13644, 13645, 13646, 13647, 13648, 5283, 12584, 13657, 13659, 13639, 13661, 13663, 13664, 13665, 13666, 13667, 13668, 13669, 8072, 13670, 13671, 13672, 13673, 13674, 13675, 8071, 8053, 5435, 13007, 9203, 9733]

// Module 1177 (native)
import StatusConstants from "StatusConstants" /* 1178 */;
import BadgeConstants from "BadgeConstants" /* 1179 */;
import Button_Button from "Button/Button" /* 1180 */;
import OverlayView from "OverlayView" /* 5210 */;
import Icon from "Icon" /* 5283 */;
import Pressables from "Pressables" /* 5435 */;
import Form from "Form" /* 8053 */;
import CardSectionDefault from "CardSection" /* 8071 */;
import LegacyText_LegacyTextDefault from "LegacyText/LegacyText" /* 8072 */;
import TextInput_TextInputDefault from "TextInput/TextInput" /* 9038 */;
import TouchableHitBoxDefault from "TouchableHitBox" /* 9203 */;
import RoleLabel from "RoleLabel" /* 9733 */;
import CutoutableAvatarImage from "CutoutableAvatarImage" /* 12584 */;
import BetaTag from "BetaTag" /* 12875 */;
import IconButton_IconButton from "IconButton/IconButton" /* 13007 */;
import ShinyButton_ShinyButtonDefault from "ShinyButton/ShinyButton" /* 13628 */;
import Checkbox_CheckboxDefault from "Checkbox/Checkbox" /* 13629 */;
import CloseIconDefault from "CloseIcon" /* 13632 */;
import EllipsisDefault from "Ellipsis" /* 13633 */;
import GradientBorderDefault from "GradientBorder" /* 13634 */;
import HelpMessage from "HelpMessage" /* 13635 */;
import IconPillDefault from "IconPill" /* 13636 */;
import NewTagDefault from "NewTag" /* 13637 */;
import RadioGroup from "RadioGroup" /* 13638 */;
import CollapsibleDefault from "Collapsible" /* 13639 */;
import SummarizedIconRow from "SummarizedIconRow" /* 13640 */;
import ThemedIconDefault from "ThemedIcon" /* 13641 */;
import ThumbnailImageDefault from "ThumbnailImage" /* 13642 */;
import Tooltip_Tooltip from "Tooltip/Tooltip" /* 13644 */;
import WarningCircleDefault from "WarningCircle" /* 13645 */;
import Status_StatusUtils from "Status/StatusUtils" /* 13646 */;
import getStatusContainerStyleDefault from "getStatusContainerStyle" /* 13647 */;
import Status from "Status" /* 13648 */;
import Avatar from "Avatar" /* 13657 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 13659 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 13661 */;
import Easing from "Easing" /* 13663 */;
import SpacerDefault from "Spacer" /* 13664 */;
import LiveTagDefault from "LiveTag" /* 13665 */;
import RoleDot from "RoleDot" /* 13666 */;
import Shadows from "Shadows" /* 13667 */;
import NitroWheelDefault from "NitroWheel" /* 13668 */;
import EmptyStateDefault from "EmptyState" /* 13669 */;
import Atoms from "Atoms" /* 13670 */;
import Badge_Badge from "Badge/Badge" /* 13671 */;
import CarouselPaginationDefault from "CarouselPagination" /* 13672 */;
import InputView from "InputView" /* 13673 */;
import Badges_Badges from "Badges/Badges" /* 13674 */;
import RefreshEmptyState from "RefreshEmptyState" /* 13675 */;
import size from "module_2" /* 2 */;

const Button_ButtonDefault = Button_Button;
const OverlayViewDefault = OverlayView;
const IconDefault = Icon;
const CutoutableAvatarImageDefault = CutoutableAvatarImage;
const BetaTagDefault = BetaTag;
const HelpMessageDefault = HelpMessage;
const RadioGroupDefault = RadioGroup;
const SummarizedIconRowDefault = SummarizedIconRow;
const Tooltip_TooltipDefault = Tooltip_Tooltip;
const StatusDefault = Status;
const AvatarDefault = Avatar;
const Badge_BadgeDefault = Badge_Badge;
const InputViewDefault = InputView;
const RefreshEmptyStateDefault = RefreshEmptyState;

const result = size.fileFinishedImporting("design/void/native.tsx");

export const Button = Button_ButtonDefault;
export const BUTTON_CORNER_RADIUS = Button_Button.BUTTON_CORNER_RADIUS;
export const useButtonStyles = Button_Button.useButtonStyles;
export const ButtonLooks = Button_Button.ButtonLooks;
export const ButtonColors = Button_Button.ButtonColors;
export const ButtonSizes = Button_Button.ButtonSizes;
export const getButtonStyles = Button_Button.getButtonStyles;
export const ButtonText = Button_Button.ButtonText;
export const getRedesignVariant = Button_Button.getRedesignVariant;
export const getRedesignSize = Button_Button.getRedesignSize;
export const ShinyButton = ShinyButton_ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = Checkbox_CheckboxDefault;
export const CloseIcon = CloseIconDefault;
export const Ellipsis = EllipsisDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = OverlayViewDefault;
export const TransitionGroupOverlayView = OverlayView.TransitionGroupOverlayView;
export const NonExpandingOverlayView = OverlayView.NonExpandingOverlayView;
export const RadioGroup = RadioGroupDefault;
export const RadioIndicator = RadioGroup.RadioIndicator;
export const RadioItem = RadioGroup.RadioItem;
export const SummarizedIconRow = SummarizedIconRowDefault;
export const OverflowText = SummarizedIconRow.OverflowText;
export const OverflowTextSmall = SummarizedIconRow.OverflowTextSmall;
export const OverflowCircle = SummarizedIconRow.OverflowCircle;
export const TextInput = TextInput_TextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = ThumbnailImageDefault;
export const Tooltip = Tooltip_TooltipDefault;
export const TooltipArrowDirections = Tooltip_Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip_Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = StatusConstants.STATUS_PADDING;
export const StatusSizes = StatusConstants.StatusSizes;
export const getAnimatedTypingTranslateX = Status_StatusUtils.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = Status_StatusUtils.getMobileStatusContainerRect;
export const getStatusTypingDimensions = Status_StatusUtils.getStatusTypingDimensions;
export const getStatusContainerStyle = getStatusContainerStyleDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconDefault;
export const IconSizes = Icon.IconSizes;
export const getIconSize = Icon.getIconSize;
export const getIconStyle = Icon.getIconStyle;
export const CutoutableAvatarImage = CutoutableAvatarImageDefault;
export const AvatarSizes = CutoutableAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = CutoutableAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = CutoutableAvatarImage.styles;
export const CutoutDirection = CutoutableAvatarImage.CutoutDirection;
export const CutoutType = CutoutableAvatarImage.CutoutType;
export const Avatar = AvatarDefault;
export const getStatusSize = Avatar.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = BadgeConstants.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = BadgeConstants.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = BadgeConstants.BADGE_PADDING;
export const BADGE_MASK_SIZE = BadgeConstants.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = BadgeConstants.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = Easing.STANDARD_EASING;
export const DECELERATED_EASING = Easing.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = Shadows.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = Shadows.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = Shadows.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = Shadows.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = Shadows.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = LegacyText_LegacyTextDefault;
export const RNTextInput = Atoms.RNTextInput;
export const Badge = Badge_BadgeDefault;
export const MaskedBadge = Badge_Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = InputViewDefault;
export const ClearButtonVisibility = InputView.ClearButtonVisibility;
export const BadgeColors = Badges_Badges.BadgeColors;
export const TextBadge = Badges_Badges.TextBadge;
export const RefreshEmptyState = RefreshEmptyStateDefault;
export const ThemedEmptyState = RefreshEmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = Pressables.PressableOpacity;
export const PressableHighlight = Pressables.PressableHighlight;
export const SquareIconButton = IconButton_IconButton.SquareIconButton;
export const CircularIconButton = IconButton_IconButton.CircularIconButton;
export const TouchableHitBox = TouchableHitBoxDefault;
export const RoleLabel = RoleLabel.RoleLabel;
