// Module ID: 9061
// Function ID: 71153
// Name: RELATIONSHIP_COUNT_ANIMATION_THRESHOLD
// Dependencies: [2]

// Module 9061 (RELATIONSHIP_COUNT_ANIMATION_THRESHOLD)
const result = require("set").fileFinishedImporting("modules/people/Constants.tsx");

export const RELATIONSHIP_COUNT_ANIMATION_THRESHOLD = 64;
export const PEOPLE_LIST_ITEM_HEIGHT = 61;
export const PEOPLE_LIST_ITEM_HEIGHT_TALL = 72;
export const PEOPLE_LIST_SECTION_HEIGHT = 50;
export const PEOPLE_LIST_SECTION_FOOTER_HEIGHT = 48;
export const MINIMUM_PENDING_INCOMING_COUNT_FOR_CLEAR_ALL = 5;
export const ACCEPT_FRIEND_REQUEST_CONFIRMATION_MODAL_ID = "ACCEPT_FRIEND_REQUEST_CONFIRMATION_MODAL";
