// Module ID: 11210
// Function ID: 11211
// Name: RowGroup
// Dependencies: [19, 21, 4663, 4251, 5634, 5300, 1236, 2255, 11211, 4193, 9594, 4767, 11212, 11214, 9464, 8663, 4219, 11216, 5905, 5255, 2]
// Exports: default

// Module 11210 (RowGroup)
import "XSmallIcon";
import jsxProd from "jsxProd";

let c3;
let c4;
const require = arg1;
function RowGroup(children) {
  const rows = children.rows;
  let obj = { spacing: 8, children: null };
  const items = [callback(require(4251) /* Text */.Text, { accessibilityRole: "header", variant: "text-sm/semibold", color: "text-muted", children: children.title }), ];
  obj = { hasIcons: true, children: null };
  obj[1] = rows.map((header) => {
    let IconComponent;
    let description;
    let negative;
    header = header.header;
    ({ description, IconComponent, negative } = header);
    const obj = { label: header, subLabel: description, icon: null };
    let str = "default";
    if (true === negative) {
      str = "text-status-dnd";
    }
    obj[2] = closure_3(callback(5300).TableRow.Icon, { variant: str, IconComponent });
    return closure_3(callback(5300).TableRow, obj, header);
  });
  items[1] = callback(require(5634) /* TableRowGroupTitle */.TableRowGroup, obj);
  obj[1] = items;
  return callback2(require(4663) /* Stack */.Stack, obj);
}
({ jsx: c3, jsxs: c4 } = jsxProd);
const result = require("Stack").fileFinishedImporting("modules/parent_tools/native/FamilyCenterDataConfirmation.tsx");

export default function FamilyCenterDataConfirmation() {
  const intl = require(1236) /* getSystemLocale */.intl;
  const intl2 = require(1236) /* getSystemLocale */.intl;
  const stringResult = intl.string(importDefault(2255).CI1Env);
  const intl3 = require(1236) /* getSystemLocale */.intl;
  const stringResult1 = intl2.string(importDefault(2255)["ksze+o"]);
  let obj = require(11211) /* useAgeSpecificText */;
  const intl4 = require(1236) /* getSystemLocale */.intl;
  const stringResult2 = intl3.string(importDefault(2255)["n73g+V"]);
  const intl5 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText = obj.useAgeSpecificText(intl4.string(importDefault(2255)["5x3taM"]), intl5.string(importDefault(2255).WZwGFX));
  let obj1 = require(11211) /* useAgeSpecificText */;
  const intl6 = require(1236) /* getSystemLocale */.intl;
  const stringResult3 = intl4.string(importDefault(2255)["5x3taM"]);
  const intl7 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText1 = obj1.useAgeSpecificText(intl6.string(importDefault(2255).FcKkcr), intl7.string(importDefault(2255).PQtDFk));
  let obj2 = require(11211) /* useAgeSpecificText */;
  const intl8 = require(1236) /* getSystemLocale */.intl;
  const stringResult4 = intl6.string(importDefault(2255).FcKkcr);
  const intl9 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText2 = obj2.useAgeSpecificText(intl8.string(importDefault(2255)["dES/2r"]), intl9.string(importDefault(2255).ep6mdN));
  let obj3 = require(11211) /* useAgeSpecificText */;
  const intl10 = require(1236) /* getSystemLocale */.intl;
  const stringResult5 = intl8.string(importDefault(2255)["dES/2r"]);
  const intl11 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText3 = obj3.useAgeSpecificText(intl10.string(importDefault(2255).GWPcQg), intl11.string(importDefault(2255).yFnKIg));
  let obj4 = require(11211) /* useAgeSpecificText */;
  const intl12 = require(1236) /* getSystemLocale */.intl;
  const stringResult6 = intl10.string(importDefault(2255).GWPcQg);
  const intl13 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText4 = obj4.useAgeSpecificText(intl12.string(importDefault(2255)["30+sih"]), intl13.string(importDefault(2255)["0cuLn1"]));
  let obj5 = require(11211) /* useAgeSpecificText */;
  const intl14 = require(1236) /* getSystemLocale */.intl;
  const stringResult7 = intl12.string(importDefault(2255)["30+sih"]);
  const intl15 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText5 = obj5.useAgeSpecificText(intl14.string(importDefault(2255).tHTyRh), intl15.string(importDefault(2255).TeNlMb));
  let obj6 = require(11211) /* useAgeSpecificText */;
  const intl16 = require(1236) /* getSystemLocale */.intl;
  const stringResult8 = intl14.string(importDefault(2255).tHTyRh);
  const intl17 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText6 = obj6.useAgeSpecificText(intl16.string(importDefault(2255).PfveQ6), intl17.string(importDefault(2255)["f7ofm/"]));
  let obj7 = require(11211) /* useAgeSpecificText */;
  const intl18 = require(1236) /* getSystemLocale */.intl;
  const stringResult9 = intl16.string(importDefault(2255).PfveQ6);
  const intl19 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText7 = obj7.useAgeSpecificText(intl18.string(importDefault(2255).MKeCj3), intl19.string(importDefault(2255).HdcGGl));
  let obj8 = require(11211) /* useAgeSpecificText */;
  const intl20 = require(1236) /* getSystemLocale */.intl;
  const stringResult10 = intl18.string(importDefault(2255).MKeCj3);
  const intl21 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText8 = obj8.useAgeSpecificText(intl20.string(importDefault(2255).wZejZr), intl21.string(importDefault(2255).tdgcf1));
  let obj9 = require(11211) /* useAgeSpecificText */;
  const intl22 = require(1236) /* getSystemLocale */.intl;
  const stringResult11 = intl20.string(importDefault(2255).wZejZr);
  const intl23 = require(1236) /* getSystemLocale */.intl;
  const ageSpecificText9 = obj9.useAgeSpecificText(intl22.string(importDefault(2255).ASf7XN), intl23.string(importDefault(2255)["82y87X"]));
  let obj10 = require(11211) /* useAgeSpecificText */;
  const intl24 = require(1236) /* getSystemLocale */.intl;
  const stringResult12 = intl22.string(importDefault(2255).ASf7XN);
  const intl25 = require(1236) /* getSystemLocale */.intl;
  obj = { header: null, description: null, IconComponent: null };
  const ageSpecificText10 = obj10.useAgeSpecificText(intl24.string(importDefault(2255)["0QDVFN"]), intl25.string(importDefault(2255)["1xBHHV"]));
  const intl26 = require(1236) /* getSystemLocale */.intl;
  obj[0] = intl26.string(importDefault(2255)["/zMYZX"]);
  obj[1] = ageSpecificText;
  obj[2] = require(4193) /* UserPlusIcon */.UserPlusIcon;
  const items = [obj, , , , , , ];
  obj = { header: null, description: null, IconComponent: null };
  const intl27 = require(1236) /* getSystemLocale */.intl;
  obj[0] = intl27.string(importDefault(2255)["44NEx6"]);
  obj[1] = ageSpecificText1;
  obj[2] = require(9594) /* ServerIcon */.ServerIcon;
  items[1] = obj;
  obj1 = { header: null, description: null, IconComponent: null };
  const intl28 = require(1236) /* getSystemLocale */.intl;
  obj1[0] = intl28.string(importDefault(2255)["Z3G+8h"]);
  const intl29 = require(1236) /* getSystemLocale */.intl;
  obj1[1] = intl29.string(importDefault(2255).KBgArX);
  obj1[2] = require(4767) /* ForumIcon */.ForumIcon;
  items[2] = obj1;
  obj2 = { header: null, description: null, IconComponent: null };
  const intl30 = require(1236) /* getSystemLocale */.intl;
  obj2[0] = intl30.string(importDefault(2255).GNs2ZH);
  const intl31 = require(1236) /* getSystemLocale */.intl;
  obj2[1] = intl31.string(importDefault(2255).Ief2xc);
  obj2[2] = require(11212) /* PhoneIcon */.PhoneIcon;
  items[3] = obj2;
  obj3 = { header: null, description: null, IconComponent: null };
  const intl32 = require(1236) /* getSystemLocale */.intl;
  obj3[0] = intl32.string(importDefault(2255).PjM3r5);
  obj3[1] = ageSpecificText2;
  obj3[2] = require(11214) /* CreditCardIcon */.CreditCardIcon;
  items[4] = obj3;
  obj4 = { header: null, description: null, IconComponent: null };
  const intl33 = require(1236) /* getSystemLocale */.intl;
  obj4[0] = intl33.string(importDefault(2255).Fv3n8L);
  obj4[1] = ageSpecificText3;
  obj4[2] = require(9464) /* GiftIcon */.GiftIcon;
  items[5] = obj4;
  obj5 = { header: ageSpecificText4, description: ageSpecificText5, IconComponent: require(8663) /* FlagIcon */.FlagIcon };
  items[6] = obj5;
  obj6 = { header: null, description: null, IconComponent: null };
  const intl34 = require(1236) /* getSystemLocale */.intl;
  obj6[0] = intl34.string(importDefault(2255).kyT6pZ);
  obj6[1] = ageSpecificText6;
  obj6[2] = require(4219) /* ClockIcon */.ClockIcon;
  const items1 = [obj6, , ];
  obj7 = { header: null, description: null, IconComponent: null };
  const intl35 = require(1236) /* getSystemLocale */.intl;
  obj7[0] = intl35.string(importDefault(2255)["52ld7c"]);
  obj7[1] = ageSpecificText7;
  obj7[2] = require(11216) /* PiggyBankIcon */.PiggyBankIcon;
  items1[1] = obj7;
  obj8 = { header: null, description: null, IconComponent: null };
  const intl36 = require(1236) /* getSystemLocale */.intl;
  obj8[0] = intl36.string(importDefault(2255).UCuHM8);
  obj8[1] = ageSpecificText8;
  obj8[2] = require(5905) /* SettingsIcon */.SettingsIcon;
  items1[2] = obj8;
  obj9 = { spacing: 24, children: null };
  const items2 = [callback(RowGroup, { title: stringResult, rows: items }), callback(RowGroup, { title: stringResult1, rows: items1 }), ];
  obj10 = { title: stringResult2, rows: null };
  const stringResult13 = intl24.string(importDefault(2255)["0QDVFN"]);
  const items3 = [{ header: ageSpecificText9, description: ageSpecificText10, IconComponent: require(5255) /* XSmallIcon */.XSmallIcon, negative: true }];
  obj10[1] = items3;
  items2[2] = callback(RowGroup, obj10);
  obj9[1] = items2;
  return callback2(require(4663) /* Stack */.Stack, obj9);
};
