// Module ID: 14819
// Function ID: 14820
// Name: NotificationSettingsConstants
// Dependencies: [2812, 14820, 14821, 2]

// Module 14819 (NotificationSettingsConstants)
import _modDef2812 from "module_2812" /* 2812 */;
import NotifSettings from "NotifSettings" /* 14820 */;
import NotifTypes from "NotifTypes" /* 14821 */;
import size from "module_2" /* 2 */;

const obj = { badge: true, visibility: "popup", vibrate: true, sound: true };
const obj2 = { badge: true, visibility: "default", vibrate: true, sound: true };
const obj3 = { badge: true, visibility: "default", vibrate: false, sound: false };
const items = [{ title: _modDef2812.S5cB9e, string_id: "111_realtime" }, , , ];
const obj4 = { title: _modDef2812.S5cB9e, string_id: "111_realtime" };
items[1] = { title: _modDef2812["UzRF+8"], string_id: "222_social" };
const obj5 = { title: _modDef2812["UzRF+8"], string_id: "222_social" };
items[2] = { title: _modDef2812.zRKbpz, string_id: "333_server" };
const obj6 = { title: _modDef2812.zRKbpz, string_id: "333_server" };
items[3] = { title: _modDef2812.q5M7HV, string_id: "444_other" };
const obj7 = { title: _modDef2812.q5M7HV, string_id: "444_other" };
const items1 = [{ title: _modDef2812["IUH/Oe"], id: NotifSettings.NotifSettings.CALLS, string_id: "calls", category: "111_realtime", behavior: { badge: false, ringtone: "call_ringing", visibility: "popup", vibrate: true, sound: true }, systemOnly: true }, , , , , , , , , , , , , , , , , , , , ];
const obj8 = { title: _modDef2812["IUH/Oe"], id: NotifSettings.NotifSettings.CALLS, string_id: "calls", category: "111_realtime", behavior: { badge: false, ringtone: "call_ringing", visibility: "popup", vibrate: true, sound: true }, systemOnly: true };
items1[1] = { title: _modDef2812.VeBD1N, id: NotifSettings.NotifSettings.VOICE_CONNECTED, string_id: "mediaConnections", category: "111_realtime", behavior: { badge: false, visibility: "default", vibrate: false, sound: true }, systemOnly: true };
const obj9 = { title: _modDef2812.VeBD1N, id: NotifSettings.NotifSettings.VOICE_CONNECTED, string_id: "mediaConnections", category: "111_realtime", behavior: { badge: false, visibility: "default", vibrate: false, sound: true }, systemOnly: true };
items1[2] = { title: _modDef2812.NGdNZb, id: NotifSettings.NotifSettings.DMS, string_id: "directMessages", category: "222_social", behavior: obj, systemOnly: true };
const obj10 = { title: _modDef2812.NGdNZb, id: NotifSettings.NotifSettings.DMS, string_id: "directMessages", category: "222_social", behavior: obj, systemOnly: true };
items1[3] = { title: _modDef2812.NxgGZA, id: NotifSettings.NotifSettings.FRIEND_REQUESTS, string_id: "friendRequests", category: "222_social", behavior: obj, systemOnly: true };
const obj11 = { title: _modDef2812.NxgGZA, id: NotifSettings.NotifSettings.FRIEND_REQUESTS, string_id: "friendRequests", category: "222_social", behavior: obj, systemOnly: true };
items1[4] = { title: _modDef2812.MOjygY, id: NotifSettings.NotifSettings.POLLS, string_id: "polls", category: "222_social", behavior: obj2, systemOnly: true };
const obj12 = { title: _modDef2812.MOjygY, id: NotifSettings.NotifSettings.POLLS, string_id: "polls", category: "222_social", behavior: obj2, systemOnly: true };
items1[5] = { title: _modDef2812.wv4QHR, id: NotifSettings.NotifSettings.REACTIONS, string_id: "reactions", category: "222_social", behavior: obj2 };
const obj13 = { title: _modDef2812.wv4QHR, id: NotifSettings.NotifSettings.REACTIONS, string_id: "reactions", category: "222_social", behavior: obj2 };
items1[6] = { title: _modDef2812.n0Wp6j, id: NotifSettings.NotifSettings.MISSED_MESSAGES_LOW, string_id: "missed_messages_low", category: "222_social", behavior: obj3, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 2, 3, 4] };
const obj14 = { title: _modDef2812.n0Wp6j, id: NotifSettings.NotifSettings.MISSED_MESSAGES_LOW, string_id: "missed_messages_low", category: "222_social", behavior: obj3, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 2, 3, 4] };
items1[7] = { title: _modDef2812.n0Wp6j, id: NotifSettings.NotifSettings.MISSED_MESSAGES_DEFAULT, string_id: "missed_messages_default", category: "222_social", behavior: obj2, experiment: "2026-05-noisier-notif-settings-defaults", variations: [1, 5] };
const obj15 = { title: _modDef2812.n0Wp6j, id: NotifSettings.NotifSettings.MISSED_MESSAGES_DEFAULT, string_id: "missed_messages_default", category: "222_social", behavior: obj2, experiment: "2026-05-noisier-notif-settings-defaults", variations: [1, 5] };
items1[8] = { title: _modDef2812.Iy9grw, id: NotifSettings.NotifSettings.VOICE_ACTIVITY_LOW, string_id: "voice_activity_low", category: "222_social", behavior: obj3, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 1, 3, 4] };
const obj16 = { title: _modDef2812.Iy9grw, id: NotifSettings.NotifSettings.VOICE_ACTIVITY_LOW, string_id: "voice_activity_low", category: "222_social", behavior: obj3, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 1, 3, 4] };
items1[9] = { title: _modDef2812.Iy9grw, id: NotifSettings.NotifSettings.VOICE_ACTIVITY_DEFAULT, string_id: "voice_activity_default", category: "222_social", behavior: obj2, experiment: "2026-05-noisier-notif-settings-defaults", variations: [2, 5] };
const obj17 = { title: _modDef2812.Iy9grw, id: NotifSettings.NotifSettings.VOICE_ACTIVITY_DEFAULT, string_id: "voice_activity_default", category: "222_social", behavior: obj2, experiment: "2026-05-noisier-notif-settings-defaults", variations: [2, 5] };
items1[10] = { title: _modDef2812["9EDo+/"], id: NotifSettings.NotifSettings.GAMING_LOW, string_id: "gaming_low", category: "222_social", behavior: obj3, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 1, 2, 4] };
const obj18 = { title: _modDef2812["9EDo+/"], id: NotifSettings.NotifSettings.GAMING_LOW, string_id: "gaming_low", category: "222_social", behavior: obj3, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 1, 2, 4] };
items1[11] = { title: _modDef2812["9EDo+/"], id: NotifSettings.NotifSettings.GAMING_DEFAULT, string_id: "gaming_default", category: "222_social", behavior: obj2, experiment: "2026-05-noisier-notif-settings-defaults", variations: [3, 5] };
const obj19 = { title: _modDef2812["9EDo+/"], id: NotifSettings.NotifSettings.GAMING_DEFAULT, string_id: "gaming_default", category: "222_social", behavior: obj2, experiment: "2026-05-noisier-notif-settings-defaults", variations: [3, 5] };
items1[12] = { title: _modDef2812.vcrTV5, id: NotifSettings.NotifSettings.FRIEND_ACTIVITY_LOW, string_id: "social", category: "222_social", behavior: obj3, systemOnly: true, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 1, 2, 3] };
const obj20 = { title: _modDef2812.vcrTV5, id: NotifSettings.NotifSettings.FRIEND_ACTIVITY_LOW, string_id: "social", category: "222_social", behavior: obj3, systemOnly: true, experiment: "2026-05-noisier-notif-settings-defaults", variations: [0, 1, 2, 3] };
items1[13] = { title: _modDef2812.vcrTV5, id: NotifSettings.NotifSettings.FRIEND_ACTIVITY_DEFAULT, string_id: "social", category: "222_social", behavior: obj2, systemOnly: true, experiment: "2026-05-noisier-notif-settings-defaults", variations: [4, 5] };
const obj21 = { title: _modDef2812.vcrTV5, id: NotifSettings.NotifSettings.FRIEND_ACTIVITY_DEFAULT, string_id: "social", category: "222_social", behavior: obj2, systemOnly: true, experiment: "2026-05-noisier-notif-settings-defaults", variations: [4, 5] };
items1[14] = { title: _modDef2812["4qWUAO"], id: NotifSettings.NotifSettings.GUILD_MESSAGES, string_id: "messages", category: "333_server", behavior: obj, systemOnly: true };
const obj22 = { title: _modDef2812["4qWUAO"], id: NotifSettings.NotifSettings.GUILD_MESSAGES, string_id: "messages", category: "333_server", behavior: obj, systemOnly: true };
items1[15] = { title: _modDef2812.HibKoy, id: NotifSettings.NotifSettings.FORUM_NOTIFICATIONS, string_id: "forumThreadCreated", category: "333_server", behavior: obj, systemOnly: true };
const obj23 = { title: _modDef2812.HibKoy, id: NotifSettings.NotifSettings.FORUM_NOTIFICATIONS, string_id: "forumThreadCreated", category: "333_server", behavior: obj, systemOnly: true };
items1[16] = { title: _modDef2812["40TIqW"], id: NotifSettings.NotifSettings.GUILD_EVENT_NOTIFICATIONS, string_id: "guildEventLive", category: "333_server", behavior: obj, systemOnly: true };
const obj24 = { title: _modDef2812["40TIqW"], id: NotifSettings.NotifSettings.GUILD_EVENT_NOTIFICATIONS, string_id: "guildEventLive", category: "333_server", behavior: obj, systemOnly: true };
items1[17] = { title: _modDef2812["4n388K"], id: NotifSettings.NotifSettings.STAGE_NOTIFICATIONS, string_id: "stageLive", category: "333_server", behavior: obj, systemOnly: true };
const obj25 = { title: _modDef2812["4n388K"], id: NotifSettings.NotifSettings.STAGE_NOTIFICATIONS, string_id: "stageLive", category: "333_server", behavior: obj, systemOnly: true };
items1[18] = { title: _modDef2812.kIrLfg, id: NotifSettings.NotifSettings.OTHER_GUILD, string_id: "other", category: "333_server", behavior: obj3, systemOnly: true };
const obj26 = { title: _modDef2812.kIrLfg, id: NotifSettings.NotifSettings.OTHER_GUILD, string_id: "other", category: "333_server", behavior: obj3, systemOnly: true };
items1[19] = { title: _modDef2812["T+79Eo"], id: NotifSettings.NotifSettings.OTHER, string_id: "default", category: "444_other", behavior: obj3, systemOnly: true };
const obj27 = { title: _modDef2812["T+79Eo"], id: NotifSettings.NotifSettings.OTHER, string_id: "default", category: "444_other", behavior: obj3, systemOnly: true };
items1[20] = { title: _modDef2812.zJlwvV, id: NotifSettings.NotifSettings.SYSTEM, string_id: "systemMessages", category: "444_other", behavior: obj, systemOnly: true };
const obj29 = {};
const items2 = [NotifSettings.NotifSettings.VOICE_ACTIVITY_LOW, NotifSettings.NotifSettings.VOICE_ACTIVITY_DEFAULT];
obj29[NotifTypes.NotifTypes.GUILD_STREAM_START] = items2;
const items3 = [NotifSettings.NotifSettings.STAGE_NOTIFICATIONS];
obj29[NotifTypes.NotifTypes.STAGE_INSTANCE_CREATE] = items3;
const items4 = [NotifSettings.NotifSettings.VOICE_ACTIVITY_LOW, NotifSettings.NotifSettings.VOICE_ACTIVITY_DEFAULT];
obj29[NotifTypes.NotifTypes.GO_LIVE_NOTIFICATION] = items4;
const items5 = [NotifSettings.NotifSettings.VOICE_ACTIVITY_LOW, NotifSettings.NotifSettings.VOICE_ACTIVITY_DEFAULT];
obj29[NotifTypes.NotifTypes.VOICE_CHANNEL_ACTIVITY] = items5;
const items6 = [NotifSettings.NotifSettings.MISSED_MESSAGES_LOW, NotifSettings.NotifSettings.MISSED_MESSAGES_DEFAULT];
obj29[NotifTypes.NotifTypes.MISSED_MESSAGE_PUSH] = items6;
const items7 = [NotifSettings.NotifSettings.GAMING_LOW, NotifSettings.NotifSettings.GAMING_DEFAULT];
obj29[NotifTypes.NotifTypes.FRIEND_GAMING_ACTIVITY_PUSH] = items7;
const items8 = [NotifSettings.NotifSettings.GAMING_LOW, NotifSettings.NotifSettings.GAMING_DEFAULT];
obj29[NotifTypes.NotifTypes.FRIENDS_PLAYING_GAME] = items8;
const items9 = [NotifSettings.NotifSettings.GAMING_LOW, NotifSettings.NotifSettings.GAMING_DEFAULT];
obj29[NotifTypes.NotifTypes.FRIENDS_PLAYING_TRENDING_GAME] = items9;
const items10 = [NotifSettings.NotifSettings.SYSTEM];
obj29[NotifTypes.NotifTypes.PARENTAL_CONSENT_FINAL_WARNING] = items10;
const items11 = [NotifSettings.NotifSettings.FRIEND_ACTIVITY_LOW, NotifSettings.NotifSettings.FRIEND_ACTIVITY_DEFAULT];
obj29[NotifTypes.NotifTypes.CUSTOM_STATUS_UPDATE] = items11;
const items12 = [NotifSettings.NotifSettings.FRIEND_ACTIVITY_LOW, NotifSettings.NotifSettings.FRIEND_ACTIVITY_DEFAULT];
obj29[NotifTypes.NotifTypes.PROFILE_UPDATES_NOTIFICATION] = items12;
const result = size.fileFinishedImporting("modules/notifications/NotificationSettingsConstants.tsx");

export const NOTIF_CATEGORIES = items;
export const NOTIF_SETTINGS = items1;
export const NOTIF_SETTING_MAPPING = obj29;
