// Module ID: 4962
// Function ID: 42623
// Name: ACTION_SHEET_START_HEIGHT_RATIO
// Dependencies: []

// Module 4962 (ACTION_SHEET_START_HEIGHT_RATIO)
const _module = require(dependencyMap[0]);
const result = _module.fileFinishedImporting("modules/action_sheet/native/ActionSheetConstants.tsx");

export const ACTION_SHEET_START_HEIGHT_RATIO = 0.6;
export const ACTION_SHEET_MAX_DYNAMIC_CONTENT_SIZE_RATIO = 0.85;
export const ACTION_SHEET_BORDER_RADIUS_LEGACY = 8;
export const ACTION_SHEET_BORDER_RADIUS_REDESIGN = 24;
export const ACTION_SHEET_INNER_BORDER_RADIUS_LEGACY = 6;
export const ACTION_SHEET_INNER_BORDER_RADIUS_REDESIGN = 22;
export const ACTION_SHEET_MAX_WIDTH = 500;
export const ACTION_SHEET_SPRING_CONFIG = {};
export const ACTION_SHEET_SPRING_CONFIG_REDUCED_MOTION = { duration: 250 };
export const ACTION_SHEET_BORDER_RADIUS = 24;
export const ACTION_SHEET_INNER_BORDER_RADIUS = 22;
export const ACTION_SHEET_GRADIENT_BORDER_WIDTH = 2;
export const ACTION_SHEET_GRADIENT_BORDER_RADIUS = 20;
export const ACTION_SHEET_HANDLE_PADDING = 8;
export const ACTION_SHEET_HANDLE_HEIGHT = 4;
export const ACTION_SHEET_HANDLE_SPACING = 20;
export const ACTION_SHEET_HANDLE_SPACING_REDESIGN = 12;
export const ACTION_SHEET_HANDLE_OVERHANG_REDESIGN = 8;
export const ACTION_SHEET_MINIMUM_BOTTOM_PADDING = 16;
