// Module ID: 14794
// Function ID: 14795
// Name: items1
// Dependencies: [676, 1236, 14795, 14796, 14797, 14798, 14799, 14800, 14801, 14802, 14803, 14804, 13585, 10058, 14805, 2]
// Exports: default

// Module 14794 (items1)
import set from "set" /* 2 */;
import ME from "ME" /* 676 */;
import getSystemLocale from "getSystemLocale" /* 1236 */;
import registerAssetDefault from "registerAsset" /* 10058 */;
import registerAssetDefault2 from "registerAsset" /* 13585 */;
import registerAssetDefault3 from "registerAsset" /* 14795 */;
import registerAssetDefault4 from "registerAsset" /* 14796 */;
import registerAssetDefault5 from "registerAsset" /* 14797 */;
import registerAssetDefault6 from "registerAsset" /* 14798 */;
import registerAssetDefault7 from "registerAsset" /* 14799 */;
import registerAssetDefault8 from "registerAsset" /* 14800 */;
import registerAssetDefault9 from "registerAsset" /* 14801 */;
import registerAssetDefault10 from "registerAsset" /* 14802 */;
import registerAssetDefault11 from "registerAsset" /* 14803 */;
import registerAssetDefault12 from "registerAsset" /* 14804 */;
import registerAssetDefault13 from "registerAsset" /* 14805 */;

const StatusTypes = ME.StatusTypes;
const result = set.fileFinishedImporting("modules/user_settings/appearance/native/SettingsAppearanceDummyData.tsx");

export default function _default() {
  const items = [{ id: "1", kind: "messages-header" }, , , , , , , , , , ];
  let obj = { id: "2", kind: "activity-cards", cards: null };
  obj = { title: null, subtitle: null, kind: "activity", image: null, avatars: null };
  const intl = getSystemLocale.intl;
  obj[0] = intl.string(getSystemLocale.t.B6GPzA);
  const intl2 = getSystemLocale.intl;
  obj[1] = intl2.string(getSystemLocale.t["Tnrh/k"]);
  obj[3] = registerAssetDefault3;
  const items1 = [registerAssetDefault4, registerAssetDefault5, registerAssetDefault6, registerAssetDefault7, registerAssetDefault8];
  obj[4] = items1;
  const items2 = [obj, ];
  obj = { title: null, subtitle: null, kind: "voice-chat", image: null };
  const intl3 = getSystemLocale.intl;
  obj[0] = intl3.string(getSystemLocale.t.YAgqmE);
  const intl4 = getSystemLocale.intl;
  obj[1] = intl4.string(getSystemLocale.t["9YJgal"]);
  obj[3] = registerAssetDefault9;
  items2[1] = obj;
  obj[2] = items2;
  items[1] = obj;
  obj1 = { id: "3", kind: "channel-row", timestamp: null, title: null, preview: null, isUnread: true, avatar1: null };
  const intl5 = getSystemLocale.intl;
  obj1[2] = intl5.formatToPlainString(getSystemLocale.t["XIGt+W"], { minutes: 24 });
  const intl6 = getSystemLocale.intl;
  obj1[3] = intl6.string(getSystemLocale.t["mK5Zd+"]);
  const intl7 = getSystemLocale.intl;
  obj1[4] = intl7.string(getSystemLocale.t.cvvVUV);
  obj1[6] = registerAssetDefault10;
  items[2] = obj1;
  const obj2 = { id: "4", kind: "channel-row", timestamp: null, title: null, preview: null, isUnread: true, avatar1: null, avatar2: null };
  const intl8 = getSystemLocale.intl;
  obj2[2] = intl8.formatToPlainString(getSystemLocale.t["XIGt+W"], { minutes: 32 });
  const intl9 = getSystemLocale.intl;
  obj2[3] = intl9.string(getSystemLocale.t.FpJH9k);
  const intl10 = getSystemLocale.intl;
  obj2[4] = intl10.string(getSystemLocale.t.F1WIrQ);
  obj2[6] = registerAssetDefault11;
  obj2[7] = registerAssetDefault12;
  items[3] = obj2;
  const obj3 = { id: "5", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, status: null };
  const intl11 = getSystemLocale.intl;
  obj3[2] = intl11.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 1 });
  const intl12 = getSystemLocale.intl;
  obj3[3] = intl12.string(getSystemLocale.t.PHbyD7);
  const intl13 = getSystemLocale.intl;
  obj3[4] = intl13.string(getSystemLocale.t.GSuP1s);
  obj3[5] = registerAssetDefault2;
  obj3[6] = StatusTypes.IDLE;
  items[4] = obj3;
  const obj4 = { id: "7", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, avatar2: null };
  const intl14 = getSystemLocale.intl;
  obj4[2] = intl14.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 2 });
  const intl15 = getSystemLocale.intl;
  obj4[3] = intl15.string(getSystemLocale.t["0HGnUV"]);
  const intl16 = getSystemLocale.intl;
  obj4[4] = intl16.string(getSystemLocale.t["VYL+vm"]);
  obj4[5] = registerAssetDefault;
  obj4[6] = registerAssetDefault6;
  items[5] = obj4;
  const obj5 = { id: "10", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null };
  const intl17 = getSystemLocale.intl;
  obj5[2] = intl17.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 2 });
  const intl18 = getSystemLocale.intl;
  obj5[3] = intl18.string(getSystemLocale.t["z+f+zN"]);
  const intl19 = getSystemLocale.intl;
  obj5[4] = intl19.string(getSystemLocale.t.Wy2xnv);
  obj5[5] = registerAssetDefault12;
  items[6] = obj5;
  const obj6 = { id: "11", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, avatar2: null };
  const intl20 = getSystemLocale.intl;
  obj6[2] = intl20.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 4 });
  const intl21 = getSystemLocale.intl;
  obj6[3] = intl21.string(getSystemLocale.t["AYOqO/"]);
  const intl22 = getSystemLocale.intl;
  obj6[4] = intl22.string(getSystemLocale.t.OrbvPP);
  obj6[5] = registerAssetDefault7;
  obj6[6] = registerAssetDefault;
  items[7] = obj6;
  const obj7 = { id: "12", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, status: null };
  const intl23 = getSystemLocale.intl;
  obj7[2] = intl23.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 6 });
  const intl24 = getSystemLocale.intl;
  obj7[3] = intl24.string(getSystemLocale.t["86rWJp"]);
  const intl25 = getSystemLocale.intl;
  obj7[4] = intl25.string(getSystemLocale.t.dFT4dX);
  obj7[5] = registerAssetDefault13;
  obj7[6] = StatusTypes.DND;
  items[8] = obj7;
  const obj8 = { id: "13", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null };
  const intl26 = getSystemLocale.intl;
  obj8[2] = intl26.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 18 });
  const intl27 = getSystemLocale.intl;
  obj8[3] = intl27.string(getSystemLocale.t["z3+vGV"]);
  const intl28 = getSystemLocale.intl;
  obj8[4] = intl28.string(getSystemLocale.t.Zj8Sl1);
  obj8[5] = registerAssetDefault7;
  items[9] = obj8;
  const obj9 = { id: "15", kind: "channel-row", timestamp: null, title: null, preview: null, avatar1: null, status: null };
  const intl29 = getSystemLocale.intl;
  obj9[2] = intl29.formatToPlainString(getSystemLocale.t.rhY1Rs, { hours: 21 });
  const intl30 = getSystemLocale.intl;
  obj9[3] = intl30.string(getSystemLocale.t["8SENG2"]);
  const intl31 = getSystemLocale.intl;
  obj9[4] = intl31.string(getSystemLocale.t["2ziAWp"]);
  obj9[5] = registerAssetDefault5;
  obj9[6] = StatusTypes.DND;
  items[10] = obj9;
  return items;
};
