// Module ID: 4503
// Function ID: 4504
// Name: parsers
// Dependencies: [4504, 4506, 4509, 4510, 4511, 4512, 4513, 4514, 4515, 4516, 4518, 4520, 4521, 4522, 4524, 4525, 4526, 4528, 4529, 4530, 4531, 4532, 4533, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4541]

// Module 4503 (parsers)
import EraParser from "EraParser" /* 4504 */;
import YearParser from "YearParser" /* 4506 */;
import LocalWeekYearParser from "LocalWeekYearParser" /* 4509 */;
import ISOWeekYearParser from "ISOWeekYearParser" /* 4510 */;
import ExtendedYearParser from "ExtendedYearParser" /* 4511 */;
import QuarterParser from "QuarterParser" /* 4512 */;
import StandAloneQuarterParser from "StandAloneQuarterParser" /* 4513 */;
import MonthParser from "MonthParser" /* 4514 */;
import StandAloneMonthParser from "StandAloneMonthParser" /* 4515 */;
import LocalWeekParser from "LocalWeekParser" /* 4516 */;
import ISOWeekParser from "ISOWeekParser" /* 4518 */;
import DateParser from "DateParser" /* 4520 */;
import DayOfYearParser from "DayOfYearParser" /* 4521 */;
import DayParser from "DayParser" /* 4522 */;
import LocalDayParser from "LocalDayParser" /* 4524 */;
import StandAloneLocalDayParser from "StandAloneLocalDayParser" /* 4525 */;
import ISODayParser from "ISODayParser" /* 4526 */;
import AMPMParser from "AMPMParser" /* 4528 */;
import AMPMMidnightParser from "AMPMMidnightParser" /* 4529 */;
import DayPeriodParser from "DayPeriodParser" /* 4530 */;
import Hour1to12Parser from "Hour1to12Parser" /* 4531 */;
import Hour0to23Parser from "Hour0to23Parser" /* 4532 */;
import Hour0To11Parser from "Hour0To11Parser" /* 4533 */;
import Hour1To24Parser from "Hour1To24Parser" /* 4534 */;
import MinuteParser from "MinuteParser" /* 4535 */;
import SecondParser from "SecondParser" /* 4536 */;
import FractionOfSecondParser from "FractionOfSecondParser" /* 4537 */;
import ISOTimezoneWithZParser from "ISOTimezoneWithZParser" /* 4538 */;
import ISOTimezoneParser from "ISOTimezoneParser" /* 4539 */;
import TimestampSecondsParser from "TimestampSecondsParser" /* 4540 */;
import TimestampMillisecondsParser from "TimestampMillisecondsParser" /* 4541 */;

let aMPMMidnightParser;
let aMPMParser;
let dateParser;
let dayOfYearParser;
let dayParser;
let dayPeriodParser;
let eraParser;
let extendedYearParser;
let fractionOfSecondParser;
let hour0To11Parser;
let hour0to23Parser;
let hour1To24Parser;
let hour1to12Parser;
let iSODayParser;
let iSOTimezoneParser;
let iSOTimezoneWithZParser;
let iSOWeekParser;
let iSOWeekYearParser;
let localDayParser;
let localWeekParser;
let localWeekYearParser;
let minuteParser;
let monthParser;
let quarterParser;
let secondParser;
let standAloneLocalDayParser;
let standAloneMonthParser;
let standAloneQuarterParser;
let timestampMillisecondsParser;
let timestampSecondsParser;
let yearParser;
const point = { G: eraParser, y: yearParser, Y: localWeekYearParser, R: iSOWeekYearParser, u: extendedYearParser, Q: quarterParser, q: standAloneQuarterParser, M: monthParser, L: standAloneMonthParser, w: localWeekParser, I: iSOWeekParser, d: dateParser, D: dayOfYearParser, E: dayParser, e: localDayParser, c: standAloneLocalDayParser, i: iSODayParser, a: aMPMParser, b: aMPMMidnightParser, B: dayPeriodParser, h: hour1to12Parser, H: hour0to23Parser, K: hour0To11Parser, k: hour1To24Parser, m: minuteParser, s: secondParser, S: fractionOfSecondParser, X: iSOTimezoneWithZParser, x: iSOTimezoneParser, t: timestampSecondsParser, T: timestampMillisecondsParser };
eraParser = new EraParser.EraParser();
yearParser = new YearParser.YearParser();
localWeekYearParser = new LocalWeekYearParser.LocalWeekYearParser();
iSOWeekYearParser = new ISOWeekYearParser.ISOWeekYearParser();
extendedYearParser = new ExtendedYearParser.ExtendedYearParser();
quarterParser = new QuarterParser.QuarterParser();
standAloneQuarterParser = new StandAloneQuarterParser.StandAloneQuarterParser();
monthParser = new MonthParser.MonthParser();
standAloneMonthParser = new StandAloneMonthParser.StandAloneMonthParser();
localWeekParser = new LocalWeekParser.LocalWeekParser();
iSOWeekParser = new ISOWeekParser.ISOWeekParser();
dateParser = new DateParser.DateParser();
dayOfYearParser = new DayOfYearParser.DayOfYearParser();
dayParser = new DayParser.DayParser();
localDayParser = new LocalDayParser.LocalDayParser();
standAloneLocalDayParser = new StandAloneLocalDayParser.StandAloneLocalDayParser();
iSODayParser = new ISODayParser.ISODayParser();
aMPMParser = new AMPMParser.AMPMParser();
aMPMMidnightParser = new AMPMMidnightParser.AMPMMidnightParser();
dayPeriodParser = new DayPeriodParser.DayPeriodParser();
hour1to12Parser = new Hour1to12Parser.Hour1to12Parser();
hour0to23Parser = new Hour0to23Parser.Hour0to23Parser();
hour0To11Parser = new Hour0To11Parser.Hour0To11Parser();
hour1To24Parser = new Hour1To24Parser.Hour1To24Parser();
minuteParser = new MinuteParser.MinuteParser();
secondParser = new SecondParser.SecondParser();
fractionOfSecondParser = new FractionOfSecondParser.FractionOfSecondParser();
iSOTimezoneWithZParser = new ISOTimezoneWithZParser.ISOTimezoneWithZParser();
iSOTimezoneParser = new ISOTimezoneParser.ISOTimezoneParser();
timestampSecondsParser = new TimestampSecondsParser.TimestampSecondsParser();
timestampMillisecondsParser = new TimestampMillisecondsParser.TimestampMillisecondsParser();

export const parsers = point;
