// Module ID: 9867
// Function ID: 9868
// Name: getName
// Dependencies: [1236, 2237, 9868, 9869, 9870, 9871, 2]
// Exports: getBlurredBackgroundScale

// Module 9867 (getName)
import { ytIYuY as IE3e0y } from "messagesProxy";
import { ytIYuY as IE3e0y } from "messagesProxy";
import { ytIYuY as IE3e0y } from "messagesProxy";
import { p7JgFM as IE3e0y } from "messagesProxy";
import { YpJ7QS } from "messagesProxy";
import { p7JgFM as IE3e0y } from "messagesProxy";
import { wxkoLF as YpJ7QS } from "messagesProxy";
import { p7JgFM as IE3e0y } from "messagesProxy";
import { Qt29nt as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { lQKxC5 as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { WMBV4i as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { "\"yG+xS0\"" as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { "\"5ZigwU\"" as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { iVfA9i as YpJ7QS } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { Qt29nt as YpJ7QS } from "messagesProxy";
import { lkzfot as IE3e0y } from "messagesProxy";
import { lkzfot as IE3e0y } from "messagesProxy";
import { lkzfot as IE3e0y } from "messagesProxy";
import { IE3e0y } from "messagesProxy";
import { IE3e0y } from "messagesProxy";
import { IE3e0y } from "messagesProxy";
import { ytIYuY as IE3e0y } from "messagesProxy";
import { ytIYuY as IE3e0y } from "messagesProxy";
import { ytIYuY as IE3e0y } from "messagesProxy";
import { p7JgFM as IE3e0y } from "messagesProxy";
import { YpJ7QS } from "messagesProxy";
import { p7JgFM as IE3e0y } from "messagesProxy";
import { wxkoLF as YpJ7QS } from "messagesProxy";
import { p7JgFM as IE3e0y } from "messagesProxy";
import { Qt29nt as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { lQKxC5 as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { WMBV4i as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { "\"yG+xS0\"" as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { "\"5ZigwU\"" as YpJ7QS } from "messagesProxy";
import { wjBOG8 as IE3e0y } from "messagesProxy";
import { iVfA9i as YpJ7QS } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { "\"C+LGlh\"" as IE3e0y } from "messagesProxy";
import { Qt29nt as YpJ7QS } from "messagesProxy";
import { lkzfot as IE3e0y } from "messagesProxy";
import { lkzfot as IE3e0y } from "messagesProxy";
import { lkzfot as IE3e0y } from "messagesProxy";
import { IE3e0y } from "messagesProxy";
import { IE3e0y } from "messagesProxy";
import { IE3e0y } from "messagesProxy";

let IE3e0y = arg1;
let YpJ7QS = importDefault;
let obj = {};
obj = { background: null, backgroundBlurred: null, aspectRatio: 1.3667000333667, getName: null, seats: null, plants: null, screen: null };
obj[0] = require("metadata");
obj[1] = require("metadata");
obj[3] = function getName() {
  const intl = IE3e0y(1236).intl;
  return intl.formatToPlainString(v3(2237)["3xb4VY"], { number: 1 });
};
obj = { name: "PC_SEAT_1", getLabel: null, position: null };
YpJ7QS = 1;
obj[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][0];
const items = [obj, , , , , , , , , , , , , , , , , , , , ];
const obj1 = { name: "PC_SEAT_2", getLabel: null, position: null };
YpJ7QS = 2;
obj1[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj1[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][1];
items[1] = obj1;
const obj2 = { name: "PC_SEAT_3", getLabel: null, position: null };
YpJ7QS = 3;
obj2[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj2[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][2];
items[2] = obj2;
const obj3 = { name: "DUO_SEAT_1", getLabel: null, position: null };
obj3[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj3[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][3];
items[3] = obj3;
const obj4 = { name: "DUO_SEAT_2", getLabel: null, position: null };
obj4[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj4[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][4];
items[4] = obj4;
const obj5 = { name: "DUO_SEAT_STANDING_1", getLabel: null, position: null };
obj5[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj5[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][5];
items[5] = obj5;
const obj6 = { name: "MAIN_COUCH_SEAT_1", getLabel: null, position: null };
obj6[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj6[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][6];
items[6] = obj6;
const obj7 = { name: "MAIN_COUCH_SEAT_2", getLabel: null, position: null };
obj7[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj7[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][7];
items[7] = obj7;
const obj8 = { name: "MAIN_COUCH_SEAT_3", getLabel: null, position: null };
obj8[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj8[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][8];
items[8] = obj8;
const obj9 = { name: "MAIN_COUCH_SEAT_4", getLabel: null, position: null };
obj9[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj9[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][9];
items[9] = obj9;
const obj10 = { name: "MAIN_COUCH_SEAT_5", getLabel: null, position: null };
obj10[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj10[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][10];
items[10] = obj10;
const obj11 = { name: "SIDE_GROUP_SEAT_1", getLabel: null, position: null };
YpJ7QS = 1;
obj11[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj11[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][11];
items[11] = obj11;
const obj12 = { name: "SIDE_GROUP_SEAT_2", getLabel: null, position: null };
YpJ7QS = 2;
obj12[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj12[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][12];
items[12] = obj12;
const obj13 = { name: "SIDE_GROUP_SEAT_3", getLabel: null, position: null };
YpJ7QS = 3;
obj13[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj13[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][13];
items[13] = obj13;
const obj14 = { name: "SIDE_GROUP_SEAT_STANDING_1", getLabel: null, position: null };
obj14[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj14[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][14];
items[14] = obj14;
const obj15 = { name: "BACKROOM_SEAT_1", getLabel: null, position: null, dim: true };
YpJ7QS = 1;
obj15[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj15[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][15];
items[15] = obj15;
const obj16 = { name: "BACKROOM_SEAT_2", getLabel: null, position: null, dim: true };
YpJ7QS = 2;
obj16[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj16[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][16];
items[16] = obj16;
const obj17 = { name: "BACKROOM_SEAT_3", getLabel: null, position: null, dim: true };
YpJ7QS = 3;
obj17[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj17[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][17];
items[17] = obj17;
const obj18 = { name: "RAFTERS_SEAT_1", getLabel: null, position: null };
YpJ7QS = 1;
obj18[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj18[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][18];
items[18] = obj18;
const obj19 = { name: "RAFTERS_SEAT_2", getLabel: null, position: null };
YpJ7QS = 2;
obj19[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj19[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][19];
items[19] = obj19;
const obj20 = { name: "RAFTERS_SEAT_3", getLabel: null, position: null };
YpJ7QS = 3;
obj20[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj20[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT][20];
items[20] = obj20;
obj[4] = items;
const items1 = [{ x: 45.57, y: 50.62 }];
obj[5] = items1;
obj[6] = { topLeft: { x: 56.8, y: 16.15 }, topRight: { x: 75.85, y: 23 }, bottomRight: { x: 75.3, y: 41.3 }, bottomLeft: { x: 56.95, y: 33.75 } };
obj[require("GuildRoomBackgrounds").GuildRoomBackgrounds.DEFAULT] = obj;
const obj21 = { background: null, backgroundBlurred: null, aspectRatio: 1.3667000333667, getName: null, seats: null, plants: null, screen: null };
obj21[0] = require("metadata");
obj21[1] = require("metadata");
obj21[3] = function getName() {
  const intl = IE3e0y(1236).intl;
  return intl.formatToPlainString(v3(2237)["3xb4VY"], { number: 2 });
};
const obj22 = { name: "PC_SEAT_1", getLabel: null, position: null };
YpJ7QS = 1;
obj22[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj22[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][0];
const items2 = [obj22, , , , , , , , , , , , , , , , , , , , ];
const obj23 = { name: "PC_SEAT_2", getLabel: null, position: null };
YpJ7QS = 2;
obj23[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj23[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][1];
items2[1] = obj23;
const obj24 = { name: "PC_SEAT_3", getLabel: null, position: null };
YpJ7QS = 3;
obj24[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj24[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][2];
items2[2] = obj24;
const obj25 = { name: "DUO_SEAT_1", getLabel: null, position: null };
obj25[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj25[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][3];
items2[3] = obj25;
const obj26 = { name: "DUO_SEAT_2", getLabel: null, position: null };
obj26[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj26[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][4];
items2[4] = obj26;
const obj27 = { name: "DUO_SEAT_STANDING_1", getLabel: null, position: null };
obj27[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj27[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][5];
items2[5] = obj27;
const obj28 = { name: "MAIN_COUCH_SEAT_1", getLabel: null, position: null };
obj28[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj28[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][6];
items2[6] = obj28;
const obj29 = { name: "MAIN_COUCH_SEAT_2", getLabel: null, position: null };
obj29[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj29[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][7];
items2[7] = obj29;
const obj30 = { name: "MAIN_COUCH_SEAT_3", getLabel: null, position: null };
obj30[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj30[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][8];
items2[8] = obj30;
const obj31 = { name: "MAIN_COUCH_SEAT_4", getLabel: null, position: null };
obj31[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj31[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][9];
items2[9] = obj31;
const obj32 = { name: "MAIN_COUCH_SEAT_5", getLabel: null, position: null };
obj32[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj32[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][10];
items2[10] = obj32;
const obj33 = { name: "SIDE_GROUP_SEAT_1", getLabel: null, position: null };
YpJ7QS = 1;
obj33[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj33[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][11];
items2[11] = obj33;
const obj34 = { name: "SIDE_GROUP_SEAT_2", getLabel: null, position: null };
YpJ7QS = 2;
obj34[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj34[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][12];
items2[12] = obj34;
const obj35 = { name: "SIDE_GROUP_SEAT_3", getLabel: null, position: null };
YpJ7QS = 3;
obj35[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj35[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][13];
items2[13] = obj35;
const obj36 = { name: "SIDE_GROUP_SEAT_STANDING_1", getLabel: null, position: null };
obj36[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, position: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  const intl3 = IE3e0y(1236).intl;
  obj[1] = intl3.string(v3);
  return intl.formatToPlainString(v3(2237).LFdLjz, obj);
};
obj36[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][14];
items2[14] = obj36;
const obj37 = { name: "BACKROOM_SEAT_1", getLabel: null, position: null, dim: true };
YpJ7QS = 1;
obj37[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj37[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][15];
items2[15] = obj37;
const obj38 = { name: "BACKROOM_SEAT_2", getLabel: null, position: null, dim: true };
YpJ7QS = 2;
obj38[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj38[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][16];
items2[16] = obj38;
const obj39 = { name: "BACKROOM_SEAT_3", getLabel: null, position: null, dim: true };
YpJ7QS = 3;
obj39[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj39[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][17];
items2[17] = obj39;
const obj40 = { name: "RAFTERS_SEAT_1", getLabel: null, position: null };
YpJ7QS = 1;
obj40[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj40[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][18];
items2[18] = obj40;
const obj41 = { name: "RAFTERS_SEAT_2", getLabel: null, position: null };
YpJ7QS = 2;
obj41[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj41[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][19];
items2[19] = obj41;
const obj42 = { name: "RAFTERS_SEAT_3", getLabel: null, position: null };
YpJ7QS = 3;
obj42[1] = () => {
  const intl = IE3e0y(1236).intl;
  const obj = { seatType: null, number: null };
  const intl2 = IE3e0y(1236).intl;
  obj[0] = intl2.string(IE3e0y);
  obj[1] = v3;
  return intl.formatToPlainString(v3(2237).crFI7e, obj);
};
obj42[2] = require("GUILD_ROOM_BACKGROUND_POSITIONS").GUILD_ROOM_BACKGROUND_POSITIONS[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2][20];
items2[20] = obj42;
obj21[4] = items2;
const items3 = [{ x: 45.57, y: 50.62 }];
obj21[5] = items3;
obj21[6] = { topLeft: { x: 56.8, y: 16.15 }, topRight: { x: 75.85, y: 23 }, bottomRight: { x: 75.3, y: 41.3 }, bottomLeft: { x: 56.95, y: 33.75 } };
obj[require("GuildRoomBackgrounds").GuildRoomBackgrounds.LIVING_ROOM_2] = obj21;
const result = require("GuildRoomBackgrounds").fileFinishedImporting("modules/guild_rooms/GuildRoomConstants.tsx");

export const GUILD_ROOM_SPATIAL_AUDIO_MODE = "guild-room";
export const DEFAULT_BACKGROUND_POSITION = { imageOffsetX: 0, imageOffsetY: 0, imageWidth: 0, imageHeight: 0 };
export const BACKGROUND_BLUR_WIDTH_FACTOR = 0.0228310502283105;
export const getBlurredBackgroundScale = function getBlurredBackgroundScale(arg0, arg1) {
  let num = 0.045662100456621;
  if (arg1) {
    num = 0.045662100456621 * arg0;
  }
  return 1 + num;
};
export const GUILD_ROOM_BACKGROUND_CONFIG = obj;
