// Module ID: 12297
// Function ID: 12298
// Name: registerSpanErrorInstrumentation
// Dependencies: [12298, 12331, 12332, 12333, 12343, 12335, 12319, 12336, 12338, 12344, 12341, 12340, 12317, 12345, 12350, 12329, 12328, 12321, 12320, 12325, 12355, 12323, 12353, 12356, 12357, 12361, 12364, 12365, 12368, 12369, 12358, 12352, 12351, 12363, 12334, 12370, 12337, 12371, 12307, 12342, 12372, 12373, 12374, 12339, 12375, 12376, 12377, 12378, 12380, 12382, 12387, 12390, 12391, 12392, 12393, 12395, 12396, 12397, 12398, 12400, 12401, 12406, 12318, 12407, 12408, 12409, 12410, 12379, 12411, 12412, 12310, 12349, 12359, 12303, 12388, 12413, 12299, 12306, 12300, 12309, 12415, 12302, 12348, 12313, 12416, 12347, 12308, 12394, 12366, 12383, 12389, 12305, 12418, 12311, 12414, 12326, 12316, 12314, 12417, 12346, 12360, 12367, 12315, 12384, 12419, 12362, 12420, 12421, 12312, 12422, 12304, 12354, 12423, 12424, 12425, 12427, 12428, 12426, 12429, 12430]

// Module 12297 (registerSpanErrorInstrumentation)
import errorCallback from "errorCallback" /* 12298 */;
import instrumentError from "instrumentError" /* 12299 */;
import addHandler from "addHandler" /* 12300 */;
import consoleSandbox from "consoleSandbox" /* 12302 */;
import getGlobalSingleton from "getGlobalSingleton" /* 12303 */;
import _mod12304 from "module_12304" /* 12304 */;
import createStackParser from "createStackParser" /* 12305 */;
import instrumentUnhandledRejection from "instrumentUnhandledRejection" /* 12306 */;
import spanTimeInputToSeconds from "spanTimeInputToSeconds" /* 12307 */;
import addNonEnumerableProperty from "addNonEnumerableProperty" /* 12308 */;
import isInstanceOf from "isInstanceOf" /* 12309 */;
import _htmlElementAsString from "_htmlElementAsString" /* 12310 */;
import isMatchingPattern from "isMatchingPattern" /* 12311 */;
import generatePropagationContext from "generatePropagationContext" /* 12312 */;
import addContextToFrame from "addContextToFrame" /* 12313 */;
import regExp from "regExp" /* 12314 */;
import baggageHeaderToDynamicSamplingContext from "baggageHeaderToDynamicSamplingContext" /* 12315 */;
import _mod12317 from "module_12317" /* 12317 */;
import getMetricSummaryJsonForSpan from "getMetricSummaryJsonForSpan" /* 12318 */;
import getSpanStatusFromHttpCode from "getSpanStatusFromHttpCode" /* 12319 */;
import getMainCarrier from "getMainCarrier" /* 12320 */;
import getAsyncContextStrategy from "getAsyncContextStrategy" /* 12321 */;
import ScopeClass from "ScopeClass" /* 12323 */;
import updateSession from "updateSession" /* 12325 */;
import SyncPromise from "SyncPromise" /* 12326 */;
import getDefaultCurrentScope from "getDefaultCurrentScope" /* 12328 */;
import getClient from "getClient" /* 12329 */;
import getCapturedScopesOnSpan from "getCapturedScopesOnSpan" /* 12331 */;
import addTracingExtensions from "addTracingExtensions" /* 12332 */;
import TRACING_DEFAULTS from "TRACING_DEFAULTS" /* 12333 */;
import hasTracingEnabled from "hasTracingEnabled" /* 12334 */;
import SentryNonRecordingSpan from "SentryNonRecordingSpan" /* 12335 */;
import createChildOrRootSpan from "createChildOrRootSpan" /* 12336 */;
import handleCallbackErrors from "handleCallbackErrors" /* 12337 */;
import getDynamicSamplingContextFromSpan from "getDynamicSamplingContextFromSpan" /* 12338 */;
import _mod12339 from "module_12339" /* 12339 */;
import logSpanEnd from "logSpanEnd" /* 12340 */;
import sampleSpan from "sampleSpan" /* 12341 */;
import parseSampleRate from "parseSampleRate" /* 12342 */;
import isFullFinishedSpan from "isFullFinishedSpan" /* 12343 */;
import setMeasurement from "setMeasurement" /* 12344 */;
import createEventEnvelope from "createEventEnvelope" /* 12345 */;
import forEachEnvelopeItem from "forEachEnvelopeItem" /* 12346 */;
import normalize from "normalize" /* 12347 */;
import memoBuilder from "memoBuilder" /* 12348 */;
import dsnFromString from "dsnFromString" /* 12349 */;
import _flush from "_flush" /* 12350 */;
import applyClientOptions from "applyClientOptions" /* 12351 */;
import applyScopeDataToEvent from "applyScopeDataToEvent" /* 12352 */;
import notifyEventProcessors from "notifyEventProcessors" /* 12353 */;
import getFilenameToDebugIdMap from "getFilenameToDebugIdMap" /* 12354 */;
import SessionFlusher from "SessionFlusher" /* 12355 */;
import getEnvelopeEndpointWithUrlEncodedAuth from "getEnvelopeEndpointWithUrlEncodedAuth" /* 12356 */;
import isErrorEvent from "isErrorEvent" /* 12357 */;
import setupIntegration from "setupIntegration" /* 12358 */;
import _isNativeReflectConstruct from "_isNativeReflectConstruct" /* 12359 */;
import createClientReportEnvelope from "createClientReportEnvelope" /* 12360 */;
import _isNativeReflectConstruct2 from "_isNativeReflectConstruct" /* 12361 */;
import eventFromMessage from "eventFromMessage" /* 12362 */;
import createCheckInEnvelope from "createCheckInEnvelope" /* 12363 */;
import initAndBind from "initAndBind" /* 12364 */;
import createTransport from "createTransport" /* 12365 */;
import makePromiseBuffer from "makePromiseBuffer" /* 12366 */;
import parseRetryAfterHeader from "parseRetryAfterHeader" /* 12367 */;
import MIN_DELAY from "MIN_DELAY" /* 12368 */;
import eventFromEnvelope from "eventFromEnvelope" /* 12369 */;
import isSentryRequestUrl from "isSentryRequestUrl" /* 12370 */;
import parameterize from "parameterize" /* 12371 */;
import applySdkMetadata from "applySdkMetadata" /* 12372 */;
import getTraceData from "getTraceData" /* 12373 */;
import getTraceMetaTags from "getTraceMetaTags" /* 12374 */;
import addBreadcrumb from "addBreadcrumb" /* 12375 */;
import weakMap from "weakMap" /* 12376 */;
import _getEventFilterUrl from "_getEventFilterUrl" /* 12377 */;
import linkedErrorsIntegration from "linkedErrorsIntegration" /* 12378 */;
import aggregateExceptionsFromError from "aggregateExceptionsFromError" /* 12379 */;
import moduleMetadataIntegration from "moduleMetadataIntegration" /* 12380 */;
import requestDataIntegration from "requestDataIntegration" /* 12382 */;
import extractRequestData from "extractRequestData" /* 12383 */;
import getNumberOfUrlSegments from "getNumberOfUrlSegments" /* 12384 */;
import captureConsoleIntegration from "captureConsoleIntegration" /* 12387 */;
import instrumentConsole from "instrumentConsole" /* 12388 */;
import severityLevelFromString from "severityLevelFromString" /* 12389 */;
import debugIntegration from "debugIntegration" /* 12390 */;
import _shouldDropEvent from "_shouldDropEvent" /* 12391 */;
import extraErrorDataIntegration from "extraErrorDataIntegration" /* 12392 */;
import generateIteratee from "generateIteratee" /* 12393 */;
import resolve from "resolve" /* 12394 */;
import sessionTimingIntegration from "sessionTimingIntegration" /* 12395 */;
import flattenIssue from "flattenIssue" /* 12396 */;
import thirdPartyErrorFilterIntegration from "thirdPartyErrorFilterIntegration" /* 12397 */;
import addToMetricsAggregator from "addToMetricsAggregator" /* 12398 */;
import _mod12400 from "module_12400" /* 12400 */;
import addToMetricsAggregator2 from "addToMetricsAggregator" /* 12401 */;
import BrowserMetricsAggregator from "BrowserMetricsAggregator" /* 12406 */;
import _addTracingHeadersToFetchRequest from "_addTracingHeadersToFetchRequest" /* 12407 */;
import trpcMiddleware from "trpcMiddleware" /* 12408 */;
import captureFeedback from "captureFeedback" /* 12409 */;
import getCurrentHubShim from "getCurrentHubShim" /* 12410 */;
import flatten from "flatten" /* 12411 */;
import getBreadcrumbLogLevelFromHttpStatusCode from "getBreadcrumbLogLevelFromHttpStatusCode" /* 12412 */;
import _resolveResponse from "_resolveResponse" /* 12413 */;
import supportsFetch from "supportsFetch" /* 12414 */;
import isBrowser from "isBrowser" /* 12415 */;
import dynamicRequire from "dynamicRequire" /* 12416 */;
import getSDKSource from "getSDKSource" /* 12417 */;
import filenameIsInApp from "filenameIsInApp" /* 12418 */;
import makeFifoCache from "makeFifoCache" /* 12419 */;
import callFrameToStackFrame from "callFrameToStackFrame" /* 12420 */;
import LRUMap from "LRUMap" /* 12421 */;
import vercelWaitUntil from "vercelWaitUntil" /* 12422 */;
import escapeStringForRegex from "escapeStringForRegex" /* 12423 */;
import supportsHistory from "supportsHistory" /* 12424 */;
import _asyncNullishCoalesce2 from "_asyncNullishCoalesce2" /* 12425 */;
import _nullishCoalesce from "_nullishCoalesce" /* 12426 */;
import _asyncOptionalChain2 from "_asyncOptionalChain2" /* 12427 */;
import _asyncOptionalChainDelete2 from "_asyncOptionalChainDelete2" /* 12428 */;
import _optionalChain from "_optionalChain" /* 12429 */;
import _optionalChainDelete from "_optionalChainDelete" /* 12430 */;


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = getCapturedScopesOnSpan.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = getCapturedScopesOnSpan.setCapturedScopesOnSpan;
export const addTracingExtensions = addTracingExtensions.addTracingExtensions;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = isFullFinishedSpan.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = getSpanStatusFromHttpCode.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = getSpanStatusFromHttpCode.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = getSpanStatusFromHttpCode.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = getSpanStatusFromHttpCode.getSpanStatusFromHttpCode;
export const setHttpStatus = getSpanStatusFromHttpCode.setHttpStatus;
export const continueTrace = createChildOrRootSpan.continueTrace;
export const startInactiveSpan = createChildOrRootSpan.startInactiveSpan;
export const startNewTrace = createChildOrRootSpan.startNewTrace;
export const startSpan = createChildOrRootSpan.startSpan;
export const startSpanManual = createChildOrRootSpan.startSpanManual;
export const suppressTracing = createChildOrRootSpan.suppressTracing;
export const withActiveSpan = createChildOrRootSpan.withActiveSpan;
export const getDynamicSamplingContextFromClient = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = getDynamicSamplingContextFromSpan.spanToBaggageHeader;
export const setMeasurement = setMeasurement.setMeasurement;
export const timedEventsToMeasurements = setMeasurement.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12317.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12317.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12317.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12317.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12317.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12317.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12317.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12317.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = createEventEnvelope.createEventEnvelope;
export const createSessionEnvelope = createEventEnvelope.createSessionEnvelope;
export const createSpanEnvelope = createEventEnvelope.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = getClient.getClient;
export const getCurrentScope = getClient.getCurrentScope;
export const getGlobalScope = getClient.getGlobalScope;
export const getIsolationScope = getClient.getIsolationScope;
export const getTraceContextFromScope = getClient.getTraceContextFromScope;
export const withIsolationScope = getClient.withIsolationScope;
export const withScope = getClient.withScope;
export const getDefaultCurrentScope = getDefaultCurrentScope.getDefaultCurrentScope;
export const getDefaultIsolationScope = getDefaultCurrentScope.getDefaultIsolationScope;
export const setAsyncContextStrategy = getAsyncContextStrategy.setAsyncContextStrategy;
export const getMainCarrier = getMainCarrier.getMainCarrier;
export const closeSession = updateSession.closeSession;
export const makeSession = updateSession.makeSession;
export const updateSession = updateSession.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = getEnvelopeEndpointWithUrlEncodedAuth.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = getEnvelopeEndpointWithUrlEncodedAuth.getReportDialogEndpoint;
export const BaseClient = isErrorEvent.BaseClient;
export const ServerRuntimeClient = _isNativeReflectConstruct2.ServerRuntimeClient;
export const initAndBind = initAndBind.initAndBind;
export const setCurrentClient = initAndBind.setCurrentClient;
export const createTransport = createTransport.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = createCheckInEnvelope.createCheckInEnvelope;
export const hasTracingEnabled = hasTracingEnabled.hasTracingEnabled;
export const isSentryRequestUrl = isSentryRequestUrl.isSentryRequestUrl;
export const handleCallbackErrors = handleCallbackErrors.handleCallbackErrors;
export const parameterize = parameterize.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = parseSampleRate.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = getTraceData.getTraceData;
export const getTraceMetaTags = getTraceMetaTags.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12339.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = addBreadcrumb.addBreadcrumb;
export const functionToStringIntegration = weakMap.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const metrics = addToMetricsAggregator.metrics;
export const profiler = _mod12400.profiler;
export const metricsDefault = addToMetricsAggregator2.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = getMetricSummaryJsonForSpan.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _addTracingHeadersToFetchRequest.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const captureFeedback = captureFeedback.captureFeedback;
export const getCurrentHub = getCurrentHubShim.getCurrentHub;
export const getCurrentHubShim = getCurrentHubShim.getCurrentHubShim;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const flatten = flatten.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = getBreadcrumbLogLevelFromHttpStatusCode.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getDomElement = _htmlElementAsString.getDomElement;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = dsnFromString.dsnFromString;
export const dsnToString = dsnFromString.dsnToString;
export const makeDsn = dsnFromString.makeDsn;
export const SentryError = _isNativeReflectConstruct.SentryError;
export const GLOBAL_OBJ = getGlobalSingleton.GLOBAL_OBJ;
export const getGlobalSingleton = getGlobalSingleton.getGlobalSingleton;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = addHandler.addHandler;
export const maybeInstrument = addHandler.maybeInstrument;
export const resetInstrumentationHandlers = addHandler.resetInstrumentationHandlers;
export const triggerHandlers = addHandler.triggerHandlers;
export const isDOMError = isInstanceOf.isDOMError;
export const isDOMException = isInstanceOf.isDOMException;
export const isElement = isInstanceOf.isElement;
export const isError = isInstanceOf.isError;
export const isErrorEvent = isInstanceOf.isErrorEvent;
export const isEvent = isInstanceOf.isEvent;
export const isInstanceOf = isInstanceOf.isInstanceOf;
export const isParameterizedString = isInstanceOf.isParameterizedString;
export const isPlainObject = isInstanceOf.isPlainObject;
export const isPrimitive = isInstanceOf.isPrimitive;
export const isRegExp = isInstanceOf.isRegExp;
export const isString = isInstanceOf.isString;
export const isSyntheticEvent = isInstanceOf.isSyntheticEvent;
export const isThenable = isInstanceOf.isThenable;
export const isVueViewModel = isInstanceOf.isVueViewModel;
export const isBrowser = isBrowser.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const logger = consoleSandbox.logger;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = addContextToFrame.addContextToFrame;
export const addExceptionMechanism = addContextToFrame.addExceptionMechanism;
export const addExceptionTypeValue = addContextToFrame.addExceptionTypeValue;
export const arrayify = addContextToFrame.arrayify;
export const checkOrSetAlreadyCaught = addContextToFrame.checkOrSetAlreadyCaught;
export const getEventDescription = addContextToFrame.getEventDescription;
export const parseSemver = addContextToFrame.parseSemver;
export const uuid4 = addContextToFrame.uuid4;
export const dynamicRequire = dynamicRequire.dynamicRequire;
export const isNodeEnv = dynamicRequire.isNodeEnv;
export const loadModule = dynamicRequire.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = addNonEnumerableProperty.addNonEnumerableProperty;
export const convertToPlainObject = addNonEnumerableProperty.convertToPlainObject;
export const dropUndefinedKeys = addNonEnumerableProperty.dropUndefinedKeys;
export const extractExceptionKeysForMessage = addNonEnumerableProperty.extractExceptionKeysForMessage;
export const fill = addNonEnumerableProperty.fill;
export const getOriginalFunction = addNonEnumerableProperty.getOriginalFunction;
export const markFunctionWrapped = addNonEnumerableProperty.markFunctionWrapped;
export const objectify = addNonEnumerableProperty.objectify;
export const urlEncode = addNonEnumerableProperty.urlEncode;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const makePromiseBuffer = makePromiseBuffer.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const validSeverityLevels = severityLevelFromString.validSeverityLevels;
export const UNKNOWN_FUNCTION = createStackParser.UNKNOWN_FUNCTION;
export const createStackParser = createStackParser.createStackParser;
export const getFramesFromEvent = createStackParser.getFramesFromEvent;
export const getFunctionName = createStackParser.getFunctionName;
export const stackParserFromStackParserOptions = createStackParser.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = createStackParser.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = isMatchingPattern.isMatchingPattern;
export const safeJoin = isMatchingPattern.safeJoin;
export const snipLine = isMatchingPattern.snipLine;
export const stringMatchesSomePattern = isMatchingPattern.stringMatchesSomePattern;
export const truncate = isMatchingPattern.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require(12316) /* dateTimestampInSeconds */._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("dateTimestampInSeconds").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("dateTimestampInSeconds").dateTimestampInSeconds;
export const timestampInSeconds = require("dateTimestampInSeconds").timestampInSeconds;
export const TRACEPARENT_REGEXP = regExp.TRACEPARENT_REGEXP;
export const extractTraceparentData = regExp.extractTraceparentData;
export const generateSentryTraceHeader = regExp.generateSentryTraceHeader;
export const propagationContextFromHeaders = regExp.propagationContextFromHeaders;
export const getSDKSource = getSDKSource.getSDKSource;
export const isBrowserBundle = getSDKSource.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = createClientReportEnvelope.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = parseRetryAfterHeader.DEFAULT_RETRY_AFTER;
export const disabledUntil = parseRetryAfterHeader.disabledUntil;
export const isRateLimited = parseRetryAfterHeader.isRateLimited;
export const parseRetryAfterHeader = parseRetryAfterHeader.parseRetryAfterHeader;
export const updateRateLimits = parseRetryAfterHeader.updateRateLimits;
export const BAGGAGE_HEADER_NAME = baggageHeaderToDynamicSamplingContext.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = baggageHeaderToDynamicSamplingContext.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = baggageHeaderToDynamicSamplingContext.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = baggageHeaderToDynamicSamplingContext.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = baggageHeaderToDynamicSamplingContext.parseBaggageHeader;
export const getNumberOfUrlSegments = getNumberOfUrlSegments.getNumberOfUrlSegments;
export const getSanitizedUrlString = getNumberOfUrlSegments.getSanitizedUrlString;
export const parseUrl = getNumberOfUrlSegments.parseUrl;
export const stripUrlQueryAndFragment = getNumberOfUrlSegments.stripUrlQueryAndFragment;
export const makeFifoCache = makeFifoCache.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const SDK_VERSION = _mod12304.SDK_VERSION;
export const getDebugImagesForResources = getFilenameToDebugIdMap.getDebugImagesForResources;
export const getFilenameToDebugIdMap = getFilenameToDebugIdMap.getFilenameToDebugIdMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
