// Module ID: 12724
// Function ID: 12725
// Name: registerSpanErrorInstrumentation
// Dependencies: [12725, 12758, 12759, 12760, 12770, 12762, 12746, 12763, 12765, 12771, 12768, 12767, 12744, 12772, 12777, 12756, 12755, 12748, 12747, 12752, 12782, 12750, 12780, 12783, 12784, 12788, 12791, 12792, 12795, 12796, 12785, 12779, 12778, 12790, 12761, 12797, 12764, 12798, 12734, 12769, 12799, 12800, 12801, 12766, 12802, 12803, 12804, 12805, 12807, 12809, 12814, 12817, 12818, 12819, 12820, 12822, 12823, 12824, 12825, 12827, 12828, 12833, 12745, 12834, 12835, 12836, 12837, 12806, 12838, 12839, 12737, 12776, 12786, 12730, 12815, 12840, 12726, 12733, 12727, 12736, 12842, 12729, 12775, 12740, 12843, 12774, 12735, 12821, 12793, 12810, 12816, 12732, 12845, 12738, 12841, 12753, 12743, 12741, 12844, 12773, 12787, 12794, 12742, 12811, 12846, 12789, 12847, 12848, 12739, 12849, 12731, 12781, 12850, 12851, 12852, 12854, 12855, 12853, 12856, 12857]

// Module 12724 (registerSpanErrorInstrumentation)
import errorCallback from "errorCallback" /* 12725 */;
import instrumentError from "instrumentError" /* 12726 */;
import addHandler from "addHandler" /* 12727 */;
import consoleSandbox from "consoleSandbox" /* 12729 */;
import getGlobalSingleton from "getGlobalSingleton" /* 12730 */;
import _mod12731 from "module_12731" /* 12731 */;
import createStackParser from "createStackParser" /* 12732 */;
import instrumentUnhandledRejection from "instrumentUnhandledRejection" /* 12733 */;
import spanTimeInputToSeconds from "spanTimeInputToSeconds" /* 12734 */;
import addNonEnumerableProperty from "addNonEnumerableProperty" /* 12735 */;
import isInstanceOf from "isInstanceOf" /* 12736 */;
import _htmlElementAsString from "_htmlElementAsString" /* 12737 */;
import isMatchingPattern from "isMatchingPattern" /* 12738 */;
import generatePropagationContext from "generatePropagationContext" /* 12739 */;
import addContextToFrame from "addContextToFrame" /* 12740 */;
import regExp from "regExp" /* 12741 */;
import baggageHeaderToDynamicSamplingContext from "baggageHeaderToDynamicSamplingContext" /* 12742 */;
import _mod12744 from "module_12744" /* 12744 */;
import getMetricSummaryJsonForSpan from "getMetricSummaryJsonForSpan" /* 12745 */;
import getSpanStatusFromHttpCode from "getSpanStatusFromHttpCode" /* 12746 */;
import getMainCarrier from "getMainCarrier" /* 12747 */;
import getAsyncContextStrategy from "getAsyncContextStrategy" /* 12748 */;
import ScopeClass from "ScopeClass" /* 12750 */;
import updateSession from "updateSession" /* 12752 */;
import SyncPromise from "SyncPromise" /* 12753 */;
import getDefaultCurrentScope from "getDefaultCurrentScope" /* 12755 */;
import getClient from "getClient" /* 12756 */;
import getCapturedScopesOnSpan from "getCapturedScopesOnSpan" /* 12758 */;
import addTracingExtensions from "addTracingExtensions" /* 12759 */;
import TRACING_DEFAULTS from "TRACING_DEFAULTS" /* 12760 */;
import hasTracingEnabled from "hasTracingEnabled" /* 12761 */;
import SentryNonRecordingSpan from "SentryNonRecordingSpan" /* 12762 */;
import createChildOrRootSpan from "createChildOrRootSpan" /* 12763 */;
import handleCallbackErrors from "handleCallbackErrors" /* 12764 */;
import getDynamicSamplingContextFromSpan from "getDynamicSamplingContextFromSpan" /* 12765 */;
import _mod12766 from "module_12766" /* 12766 */;
import logSpanEnd from "logSpanEnd" /* 12767 */;
import sampleSpan from "sampleSpan" /* 12768 */;
import parseSampleRate from "parseSampleRate" /* 12769 */;
import isFullFinishedSpan from "isFullFinishedSpan" /* 12770 */;
import setMeasurement from "setMeasurement" /* 12771 */;
import createEventEnvelope from "createEventEnvelope" /* 12772 */;
import forEachEnvelopeItem from "forEachEnvelopeItem" /* 12773 */;
import normalize from "normalize" /* 12774 */;
import memoBuilder from "memoBuilder" /* 12775 */;
import dsnFromString from "dsnFromString" /* 12776 */;
import _flush from "_flush" /* 12777 */;
import applyClientOptions from "applyClientOptions" /* 12778 */;
import applyScopeDataToEvent from "applyScopeDataToEvent" /* 12779 */;
import notifyEventProcessors from "notifyEventProcessors" /* 12780 */;
import getFilenameToDebugIdMap from "getFilenameToDebugIdMap" /* 12781 */;
import SessionFlusher from "SessionFlusher" /* 12782 */;
import getEnvelopeEndpointWithUrlEncodedAuth from "getEnvelopeEndpointWithUrlEncodedAuth" /* 12783 */;
import isErrorEvent from "isErrorEvent" /* 12784 */;
import setupIntegration from "setupIntegration" /* 12785 */;
import _isNativeReflectConstruct from "_isNativeReflectConstruct" /* 12786 */;
import createClientReportEnvelope from "createClientReportEnvelope" /* 12787 */;
import _isNativeReflectConstruct2 from "_isNativeReflectConstruct" /* 12788 */;
import eventFromMessage from "eventFromMessage" /* 12789 */;
import createCheckInEnvelope from "createCheckInEnvelope" /* 12790 */;
import initAndBind from "initAndBind" /* 12791 */;
import createTransport from "createTransport" /* 12792 */;
import makePromiseBuffer from "makePromiseBuffer" /* 12793 */;
import parseRetryAfterHeader from "parseRetryAfterHeader" /* 12794 */;
import MIN_DELAY from "MIN_DELAY" /* 12795 */;
import eventFromEnvelope from "eventFromEnvelope" /* 12796 */;
import isSentryRequestUrl from "isSentryRequestUrl" /* 12797 */;
import parameterize from "parameterize" /* 12798 */;
import applySdkMetadata from "applySdkMetadata" /* 12799 */;
import getTraceData from "getTraceData" /* 12800 */;
import getTraceMetaTags from "getTraceMetaTags" /* 12801 */;
import addBreadcrumb from "addBreadcrumb" /* 12802 */;
import weakMap from "weakMap" /* 12803 */;
import _getEventFilterUrl from "_getEventFilterUrl" /* 12804 */;
import linkedErrorsIntegration from "linkedErrorsIntegration" /* 12805 */;
import aggregateExceptionsFromError from "aggregateExceptionsFromError" /* 12806 */;
import moduleMetadataIntegration from "moduleMetadataIntegration" /* 12807 */;
import requestDataIntegration from "requestDataIntegration" /* 12809 */;
import extractRequestData from "extractRequestData" /* 12810 */;
import getNumberOfUrlSegments from "getNumberOfUrlSegments" /* 12811 */;
import captureConsoleIntegration from "captureConsoleIntegration" /* 12814 */;
import instrumentConsole from "instrumentConsole" /* 12815 */;
import severityLevelFromString from "severityLevelFromString" /* 12816 */;
import debugIntegration from "debugIntegration" /* 12817 */;
import _shouldDropEvent from "_shouldDropEvent" /* 12818 */;
import extraErrorDataIntegration from "extraErrorDataIntegration" /* 12819 */;
import generateIteratee from "generateIteratee" /* 12820 */;
import resolve from "resolve" /* 12821 */;
import sessionTimingIntegration from "sessionTimingIntegration" /* 12822 */;
import flattenIssue from "flattenIssue" /* 12823 */;
import thirdPartyErrorFilterIntegration from "thirdPartyErrorFilterIntegration" /* 12824 */;
import addToMetricsAggregator from "addToMetricsAggregator" /* 12825 */;
import _mod12827 from "module_12827" /* 12827 */;
import addToMetricsAggregator2 from "addToMetricsAggregator" /* 12828 */;
import BrowserMetricsAggregator from "BrowserMetricsAggregator" /* 12833 */;
import _addTracingHeadersToFetchRequest from "_addTracingHeadersToFetchRequest" /* 12834 */;
import trpcMiddleware from "trpcMiddleware" /* 12835 */;
import captureFeedback from "captureFeedback" /* 12836 */;
import getCurrentHubShim from "getCurrentHubShim" /* 12837 */;
import flatten from "flatten" /* 12838 */;
import getBreadcrumbLogLevelFromHttpStatusCode from "getBreadcrumbLogLevelFromHttpStatusCode" /* 12839 */;
import _resolveResponse from "_resolveResponse" /* 12840 */;
import supportsFetch from "supportsFetch" /* 12841 */;
import isBrowser from "isBrowser" /* 12842 */;
import dynamicRequire from "dynamicRequire" /* 12843 */;
import getSDKSource from "getSDKSource" /* 12844 */;
import filenameIsInApp from "filenameIsInApp" /* 12845 */;
import makeFifoCache from "makeFifoCache" /* 12846 */;
import callFrameToStackFrame from "callFrameToStackFrame" /* 12847 */;
import LRUMap from "LRUMap" /* 12848 */;
import vercelWaitUntil from "vercelWaitUntil" /* 12849 */;
import escapeStringForRegex from "escapeStringForRegex" /* 12850 */;
import supportsHistory from "supportsHistory" /* 12851 */;
import _asyncNullishCoalesce2 from "_asyncNullishCoalesce2" /* 12852 */;
import _nullishCoalesce from "_nullishCoalesce" /* 12853 */;
import _asyncOptionalChain2 from "_asyncOptionalChain2" /* 12854 */;
import _asyncOptionalChainDelete2 from "_asyncOptionalChainDelete2" /* 12855 */;
import _optionalChain from "_optionalChain" /* 12856 */;
import _optionalChainDelete from "_optionalChainDelete" /* 12857 */;


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = getCapturedScopesOnSpan.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = getCapturedScopesOnSpan.setCapturedScopesOnSpan;
export const addTracingExtensions = addTracingExtensions.addTracingExtensions;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = isFullFinishedSpan.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = getSpanStatusFromHttpCode.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = getSpanStatusFromHttpCode.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = getSpanStatusFromHttpCode.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = getSpanStatusFromHttpCode.getSpanStatusFromHttpCode;
export const setHttpStatus = getSpanStatusFromHttpCode.setHttpStatus;
export const continueTrace = createChildOrRootSpan.continueTrace;
export const startInactiveSpan = createChildOrRootSpan.startInactiveSpan;
export const startNewTrace = createChildOrRootSpan.startNewTrace;
export const startSpan = createChildOrRootSpan.startSpan;
export const startSpanManual = createChildOrRootSpan.startSpanManual;
export const suppressTracing = createChildOrRootSpan.suppressTracing;
export const withActiveSpan = createChildOrRootSpan.withActiveSpan;
export const getDynamicSamplingContextFromClient = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = getDynamicSamplingContextFromSpan.spanToBaggageHeader;
export const setMeasurement = setMeasurement.setMeasurement;
export const timedEventsToMeasurements = setMeasurement.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod12744.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod12744.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod12744.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod12744.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod12744.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod12744.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod12744.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod12744.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = createEventEnvelope.createEventEnvelope;
export const createSessionEnvelope = createEventEnvelope.createSessionEnvelope;
export const createSpanEnvelope = createEventEnvelope.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = getClient.getClient;
export const getCurrentScope = getClient.getCurrentScope;
export const getGlobalScope = getClient.getGlobalScope;
export const getIsolationScope = getClient.getIsolationScope;
export const getTraceContextFromScope = getClient.getTraceContextFromScope;
export const withIsolationScope = getClient.withIsolationScope;
export const withScope = getClient.withScope;
export const getDefaultCurrentScope = getDefaultCurrentScope.getDefaultCurrentScope;
export const getDefaultIsolationScope = getDefaultCurrentScope.getDefaultIsolationScope;
export const setAsyncContextStrategy = getAsyncContextStrategy.setAsyncContextStrategy;
export const getMainCarrier = getMainCarrier.getMainCarrier;
export const closeSession = updateSession.closeSession;
export const makeSession = updateSession.makeSession;
export const updateSession = updateSession.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = getEnvelopeEndpointWithUrlEncodedAuth.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = getEnvelopeEndpointWithUrlEncodedAuth.getReportDialogEndpoint;
export const BaseClient = isErrorEvent.BaseClient;
export const ServerRuntimeClient = _isNativeReflectConstruct2.ServerRuntimeClient;
export const initAndBind = initAndBind.initAndBind;
export const setCurrentClient = initAndBind.setCurrentClient;
export const createTransport = createTransport.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = createCheckInEnvelope.createCheckInEnvelope;
export const hasTracingEnabled = hasTracingEnabled.hasTracingEnabled;
export const isSentryRequestUrl = isSentryRequestUrl.isSentryRequestUrl;
export const handleCallbackErrors = handleCallbackErrors.handleCallbackErrors;
export const parameterize = parameterize.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = parseSampleRate.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = getTraceData.getTraceData;
export const getTraceMetaTags = getTraceMetaTags.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod12766.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = addBreadcrumb.addBreadcrumb;
export const functionToStringIntegration = weakMap.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const metrics = addToMetricsAggregator.metrics;
export const profiler = _mod12827.profiler;
export const metricsDefault = addToMetricsAggregator2.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = getMetricSummaryJsonForSpan.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _addTracingHeadersToFetchRequest.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const captureFeedback = captureFeedback.captureFeedback;
export const getCurrentHub = getCurrentHubShim.getCurrentHub;
export const getCurrentHubShim = getCurrentHubShim.getCurrentHubShim;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const flatten = flatten.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = getBreadcrumbLogLevelFromHttpStatusCode.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getDomElement = _htmlElementAsString.getDomElement;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = dsnFromString.dsnFromString;
export const dsnToString = dsnFromString.dsnToString;
export const makeDsn = dsnFromString.makeDsn;
export const SentryError = _isNativeReflectConstruct.SentryError;
export const GLOBAL_OBJ = getGlobalSingleton.GLOBAL_OBJ;
export const getGlobalSingleton = getGlobalSingleton.getGlobalSingleton;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = addHandler.addHandler;
export const maybeInstrument = addHandler.maybeInstrument;
export const resetInstrumentationHandlers = addHandler.resetInstrumentationHandlers;
export const triggerHandlers = addHandler.triggerHandlers;
export const isDOMError = isInstanceOf.isDOMError;
export const isDOMException = isInstanceOf.isDOMException;
export const isElement = isInstanceOf.isElement;
export const isError = isInstanceOf.isError;
export const isErrorEvent = isInstanceOf.isErrorEvent;
export const isEvent = isInstanceOf.isEvent;
export const isInstanceOf = isInstanceOf.isInstanceOf;
export const isParameterizedString = isInstanceOf.isParameterizedString;
export const isPlainObject = isInstanceOf.isPlainObject;
export const isPrimitive = isInstanceOf.isPrimitive;
export const isRegExp = isInstanceOf.isRegExp;
export const isString = isInstanceOf.isString;
export const isSyntheticEvent = isInstanceOf.isSyntheticEvent;
export const isThenable = isInstanceOf.isThenable;
export const isVueViewModel = isInstanceOf.isVueViewModel;
export const isBrowser = isBrowser.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const logger = consoleSandbox.logger;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = addContextToFrame.addContextToFrame;
export const addExceptionMechanism = addContextToFrame.addExceptionMechanism;
export const addExceptionTypeValue = addContextToFrame.addExceptionTypeValue;
export const arrayify = addContextToFrame.arrayify;
export const checkOrSetAlreadyCaught = addContextToFrame.checkOrSetAlreadyCaught;
export const getEventDescription = addContextToFrame.getEventDescription;
export const parseSemver = addContextToFrame.parseSemver;
export const uuid4 = addContextToFrame.uuid4;
export const dynamicRequire = dynamicRequire.dynamicRequire;
export const isNodeEnv = dynamicRequire.isNodeEnv;
export const loadModule = dynamicRequire.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = addNonEnumerableProperty.addNonEnumerableProperty;
export const convertToPlainObject = addNonEnumerableProperty.convertToPlainObject;
export const dropUndefinedKeys = addNonEnumerableProperty.dropUndefinedKeys;
export const extractExceptionKeysForMessage = addNonEnumerableProperty.extractExceptionKeysForMessage;
export const fill = addNonEnumerableProperty.fill;
export const getOriginalFunction = addNonEnumerableProperty.getOriginalFunction;
export const markFunctionWrapped = addNonEnumerableProperty.markFunctionWrapped;
export const objectify = addNonEnumerableProperty.objectify;
export const urlEncode = addNonEnumerableProperty.urlEncode;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const makePromiseBuffer = makePromiseBuffer.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const validSeverityLevels = severityLevelFromString.validSeverityLevels;
export const UNKNOWN_FUNCTION = createStackParser.UNKNOWN_FUNCTION;
export const createStackParser = createStackParser.createStackParser;
export const getFramesFromEvent = createStackParser.getFramesFromEvent;
export const getFunctionName = createStackParser.getFunctionName;
export const stackParserFromStackParserOptions = createStackParser.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = createStackParser.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = isMatchingPattern.isMatchingPattern;
export const safeJoin = isMatchingPattern.safeJoin;
export const snipLine = isMatchingPattern.snipLine;
export const stringMatchesSomePattern = isMatchingPattern.stringMatchesSomePattern;
export const truncate = isMatchingPattern.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require(12743) /* dateTimestampInSeconds */._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("dateTimestampInSeconds").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("dateTimestampInSeconds").dateTimestampInSeconds;
export const timestampInSeconds = require("dateTimestampInSeconds").timestampInSeconds;
export const TRACEPARENT_REGEXP = regExp.TRACEPARENT_REGEXP;
export const extractTraceparentData = regExp.extractTraceparentData;
export const generateSentryTraceHeader = regExp.generateSentryTraceHeader;
export const propagationContextFromHeaders = regExp.propagationContextFromHeaders;
export const getSDKSource = getSDKSource.getSDKSource;
export const isBrowserBundle = getSDKSource.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = createClientReportEnvelope.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = parseRetryAfterHeader.DEFAULT_RETRY_AFTER;
export const disabledUntil = parseRetryAfterHeader.disabledUntil;
export const isRateLimited = parseRetryAfterHeader.isRateLimited;
export const parseRetryAfterHeader = parseRetryAfterHeader.parseRetryAfterHeader;
export const updateRateLimits = parseRetryAfterHeader.updateRateLimits;
export const BAGGAGE_HEADER_NAME = baggageHeaderToDynamicSamplingContext.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = baggageHeaderToDynamicSamplingContext.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = baggageHeaderToDynamicSamplingContext.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = baggageHeaderToDynamicSamplingContext.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = baggageHeaderToDynamicSamplingContext.parseBaggageHeader;
export const getNumberOfUrlSegments = getNumberOfUrlSegments.getNumberOfUrlSegments;
export const getSanitizedUrlString = getNumberOfUrlSegments.getSanitizedUrlString;
export const parseUrl = getNumberOfUrlSegments.parseUrl;
export const stripUrlQueryAndFragment = getNumberOfUrlSegments.stripUrlQueryAndFragment;
export const makeFifoCache = makeFifoCache.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const SDK_VERSION = _mod12731.SDK_VERSION;
export const getDebugImagesForResources = getFilenameToDebugIdMap.getDebugImagesForResources;
export const getFilenameToDebugIdMap = getFilenameToDebugIdMap.getFilenameToDebugIdMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
