// Module ID: 14301
// Function ID: 108064
// Name: MyTableRow
// Dependencies: []
// Exports: default

// Module 14301 (MyTableRow)
function MyTableRow() {
  let obj = { label: "Notifications", onPress: closure_10 };
  obj = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj);
  return callback2(arg1(dependencyMap[7]).TableRow, obj);
}
let closure_3 = importDefault(dependencyMap[0]);
let closure_4 = importAll(dependencyMap[1]);
({ View: closure_5, Image: closure_6, ScrollView: closure_7 } = arg1(dependencyMap[2]));
let closure_8 = importDefault(dependencyMap[3]);
let closure_9 = importDefault(dependencyMap[4]);
const tmp2 = arg1(dependencyMap[2]);
({ NOOP: closure_10, StatusTypes: closure_11 } = arg1(dependencyMap[5]));
const tmp3 = arg1(dependencyMap[5]);
({ jsx: closure_12, jsxs: closure_13 } = arg1(dependencyMap[6]));
const tmp4 = arg1(dependencyMap[6]);
const result = arg1(dependencyMap[27]).fileFinishedImporting("modules/user_settings/design_system/native/UserSettingsDesignSystemTableRow.tsx");

export default function UserSettingsDesignSystemTableRow() {
  let tmp4;
  let tmp6;
  let obj = arg1(dependencyMap[9]);
  const items = [closure_9];
  const stateFromStores = obj.useStateFromStores(items, () => currentUser.getCurrentUser());
  const guildId = guildId.getGuildId();
  const rect = importDefault(dependencyMap[10])();
  [tmp4, closure_0] = callback(React.useState(false), 2);
  const tmp3 = callback(React.useState(false), 2);
  [tmp6, closure_1] = callback(React.useState(false), 2);
  const callback = React.useCallback((arg0) => {
    callback(arg0);
  }, []);
  obj = {};
  const callback1 = React.useCallback((arg0) => {
    callback2(arg0);
  }, []);
  obj = { spacing: 24, style: obj1 };
  const obj2 = { hasIcons: true };
  const obj3 = { onPress: closure_10 };
  const obj4 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj3.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj4);
  obj3.label = "Boost your Server";
  obj3.subLabel = "Unlock perks for the entire community";
  obj3.trailing = callback2(arg1(dependencyMap[7]).TableRow.Arrow, {});
  const items1 = [callback2(arg1(dependencyMap[7]).TableRow, obj3), callback2(MyTableRow, {}), , , , , ];
  const obj5 = {};
  const obj6 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj5.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj6);
  obj5.label = "Add a Friend";
  items1[2] = callback2(arg1(dependencyMap[7]).TableRow, obj5);
  const obj7 = { disabled: "heading-sm/semibold", value: "Row buttons", label: "Are you sure?" };
  const obj8 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj7.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj8);
  items1[3] = callback2(arg1(dependencyMap[7]).TableRow, obj7);
  const obj9 = { disabled: false, value: false, label: false };
  const obj10 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj9.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj10);
  obj9.trailing = callback2(arg1(dependencyMap[7]).TableRow.Arrow, {});
  items1[4] = callback2(arg1(dependencyMap[7]).TableRow, obj9);
  const obj11 = {};
  const obj12 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj11.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj12);
  obj11.label = callback2(arg1(dependencyMap[13]).Text, { resourceId: true, renderSettingSearchResultItem: true, base64GIFRegex: true });
  const obj13 = { style: { -9223372036854775808: true, filter: true } };
  const obj14 = { style: { VOICE_PANEL_CARD_INNER_PADDING: "text-md/medium", allRewards: "text-subtle", _graphQL: "You press the button to open the menu and then select an action, or tap and pan down in a single gesture.", useFindFirstMediaProperties: "text-lg/bold" } };
  const obj15 = {};
  let obj18 = importDefault(dependencyMap[14]);
  obj15.uri = obj18.getEmojiURL({ "Null": "Array", "Null": "getFirefoxVersion", "Null": "CONTROL_CONNECTED_BORDER_ACTIVE" });
  obj14.source = obj15;
  obj14.resizeMode = "contain";
  const items2 = [callback2(closure_6, obj14), callback2(arg1(dependencyMap[13]).Text, { style: { flexShrink: 1 } })];
  obj13.children = items2;
  obj11.subLabel = callback3(closure_5, obj13);
  items1[5] = callback2(arg1(dependencyMap[7]).TableRow, obj11);
  const obj16 = { 0: false, 9223372036854775807: false, 0: false, 0: false };
  const obj17 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj16.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj17);
  items1[6] = callback2(arg1(dependencyMap[7]).TableRow, obj16);
  obj2.children = items1;
  const items3 = [callback3(arg1(dependencyMap[12]).TableRowGroup, obj2), , , , , , ];
  obj18 = {};
  const obj19 = { label: stateFromStores.globalName, subLabel: stateFromStores.username };
  const obj20 = { user: stateFromStores, guildId, status: constants.ONLINE, size: arg1(dependencyMap[15]).AvatarSizes.REFRESH_MEDIUM_32 };
  obj19.icon = callback2(arg1(dependencyMap[15]).Avatar, obj20);
  const items4 = [callback2(arg1(dependencyMap[7]).TableRow, obj19), , , , , , , , , , ];
  const obj21 = {};
  const obj22 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj21.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj22);
  obj21.label = "Language";
  obj21.trailing = callback2(arg1(dependencyMap[7]).TableRow.TrailingText, { text: "English (US)" });
  items4[1] = callback2(arg1(dependencyMap[7]).TableRow, obj21);
  const obj23 = {};
  const obj24 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj23.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj24);
  obj23.label = "Display Name";
  obj23.trailing = callback2(arg1(dependencyMap[7]).TableRow.TrailingText, { text: "thisisareallylongusernamewhichshouldtruncate" });
  items4[2] = callback2(arg1(dependencyMap[7]).TableRow, obj23);
  const obj25 = {};
  const obj26 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj25.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj26);
  obj25.label = "Display Name";
  obj25.trailing = callback2(arg1(dependencyMap[7]).TableRow.TrailingText, { text: "thisisareallylongusernamewhichshouldtruncate" });
  obj25.arrow = true;
  items4[3] = callback2(arg1(dependencyMap[7]).TableRow, obj25);
  const obj27 = {};
  const obj28 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj27.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj28);
  obj27.label = "Display Name That Is Very Long And Maybe Wrap";
  obj27.trailing = callback2(arg1(dependencyMap[7]).TableRow.TrailingText, { text: "thisisareallylongusernamewhichshouldtruncate" });
  items4[4] = callback2(arg1(dependencyMap[7]).TableRow, obj27);
  const obj29 = {};
  const obj30 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj29.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj30);
  obj29.label = "Display Name That Is Very Long And Maybe Wrap";
  obj29.trailing = callback2(arg1(dependencyMap[7]).TableRow.TrailingText, { text: "100" });
  items4[5] = callback2(arg1(dependencyMap[7]).TableRow, obj29);
  const obj31 = { disabled: null, value: null, label: null };
  const obj32 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj31.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj32);
  items4[6] = callback2(arg1(dependencyMap[7]).TableRow, obj31);
  const obj33 = { disabled: 3, value: 2, label: "text-lg/bold" };
  const obj34 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj33.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj34);
  obj33.value = tmp4;
  obj33.onValueChange = callback;
  items4[7] = callback2(arg1(dependencyMap[16]).TableSwitchRow, obj33);
  const obj35 = { minWidth: false, maxHeight: false, aspectRatio: false, flexDirection: false, alignItems: false, justifyContent: false };
  const obj36 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj35.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj36);
  obj35.onValueChange = closure_10;
  items4[8] = callback2(arg1(dependencyMap[16]).TableSwitchRow, obj35);
  const obj37 = { disabled: "r", value: "_rdate", label: "Array" };
  const obj38 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj37.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj38);
  obj37.checked = tmp6;
  obj37.onPress = callback1;
  items4[9] = callback2(arg1(dependencyMap[17]).TableCheckboxRow, obj37);
  const obj39 = { "Bool(false)": "<string:36202050>", "Bool(false)": "<string:28428288>", "Bool(false)": "<string:44974592>", "Bool(false)": "<string:1086980097>", "Bool(false)": "<string:3461414913>" };
  const obj40 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj39.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj40);
  obj39.onPress = closure_10;
  items4[10] = callback2(arg1(dependencyMap[17]).TableCheckboxRow, obj39);
  obj18.children = items4;
  items3[1] = callback3(arg1(dependencyMap[12]).TableRowGroup, obj18);
  const obj41 = { label: true, subLabel: "/assets/.cache/intl/bW9kdWxlcy9nb19saXZl", checked: null };
  const obj42 = { -865739878: false, -1594107668: false, 1644428625: false, 877739003: false, 1379557832: false, onPress: closure_10 };
  const obj43 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj42.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj43);
  obj42.trailing = callback2(arg1(dependencyMap[7]).TableRow.Arrow, {});
  const items5 = [callback2(arg1(dependencyMap[7]).TableRow, obj42), ];
  const obj44 = { -865739878: false, -1594107668: false, 1644428625: false, 877739003: false, 1379557832: false, onPress: closure_10 };
  const obj45 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj44.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj45);
  obj44.trailing = callback2(arg1(dependencyMap[7]).TableRow.Arrow, {});
  items5[1] = callback2(arg1(dependencyMap[7]).TableRow, obj44);
  obj41.children = items5;
  items3[2] = callback3(arg1(dependencyMap[12]).TableRowGroup, obj41);
  const obj46 = { width: "text-subtle", height: "It will also position itself vertically, so that it doesn't overflow offscreen vertically." };
  const obj47 = { "Bool(false)": -633208831, "Bool(false)": -1342176768, onPress: closure_10 };
  const items6 = [callback2(arg1(dependencyMap[7]).TableRow, obj47), , ];
  const obj48 = { "Bool(false)": "<string:3461414913>", "Bool(false)": "<string:677790281>", onPress: closure_10 };
  items6[1] = callback2(arg1(dependencyMap[7]).TableRow, obj48);
  const obj49 = { "Bool(false)": null, "Bool(false)": null, onPress: closure_10 };
  items6[2] = callback2(arg1(dependencyMap[7]).TableRow, obj49);
  obj46.children = items6;
  items3[3] = callback3(arg1(dependencyMap[12]).TableRowGroup, obj46);
  const obj50 = { 1362885474: "text-subtle", 979486772: "The align prop can be set to above, below, left, or right of the menu trigger. How the menu positions relative to the start or end of the trigger is then automatically determined based on the available space.", 664821074: 3, onChange: closure_10 };
  const items7 = [callback2(arg1(dependencyMap[19]).TableRadioRow, {}), callback2(arg1(dependencyMap[19]).TableRadioRow, {}), callback2(arg1(dependencyMap[19]).TableRadioRow, {}), callback2(arg1(dependencyMap[19]).TableRadioRow, { "Null": true, "Null": "/assets/.cache/intl/bW9kdWxlcy9nb19saXZl", "Null": null, "Null": "893f3cf496dc4a4983e7471163e63be3" })];
  obj50.children = items7;
  items3[4] = callback3(arg1(dependencyMap[18]).TableRadioGroup, obj50);
  const obj51 = { onChange: closure_10 };
  const obj52 = { source: "above", enableAnimation: "Always Open Above", resizeMode: "text-lg/bold" };
  const obj53 = { variant: "text-status-online", source: importDefault(dependencyMap[21]) };
  obj52.icon = callback2(arg1(dependencyMap[20]).TableRowIcon, obj53);
  const items8 = [callback2(arg1(dependencyMap[19]).TableRadioRow, obj52), , , ];
  const obj54 = {};
  const obj55 = { variant: "text-status-idle", source: importDefault(dependencyMap[22]) };
  obj54.icon = callback2(arg1(dependencyMap[20]).TableRowIcon, obj55);
  items8[1] = callback2(arg1(dependencyMap[19]).TableRadioRow, obj54);
  const obj56 = { source: "<string:36202050>", enableAnimation: "<string:24768256>", resizeMode: "<string:759238912>" };
  const obj57 = { variant: "text-status-dnd", source: importDefault(dependencyMap[23]) };
  obj56.icon = callback2(arg1(dependencyMap[20]).TableRowIcon, obj57);
  items8[2] = callback2(arg1(dependencyMap[19]).TableRadioRow, obj56);
  const obj58 = { source: true, enableAnimation: "/assets/design/components/Icon/native/redesign/generated/images", resizeMode: 24 };
  const obj59 = { variant: "text-status-offline", source: importDefault(dependencyMap[24]) };
  obj58.icon = callback2(arg1(dependencyMap[20]).TableRowIcon, obj59);
  items8[3] = callback2(arg1(dependencyMap[19]).TableRadioRow, obj58);
  obj51.children = items8;
  items3[5] = callback3(arg1(dependencyMap[18]).TableRadioGroup, obj51);
  const obj60 = { spacing: 12 };
  const items9 = [callback2(arg1(dependencyMap[13]).Text, {}), , , ];
  const obj61 = {};
  const obj62 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon };
  obj61.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj62);
  obj61.label = "Boost your server";
  obj61.onPress = closure_10;
  items9[1] = callback2(arg1(dependencyMap[25]).RowButton, obj61);
  items9[2] = callback2(arg1(dependencyMap[25]).RowButton, { onPress: closure_10 });
  const obj64 = { style: { padding: 8 }, start: { "Null": false, "Null": true }, end: { "Null": null, "Null": null }, colors: [100832303, -435550186, 1628648554, -217004190, 101435675, -1960608493, 839670834] };
  const obj1 = { paddingTop: rect.top, paddingBottom: rect.bottom, paddingHorizontal: 12 };
  const obj63 = { onPress: closure_10 };
  const tmp5 = callback(React.useState(false), 2);
  const obj65 = {};
  const obj66 = { IconComponent: arg1(dependencyMap[8]).SettingsIcon, variant: "translucent" };
  obj65.icon = callback2(arg1(dependencyMap[7]).TableRow.Icon, obj66);
  obj65.onPress = closure_10;
  obj64.children = callback2(arg1(dependencyMap[25]).RowButton, obj65);
  items9[3] = callback2(importDefault(dependencyMap[26]), obj64);
  obj60.children = items9;
  items3[6] = callback3(arg1(dependencyMap[11]).Stack, obj60);
  obj.children = items3;
  obj.children = callback3(arg1(dependencyMap[11]).Stack, obj);
  return callback2(closure_7, obj);
};
