// Module ID: 1711
// Function ID: 1712
// Name: FadeInData
// Dependencies: [1712]

// Module 1711 (FadeInData)
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes" /* 1712 */;

obj = { FadeIn: { name: "FadeIn", style: obj, duration: 0.3 }, FadeInRight: { name: "FadeInRight", style: obj, duration: 0.3 }, FadeInLeft: { name: "FadeInLeft", style: obj1, duration: 0.3 }, FadeInUp: { name: "FadeInUp", style: obj2, duration: 0.3 }, FadeInDown: { name: "FadeInDown", style: obj3, duration: 0.3 } };
obj = { 0: { opacity: 0 }, 100: null };
obj[100] = { opacity: 1 };
obj = { 0: { opacity: 0, transform: items }, 100: null };
items = [{ translateX: "25px" }];
const items1 = [{ translateX: "0px" }];
obj[100] = { opacity: 1, transform: items1 };
obj1 = { 0: { opacity: 0, transform: items2 }, 100: null };
items2 = [{ translateX: "-25px" }];
const items3 = [{ translateX: "0px" }];
obj1[100] = { opacity: 1, transform: items3 };
obj2 = { 0: { opacity: 0, transform: items4 }, 100: null };
items4 = [{ translateY: "-25px" }];
const items5 = [{ translateY: "0px" }];
obj2[100] = { opacity: 1, transform: items5 };
obj3 = { 0: { opacity: 0, transform: items6 }, 100: null };
items6 = [{ translateY: "25px" }];
const items7 = [{ translateY: "0px" }];
obj3[100] = { opacity: 1, transform: items7 };
const obj4 = { FadeOut: { name: "FadeOut", style: obj5, duration: 0.3 }, FadeOutRight: { name: "FadeOutRight", style: obj6, duration: 0.3 }, FadeOutLeft: { name: "FadeOutLeft", style: obj7, duration: 0.3 }, FadeOutUp: { name: "FadeOutUp", style: obj8, duration: 0.3 }, FadeOutDown: { name: "FadeOutDown", style: obj9, duration: 0.3 } };
obj5 = { 0: { opacity: 1 }, 100: null };
obj5[100] = { opacity: 0 };
obj6 = { 0: { opacity: 1, transform: items8 }, 100: null };
items8 = [{ translateX: "0px" }];
const items9 = [{ translateX: "25px" }];
obj6[100] = { opacity: 0, transform: items9 };
obj7 = { 0: { opacity: 1, transform: items10 }, 100: null };
items10 = [{ translateX: "0px" }];
const items11 = [{ translateX: "-25px" }];
obj7[100] = { opacity: 0, transform: items11 };
obj8 = { 0: { opacity: 1, transform: items12 }, 100: null };
items12 = [{ translateY: "0px" }];
const items13 = [{ translateY: "-25px" }];
obj8[100] = { opacity: 0, transform: items13 };
obj9 = { 0: { opacity: 1, transform: items14 }, 100: null };
items14 = [{ translateY: "0px" }];
const items15 = [{ translateY: "25px" }];
obj9[100] = { opacity: 0, transform: items15 };
const obj10 = { FadeIn: null, FadeInRight: null, FadeInLeft: null, FadeInUp: null, FadeInDown: null };
const obj11 = { style: null, duration: null };
obj11[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.FadeIn);
obj11[1] = obj.FadeIn.duration;
obj10[0] = obj11;
const obj12 = { style: null, duration: null };
obj12[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.FadeInRight);
obj12[1] = obj.FadeInRight.duration;
obj10[1] = obj12;
const obj13 = { style: null, duration: null };
obj13[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.FadeInLeft);
obj13[1] = obj.FadeInLeft.duration;
obj10[2] = obj13;
const obj14 = { style: null, duration: null };
obj14[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.FadeInUp);
obj14[1] = obj.FadeInUp.duration;
obj10[3] = obj14;
const obj15 = { style: null, duration: null };
obj15[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.FadeInDown);
obj15[1] = obj.FadeInDown.duration;
obj10[4] = obj15;
const obj16 = { FadeOut: null, FadeOutRight: null, FadeOutLeft: null, FadeOutUp: null, FadeOutDown: null };
const obj17 = { style: null, duration: null };
obj17[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.FadeOut);
obj17[1] = obj4.FadeOut.duration;
obj16[0] = obj17;
const obj18 = { style: null, duration: null };
obj18[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.FadeOutRight);
obj18[1] = obj4.FadeOutRight.duration;
obj16[1] = obj18;
const obj19 = { style: null, duration: null };
obj19[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.FadeOutLeft);
obj19[1] = obj4.FadeOutLeft.duration;
obj16[2] = obj19;
const obj20 = { style: null, duration: null };
obj20[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.FadeOutUp);
obj20[1] = obj4.FadeOutUp.duration;
obj16[3] = obj20;
const obj21 = { style: null, duration: null };
obj21[0] = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.FadeOutDown);
obj21[1] = obj4.FadeOutDown.duration;
obj16[4] = obj21;

export const FadeInData = obj;
export const FadeOutData = obj4;
export const FadeIn = obj10;
export const FadeOut = obj16;
