// Module ID: 16757
// Function ID: 16758
// Name: PremiumDiscountOfferActionSheetContent
// Dependencies: [19, 17, 1374, 21, 4836, 576, 11303, 1115, 8724, 5388, 5442, 4488, 15289, 4832, 15291, 5281, 8122, 2]

// Module 16757 (PremiumDiscountOfferActionSheetContent)
import react_native from "react-native" /* 17 */;
import nativeDefault from "native" /* 576 */;
import intl10 from "intl" /* 1115 */;
import PremiumConstants from "PremiumConstants" /* 1374 */;
import PremiumUtils from "PremiumUtils" /* 4488 */;
import Text_Text from "Text/Text" /* 4832 */;
import components_Button_Button from "components/Button/Button" /* 5281 */;
import FolderIcon from "FolderIcon" /* 5388 */;
import NitroFileUploadExperiments from "NitroFileUploadExperiments" /* 5442 */;
import NitroWheelIcon2 from "NitroWheelIcon" /* 8122 */;
import ChatSmileIcon from "ChatSmileIcon" /* 8724 */;
import UserIcon from "UserIcon" /* 11303 */;
import NitroWumpusFlightRight3dIllustration from "NitroWumpusFlightRight3dIllustration" /* 15289 */;
import PremiumPerksListDefault from "PremiumPerksList" /* 15291 */;
import react from "react" /* 19 */;
import Fragment from "Fragment" /* 21 */;
import createStyles from "createStyles" /* 4836 */;
import size from "module_2" /* 2 */;

let hasOwnProperty;
let metroRequire;
let obj2;
const View = react_native.View;
const PremiumTypes = PremiumConstants.PremiumTypes;
({ jsx: hasOwnProperty, jsxs: metroRequire } = Fragment);
let obj = { contentContainer: obj2, buttonContainer: { marginVertical: 6, width: "100%", height: 48 }, title: { width: "100%", textAlign: "center" }, heroIllustrationContainer: { alignItems: "center", justifyContent: "center", height: 188, width: "100%" } };
obj2 = { paddingHorizontal: 36, paddingTop: 18, paddingBottom: 36, width: "100%", backgroundColor: nativeDefault.colors.BACKGROUND_BASE_LOW, alignItems: "flex-start", display: "flex", flexDirection: "column", gap: 0 };
let closure_7 = createStyles.createStyles(obj);
const memoResult = react.memo(function PremiumDiscountOfferActionSheetContent(arg0) {
  let Button;
  let NitroWheelIcon;
  let PvqncD;
  let discountOffer;
  let formatToPlainString;
  let getNitroFileUploadRolloutCopy;
  let intl;
  let intl2;
  let intl3;
  let intl4;
  let intl5;
  let intl6;
  let intl8;
  let intl9;
  let items1;
  let obj11;
  let obj12;
  let obj4;
  let obj5;
  let obj6;
  let onConfirm;
  ({ discountOffer, onConfirm } = arg0);
  const tmp = closure_7();
  const obj = { IconComponent: UserIcon.UserIcon, label: intl.string(intl10.t.kpMomJ), description: intl2.string(intl10.t.uVUtPw) };
  intl = intl10.intl;
  intl2 = intl10.intl;
  const items = [obj, , ];
  const obj2 = { IconComponent: ChatSmileIcon.ChatSmileIcon, label: intl3.string(intl10.t["R2IV/Q"]), description: intl4.string(intl10.t["3SUJLd"]) };
  intl3 = intl10.intl;
  intl4 = intl10.intl;
  items[1] = obj2;
  const obj3 = { IconComponent: FolderIcon.FolderIcon, label: intl5.string(intl10.t["u/NJKc"]), description: getNitroFileUploadRolloutCopy(obj4) };
  intl5 = intl10.intl;
  obj4 = { legacyCopy: intl6.string(intl10.t.i1UuMk), rolloutCopy: formatToPlainString(PvqncD, obj5) };
  getNitroFileUploadRolloutCopy = NitroFileUploadExperiments.getNitroFileUploadRolloutCopy;
  NitroFileUploadExperiments;
  intl6 = intl10.intl;
  const intl7 = intl10.intl;
  formatToPlainString = intl7.formatToPlainString;
  obj5 = { maxFileSize: obj6.getMaxFileSizeForPremiumType(PremiumTypes.TIER_2, { useSpace: false }) };
  PvqncD = intl10.t.PvqncD;
  items[2] = obj3;
  const amount = discountOffer.discount.amount;
  const obj7 = { style: tmp.contentContainer, children: items1 };
  items1 = [, , , ];
  obj6 = PremiumUtils;
  const obj8 = { style: tmp.heroIllustrationContainer, children: hasOwnProperty(NitroWumpusFlightRight3dIllustration.NitroWumpusFlightRight3dIllustration, { width: 180, height: 180 }) };
  items1[0] = hasOwnProperty(View, obj8);
  const obj9 = { variant: "heading-xl/bold", color: "mobile-text-heading-primary", style: tmp.title, children: intl8.formatToPlainString(intl10.t.qowbUk, { percent: amount }) };
  const Text = Text_Text.Text;
  intl8 = intl10.intl;
  items1[1] = hasOwnProperty(Text, obj9);
  items1[2] = hasOwnProperty(PremiumPerksListDefault, { perks: items });
  const obj10 = { style: tmp.buttonContainer, children: hasOwnProperty(Button, obj11) };
  obj11 = { size: "lg", text: intl9.formatToPlainString(intl10.t.bkQ4bH, { percent: amount }), onPress: onConfirm, grow: true, icon: hasOwnProperty(NitroWheelIcon, obj12) };
  Button = components_Button_Button.Button;
  intl9 = intl10.intl;
  obj12 = { size: "md", color: nativeDefault.unsafe_rawColors.WHITE };
  NitroWheelIcon = NitroWheelIcon2.NitroWheelIcon;
  items1[3] = hasOwnProperty(View, obj10);
  return metroRequire(View, obj7);
});
const result = size.fileFinishedImporting("modules/premium/native/discounts/PremiumDiscountOfferActionSheetContent.tsx");

export default memoResult;
