// Module ID: 16884
// Function ID: 16885
// Name: NATIVE_REQUIRED_ASSETS_ICONS
// Dependencies: [4752, 7612, 10213, 10161, 5258, 16885, 9709, 12480, 7617, 13109, 4238, 11745, 5344, 9397, 5362, 16886, 16887, 14306, 14134, 11172, 16888, 16889, 15408, 15406, 4236, 8421, 8419, 8163, 8107, 4750, 10735, 16527, 16890, 4768, 4769, 4230, 4780, 9821, 10719, 10794, 9110, 8528, 9569, 8491, 8781, 7997, 8322, 8324, 9642, 8779, 12101, 9930, 7577, 13764, 12099, 13107, 9463, 15127, 4753, 7628, 7623, 4747, 14356, 11035, 8098, 4754, 10776, 7886, 12150, 5310, 9224, 2]

// Module 16884 (NATIVE_REQUIRED_ASSETS_ICONS)
const obj = { AnnouncementsIcon: require("registerAsset"), AppsIcon: require("registerAsset"), ArrowAngleLeftUpIcon: require("registerAsset"), ArrowAngleRightUpIcon: require("registerAsset"), ArrowLargeLeftIcon: require("registerAsset"), ArrowLargeRightIcon: require("registerAsset"), AttachmentIcon: require("registerAsset"), BellZIcon: require("registerAsset"), BoostGemIcon: require("registerAsset"), ChannelListMagnifyingGlassIcon: require("registerAsset"), CheckmarkLargeIcon: require("registerAsset"), ChatXIcon: require("registerAsset"), CheckmarkSmallIcon: require("registerAsset"), ChevronSmallDownIcon: require("registerAsset"), ChevronSmallRightIcon: require("registerAsset"), CircleErrorIcon: require("registerAsset"), CircleInformationIcon: require("registerAsset"), CircleQuestionIcon: require("registerAsset"), ClipsIcon: require("registerAsset"), ClockWarningIcon: require("registerAsset"), ConnectionAverageIcon: require("registerAsset"), ConnectionBadIcon: require("registerAsset"), ConnectionFineIcon: require("registerAsset"), ConnectionUnknownIcon: require("registerAsset"), DownloadIcon: require("registerAsset"), EyeIcon: require("registerAsset"), EyeSlashIcon: require("registerAsset"), GameControllerIcon: require("registerAsset"), GifIcon: require("registerAsset"), GroupIcon: require("registerAsset"), HandRequestSpeakIcon: require("registerAsset"), HomeIcon: require("registerAsset"), ImageBrokenIcon: require("registerAsset"), ImageIcon: require("registerAsset"), ImageWarningIcon: require("registerAsset"), LinkIcon: require("registerAsset"), LockIcon: require("registerAsset"), LockUnlockedIcon: require("registerAsset"), MicrophoneArrowRightIcon: require("registerAsset"), MicrophoneIcon: require("registerAsset"), MicrophoneSlashIcon: require("registerAsset"), MoreHorizontalIcon: require("registerAsset"), MusicIcon: require("registerAsset"), PaperIcon: require("registerAsset"), PauseIcon: require("registerAsset"), PencilIcon: require("registerAsset"), PhoneCallIcon: require("registerAsset"), PhoneHangUpIcon: require("registerAsset"), PinIcon: require("registerAsset"), PlayIcon: require("registerAsset"), PlaystationNeutralIcon: require("registerAsset"), PollsIcon: require("registerAsset"), ReactionIcon: require("registerAsset"), RefreshIcon: require("registerAsset"), ScreenIcon: require("registerAsset"), SignPostIcon: require("registerAsset"), SlashBoxIcon: require("registerAsset"), SpotifyNeutralIcon: require("registerAsset"), StageIcon: require("registerAsset"), StickerIcon: require("registerAsset"), SuperReactionIcon: require("registerAsset"), ThreadIcon: require("registerAsset"), TicketIcon: require("registerAsset"), TopicsIcon: require("registerAsset"), UserCheckIcon: require("registerAsset"), VoiceNormalIcon: require("registerAsset"), VoiceXIcon: require("registerAsset"), WarningIcon: require("registerAsset"), WindowLaunchIcon: require("registerAsset"), XSmallIcon: require("registerAsset"), XboxNeutralIcon: require("registerAsset") };
const result = require("registerAsset").fileFinishedImporting("modules/react_asset/native/native_required_assets_icons.tsx");

export const NATIVE_REQUIRED_ASSETS_ICONS = obj;
