// Module ID: 16981
// Function ID: 16982
// Name: NATIVE_REQUIRED_ASSETS_ICONS
// Dependencies: [4771, 7691, 10295, 10243, 5275, 16982, 9791, 12565, 7696, 13193, 4256, 11826, 5364, 9479, 5382, 16983, 16984, 14393, 14218, 11253, 16985, 16986, 15507, 15505, 4254, 8498, 8496, 8240, 8184, 4769, 10813, 16629, 16987, 4787, 4788, 4248, 4799, 9903, 10797, 10872, 9187, 8605, 9650, 8568, 8858, 8074, 8399, 8401, 9723, 8856, 12183, 10012, 7656, 13848, 12181, 13191, 9545, 15213, 4772, 7707, 7702, 4766, 14442, 11116, 8175, 4773, 10854, 7963, 12232, 5327, 9306, 2]

// Module 16981 (NATIVE_REQUIRED_ASSETS_ICONS)
const obj = { AnnouncementsIcon: require("registerAsset"), AppsIcon: require("registerAsset"), ArrowAngleLeftUpIcon: require("registerAsset"), ArrowAngleRightUpIcon: require("registerAsset"), ArrowLargeLeftIcon: require("registerAsset"), ArrowLargeRightIcon: require("registerAsset"), AttachmentIcon: require("registerAsset"), BellZIcon: require("registerAsset"), BoostGemIcon: require("registerAsset"), ChannelListMagnifyingGlassIcon: require("registerAsset"), CheckmarkLargeIcon: require("registerAsset"), ChatXIcon: require("registerAsset"), CheckmarkSmallIcon: require("registerAsset"), ChevronSmallDownIcon: require("registerAsset"), ChevronSmallRightIcon: require("registerAsset"), CircleErrorIcon: require("registerAsset"), CircleInformationIcon: require("registerAsset"), CircleQuestionIcon: require("registerAsset"), ClipsIcon: require("registerAsset"), ClockWarningIcon: require("registerAsset"), ConnectionAverageIcon: require("registerAsset"), ConnectionBadIcon: require("registerAsset"), ConnectionFineIcon: require("registerAsset"), ConnectionUnknownIcon: require("registerAsset"), DownloadIcon: require("registerAsset"), EyeIcon: require("registerAsset"), EyeSlashIcon: require("registerAsset"), GameControllerIcon: require("registerAsset"), GifIcon: require("registerAsset"), GroupIcon: require("registerAsset"), HandRequestSpeakIcon: require("registerAsset"), HomeIcon: require("registerAsset"), ImageBrokenIcon: require("registerAsset"), ImageIcon: require("registerAsset"), ImageWarningIcon: require("registerAsset"), LinkIcon: require("registerAsset"), LockIcon: require("registerAsset"), LockUnlockedIcon: require("registerAsset"), MicrophoneArrowRightIcon: require("registerAsset"), MicrophoneIcon: require("registerAsset"), MicrophoneSlashIcon: require("registerAsset"), MoreHorizontalIcon: require("registerAsset"), MusicIcon: require("registerAsset"), PaperIcon: require("registerAsset"), PauseIcon: require("registerAsset"), PencilIcon: require("registerAsset"), PhoneCallIcon: require("registerAsset"), PhoneHangUpIcon: require("registerAsset"), PinIcon: require("registerAsset"), PlayIcon: require("registerAsset"), PlaystationNeutralIcon: require("registerAsset"), PollsIcon: require("registerAsset"), ReactionIcon: require("registerAsset"), RefreshIcon: require("registerAsset"), ScreenIcon: require("registerAsset"), SignPostIcon: require("registerAsset"), SlashBoxIcon: require("registerAsset"), SpotifyNeutralIcon: require("registerAsset"), StageIcon: require("registerAsset"), StickerIcon: require("registerAsset"), SuperReactionIcon: require("registerAsset"), ThreadIcon: require("registerAsset"), TicketIcon: require("registerAsset"), TopicsIcon: require("registerAsset"), UserCheckIcon: require("registerAsset"), VoiceNormalIcon: require("registerAsset"), VoiceXIcon: require("registerAsset"), WarningIcon: require("registerAsset"), WindowLaunchIcon: require("registerAsset"), XSmallIcon: require("registerAsset"), XboxNeutralIcon: require("registerAsset") };
const result = require("registerAsset").fileFinishedImporting("modules/react_asset/native/native_required_assets_icons.tsx");

export const NATIVE_REQUIRED_ASSETS_ICONS = obj;
