// Module ID: 16644
// Function ID: 129829
// Name: NATIVE_REQUIRED_ASSETS_ICONS
// Dependencies: [4600, 7473, 9984, 9914, 5092, 16645, 9692, 14893, 7478, 12905, 4083, 11529, 5155, 8571, 5172, 16646, 16647, 14099, 13927, 11026, 16648, 16649, 15174, 15172, 4081, 8778, 8542, 7908, 7853, 4598, 10707, 16288, 16650, 4616, 4617, 4075, 4628, 10372, 10691, 10765, 8914, 9008, 9115, 9321, 8333, 7743, 9124, 9171, 9990, 8331, 11885, 9690, 7438, 13563, 11883, 12903, 10910, 14991, 4601, 7489, 7484, 4595, 14147, 10921, 7844, 4602, 10747, 7632, 10190, 5120, 8666, 2]

// Module 16644 (NATIVE_REQUIRED_ASSETS_ICONS)
const obj = { AnnouncementsIcon: require("registerAsset"), AppsIcon: require("registerAsset"), ArrowAngleLeftUpIcon: require("registerAsset"), ArrowAngleRightUpIcon: require("registerAsset"), ArrowLargeLeftIcon: require("registerAsset"), ArrowLargeRightIcon: require("registerAsset"), AttachmentIcon: require("registerAsset"), BellZIcon: require("registerAsset"), BoostGemIcon: require("registerAsset"), ChannelListMagnifyingGlassIcon: require("registerAsset"), CheckmarkLargeIcon: require("registerAsset"), ChatXIcon: require("registerAsset"), CheckmarkSmallIcon: require("registerAsset"), ChevronSmallDownIcon: require("registerAsset"), ChevronSmallRightIcon: require("registerAsset"), CircleErrorIcon: require("registerAsset"), CircleInformationIcon: require("registerAsset"), CircleQuestionIcon: require("registerAsset"), ClipsIcon: require("registerAsset"), ClockWarningIcon: require("registerAsset"), ConnectionAverageIcon: require("registerAsset"), ConnectionBadIcon: require("registerAsset"), ConnectionFineIcon: require("registerAsset"), ConnectionUnknownIcon: require("registerAsset"), DownloadIcon: require("registerAsset"), EyeIcon: require("registerAsset"), EyeSlashIcon: require("registerAsset"), GameControllerIcon: require("registerAsset"), GifIcon: require("registerAsset"), GroupIcon: require("registerAsset"), HandRequestSpeakIcon: require("registerAsset"), HomeIcon: require("registerAsset"), ImageBrokenIcon: require("registerAsset"), ImageIcon: require("registerAsset"), ImageWarningIcon: require("registerAsset"), LinkIcon: require("registerAsset"), LockIcon: require("registerAsset"), LockUnlockedIcon: require("registerAsset"), MicrophoneArrowRightIcon: require("registerAsset"), MicrophoneIcon: require("registerAsset"), MicrophoneSlashIcon: require("registerAsset"), MoreHorizontalIcon: require("registerAsset"), MusicIcon: require("registerAsset"), PaperIcon: require("registerAsset"), PauseIcon: require("registerAsset"), PencilIcon: require("registerAsset"), PhoneCallIcon: require("registerAsset"), PhoneHangUpIcon: require("registerAsset"), PinIcon: require("registerAsset"), PlayIcon: require("registerAsset"), PlaystationNeutralIcon: require("registerAsset"), PollsIcon: require("registerAsset"), ReactionIcon: require("registerAsset"), RefreshIcon: require("registerAsset"), ScreenIcon: require("registerAsset"), SignPostIcon: require("registerAsset"), SlashBoxIcon: require("registerAsset"), SpotifyNeutralIcon: require("registerAsset"), StageIcon: require("registerAsset"), StickerIcon: require("registerAsset"), SuperReactionIcon: require("registerAsset"), ThreadIcon: require("registerAsset"), TicketIcon: require("registerAsset"), TopicsIcon: require("registerAsset"), UserCheckIcon: require("registerAsset"), VoiceNormalIcon: require("registerAsset"), VoiceXIcon: require("registerAsset"), WarningIcon: require("registerAsset"), WindowLaunchIcon: require("registerAsset"), XSmallIcon: require("registerAsset"), XboxNeutralIcon: require("registerAsset") };
const result = require("registerAsset").fileFinishedImporting("modules/react_asset/native/native_required_assets_icons.tsx");

export const NATIVE_REQUIRED_ASSETS_ICONS = obj;
