// Module ID: 8176
// Function ID: 8177
// Name: Circle
// Dependencies: [8177, 8201, 8203, 8205, 8207, 8209, 8213, 8215, 8216, 8218, 8219, 8220, 8221, 8222, 8227, 8232, 8223, 8233, 8229, 8231, 8234, 8225, 8235, 8236, 8237, 8238, 8239, 8240, 8242, 8187, 8244, 8246, 8248, 8252, 8254, 8257, 8259, 8261, 8263, 8264, 8266, 8268, 8269, 8271, 8275, 8272, 8277]

// Module 8176 (Circle)
import _isNativeReflectConstructDefault from "_isNativeReflectConstruct" /* 8177 */;
import _isNativeReflectConstructDefault2 from "_isNativeReflectConstruct" /* 8187 */;
import _isNativeReflectConstructDefault3 from "_isNativeReflectConstruct" /* 8201 */;
import _isNativeReflectConstructDefault4 from "_isNativeReflectConstruct" /* 8203 */;
import _isNativeReflectConstructDefault5 from "_isNativeReflectConstruct" /* 8205 */;
import _isNativeReflectConstructDefault6 from "_isNativeReflectConstruct" /* 8207 */;
import _isNativeReflectConstructDefault7 from "_isNativeReflectConstruct" /* 8209 */;
import _isNativeReflectConstructDefault8 from "_isNativeReflectConstruct" /* 8213 */;
import _isNativeReflectConstructDefault9 from "_isNativeReflectConstruct" /* 8215 */;
import _isNativeReflectConstructDefault10 from "_isNativeReflectConstruct" /* 8216 */;
import _isNativeReflectConstructDefault11 from "_isNativeReflectConstruct" /* 8218 */;
import _isNativeReflectConstructDefault12 from "_isNativeReflectConstruct" /* 8219 */;
import _isNativeReflectConstructDefault13 from "_isNativeReflectConstruct" /* 8220 */;
import _isNativeReflectConstructDefault14 from "_isNativeReflectConstruct" /* 8221 */;
import _isNativeReflectConstructDefault15 from "_isNativeReflectConstruct" /* 8222 */;
import _isNativeReflectConstructDefault16 from "_isNativeReflectConstruct" /* 8223 */;
import _isNativeReflectConstructDefault17 from "_isNativeReflectConstruct" /* 8225 */;
import _isNativeReflectConstructDefault18 from "_isNativeReflectConstruct" /* 8227 */;
import _isNativeReflectConstructDefault19 from "_isNativeReflectConstruct" /* 8229 */;
import _isNativeReflectConstructDefault20 from "_isNativeReflectConstruct" /* 8231 */;
import _isNativeReflectConstructDefault21 from "_isNativeReflectConstruct" /* 8233 */;
import _isNativeReflectConstructDefault22 from "_isNativeReflectConstruct" /* 8234 */;
import _isNativeReflectConstructDefault23 from "_isNativeReflectConstruct" /* 8235 */;
import _isNativeReflectConstructDefault24 from "_isNativeReflectConstruct" /* 8236 */;
import _isNativeReflectConstructDefault25 from "_isNativeReflectConstruct" /* 8237 */;
import _isNativeReflectConstructDefault26 from "_isNativeReflectConstruct" /* 8238 */;
import _isNativeReflectConstructDefault27 from "_isNativeReflectConstruct" /* 8239 */;
import _isNativeReflectConstructDefault28 from "_isNativeReflectConstruct" /* 8240 */;
import _isNativeReflectConstructDefault29 from "_isNativeReflectConstruct" /* 8242 */;
import _isNativeReflectConstructDefault30 from "_isNativeReflectConstruct" /* 8244 */;
import _isNativeReflectConstructDefault31 from "_isNativeReflectConstruct" /* 8246 */;
import _isNativeReflectConstructDefault32 from "_isNativeReflectConstruct" /* 8248 */;
import _isNativeReflectConstructDefault33 from "_isNativeReflectConstruct" /* 8252 */;
import _isNativeReflectConstructDefault34 from "_isNativeReflectConstruct" /* 8254 */;
import _isNativeReflectConstructDefault35 from "_isNativeReflectConstruct" /* 8257 */;
import _isNativeReflectConstructDefault36 from "_isNativeReflectConstruct" /* 8259 */;
import _isNativeReflectConstructDefault37 from "_isNativeReflectConstruct" /* 8261 */;
import _isNativeReflectConstructDefault38 from "_isNativeReflectConstruct" /* 8263 */;
import _isNativeReflectConstructDefault39 from "_isNativeReflectConstruct" /* 8264 */;
import _isNativeReflectConstructDefault40 from "_isNativeReflectConstruct" /* 8266 */;
import _isNativeReflectConstructDefault41 from "_isNativeReflectConstruct" /* 8268 */;
import _isNativeReflectConstructDefault42 from "_isNativeReflectConstruct" /* 8269 */;
import _isNativeReflectConstructDefault43 from "_isNativeReflectConstruct" /* 8271 */;
import _isNativeReflectConstructDefault44 from "_isNativeReflectConstruct" /* 8272 */;
import _isNativeReflectConstructDefault45 from "_isNativeReflectConstruct" /* 8275 */;
import _isNativeReflectConstructDefault46 from "_isNativeReflectConstruct" /* 8277 */;


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;
