// Module ID: 8244
// Function ID: 8245
// Name: Circle
// Dependencies: [8245, 8269, 8271, 8273, 8275, 8277, 8281, 8283, 8284, 8286, 8287, 8288, 8289, 8290, 8295, 8300, 8291, 8301, 8297, 8299, 8302, 8293, 8303, 8304, 8305, 8306, 8307, 8308, 8310, 8255, 8312, 8314, 8316, 8320, 8322, 8325, 8327, 8329, 8331, 8332, 8334, 8336, 8337, 8339, 8343, 8340, 8345]

// Module 8244 (Circle)
import _isNativeReflectConstructDefault from "_isNativeReflectConstruct" /* 8245 */;
import _isNativeReflectConstructDefault2 from "_isNativeReflectConstruct" /* 8255 */;
import _isNativeReflectConstructDefault3 from "_isNativeReflectConstruct" /* 8269 */;
import _isNativeReflectConstructDefault4 from "_isNativeReflectConstruct" /* 8271 */;
import _isNativeReflectConstructDefault5 from "_isNativeReflectConstruct" /* 8273 */;
import _isNativeReflectConstructDefault6 from "_isNativeReflectConstruct" /* 8275 */;
import _isNativeReflectConstructDefault7 from "_isNativeReflectConstruct" /* 8277 */;
import _isNativeReflectConstructDefault8 from "_isNativeReflectConstruct" /* 8281 */;
import _isNativeReflectConstructDefault9 from "_isNativeReflectConstruct" /* 8283 */;
import _isNativeReflectConstructDefault10 from "_isNativeReflectConstruct" /* 8284 */;
import _isNativeReflectConstructDefault11 from "_isNativeReflectConstruct" /* 8286 */;
import _isNativeReflectConstructDefault12 from "_isNativeReflectConstruct" /* 8287 */;
import _isNativeReflectConstructDefault13 from "_isNativeReflectConstruct" /* 8288 */;
import _isNativeReflectConstructDefault14 from "_isNativeReflectConstruct" /* 8289 */;
import _isNativeReflectConstructDefault15 from "_isNativeReflectConstruct" /* 8290 */;
import _isNativeReflectConstructDefault16 from "_isNativeReflectConstruct" /* 8291 */;
import _isNativeReflectConstructDefault17 from "_isNativeReflectConstruct" /* 8293 */;
import _isNativeReflectConstructDefault18 from "_isNativeReflectConstruct" /* 8295 */;
import _isNativeReflectConstructDefault19 from "_isNativeReflectConstruct" /* 8297 */;
import _isNativeReflectConstructDefault20 from "_isNativeReflectConstruct" /* 8299 */;
import _isNativeReflectConstructDefault21 from "_isNativeReflectConstruct" /* 8301 */;
import _isNativeReflectConstructDefault22 from "_isNativeReflectConstruct" /* 8302 */;
import _isNativeReflectConstructDefault23 from "_isNativeReflectConstruct" /* 8303 */;
import _isNativeReflectConstructDefault24 from "_isNativeReflectConstruct" /* 8304 */;
import _isNativeReflectConstructDefault25 from "_isNativeReflectConstruct" /* 8305 */;
import _isNativeReflectConstructDefault26 from "_isNativeReflectConstruct" /* 8306 */;
import _isNativeReflectConstructDefault27 from "_isNativeReflectConstruct" /* 8307 */;
import _isNativeReflectConstructDefault28 from "_isNativeReflectConstruct" /* 8308 */;
import _isNativeReflectConstructDefault29 from "_isNativeReflectConstruct" /* 8310 */;
import _isNativeReflectConstructDefault30 from "_isNativeReflectConstruct" /* 8312 */;
import _isNativeReflectConstructDefault31 from "_isNativeReflectConstruct" /* 8314 */;
import _isNativeReflectConstructDefault32 from "_isNativeReflectConstruct" /* 8316 */;
import _isNativeReflectConstructDefault33 from "_isNativeReflectConstruct" /* 8320 */;
import _isNativeReflectConstructDefault34 from "_isNativeReflectConstruct" /* 8322 */;
import _isNativeReflectConstructDefault35 from "_isNativeReflectConstruct" /* 8325 */;
import _isNativeReflectConstructDefault36 from "_isNativeReflectConstruct" /* 8327 */;
import _isNativeReflectConstructDefault37 from "_isNativeReflectConstruct" /* 8329 */;
import _isNativeReflectConstructDefault38 from "_isNativeReflectConstruct" /* 8331 */;
import _isNativeReflectConstructDefault39 from "_isNativeReflectConstruct" /* 8332 */;
import _isNativeReflectConstructDefault40 from "_isNativeReflectConstruct" /* 8334 */;
import _isNativeReflectConstructDefault41 from "_isNativeReflectConstruct" /* 8336 */;
import _isNativeReflectConstructDefault42 from "_isNativeReflectConstruct" /* 8337 */;
import _isNativeReflectConstructDefault43 from "_isNativeReflectConstruct" /* 8339 */;
import _isNativeReflectConstructDefault44 from "_isNativeReflectConstruct" /* 8340 */;
import _isNativeReflectConstructDefault45 from "_isNativeReflectConstruct" /* 8343 */;
import _isNativeReflectConstructDefault46 from "_isNativeReflectConstruct" /* 8345 */;


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;
