// Module ID: 8456
// Function ID: 8457
// Name: Circle
// Dependencies: [8457, 8481, 8483, 8485, 8487, 8489, 8493, 8495, 8496, 8498, 8499, 8500, 8501, 8502, 8507, 8512, 8503, 8513, 8509, 8511, 8514, 8505, 8515, 8516, 8517, 8518, 8519, 8520, 8522, 8467, 8524, 8526, 8528, 8532, 8534, 8537, 8539, 8541, 8543, 8544, 8546, 8548, 8549, 8551, 8555, 8552, 8557]

// Module 8456 (Circle)
import _isNativeReflectConstructDefault from "_isNativeReflectConstruct" /* 8457 */;
import _isNativeReflectConstructDefault2 from "_isNativeReflectConstruct" /* 8467 */;
import _isNativeReflectConstructDefault3 from "_isNativeReflectConstruct" /* 8481 */;
import _isNativeReflectConstructDefault4 from "_isNativeReflectConstruct" /* 8483 */;
import _isNativeReflectConstructDefault5 from "_isNativeReflectConstruct" /* 8485 */;
import _isNativeReflectConstructDefault6 from "_isNativeReflectConstruct" /* 8487 */;
import _isNativeReflectConstructDefault7 from "_isNativeReflectConstruct" /* 8489 */;
import _isNativeReflectConstructDefault8 from "_isNativeReflectConstruct" /* 8493 */;
import _isNativeReflectConstructDefault9 from "_isNativeReflectConstruct" /* 8495 */;
import _isNativeReflectConstructDefault10 from "_isNativeReflectConstruct" /* 8496 */;
import _isNativeReflectConstructDefault11 from "_isNativeReflectConstruct" /* 8498 */;
import _isNativeReflectConstructDefault12 from "_isNativeReflectConstruct" /* 8499 */;
import _isNativeReflectConstructDefault13 from "_isNativeReflectConstruct" /* 8500 */;
import _isNativeReflectConstructDefault14 from "_isNativeReflectConstruct" /* 8501 */;
import _isNativeReflectConstructDefault15 from "_isNativeReflectConstruct" /* 8502 */;
import _isNativeReflectConstructDefault16 from "_isNativeReflectConstruct" /* 8503 */;
import _isNativeReflectConstructDefault17 from "_isNativeReflectConstruct" /* 8505 */;
import _isNativeReflectConstructDefault18 from "_isNativeReflectConstruct" /* 8507 */;
import _isNativeReflectConstructDefault19 from "_isNativeReflectConstruct" /* 8509 */;
import _isNativeReflectConstructDefault20 from "_isNativeReflectConstruct" /* 8511 */;
import _isNativeReflectConstructDefault21 from "_isNativeReflectConstruct" /* 8513 */;
import _isNativeReflectConstructDefault22 from "_isNativeReflectConstruct" /* 8514 */;
import _isNativeReflectConstructDefault23 from "_isNativeReflectConstruct" /* 8515 */;
import _isNativeReflectConstructDefault24 from "_isNativeReflectConstruct" /* 8516 */;
import _isNativeReflectConstructDefault25 from "_isNativeReflectConstruct" /* 8517 */;
import _isNativeReflectConstructDefault26 from "_isNativeReflectConstruct" /* 8518 */;
import _isNativeReflectConstructDefault27 from "_isNativeReflectConstruct" /* 8519 */;
import _isNativeReflectConstructDefault28 from "_isNativeReflectConstruct" /* 8520 */;
import _isNativeReflectConstructDefault29 from "_isNativeReflectConstruct" /* 8522 */;
import _isNativeReflectConstructDefault30 from "_isNativeReflectConstruct" /* 8524 */;
import _isNativeReflectConstructDefault31 from "_isNativeReflectConstruct" /* 8526 */;
import _isNativeReflectConstructDefault32 from "_isNativeReflectConstruct" /* 8528 */;
import _isNativeReflectConstructDefault33 from "_isNativeReflectConstruct" /* 8532 */;
import _isNativeReflectConstructDefault34 from "_isNativeReflectConstruct" /* 8534 */;
import _isNativeReflectConstructDefault35 from "_isNativeReflectConstruct" /* 8537 */;
import _isNativeReflectConstructDefault36 from "_isNativeReflectConstruct" /* 8539 */;
import _isNativeReflectConstructDefault37 from "_isNativeReflectConstruct" /* 8541 */;
import _isNativeReflectConstructDefault38 from "_isNativeReflectConstruct" /* 8543 */;
import _isNativeReflectConstructDefault39 from "_isNativeReflectConstruct" /* 8544 */;
import _isNativeReflectConstructDefault40 from "_isNativeReflectConstruct" /* 8546 */;
import _isNativeReflectConstructDefault41 from "_isNativeReflectConstruct" /* 8548 */;
import _isNativeReflectConstructDefault42 from "_isNativeReflectConstruct" /* 8549 */;
import _isNativeReflectConstructDefault43 from "_isNativeReflectConstruct" /* 8551 */;
import _isNativeReflectConstructDefault44 from "_isNativeReflectConstruct" /* 8552 */;
import _isNativeReflectConstructDefault45 from "_isNativeReflectConstruct" /* 8555 */;
import _isNativeReflectConstructDefault46 from "_isNativeReflectConstruct" /* 8557 */;


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;
