// Module ID: 7844
// Function ID: 62553
// Name: UploadTypes
// Dependencies: [57, 31]

// Module 7844 (UploadTypes)
import { BACKGROUND_REPLACEMENT_SIZE } from "_slicedToArray";
import module_31 from "module_31";

const result = BACKGROUND_REPLACEMENT_SIZE.width / BACKGROUND_REPLACEMENT_SIZE.height;
const result1 = 432 / result;
const result2 = module_31.fileFinishedImporting("modules/image_cropping/web/ImageCroppingConstants.tsx");

export const UploadTypes = { AVATAR: "AVATAR", BANNER: "BANNER", GUILD_BANNER: "GUILD_BANNER", VIDEO_BACKGROUND: "VIDEO_BACKGROUND", SCHEDULED_EVENT_IMAGE: "SCHEDULED_EVENT_IMAGE", HOME_HEADER: "HOME_HEADER", AVATAR_DECORATION: "AVATAR_DECORATION", GUILD_ICON: "GUILD_ICON" };
export const EDITING_CONTAINER_WIDTH = 432;
export const USER_BANNER_MAX_WIDTH = 2400;
export const USER_BANNER_MAX_HEIGHT = 848;
export const GUILD_BANNER_MAX_WIDTH = 2400;
export const GUILD_BANNER_MAX_HEIGHT = 1350;
export const SCHEDULED_EVENT_IMAGE_MAX_WIDTH = 2400;
export const SCHEDULED_EVENT_IMAGE_MAX_HEIGHT = 960;
export const HOME_HEADER_MAX_WIDTH = 2400;
export const HOME_HEADER_MAX_HEIGHT = 600;
export const BANNER_ASPECT_RATIO = 2.8333333333333335;
export const GUILD_BANNER_ASPECT_RATIO = 1.7777777777777777;
export const SCHEDULED_EVENT_IMAGE_ASPECT_RATIO = 2.5;
export const HOME_HEADER_ASPECT_RATIO = 4;
export const MAX_BANNER_OVERLAY_HEIGHT = 152.47058823529412;
export const MAX_GUILD_BANNER_OVERLAY_HEIGHT = 243;
export const MAX_SCHEDULED_EVENT_IMAGE_OVERLAY_HEIGHT = 172.8;
export const MAX_HOME_HEADER_OVERLAY_HEIGHT = 108;
export const VIDEO_BACKGROUND_ASPECT_RATIO = result;
export const MAX_VIDEO_OVERLAY_HEIGHT = result1;
export const MessageTypes = { CROP_ANIMATED_IMAGE_START: 0, [0]: "CROP_ANIMATED_IMAGE_START", CROP_ANIMATED_IMAGE_COMPLETE: 1, [1]: "CROP_ANIMATED_IMAGE_COMPLETE", CROP_ANIMATED_IMAGE_ERROR: 2, [2]: "CROP_ANIMATED_IMAGE_ERROR" };
