// Module ID: 1177
// Function ID: 1178
// Name: native
// Dependencies: [1178, 1179, 2, 1180, 14385, 13634, 14386, 14389, 14390, 14391, 14392, 14393, 14394, 5147, 14395, 14397, 9877, 14398, 14399, 14401, 14402, 14403, 14404, 14405, 5220, 13350, 14414, 14416, 14396, 14418, 14420, 14421, 14422, 14423, 14424, 14425, 14426, 8922, 14427, 14490, 14491, 14492, 14493, 14494, 8921, 8903, 5371, 13760, 10043, 10567]

// Module 1177 (native)
import StatusConstants from "StatusConstants" /* 1178 */;
import BadgeConstants from "BadgeConstants" /* 1179 */;
import Button_Button from "Button/Button" /* 1180 */;
import OverlayView from "OverlayView" /* 5147 */;
import Icon from "Icon" /* 5220 */;
import Pressables from "Pressables" /* 5371 */;
import Form from "Form" /* 8903 */;
import CardSectionDefault from "CardSection" /* 8921 */;
import LegacyText_LegacyTextDefault from "LegacyText/LegacyText" /* 8922 */;
import TextInput_TextInputDefault from "TextInput/TextInput" /* 9877 */;
import TouchableHitBoxDefault from "TouchableHitBox" /* 10043 */;
import RoleLabel from "RoleLabel" /* 10567 */;
import CutoutableAvatarImage from "CutoutableAvatarImage" /* 13350 */;
import BetaTag from "BetaTag" /* 13634 */;
import IconButton_IconButton from "IconButton/IconButton" /* 13760 */;
import ShinyButton_ShinyButtonDefault from "ShinyButton/ShinyButton" /* 14385 */;
import Checkbox_CheckboxDefault from "Checkbox/Checkbox" /* 14386 */;
import CloseIconDefault from "CloseIcon" /* 14389 */;
import EllipsisDefault from "Ellipsis" /* 14390 */;
import GradientBorderDefault from "GradientBorder" /* 14391 */;
import HelpMessage from "HelpMessage" /* 14392 */;
import IconPillDefault from "IconPill" /* 14393 */;
import NewTagDefault from "NewTag" /* 14394 */;
import RadioGroup from "RadioGroup" /* 14395 */;
import CollapsibleDefault from "Collapsible" /* 14396 */;
import SummarizedIconRow from "SummarizedIconRow" /* 14397 */;
import ThemedIconDefault from "ThemedIcon" /* 14398 */;
import ThumbnailImageDefault from "ThumbnailImage" /* 14399 */;
import Tooltip_Tooltip from "Tooltip/Tooltip" /* 14401 */;
import WarningCircleDefault from "WarningCircle" /* 14402 */;
import Status_StatusUtils from "Status/StatusUtils" /* 14403 */;
import getStatusContainerStyleDefault from "getStatusContainerStyle" /* 14404 */;
import Status from "Status" /* 14405 */;
import Avatar from "Avatar" /* 14414 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 14416 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 14418 */;
import Easing from "Easing" /* 14420 */;
import SpacerDefault from "Spacer" /* 14421 */;
import LiveTagDefault from "LiveTag" /* 14422 */;
import RoleDot from "RoleDot" /* 14423 */;
import Shadows from "Shadows" /* 14424 */;
import NitroWheelDefault from "NitroWheel" /* 14425 */;
import EmptyStateDefault from "EmptyState" /* 14426 */;
import Atoms from "Atoms" /* 14427 */;
import Badge_Badge from "Badge/Badge" /* 14490 */;
import CarouselPaginationDefault from "CarouselPagination" /* 14491 */;
import InputView from "InputView" /* 14492 */;
import Badges_Badges from "Badges/Badges" /* 14493 */;
import RefreshEmptyState from "RefreshEmptyState" /* 14494 */;
import size from "module_2" /* 2 */;

const Button_ButtonDefault = Button_Button;
const OverlayViewDefault = OverlayView;
const IconDefault = Icon;
const CutoutableAvatarImageDefault = CutoutableAvatarImage;
const BetaTagDefault = BetaTag;
const HelpMessageDefault = HelpMessage;
const RadioGroupDefault = RadioGroup;
const SummarizedIconRowDefault = SummarizedIconRow;
const Tooltip_TooltipDefault = Tooltip_Tooltip;
const StatusDefault = Status;
const AvatarDefault = Avatar;
const Badge_BadgeDefault = Badge_Badge;
const InputViewDefault = InputView;
const RefreshEmptyStateDefault = RefreshEmptyState;

const result = size.fileFinishedImporting("design/void/native.tsx");

export const Button = Button_ButtonDefault;
export const BUTTON_CORNER_RADIUS = Button_Button.BUTTON_CORNER_RADIUS;
export const useButtonStyles = Button_Button.useButtonStyles;
export const ButtonLooks = Button_Button.ButtonLooks;
export const ButtonColors = Button_Button.ButtonColors;
export const ButtonSizes = Button_Button.ButtonSizes;
export const getButtonStyles = Button_Button.getButtonStyles;
export const ButtonText = Button_Button.ButtonText;
export const getRedesignVariant = Button_Button.getRedesignVariant;
export const getRedesignSize = Button_Button.getRedesignSize;
export const ShinyButton = ShinyButton_ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = Checkbox_CheckboxDefault;
export const CloseIcon = CloseIconDefault;
export const Ellipsis = EllipsisDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = OverlayViewDefault;
export const TransitionGroupOverlayView = OverlayView.TransitionGroupOverlayView;
export const NonExpandingOverlayView = OverlayView.NonExpandingOverlayView;
export const RadioGroup = RadioGroupDefault;
export const RadioIndicator = RadioGroup.RadioIndicator;
export const RadioItem = RadioGroup.RadioItem;
export const SummarizedIconRow = SummarizedIconRowDefault;
export const OverflowText = SummarizedIconRow.OverflowText;
export const OverflowTextSmall = SummarizedIconRow.OverflowTextSmall;
export const OverflowCircle = SummarizedIconRow.OverflowCircle;
export const TextInput = TextInput_TextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = ThumbnailImageDefault;
export const Tooltip = Tooltip_TooltipDefault;
export const TooltipArrowDirections = Tooltip_Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip_Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = StatusConstants.STATUS_PADDING;
export const StatusSizes = StatusConstants.StatusSizes;
export const getAnimatedTypingTranslateX = Status_StatusUtils.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = Status_StatusUtils.getMobileStatusContainerRect;
export const getStatusTypingDimensions = Status_StatusUtils.getStatusTypingDimensions;
export const getStatusContainerStyle = getStatusContainerStyleDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconDefault;
export const IconSizes = Icon.IconSizes;
export const getIconSize = Icon.getIconSize;
export const getIconStyle = Icon.getIconStyle;
export const CutoutableAvatarImage = CutoutableAvatarImageDefault;
export const AvatarSizes = CutoutableAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = CutoutableAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = CutoutableAvatarImage.styles;
export const CutoutDirection = CutoutableAvatarImage.CutoutDirection;
export const CutoutType = CutoutableAvatarImage.CutoutType;
export const Avatar = AvatarDefault;
export const getStatusSize = Avatar.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = BadgeConstants.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = BadgeConstants.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = BadgeConstants.BADGE_PADDING;
export const BADGE_MASK_SIZE = BadgeConstants.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = BadgeConstants.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = Easing.STANDARD_EASING;
export const DECELERATED_EASING = Easing.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = Shadows.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = Shadows.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = Shadows.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = Shadows.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = Shadows.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = LegacyText_LegacyTextDefault;
export const RNTextInput = Atoms.RNTextInput;
export const Badge = Badge_BadgeDefault;
export const MaskedBadge = Badge_Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = InputViewDefault;
export const ClearButtonVisibility = InputView.ClearButtonVisibility;
export const BadgeColors = Badges_Badges.BadgeColors;
export const TextBadge = Badges_Badges.TextBadge;
export const RefreshEmptyState = RefreshEmptyStateDefault;
export const ThemedEmptyState = RefreshEmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = Pressables.PressableOpacity;
export const PressableHighlight = Pressables.PressableHighlight;
export const SquareIconButton = IconButton_IconButton.SquareIconButton;
export const CircularIconButton = IconButton_IconButton.CircularIconButton;
export const TouchableHitBox = TouchableHitBoxDefault;
export const RoleLabel = RoleLabel.RoleLabel;
