// Module ID: 1296
// Function ID: 1297
// Name: Button
// Dependencies: [1297, 1298, 2, 1299, 13967, 13191, 13968, 13971, 13972, 13973, 13974, 13975, 13976, 4865, 13977, 13979, 9744, 13980, 13981, 13983, 13984, 13985, 13986, 13987, 4931, 9445, 13996, 13998, 13978, 14000, 14002, 14003, 14004, 14005, 14006, 14007, 14008, 8404, 14009, 14061, 14062, 14063, 14064, 14065, 8403, 8376, 5077, 13360, 9085, 10373]

// Module 1296 (Button)
import set from "set" /* 2 */;
import STATUS_PADDING from "STATUS_PADDING" /* 1297 */;
import PX_16 from "PX_16" /* 1298 */;
import getTextStyles from "getTextStyles" /* 1299 */;
import getTextStylesDefault from "getTextStyles" /* 1299 */;
import View from "View" /* 4865 */;
import ViewDefault from "View" /* 4865 */;
import IconSizes from "IconSizes" /* 4931 */;
import IconSizesDefault from "IconSizes" /* 4931 */;
import PressableBase from "PressableBase" /* 5077 */;
import Form from "Form" /* 8376 */;
import CardSectionDefault from "CardSection" /* 8403 */;
import _modDef8404 from "module_8404" /* 8404 */;
import renderDefault from "render" /* 9085 */;
import StaticNativeCutoutAvatarImage from "StaticNativeCutoutAvatarImage" /* 9445 */;
import StaticNativeCutoutAvatarImageDefault from "StaticNativeCutoutAvatarImage" /* 9445 */;
import VoidTextInputDefault from "VoidTextInput" /* 9744 */;
import RoleLabel from "RoleLabel" /* 10373 */;
import BetaTag from "BetaTag" /* 13191 */;
import BetaTagDefault from "BetaTag" /* 13191 */;
import SquareIconButton from "SquareIconButton" /* 13360 */;
import ShinyButtonDefault from "ShinyButton" /* 13967 */;
import CheckboxDefault from "Checkbox" /* 13968 */;
import CloseDefault from "Close" /* 13971 */;
import AnimatedEllipsisDotDefault from "AnimatedEllipsisDot" /* 13972 */;
import GradientBorderDefault from "GradientBorder" /* 13973 */;
import HelpMessage from "HelpMessage" /* 13974 */;
import HelpMessageDefault from "HelpMessage" /* 13974 */;
import IconPillDefault from "IconPill" /* 13975 */;
import NewTagDefault from "NewTag" /* 13976 */;
import RadioEmpty from "RadioEmpty" /* 13977 */;
import RadioEmptyDefault from "RadioEmpty" /* 13977 */;
import CollapsibleDefault from "Collapsible" /* 13978 */;
import OverflowSquircle from "OverflowSquircle" /* 13979 */;
import OverflowSquircleDefault from "OverflowSquircle" /* 13979 */;
import ThemedIconDefault from "ThemedIcon" /* 13980 */;
import LocalImageThumbnailDefault from "LocalImageThumbnail" /* 13981 */;
import Tooltip from "Tooltip" /* 13983 */;
import TooltipDefault from "Tooltip" /* 13983 */;
import WarningCircleDefault from "WarningCircle" /* 13984 */;
import getAnimatedTypingTranslateX from "getAnimatedTypingTranslateX" /* 13985 */;
import STATUS_PADDINGDefault from "STATUS_PADDING" /* 13986 */;
import Status from "Status" /* 13987 */;
import StatusDefault from "Status" /* 13987 */;
import getStatusSize from "getStatusSize" /* 13996 */;
import getStatusSizeDefault from "getStatusSize" /* 13996 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 13998 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 14000 */;
import STANDARD_EASING from "STANDARD_EASING" /* 14002 */;
import SpacerDefault from "Spacer" /* 14003 */;
import LiveTagDefault from "LiveTag" /* 14004 */;
import RoleDot from "RoleDot" /* 14005 */;
import generateBoxShadowStyle from "generateBoxShadowStyle" /* 14006 */;
import NitroWheelDefault from "NitroWheel" /* 14007 */;
import EmptyStateDefault from "EmptyState" /* 14008 */;
import RNTextInput from "RNTextInput" /* 14009 */;
import Badge from "Badge" /* 14061 */;
import BadgeDefault from "Badge" /* 14061 */;
import CarouselPaginationDefault from "CarouselPagination" /* 14062 */;
import Fonts from "Fonts" /* 14063 */;
import FontsDefault from "Fonts" /* 14063 */;
import BadgeColors from "BadgeColors" /* 14064 */;
import EmptyState from "EmptyState" /* 14065 */;
import EmptyStateDefault2 from "EmptyState" /* 14065 */;

const result = set.fileFinishedImporting("design/void/native.tsx");

export const Button = getTextStylesDefault;
export const BUTTON_CORNER_RADIUS = getTextStyles.BUTTON_CORNER_RADIUS;
export const useButtonStyles = getTextStyles.useButtonStyles;
export const ButtonLooks = getTextStyles.ButtonLooks;
export const ButtonColors = getTextStyles.ButtonColors;
export const ButtonSizes = getTextStyles.ButtonSizes;
export const getButtonStyles = getTextStyles.getButtonStyles;
export const ButtonText = getTextStyles.ButtonText;
export const getRedesignVariant = getTextStyles.getRedesignVariant;
export const getRedesignSize = getTextStyles.getRedesignSize;
export const ShinyButton = ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = CheckboxDefault;
export const CloseIcon = CloseDefault;
export const Ellipsis = AnimatedEllipsisDotDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = ViewDefault;
export const TransitionGroupOverlayView = View.TransitionGroupOverlayView;
export const NonExpandingOverlayView = View.NonExpandingOverlayView;
export const RadioGroup = RadioEmptyDefault;
export const RadioIndicator = RadioEmpty.RadioIndicator;
export const RadioItem = RadioEmpty.RadioItem;
export const SummarizedIconRow = OverflowSquircleDefault;
export const OverflowText = OverflowSquircle.OverflowText;
export const OverflowTextSmall = OverflowSquircle.OverflowTextSmall;
export const OverflowCircle = OverflowSquircle.OverflowCircle;
export const TextInput = VoidTextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = LocalImageThumbnailDefault;
export const Tooltip = TooltipDefault;
export const TooltipArrowDirections = Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = STATUS_PADDING.STATUS_PADDING;
export const StatusSizes = STATUS_PADDING.StatusSizes;
export const getAnimatedTypingTranslateX = getAnimatedTypingTranslateX.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = getAnimatedTypingTranslateX.getMobileStatusContainerRect;
export const getStatusTypingDimensions = getAnimatedTypingTranslateX.getStatusTypingDimensions;
export const getStatusContainerStyle = STATUS_PADDINGDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconSizesDefault;
export const IconSizes = IconSizes.IconSizes;
export const getIconSize = IconSizes.getIconSize;
export const getIconStyle = IconSizes.getIconStyle;
export const CutoutableAvatarImage = StaticNativeCutoutAvatarImageDefault;
export const AvatarSizes = StaticNativeCutoutAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = StaticNativeCutoutAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = StaticNativeCutoutAvatarImage.styles;
export const CutoutDirection = StaticNativeCutoutAvatarImage.CutoutDirection;
export const CutoutType = StaticNativeCutoutAvatarImage.CutoutType;
export const Avatar = getStatusSizeDefault;
export const getStatusSize = getStatusSize.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = PX_16.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = PX_16.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = PX_16.BADGE_PADDING;
export const BADGE_MASK_SIZE = PX_16.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = PX_16.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = STANDARD_EASING.STANDARD_EASING;
export const DECELERATED_EASING = STANDARD_EASING.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = generateBoxShadowStyle.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = _modDef8404;
export const RNTextInput = RNTextInput.RNTextInput;
export const Badge = BadgeDefault;
export const MaskedBadge = Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = FontsDefault;
export const ClearButtonVisibility = Fonts.ClearButtonVisibility;
export const BadgeColors = BadgeColors.BadgeColors;
export const TextBadge = BadgeColors.TextBadge;
export const RefreshEmptyState = EmptyStateDefault2;
export const ThemedEmptyState = EmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = PressableBase.PressableOpacity;
export const PressableHighlight = PressableBase.PressableHighlight;
export const SquareIconButton = SquareIconButton.SquareIconButton;
export const CircularIconButton = SquareIconButton.CircularIconButton;
export const TouchableHitBox = renderDefault;
export const RoleLabel = RoleLabel.RoleLabel;
