// Module ID: 1297
// Function ID: 1298
// Name: Button
// Dependencies: [1298, 1299, 2, 1300, 13642, 12871, 13643, 13646, 13647, 13648, 13649, 13650, 13651, 4816, 13652, 13654, 9639, 13655, 13656, 13658, 13659, 13660, 13661, 13662, 4882, 9349, 13671, 13673, 13653, 13675, 13677, 13678, 13679, 13680, 13681, 13682, 13683, 8323, 13684, 13736, 13737, 13738, 13739, 13740, 8322, 8295, 5020, 13037, 8988, 10266]

// Module 1297 (Button)
import set from "set" /* 2 */;
import STATUS_PADDING from "STATUS_PADDING" /* 1298 */;
import PX_16 from "PX_16" /* 1299 */;
import getTextStyles from "getTextStyles" /* 1300 */;
import getTextStylesDefault from "getTextStyles" /* 1300 */;
import View from "View" /* 4816 */;
import ViewDefault from "View" /* 4816 */;
import IconSizes from "IconSizes" /* 4882 */;
import IconSizesDefault from "IconSizes" /* 4882 */;
import PressableBase from "PressableBase" /* 5020 */;
import Form from "Form" /* 8295 */;
import CardSectionDefault from "CardSection" /* 8322 */;
import _modDef8323 from "module_8323" /* 8323 */;
import renderDefault from "render" /* 8988 */;
import StaticNativeCutoutAvatarImage from "StaticNativeCutoutAvatarImage" /* 9349 */;
import StaticNativeCutoutAvatarImageDefault from "StaticNativeCutoutAvatarImage" /* 9349 */;
import VoidTextInputDefault from "VoidTextInput" /* 9639 */;
import RoleLabel from "RoleLabel" /* 10266 */;
import BetaTag from "BetaTag" /* 12871 */;
import BetaTagDefault from "BetaTag" /* 12871 */;
import SquareIconButton from "SquareIconButton" /* 13037 */;
import ShinyButtonDefault from "ShinyButton" /* 13642 */;
import CheckboxDefault from "Checkbox" /* 13643 */;
import CloseDefault from "Close" /* 13646 */;
import AnimatedEllipsisDotDefault from "AnimatedEllipsisDot" /* 13647 */;
import GradientBorderDefault from "GradientBorder" /* 13648 */;
import HelpMessage from "HelpMessage" /* 13649 */;
import HelpMessageDefault from "HelpMessage" /* 13649 */;
import IconPillDefault from "IconPill" /* 13650 */;
import NewTagDefault from "NewTag" /* 13651 */;
import RadioEmpty from "RadioEmpty" /* 13652 */;
import RadioEmptyDefault from "RadioEmpty" /* 13652 */;
import CollapsibleDefault from "Collapsible" /* 13653 */;
import OverflowSquircle from "OverflowSquircle" /* 13654 */;
import OverflowSquircleDefault from "OverflowSquircle" /* 13654 */;
import ThemedIconDefault from "ThemedIcon" /* 13655 */;
import LocalImageThumbnailDefault from "LocalImageThumbnail" /* 13656 */;
import Tooltip from "Tooltip" /* 13658 */;
import TooltipDefault from "Tooltip" /* 13658 */;
import WarningCircleDefault from "WarningCircle" /* 13659 */;
import getAnimatedTypingTranslateX from "getAnimatedTypingTranslateX" /* 13660 */;
import STATUS_PADDINGDefault from "STATUS_PADDING" /* 13661 */;
import Status from "Status" /* 13662 */;
import StatusDefault from "Status" /* 13662 */;
import getStatusSize from "getStatusSize" /* 13671 */;
import getStatusSizeDefault from "getStatusSize" /* 13671 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 13673 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 13675 */;
import STANDARD_EASING from "STANDARD_EASING" /* 13677 */;
import SpacerDefault from "Spacer" /* 13678 */;
import LiveTagDefault from "LiveTag" /* 13679 */;
import RoleDot from "RoleDot" /* 13680 */;
import generateBoxShadowStyle from "generateBoxShadowStyle" /* 13681 */;
import NitroWheelDefault from "NitroWheel" /* 13682 */;
import EmptyStateDefault from "EmptyState" /* 13683 */;
import RNTextInput from "RNTextInput" /* 13684 */;
import Badge from "Badge" /* 13736 */;
import BadgeDefault from "Badge" /* 13736 */;
import CarouselPaginationDefault from "CarouselPagination" /* 13737 */;
import Fonts from "Fonts" /* 13738 */;
import FontsDefault from "Fonts" /* 13738 */;
import BadgeColors from "BadgeColors" /* 13739 */;
import EmptyState from "EmptyState" /* 13740 */;
import EmptyStateDefault2 from "EmptyState" /* 13740 */;

const result = set.fileFinishedImporting("design/void/native.tsx");

export const Button = getTextStylesDefault;
export const BUTTON_CORNER_RADIUS = getTextStyles.BUTTON_CORNER_RADIUS;
export const useButtonStyles = getTextStyles.useButtonStyles;
export const ButtonLooks = getTextStyles.ButtonLooks;
export const ButtonColors = getTextStyles.ButtonColors;
export const ButtonSizes = getTextStyles.ButtonSizes;
export const getButtonStyles = getTextStyles.getButtonStyles;
export const ButtonText = getTextStyles.ButtonText;
export const getRedesignVariant = getTextStyles.getRedesignVariant;
export const getRedesignSize = getTextStyles.getRedesignSize;
export const ShinyButton = ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = CheckboxDefault;
export const CloseIcon = CloseDefault;
export const Ellipsis = AnimatedEllipsisDotDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = ViewDefault;
export const TransitionGroupOverlayView = View.TransitionGroupOverlayView;
export const NonExpandingOverlayView = View.NonExpandingOverlayView;
export const RadioGroup = RadioEmptyDefault;
export const RadioIndicator = RadioEmpty.RadioIndicator;
export const RadioItem = RadioEmpty.RadioItem;
export const SummarizedIconRow = OverflowSquircleDefault;
export const OverflowText = OverflowSquircle.OverflowText;
export const OverflowTextSmall = OverflowSquircle.OverflowTextSmall;
export const OverflowCircle = OverflowSquircle.OverflowCircle;
export const TextInput = VoidTextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = LocalImageThumbnailDefault;
export const Tooltip = TooltipDefault;
export const TooltipArrowDirections = Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = STATUS_PADDING.STATUS_PADDING;
export const StatusSizes = STATUS_PADDING.StatusSizes;
export const getAnimatedTypingTranslateX = getAnimatedTypingTranslateX.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = getAnimatedTypingTranslateX.getMobileStatusContainerRect;
export const getStatusTypingDimensions = getAnimatedTypingTranslateX.getStatusTypingDimensions;
export const getStatusContainerStyle = STATUS_PADDINGDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconSizesDefault;
export const IconSizes = IconSizes.IconSizes;
export const getIconSize = IconSizes.getIconSize;
export const getIconStyle = IconSizes.getIconStyle;
export const CutoutableAvatarImage = StaticNativeCutoutAvatarImageDefault;
export const AvatarSizes = StaticNativeCutoutAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = StaticNativeCutoutAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = StaticNativeCutoutAvatarImage.styles;
export const CutoutDirection = StaticNativeCutoutAvatarImage.CutoutDirection;
export const CutoutType = StaticNativeCutoutAvatarImage.CutoutType;
export const Avatar = getStatusSizeDefault;
export const getStatusSize = getStatusSize.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = PX_16.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = PX_16.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = PX_16.BADGE_PADDING;
export const BADGE_MASK_SIZE = PX_16.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = PX_16.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = STANDARD_EASING.STANDARD_EASING;
export const DECELERATED_EASING = STANDARD_EASING.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = generateBoxShadowStyle.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = _modDef8323;
export const RNTextInput = RNTextInput.RNTextInput;
export const Badge = BadgeDefault;
export const MaskedBadge = Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = FontsDefault;
export const ClearButtonVisibility = Fonts.ClearButtonVisibility;
export const BadgeColors = BadgeColors.BadgeColors;
export const TextBadge = BadgeColors.TextBadge;
export const RefreshEmptyState = EmptyStateDefault2;
export const ThemedEmptyState = EmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = PressableBase.PressableOpacity;
export const PressableHighlight = PressableBase.PressableHighlight;
export const SquareIconButton = SquareIconButton.SquareIconButton;
export const CircularIconButton = SquareIconButton.CircularIconButton;
export const TouchableHitBox = renderDefault;
export const RoleLabel = RoleLabel.RoleLabel;
