// Module ID: 1178
// Function ID: 1179
// Name: Button
// Dependencies: [1179, 1180, 2, 1181, 14085, 13296, 14086, 14089, 14090, 14091, 14092, 14093, 14094, 4911, 14095, 14097, 9757, 14098, 14099, 14101, 14102, 14103, 14104, 14105, 4977, 13028, 14114, 14116, 14096, 14118, 14120, 14121, 14122, 14123, 14124, 14125, 14126, 8612, 14127, 14179, 14180, 14181, 14182, 14183, 8611, 8593, 5123, 13466, 9050, 10270]

// Module 1178 (Button)
import set from "set" /* 2 */;
import STATUS_PADDING from "STATUS_PADDING" /* 1179 */;
import PX_16 from "PX_16" /* 1180 */;
import getTextStyles from "getTextStyles" /* 1181 */;
import getTextStylesDefault from "getTextStyles" /* 1181 */;
import View from "View" /* 4911 */;
import ViewDefault from "View" /* 4911 */;
import IconSizes from "IconSizes" /* 4977 */;
import IconSizesDefault from "IconSizes" /* 4977 */;
import PressableBase from "PressableBase" /* 5123 */;
import Form from "Form" /* 8593 */;
import CardSectionDefault from "CardSection" /* 8611 */;
import _modDef8612 from "module_8612" /* 8612 */;
import renderDefault from "render" /* 9050 */;
import VoidTextInputDefault from "VoidTextInput" /* 9757 */;
import RoleLabel from "RoleLabel" /* 10270 */;
import StaticNativeCutoutAvatarImage from "StaticNativeCutoutAvatarImage" /* 13028 */;
import StaticNativeCutoutAvatarImageDefault from "StaticNativeCutoutAvatarImage" /* 13028 */;
import BetaTag from "BetaTag" /* 13296 */;
import BetaTagDefault from "BetaTag" /* 13296 */;
import SquareIconButton from "SquareIconButton" /* 13466 */;
import ShinyButtonDefault from "ShinyButton" /* 14085 */;
import CheckboxDefault from "Checkbox" /* 14086 */;
import CloseDefault from "Close" /* 14089 */;
import AnimatedEllipsisDotDefault from "AnimatedEllipsisDot" /* 14090 */;
import GradientBorderDefault from "GradientBorder" /* 14091 */;
import HelpMessage from "HelpMessage" /* 14092 */;
import HelpMessageDefault from "HelpMessage" /* 14092 */;
import IconPillDefault from "IconPill" /* 14093 */;
import NewTagDefault from "NewTag" /* 14094 */;
import RadioEmpty from "RadioEmpty" /* 14095 */;
import RadioEmptyDefault from "RadioEmpty" /* 14095 */;
import CollapsibleDefault from "Collapsible" /* 14096 */;
import OverflowSquircle from "OverflowSquircle" /* 14097 */;
import OverflowSquircleDefault from "OverflowSquircle" /* 14097 */;
import ThemedIconDefault from "ThemedIcon" /* 14098 */;
import LocalImageThumbnailDefault from "LocalImageThumbnail" /* 14099 */;
import Tooltip from "Tooltip" /* 14101 */;
import TooltipDefault from "Tooltip" /* 14101 */;
import WarningCircleDefault from "WarningCircle" /* 14102 */;
import getAnimatedTypingTranslateX from "getAnimatedTypingTranslateX" /* 14103 */;
import STATUS_PADDINGDefault from "STATUS_PADDING" /* 14104 */;
import Status from "Status" /* 14105 */;
import StatusDefault from "Status" /* 14105 */;
import getStatusSize from "getStatusSize" /* 14114 */;
import getStatusSizeDefault from "getStatusSize" /* 14114 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 14116 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 14118 */;
import STANDARD_EASING from "STANDARD_EASING" /* 14120 */;
import SpacerDefault from "Spacer" /* 14121 */;
import LiveTagDefault from "LiveTag" /* 14122 */;
import RoleDot from "RoleDot" /* 14123 */;
import generateBoxShadowStyle from "generateBoxShadowStyle" /* 14124 */;
import NitroWheelDefault from "NitroWheel" /* 14125 */;
import EmptyStateDefault from "EmptyState" /* 14126 */;
import RNTextInput from "RNTextInput" /* 14127 */;
import Badge from "Badge" /* 14179 */;
import BadgeDefault from "Badge" /* 14179 */;
import CarouselPaginationDefault from "CarouselPagination" /* 14180 */;
import Fonts from "Fonts" /* 14181 */;
import FontsDefault from "Fonts" /* 14181 */;
import BadgeColors from "BadgeColors" /* 14182 */;
import EmptyState from "EmptyState" /* 14183 */;
import EmptyStateDefault2 from "EmptyState" /* 14183 */;

const result = set.fileFinishedImporting("design/void/native.tsx");

export const Button = getTextStylesDefault;
export const BUTTON_CORNER_RADIUS = getTextStyles.BUTTON_CORNER_RADIUS;
export const useButtonStyles = getTextStyles.useButtonStyles;
export const ButtonLooks = getTextStyles.ButtonLooks;
export const ButtonColors = getTextStyles.ButtonColors;
export const ButtonSizes = getTextStyles.ButtonSizes;
export const getButtonStyles = getTextStyles.getButtonStyles;
export const ButtonText = getTextStyles.ButtonText;
export const getRedesignVariant = getTextStyles.getRedesignVariant;
export const getRedesignSize = getTextStyles.getRedesignSize;
export const ShinyButton = ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = CheckboxDefault;
export const CloseIcon = CloseDefault;
export const Ellipsis = AnimatedEllipsisDotDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = ViewDefault;
export const TransitionGroupOverlayView = View.TransitionGroupOverlayView;
export const NonExpandingOverlayView = View.NonExpandingOverlayView;
export const RadioGroup = RadioEmptyDefault;
export const RadioIndicator = RadioEmpty.RadioIndicator;
export const RadioItem = RadioEmpty.RadioItem;
export const SummarizedIconRow = OverflowSquircleDefault;
export const OverflowText = OverflowSquircle.OverflowText;
export const OverflowTextSmall = OverflowSquircle.OverflowTextSmall;
export const OverflowCircle = OverflowSquircle.OverflowCircle;
export const TextInput = VoidTextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = LocalImageThumbnailDefault;
export const Tooltip = TooltipDefault;
export const TooltipArrowDirections = Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = STATUS_PADDING.STATUS_PADDING;
export const StatusSizes = STATUS_PADDING.StatusSizes;
export const getAnimatedTypingTranslateX = getAnimatedTypingTranslateX.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = getAnimatedTypingTranslateX.getMobileStatusContainerRect;
export const getStatusTypingDimensions = getAnimatedTypingTranslateX.getStatusTypingDimensions;
export const getStatusContainerStyle = STATUS_PADDINGDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconSizesDefault;
export const IconSizes = IconSizes.IconSizes;
export const getIconSize = IconSizes.getIconSize;
export const getIconStyle = IconSizes.getIconStyle;
export const CutoutableAvatarImage = StaticNativeCutoutAvatarImageDefault;
export const AvatarSizes = StaticNativeCutoutAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = StaticNativeCutoutAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = StaticNativeCutoutAvatarImage.styles;
export const CutoutDirection = StaticNativeCutoutAvatarImage.CutoutDirection;
export const CutoutType = StaticNativeCutoutAvatarImage.CutoutType;
export const Avatar = getStatusSizeDefault;
export const getStatusSize = getStatusSize.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = PX_16.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = PX_16.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = PX_16.BADGE_PADDING;
export const BADGE_MASK_SIZE = PX_16.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = PX_16.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = STANDARD_EASING.STANDARD_EASING;
export const DECELERATED_EASING = STANDARD_EASING.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = generateBoxShadowStyle.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = generateBoxShadowStyle.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = _modDef8612;
export const RNTextInput = RNTextInput.RNTextInput;
export const Badge = BadgeDefault;
export const MaskedBadge = Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = FontsDefault;
export const ClearButtonVisibility = Fonts.ClearButtonVisibility;
export const BadgeColors = BadgeColors.BadgeColors;
export const TextBadge = BadgeColors.TextBadge;
export const RefreshEmptyState = EmptyStateDefault2;
export const ThemedEmptyState = EmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = PressableBase.PressableOpacity;
export const PressableHighlight = PressableBase.PressableHighlight;
export const SquareIconButton = SquareIconButton.SquareIconButton;
export const CircularIconButton = SquareIconButton.CircularIconButton;
export const TouchableHitBox = renderDefault;
export const RoleLabel = RoleLabel.RoleLabel;
