// Module ID: 4354
// Function ID: 4355
// Dependencies: []

// Module 4354
arg5.ACTIONS = { REGISTER_HOST: 0, [0]: "REGISTER_HOST", DEREGISTER_HOST: 1, [1]: "DEREGISTER_HOST", ADD_UPDATE_PORTAL: 2, [2]: "ADD_UPDATE_PORTAL", REMOVE_PORTAL: 3, [3]: "REMOVE_PORTAL" };
arg5.INITIAL_STATE = {};
