// Module ID: 14756
// Function ID: 14757
// Name: SettingsRendererConfig
// Dependencies: [7974, 14757, 14874, 14899, 14907, 14908, 14909, 14910, 14923, 14924, 14926, 14927, 14928, 14930, 14931, 14945, 14949, 14950, 14964, 14966, 14970, 14971, 14980, 14988, 14990, 14992, 14994, 15002, 15005, 15007, 15008, 15021, 15026, 15027, 15028, 15029, 15030, 15031, 15033, 15037, 15038, 15040, 15043, 15044, 15045, 15046, 15047, 15051, 15054, 15055, 15061, 15125, 15130, 15134, 15136, 15139, 15142, 15150, 15169, 15173, 15174, 15175, 15176, 15177, 15178, 15182, 15184, 15187, 15189, 15190, 15191, 15362, 15412, 15432, 15451, 15454, 15456, 15457, 15458, 15459, 15460, 15461, 15462, 15463, 15464, 15465, 15466, 15467, 15468, 15469, 15475, 15512, 15513, 15516, 15518, 15520, 15521, 15525, 15526, 15531, 15532, 15533, 15534, 15536, 15541, 15542, 15543, 15566, 15618, 15619, 15620, 15621, 15622, 15623, 15624, 15625, 15626, 15627, 15628, 15629, 15630, 15631, 15632, 15668, 15672, 15673, 15674, 15676, 15677, 15678, 15679, 15680, 15681, 15682, 15683, 15684, 15685, 15686, 15687, 10628, 15689, 15690, 15692, 15693, 15700, 15702, 15703, 15704, 15705, 15707, 15708, 15709, 15710, 15711, 15712, 15714, 15716, 15717, 15719, 15721, 15723, 15725, 15728, 15731, 15733, 15734, 15736, 15738, 15744, 15746, 15747, 15748, 15749, 15751, 15753, 15754, 15757, 15758, 15772, 15773, 15775, 15778, 15774, 15786, 15794, 15798, 16030, 16033, 16034, 16035, 16042, 16043, 16044, 16046, 16048, 16053, 16055, 16057, 16059, 16061, 16063, 16065, 16066, 16067, 16069, 16071, 16075, 16077, 16079, 16081, 16084, 16086, 16088, 16090, 16092, 16094, 16097, 16099, 16101, 16103, 16105, 16111, 16162, 16167, 16171, 16173, 16175, 16178, 16179, 16180, 16182, 16184, 16185, 16187, 16196, 16197, 16189, 16198, 16200, 16203, 16204, 16205, 16206, 16207, 16208, 16210, 16211, 16212, 16213, 16215, 16216, 16217, 16218, 16219, 16220, 16221, 16222, 16223, 16224, 16225, 16226, 16227, 16228, 16229, 16231, 16232, 16233, 16235, 16237, 16238, 2]

// Module 14756 (SettingsRendererConfig)
import SettingsConstants from "SettingsConstants" /* 7974 */;
import ChatGestureSettingsDefault from "ChatGestureSettings" /* 10628 */;
import ProfileCustomizationSettingDefault from "ProfileCustomizationSetting" /* 14757 */;
import AccountSettingDefault from "AccountSetting" /* 14874 */;
import AccountUsernameSettingDefault from "AccountUsernameSetting" /* 14899 */;
import AccountDisplayNameSettingDefault from "AccountDisplayNameSetting" /* 14907 */;
import AccountEmailSettingDefault from "AccountEmailSetting" /* 14908 */;
import AccountPhoneSettingDefault from "AccountPhoneSetting" /* 14909 */;
import AccountAgeGroupSettingDefault from "AccountAgeGroupSetting" /* 14910 */;
import AccountAgeGroupAdultSettingDefault from "AccountAgeGroupAdultSetting" /* 14923 */;
import AccountAgeGroupAssignedAdultSettingDefault from "AccountAgeGroupAssignedAdultSetting" /* 14924 */;
import AccountAgeGroupNonAdultSettingDefault from "AccountAgeGroupNonAdultSetting" /* 14926 */;
import AgeGroupConfirmSettingDefault from "AgeGroupConfirmSetting" /* 14927 */;
import AgeGroupResetSettingDefault from "AgeGroupResetSetting" /* 14928 */;
import AgeGroupConfirmAccountStatusSettingDefault from "AgeGroupConfirmAccountStatusSetting" /* 14930 */;
import AccountStandingSettingDefault from "AccountStandingSetting" /* 14931 */;
import AccountChangePasswordSettingDefault from "AccountChangePasswordSetting" /* 14945 */;
import AccountConfirmPasswordSettingDefault from "AccountConfirmPasswordSetting" /* 14949 */;
import AccountEnable2faSettingDefault from "AccountEnable2faSetting" /* 14950 */;
import AccountRemove2faSettingDefault from "AccountRemove2faSetting" /* 14964 */;
import AccountViewBackupCodesSettingDefault from "AccountViewBackupCodesSetting" /* 14966 */;
import AccountSmsBackupSettingDefault from "AccountSmsBackupSetting" /* 14970 */;
import AccountWebAuthnViewSettingDefault from "AccountWebAuthnViewSetting" /* 14971 */;
import AccountWebAuthnRegisterSettingDefault from "AccountWebAuthnRegisterSetting" /* 14980 */;
import AccountWebAuthnNameSettingDefault from "AccountWebAuthnNameSetting" /* 14988 */;
import AccountWebAuthnEditSettingDefault from "AccountWebAuthnEditSetting" /* 14990 */;
import AccountWebAuthnSuccessSettingDefault from "AccountWebAuthnSuccessSetting" /* 14992 */;
import AccountBlockedUsersSettingDefault from "AccountBlockedUsersSetting" /* 14994 */;
import AccountIgnoredUsersSettingDefault from "AccountIgnoredUsersSetting" /* 15002 */;
import AccountDeleteSettingDefault from "AccountDeleteSetting" /* 15005 */;
import AccountDisableSettingDefault from "AccountDisableSetting" /* 15007 */;
import SensitiveContentFilterSettingDefault from "SensitiveContentFilterSetting" /* 15008 */;
import ExplicitMediaFiltersFriendsDMsSettingDefault from "ExplicitMediaFiltersFriendsDMsSetting" /* 15021 */;
import ExplicitMediaFiltersNonFriendsDMsSettingDefault from "ExplicitMediaFiltersNonFriendsDMsSetting" /* 15026 */;
import ExplicitMediaFiltersGuildsSettingDefault from "ExplicitMediaFiltersGuildsSetting" /* 15027 */;
import GoreMediaFiltersFriendsDMsSettingDefault from "GoreMediaFiltersFriendsDMsSetting" /* 15028 */;
import GoreMediaFiltersNonFriendsDMsSettingDefault from "GoreMediaFiltersNonFriendsDMsSetting" /* 15029 */;
import GoreMediaFiltersGuildsSettingDefault from "GoreMediaFiltersGuildsSetting" /* 15030 */;
import DirectMessageSafetyAlertsSettingDefault from "DirectMessageSafetyAlertsSetting" /* 15031 */;
import DirectMessageSpamFilterSettingDefault from "DirectMessageSpamFilterSetting" /* 15033 */;
import AndroidViewNsfwDmCommandsSettingDefault from "AndroidViewNsfwDmCommandsSetting" /* 15037 */;
import StaffOnlyFindYourFriendsDeletionSettingDefault from "StaffOnlyFindYourFriendsDeletionSetting" /* 15038 */;
import SyncContactsSettingDefault from "SyncContactsSetting" /* 15040 */;
import SyncContactsNameSettingDefault from "SyncContactsNameSetting" /* 15043 */;
import DiscoveryByPhoneSettingDefault from "DiscoveryByPhoneSetting" /* 15044 */;
import DiscoveryByEmailSettingDefault from "DiscoveryByEmailSetting" /* 15045 */;
import IOSConversationSuggestionsSettingDefault from "IOSConversationSuggestionsSetting" /* 15046 */;
import ProfilePrivacySettingDefault from "ProfilePrivacySetting" /* 15047 */;
import UseDataToImproveDiscordSettingDefault from "UseDataToImproveDiscordSetting" /* 15051 */;
import UseDataToCustomizeDiscordSettingDefault from "UseDataToCustomizeDiscordSetting" /* 15054 */;
import RequestYourDataSettingDefault from "RequestYourDataSetting" /* 15055 */;
import FamilyCenterSettingDefault from "FamilyCenterSetting" /* 15061 */;
import FamilyCenterSettingParentalControlsSettingDefault from "FamilyCenterSettingParentalControlsSetting" /* 15125 */;
import FamilyCenterScheduleDowntimeSettingDefault from "FamilyCenterScheduleDowntimeSetting" /* 15130 */;
import AuthorizedAppsSettingDefault from "AuthorizedAppsSetting" /* 15134 */;
import AuthorizedAppSettingDefault from "AuthorizedAppSetting" /* 15136 */;
import AuthorizedAppPermissionsSettingDefault from "AuthorizedAppPermissionsSetting" /* 15139 */;
import DevicesSettingDefault from "DevicesSetting" /* 15142 */;
import ConnectionsSettingDefault from "ConnectionsSetting" /* 15150 */;
import ClipsSettingDefault from "ClipsSetting" /* 15169 */;
import ClipsOptOutOfVoiceRecordingSettingDefault from "ClipsOptOutOfVoiceRecordingSetting" /* 15173 */;
import FriendRequestsEveryoneSettingDefault from "FriendRequestsEveryoneSetting" /* 15174 */;
import FriendRequestsMutualFriendsSettingDefault from "FriendRequestsMutualFriendsSetting" /* 15175 */;
import FriendRequestsMutualGuildsSettingDefault from "FriendRequestsMutualGuildsSetting" /* 15176 */;
import ScanQrCodeSettingDefault from "ScanQrCodeSetting" /* 15177 */;
import PremiumSettingDefault from "PremiumSetting" /* 15178 */;
import PremiumManagePlanSettingDefault from "PremiumManagePlanSetting" /* 15182 */;
import PremiumManageSubscriptionsSettingDefault from "PremiumManageSubscriptionsSetting" /* 15184 */;
import PremiumPlanSelectSettingDefault from "PremiumPlanSelectSetting" /* 15187 */;
import PremiumGuildBoostingSettingDefault from "PremiumGuildBoostingSetting" /* 15189 */;
import PremiumGiftingSettingDefault from "PremiumGiftingSetting" /* 15190 */;
import defs_QuestHomeSettingDefault from "defs/QuestHomeSetting" /* 15191 */;
import QuestPreviewToolSettingDefault from "QuestPreviewToolSetting" /* 15362 */;
import GuildRoleSubscriptionsSettingDefault from "GuildRoleSubscriptionsSetting" /* 15412 */;
import GuildRoleSubscriptionsCancelSettingDefault from "GuildRoleSubscriptionsCancelSetting" /* 15432 */;
import PremiumRestoreSubscriptionSettingDefault from "PremiumRestoreSubscriptionSetting" /* 15451 */;
import VoiceSettingDefault from "VoiceSetting" /* 15454 */;
import InputModeSettingDefault from "InputModeSetting" /* 15456 */;
import AutoVoiceSensitivitySettingDefault from "AutoVoiceSensitivitySetting" /* 15457 */;
import VoiceSensitivitySettingDefault from "VoiceSensitivitySetting" /* 15458 */;
import OutputVolumeSettingDefault from "OutputVolumeSetting" /* 15459 */;
import StreamOutputVolumeSettingDefault from "StreamOutputVolumeSetting" /* 15460 */;
import SoundboardVolumeSettingDefault from "SoundboardVolumeSetting" /* 15461 */;
import AndroidMobileOverlaySettingDefault from "AndroidMobileOverlaySetting" /* 15462 */;
import NoiseSuppressionKrispSettingDefault from "NoiseSuppressionKrispSetting" /* 15463 */;
import NoiseSuppressionSettingDefault from "NoiseSuppressionSetting" /* 15464 */;
import EchoCancellationSettingDefault from "EchoCancellationSetting" /* 15465 */;
import SidechainCompressionSettingDefault from "SidechainCompressionSetting" /* 15466 */;
import AutomaticGainControlSettingDefault from "AutomaticGainControlSetting" /* 15467 */;
import AdvancedVoiceActivitySettingDefault from "AdvancedVoiceActivitySetting" /* 15468 */;
import AppearanceSettingDefault from "AppearanceSetting" /* 15469 */;
import AppearanceThemePickerSettingDefault from "AppearanceThemePickerSetting" /* 15475 */;
import SameAsDeviceThemeSettingDefault from "SameAsDeviceThemeSetting" /* 15512 */;
import LightModeThemeSettingDefault from "LightModeThemeSetting" /* 15513 */;
import DarkModeThemeSettingDefault from "DarkModeThemeSetting" /* 15516 */;
import SyncThemeSettingDefault from "SyncThemeSetting" /* 15518 */;
import DefaultGuildThemePreferenceSettingDefault from "DefaultGuildThemePreferenceSetting" /* 15520 */;
import AndroidFontScaleSettingDefault from "AndroidFontScaleSetting" /* 15521 */;
import AndroidClassicChatFontScaleSettingDefault from "AndroidClassicChatFontScaleSetting" /* 15525 */;
import DmsMessagePreviewsSettingDefault from "DmsMessagePreviewsSetting" /* 15526 */;
import DmsHappeningNowCardsSettingDefault from "DmsHappeningNowCardsSetting" /* 15531 */;
import ExactSearchResultCountsSettingDefault from "ExactSearchResultCountsSetting" /* 15532 */;
import GameMentionsAutocompleteSettingDefault from "GameMentionsAutocompleteSetting" /* 15533 */;
import FavoritesGuildToggleSettingDefault from "FavoritesGuildToggleSetting" /* 15534 */;
import AccessibilitySettingDefault from "AccessibilitySetting" /* 15536 */;
import RoleColorsSettingDefault from "RoleColorsSetting" /* 15541 */;
import OfficialMessageStyleSettingDefault from "OfficialMessageStyleSetting" /* 15542 */;
import DisplayNameStylesRouteSettingDefault from "DisplayNameStylesRouteSetting" /* 15543 */;
import TypingIndicatorSettingDefault from "TypingIndicatorSetting" /* 15566 */;
import DisplayNameStylesAccessibilitySettingDefault from "DisplayNameStylesAccessibilitySetting" /* 15618 */;
import YouBarNameplateAccessibilitySettingDefault from "YouBarNameplateAccessibilitySetting" /* 15619 */;
import YouBarAvatarDecoAccessibilitySettingDefault from "YouBarAvatarDecoAccessibilitySetting" /* 15620 */;
import ShowLinkDecorationsSettingDefault from "ShowLinkDecorationsSetting" /* 15621 */;
import EnableSwitchIconsSettingDefault from "EnableSwitchIconsSetting" /* 15622 */;
import ContrastModeSettingDefault from "ContrastModeSetting" /* 15623 */;
import ReduceSaturationSettingDefault from "ReduceSaturationSetting" /* 15624 */;
import ToastDurationSettingDefault from "ToastDurationSetting" /* 15625 */;
import SyncProfileColorsSettingDefault from "SyncProfileColorsSetting" /* 15626 */;
import EnableReducedMotionSettingDefault from "EnableReducedMotionSetting" /* 15627 */;
import SyncReducedMotionWithDeviceSettingDefault from "SyncReducedMotionWithDeviceSetting" /* 15628 */;
import AutoplayGifSettingDefault from "AutoplayGifSetting" /* 15629 */;
import AnimateEmojiSettingDefault from "AnimateEmojiSetting" /* 15630 */;
import AnimateStickersSettingDefault from "AnimateStickersSetting" /* 15631 */;
import LanguageSettingDefault from "LanguageSetting" /* 15632 */;
import ChatSettingDefault from "ChatSetting" /* 15668 */;
import DisplayMediaLinksSettingDefault from "DisplayMediaLinksSetting" /* 15672 */;
import DisplayMediaUploadsSettingDefault from "DisplayMediaUploadsSetting" /* 15673 */;
import ImageDescriptionsSettingDefault from "ImageDescriptionsSetting" /* 15674 */;
import VideoUploadQualitySettingDefault from "VideoUploadQualitySetting" /* 15676 */;
import DataSavingModeSettingDefault from "DataSavingModeSetting" /* 15677 */;
import SaveCameraUploadsToDeviceSettingDefault from "SaveCameraUploadsToDeviceSetting" /* 15678 */;
import EmbedAndLinkPreviewsSettingDefault from "EmbedAndLinkPreviewsSetting" /* 15679 */;
import EmojiReactionsOnMessagesSettingDefault from "EmojiReactionsOnMessagesSetting" /* 15680 */;
import ChatEmojiEmoticonsSettingDefault from "ChatEmojiEmoticonsSetting" /* 15681 */;
import StickerAutocompleteSettingDefault from "StickerAutocompleteSetting" /* 15682 */;
import ShowSpoilersSettingDefault from "ShowSpoilersSetting" /* 15683 */;
import InlineEmojiSuggestionsSettingDefault from "InlineEmojiSuggestionsSetting" /* 15684 */;
import TextAndMediaSyncSettingDefault from "TextAndMediaSyncSetting" /* 15685 */;
import TimestampHourCycleSettingDefault from "TimestampHourCycleSetting" /* 15686 */;
import SwipeRightToLeftSettingDefault from "SwipeRightToLeftSetting" /* 15687 */;
import WebBrowserSettingDefault from "WebBrowserSetting" /* 15689 */;
import SelectWebBrowserSettingDefault from "SelectWebBrowserSetting" /* 15690 */;
import ClearWebBrowserDataSettingDefault from "ClearWebBrowserDataSetting" /* 15692 */;
import NotificationsSettingDefault from "NotificationsSetting" /* 15693 */;
import InAppNotificationsSetting from "InAppNotificationsSetting" /* 15700 */;
import SystemNotificationsSettingDefault from "SystemNotificationsSetting" /* 15702 */;
import ReactionNotificationsSettingsDefault from "ReactionNotificationsSettings" /* 15703 */;
import CustomStatusNotificationSettingsDefault from "CustomStatusNotificationSettings" /* 15704 */;
import IOSNativePhoneIntegrationSetting from "IOSNativePhoneIntegrationSetting" /* 15705 */;
import AndroidMessageNotificationsSetting from "AndroidMessageNotificationsSetting" /* 15707 */;
import AndroidNotificationLightsSetting from "AndroidNotificationLightsSetting" /* 15708 */;
import AndroidNotificationVibrationsSetting from "AndroidNotificationVibrationsSetting" /* 15709 */;
import AndroidNotificationSoundsSetting from "AndroidNotificationSoundsSetting" /* 15710 */;
import InAppMessageSoundsSetting from "InAppMessageSoundsSetting" /* 15711 */;
import FriendStreamNotificationsSettingDefault from "FriendStreamNotificationsSetting" /* 15712 */;
import FriendAnniversaryNotificationSettingDefault from "FriendAnniversaryNotificationSetting" /* 15714 */;
import VoiceActivityNotificationSettingDefault from "VoiceActivityNotificationSetting" /* 15716 */;
import FriendOnlineNotificationSettingDefault from "FriendOnlineNotificationSetting" /* 15717 */;
import FriendGamingActivityNotificationSettingDefault from "FriendGamingActivityNotificationSetting" /* 15719 */;
import ProfileUpdatesNotificationSettingDefault from "ProfileUpdatesNotificationSetting" /* 15721 */;
import ServerTrendingNotificationSettingDefault from "ServerTrendingNotificationSetting" /* 15723 */;
import UpcomingServerEventNotificationSettingDefault from "UpcomingServerEventNotificationSetting" /* 15725 */;
import SummaryReminderNotificationSettingDefault from "SummaryReminderNotificationSetting" /* 15728 */;
import ScreenDowntimeReminderSettingDefault from "ScreenDowntimeReminderSetting" /* 15731 */;
import ScreenDowntimeScheduleSettingDefault from "ScreenDowntimeScheduleSetting" /* 15733 */;
import CommunityActivityAlertsSettingDefault from "CommunityActivityAlertsSetting" /* 15734 */;
import HighlightNotificationsSettingDefault from "HighlightNotificationsSetting" /* 15736 */;
import AppIconsSettingDefault from "AppIconsSetting" /* 15738 */;
import AdvancedSettingDefault from "AdvancedSetting" /* 15744 */;
import DeveloperModeSettingDefault from "DeveloperModeSetting" /* 15746 */;
import LaunchpadSettingDefault from "LaunchpadSetting" /* 15747 */;
import ChannelListLayoutSettingDefault from "ChannelListLayoutSetting" /* 15748 */;
import IcymiTabSettingDefault from "IcymiTabSetting" /* 15749 */;
import SupportSettingDefault from "SupportSetting" /* 15751 */;
import UploadDebugLogsSettingDefault from "UploadDebugLogsSetting" /* 15753 */;
import UploadIntlDataSettingDefault from "UploadIntlDataSetting" /* 15754 */;
import AcknowledgementsSettingDefault from "AcknowledgementsSetting" /* 15757 */;
import ChangeLogSettingDefault from "ChangeLogSetting" /* 15758 */;
import LogoutSettingDefault from "LogoutSetting" /* 15772 */;
import AppVersionSettingDefault from "AppVersionSetting" /* 15773 */;
import CopyClientInfoSettingDefault from "CopyClientInfoSetting" /* 15774 */;
import DeviceInfoSettingDefault from "DeviceInfoSetting" /* 15775 */;
import ViewDebugLogsSettingDefault from "ViewDebugLogsSetting" /* 15778 */;
import CacheActionsSettingDefault from "CacheActionsSetting" /* 15786 */;
import ShowDevWidgetSettingDefault from "ShowDevWidgetSetting" /* 15794 */;
import ShowDevToolsSettingDefault from "ShowDevToolsSetting" /* 15798 */;
import BugReporterSettingDefault from "BugReporterSetting" /* 16030 */;
import InternalBuildActiveSettingDefault from "InternalBuildActiveSetting" /* 16033 */;
import InternalBuildUpdateSettingDefault from "InternalBuildUpdateSetting" /* 16034 */;
import ExperimentOverrideActiveSettingDefault from "ExperimentOverrideActiveSetting" /* 16035 */;
import BuildOverrideActiveSettingDefault from "BuildOverrideActiveSetting" /* 16042 */;
import CreateBugReportSettingDefault from "CreateBugReportSetting" /* 16043 */;
import DesignSystemsSettingDefault from "DesignSystemsSetting" /* 16044 */;
import DesignSystemsTextSettingDefault from "DesignSystemsTextSetting" /* 16046 */;
import DesignSystemsButtonSettingDefault from "DesignSystemsButtonSetting" /* 16048 */;
import DesignSystemsLegacyButtonSettingDefault from "DesignSystemsLegacyButtonSetting" /* 16053 */;
import DesignSystemsButtonGroupSettingDefault from "DesignSystemsButtonGroupSetting" /* 16055 */;
import DesignSystemsRowButtonSettingDefault from "DesignSystemsRowButtonSetting" /* 16057 */;
import DesignSystemsExperimentalButtonsSettingDefault from "DesignSystemsExperimentalButtonsSetting" /* 16059 */;
import DesignSystemsTableRowSettingDefault from "DesignSystemsTableRowSetting" /* 16061 */;
import DesignSystemsAlertModalSettingDefault from "DesignSystemsAlertModalSetting" /* 16063 */;
import DesignSystemsBackgroundBlurViewSettingDefault from "DesignSystemsBackgroundBlurViewSetting" /* 16065 */;
import DesignSystemsShadowsSettingDefault from "DesignSystemsShadowsSetting" /* 16066 */;
import DesignSystemSegmentedControlSettingDefault from "DesignSystemSegmentedControlSetting" /* 16067 */;
import DesignSystemsTabsSettingDefault from "DesignSystemsTabsSetting" /* 16069 */;
import DesignSystemsContextMenuSettingDefault from "DesignSystemsContextMenuSetting" /* 16071 */;
import DesignSystemsToastSettingDefault from "DesignSystemsToastSetting" /* 16075 */;
import DesignSystemsTextInputSettingDefault from "DesignSystemsTextInputSetting" /* 16077 */;
import DesignSystemsTooltipSettingDefault from "DesignSystemsTooltipSetting" /* 16079 */;
import DesignSystemsCoachmarkSettingDefault from "DesignSystemsCoachmarkSetting" /* 16081 */;
import DesignSystemStackSettingDefault from "DesignSystemStackSetting" /* 16084 */;
import DesignSystemBackdropSettingDefault from "DesignSystemBackdropSetting" /* 16086 */;
import DesignSystemsModalSettingDefault from "DesignSystemsModalSetting" /* 16088 */;
import DesignSystemPileSettingDefault from "DesignSystemPileSetting" /* 16090 */;
import DesignSystemTagGroupSettingDefault from "DesignSystemTagGroupSetting" /* 16092 */;
import DesignSystemSheetsSettingDefault from "DesignSystemSheetsSetting" /* 16094 */;
import DesignSystemFormPrimitivesSettingDefault from "DesignSystemFormPrimitivesSetting" /* 16097 */;
import DesignSystemHapticsSettingDefault from "DesignSystemHapticsSetting" /* 16099 */;
import DesignSystemAILoaderSettingDefault from "DesignSystemAILoaderSetting" /* 16101 */;
import DesignSystemAIShimmerSettingDefault from "DesignSystemAIShimmerSetting" /* 16103 */;
import PremiumProfileCustomizationTryItOutSettingDefault from "PremiumProfileCustomizationTryItOutSetting" /* 16105 */;
import CollectiblesShopSettingDefault from "CollectiblesShopSetting" /* 16111 */;
import CollectiblesShopViewAllCategoryItemsSettingDefault from "CollectiblesShopViewAllCategoryItemsSetting" /* 16162 */;
import EncryptionSettingDefault from "EncryptionSetting" /* 16167 */;
import SecureFramesPersistentCodesSettingDefault from "SecureFramesPersistentCodesSetting" /* 16171 */;
import SecureFramesVerifiedDevicesSettingDefault from "SecureFramesVerifiedDevicesSetting" /* 16173 */;
import UseDataForQuestsSetting from "UseDataForQuestsSetting" /* 16175 */;
import UseDataForQuests3PSetting from "UseDataForQuests3PSetting" /* 16178 */;
import PinotSettingsLazy from "PinotSettingsLazy" /* 16179 */;
import SponsoredContentPreferencesSettingDefault from "SponsoredContentPreferencesSetting" /* 16180 */;
import ManageSponsoredContentSettingDefault from "ManageSponsoredContentSetting" /* 16182 */;
import DisableStreamPreviewsSettingDefault from "DisableStreamPreviewsSetting" /* 16184 */;
import DataAndPrivacySettingDefault from "DataAndPrivacySetting" /* 16185 */;
import ContentAndSocialSettingDefault from "ContentAndSocialSetting" /* 16187 */;
import SafetyGuildSettingGuildSelectDefault from "SafetyGuildSettingGuildSelect" /* 16189 */;
import SafetyTermsOfServiceSettingDefault from "SafetyTermsOfServiceSetting" /* 16196 */;
import SafetyPrivacyPolicySettingDefault from "SafetyPrivacyPolicySetting" /* 16197 */;
import SafetyGuildSettingDirectMessagesDefault from "SafetyGuildSettingDirectMessages" /* 16198 */;
import SafetyGuildSettingMessageRequestsDefault from "SafetyGuildSettingMessageRequests" /* 16200 */;
import GuildSettingActivityStatusDefault from "GuildSettingActivityStatus" /* 16203 */;
import GuildSettingActivityJoiningDefault from "GuildSettingActivityJoining" /* 16204 */;
import ReactCompilerSettingDefault from "ReactCompilerSetting" /* 16205 */;
import ContentAndSocialDiscordRouteSettingDefault from "ContentAndSocialDiscordRouteSetting" /* 16206 */;
import ConnectedGamesRouteSettingDefault from "ConnectedGamesRouteSetting" /* 16207 */;
import AllowGameFriendDMsSettingDefault from "AllowGameFriendDMsSetting" /* 16208 */;
import InGameDMsSettingDefault from "InGameDMsSetting" /* 16210 */;
import DoubleTapEmojiSettingDefault from "DoubleTapEmojiSetting" /* 16211 */;
import DoubleTapToReactSettingDefault from "DoubleTapToReactSetting" /* 16212 */;
import ParentalControlsSensitiveContentFilterSettingDefault from "ParentalControlsSensitiveContentFilterSetting" /* 16213 */;
import ParentalControlsDirectMessagesDefault from "ParentalControlsDirectMessages" /* 16215 */;
import ParentalControlsMessageRequestsDefault from "ParentalControlsMessageRequests" /* 16216 */;
import ParentalControlsFriendRequestsEveryoneSettingDefault from "ParentalControlsFriendRequestsEveryoneSetting" /* 16217 */;
import ParentalControlsFriendRequestsMutualFriendsSettingDefault from "ParentalControlsFriendRequestsMutualFriendsSetting" /* 16218 */;
import ParentalControlsFriendRequestsMutualGuildsSettingDefault from "ParentalControlsFriendRequestsMutualGuildsSetting" /* 16219 */;
import ParentalControlsExplicitMediaFiltersFriendsDMsSettingDefault from "ParentalControlsExplicitMediaFiltersFriendsDMsSetting" /* 16220 */;
import ParentalControlsExplicitMediaFiltersNonFriendsDMsSettingDefault from "ParentalControlsExplicitMediaFiltersNonFriendsDMsSetting" /* 16221 */;
import ParentalControlsGoreMediaFiltersFriendsDMsSettingDefault from "ParentalControlsGoreMediaFiltersFriendsDMsSetting" /* 16222 */;
import ParentalControlsGoreMediaFiltersNonFriendsDMsSettingDefault from "ParentalControlsGoreMediaFiltersNonFriendsDMsSetting" /* 16223 */;
import ParentalControlsUseDataToImproveDiscordSettingDefault from "ParentalControlsUseDataToImproveDiscordSetting" /* 16224 */;
import ParentalControlsUseDataToCustomizeDiscordSettingDefault from "ParentalControlsUseDataToCustomizeDiscordSetting" /* 16225 */;
import ParentalControlsUseDataForQuestsSettingDefault from "ParentalControlsUseDataForQuestsSetting" /* 16226 */;
import ParentalControlsUseDataForQuests3PSettingDefault from "ParentalControlsUseDataForQuests3PSetting" /* 16227 */;
import ActivityPrivacyShareMyActivitySettingDefault from "ActivityPrivacyShareMyActivitySetting" /* 16228 */;
import ActivityPrivacyDefaultSharingSettingDefault from "ActivityPrivacyDefaultSharingSetting" /* 16229 */;
import FriendRequestsNotesSettingDefault from "FriendRequestsNotesSetting" /* 16231 */;
import NotifyFriendsOnComeOnlineSettingDefault from "NotifyFriendsOnComeOnlineSetting" /* 16232 */;
import NotifyFriendsOnProfileUpdateSettingDefault from "NotifyFriendsOnProfileUpdateSetting" /* 16233 */;
import NotifyServerMembersOnGoLiveSettingDefault from "NotifyServerMembersOnGoLiveSetting" /* 16235 */;
import VideoBackgroundSettingDefault from "VideoBackgroundSetting" /* 16237 */;
import MobileNotifSettingsRendererConfig from "MobileNotifSettingsRendererConfig" /* 16238 */;
import size from "module_2" /* 2 */;

const InAppNotificationsSettingDefault = InAppNotificationsSetting;
const IOSNativePhoneIntegrationSettingDefault = IOSNativePhoneIntegrationSetting;
const AndroidMessageNotificationsSettingDefault = AndroidMessageNotificationsSetting;
const AndroidNotificationLightsSettingDefault = AndroidNotificationLightsSetting;
const AndroidNotificationVibrationsSettingDefault = AndroidNotificationVibrationsSetting;
const AndroidNotificationSoundsSettingDefault = AndroidNotificationSoundsSetting;
const InAppMessageSoundsSettingDefault = InAppMessageSoundsSetting;
const UseDataForQuestsSettingDefault = UseDataForQuestsSetting;
const UseDataForQuests3PSettingDefault = UseDataForQuests3PSetting;

let ACCESSIBILITY;
let ACCOUNT;
let ACCOUNT_AGE_GROUP;
let ACCOUNT_AGE_GROUP_ADULT;
let ACCOUNT_AGE_GROUP_ASSIGNED_ADULT;
let ACCOUNT_AGE_GROUP_NON_ADULT;
let ACCOUNT_BLOCKED_USERS_V2;
let ACCOUNT_CHANGE_PASSWORD;
let ACCOUNT_CONFIRM_PASSWORD;
let ACCOUNT_DELETE;
let ACCOUNT_DISABLE;
let ACCOUNT_DISPLAY_NAME;
let ACCOUNT_EMAIL;
let ACCOUNT_ENABLE_2FA;
let ACCOUNT_IGNORED_USERS;
let ACCOUNT_PHONE;
let ACCOUNT_REMOVE_2FA;
let ACCOUNT_SMS_BACKUP;
let ACCOUNT_STANDING;
let ACCOUNT_USERNAME;
let ACCOUNT_VIEW_BACKUP_CODES;
let ACCOUNT_WEB_AUTHN_EDIT;
let ACCOUNT_WEB_AUTHN_NAME;
let ACCOUNT_WEB_AUTHN_REGISTER;
let ACCOUNT_WEB_AUTHN_SUCCESS;
let ACCOUNT_WEB_AUTHN_VIEW;
let ACKNOWLEDGEMENTS;
let ACTIVITY_PRIVACY_DEFAULT_SHARING;
let ACTIVITY_PRIVACY_SHARE_MY_ACTIVITY;
let ADVANCED;
let ADVANCED_VOICE_ACTIVITY;
let AGE_GROUP_CONFIRM;
let AGE_GROUP_CONFIRM_ACCOUNT_STATUS;
let AGE_GROUP_RESET;
let ALLOW_GAME_FRIEND_DMS;
let ANDROID_CLASSIC_CHAT_FONT_SCALE;
let ANDROID_FONT_SCALE;
let ANDROID_MESSAGE_NOTIFICATIONS;
let ANDROID_MOBILE_OVERLAY;
let ANDROID_NOTIFICATION_LIGHTS;
let ANDROID_NOTIFICATION_SOUNDS;
let ANDROID_NOTIFICATION_VIBRATIONS;
let ANDROID_VIEW_NSFW_DM_COMMANDS_V2;
let ANIMATE_EMOJI;
let ANIMATE_STICKERS;
let APPEARANCE;
let APPEARANCE_THEME_PICKER;
let APP_ICONS;
let APP_VERSION;
let AUTHORIZED_APP;
let AUTHORIZED_APPS;
let AUTHORIZED_APP_PERMISSIONS;
let AUTOMATIC_GAIN_CONTROL;
let AUTOPLAY_GIF;
let AUTO_VOICE_SENSITIVITY;
let BUG_REPORTER;
let BUILD_OVERRIDE_ACTIVE;
let CACHE_ACTIONS;
let CHANGE_LOG;
let CHANNEL_LIST_LAYOUT;
let CHAT;
let CHAT_EMOJI_EMOTICONS;
let CHAT_GESTURES;
let CLEAR_WEB_BROWSER_DATA;
let CLIPS;
let CLIPS_OPT_OUT_OF_VOICE_RECORDING;
let COLLECTIBLES_SHOP;
let COLLECTIBLES_SHOP_VIEW_ALL_CATEGORY_ITEMS;
let COMMUNITY_ACTIVITY_ALERTS;
let CONNECTED_GAMES;
let CONNECTIONS;
let CONTENT_AND_SOCIAL;
let CONTENT_AND_SOCIAL_DISCORD;
let CONTRAST_MODE;
let COPY_CLIENT_INFO;
let CREATE_BUG_REPORT;
let CUSTOM_STATUS_NOTIFICATIONS;
let DARK_MODE_THEME_PICKER;
let DATA_AND_PRIVACY;
let DATA_AND_PRIVACY_SECURE_FRAMES_PERSISTENT_CODES;
let DATA_SAVING_MODE;
let DEFAULT_GUILD_THEME_PREFERENCE;
let DESIGN_SYSTEMS;
let DESIGN_SYSTEMS_ALERT_MODAL;
let DESIGN_SYSTEMS_BACKGROUND_BLUR_VIEW;
let DESIGN_SYSTEMS_BUTTON;
let DESIGN_SYSTEMS_BUTTON_GROUP;
let DESIGN_SYSTEMS_COACHMARK;
let DESIGN_SYSTEMS_CONTEXT_MENU;
let DESIGN_SYSTEMS_EXPERIMENTAL_BUTTONS;
let DESIGN_SYSTEMS_LEGACY_BUTTON;
let DESIGN_SYSTEMS_MODAL;
let DESIGN_SYSTEMS_ROW_BUTTON;
let DESIGN_SYSTEMS_SHADOWS;
let DESIGN_SYSTEMS_TABLE_ROW;
let DESIGN_SYSTEMS_TABS;
let DESIGN_SYSTEMS_TEXT;
let DESIGN_SYSTEMS_TEXT_INPUT;
let DESIGN_SYSTEMS_TOAST;
let DESIGN_SYSTEMS_TOOLTIP;
let DESIGN_SYSTEM_AI_LOADER;
let DESIGN_SYSTEM_AI_SHIMMER;
let DESIGN_SYSTEM_BACKDROP;
let DESIGN_SYSTEM_FORM_PRIMITIVES;
let DESIGN_SYSTEM_HAPTICS;
let DESIGN_SYSTEM_PILE;
let DESIGN_SYSTEM_SEGMENTED_CONTROL;
let DESIGN_SYSTEM_SHEETS;
let DESIGN_SYSTEM_STACK;
let DESIGN_SYSTEM_TAG_GROUP;
let DEVELOPER_MODE;
let DEVICES;
let DEVICE_INFO;
let DIRECT_MESSAGE_SAFETY_ALERTS;
let DIRECT_MESSAGE_SPAM_FILTER;
let DISABLE_STREAM_PREVIEWS;
let DISCOVERY_BY_EMAIL;
let DISCOVERY_BY_PHONE;
let DISPLAY_MEDIA_LINKS;
let DISPLAY_MEDIA_UPLOADS;
let DISPLAY_NAME_STYLES_ACCESSIBILITY;
let DISPLAY_NAME_STYLES_ROUTE;
let DMS_HAPPENING_NOW_CARDS;
let DMS_MESSAGE_PREVIEWS;
let DOUBLE_TAP_EMOJI;
let DOUBLE_TAP_TO_REACT_ENABLED;
let ECHO_CANCELLATION;
let EMBED_AND_LINK_PREVIEWS;
let EMOJI_REACTIONS_ON_MESSAGES;
let ENABLE_REDUCED_MOTION;
let ENCRYPTION_VERIFIED_DEVICES;
let EXACT_SEARCH_RESULT_COUNTS;
let EXPERIMENT_OVERRIDE_ACTIVE;
let EXPLICIT_MEDIA_FILTERS_FRIENDS_DMS;
let EXPLICIT_MEDIA_FILTERS_GUILDS;
let EXPLICIT_MEDIA_FILTERS_NON_FRIENDS_DMS;
let FAMILY_CENTER;
let FAMILY_CENTER_PARENTAL_CONTROLS_SETTINGS;
let FAMILY_CENTER_SCHEDULE_DOWNTIME;
let FAVORITES_GUILD_TOGGLE;
let FRIEND_ANNIVERSARY_NOTIFICATIONS;
let FRIEND_GAMING_ACTIVITY_NOTIFICATIONS;
let FRIEND_ONLINE_NOTIFICATIONS;
let FRIEND_REQUEST_NOTES;
let FRIEND_STREAM_NOTIFICATIONS;
let GAME_MENTIONS_AUTOCOMPLETE;
let GORE_MEDIA_FILTERS_FRIENDS_DMS;
let GORE_MEDIA_FILTERS_GUILDS;
let GORE_MEDIA_FILTERS_NON_FRIENDS_DMS;
let GUILD_ROLE_SUBSCRIPTIONS;
let GUILD_ROLE_SUBSCRIPTIONS_CANCEL;
let GUILD_SETTING_ACTIVITY_JOINING;
let GUILD_SETTING_ACTIVITY_STATUS;
let HIGHLIGHT_NOTIFICATIONS;
let ICYMI_TAB;
let IMAGE_DESCRIPTIONS;
let INLINE_EMOJI_SUGGESTIONS;
let INPUT_MODE;
let INTERNAL_BUILD_ACTIVE;
let INTERNAL_BUILD_UPDATE;
let IN_APP_MESSAGE_SOUNDS;
let IN_APP_NOTIFICATIONS;
let IN_GAME_DMS;
let IOS_CONVERSATION_SUGGESTIONS;
let IOS_NATIVE_PHONE_INTEGRATION;
let LANGUAGE;
let LAUNCHPAD;
let LIGHT_MODE_THEME_PICKER;
let LOGOUT;
let MANAGE_SPONSORED_CONTENT;
let NOISE_SUPPRESSION;
let NOISE_SUPPRESSION_KRISP;
let NOTIFICATIONS;
let NOTIFY_FRIENDS_ON_COME_ONLINE;
let NOTIFY_FRIENDS_ON_PROFILE_UPDATE;
let NOTIFY_SERVER_MEMBERS_ON_GO_LIVE;
let OFFICIAL_MESSAGE_STYLE;
let OUTPUT_VOLUME;
let PARENTAL_CONTROLS_DATA_USAGE_PERSONALIZATION;
let PARENTAL_CONTROLS_DATA_USAGE_QUESTS;
let PARENTAL_CONTROLS_DATA_USAGE_QUESTS_3P;
let PARENTAL_CONTROLS_DATA_USAGE_STATISTICS;
let PARENTAL_CONTROLS_DIRECT_MESSAGES;
let PARENTAL_CONTROLS_EXPLICIT_MEDIA_FILTERS_FRIENDS_DMS;
let PARENTAL_CONTROLS_EXPLICIT_MEDIA_FILTERS_NON_FRIENDS_DMS;
let PARENTAL_CONTROLS_FRIEND_REQUESTS_EVERYONE;
let PARENTAL_CONTROLS_FRIEND_REQUESTS_MUTUAL_FRIENDS;
let PARENTAL_CONTROLS_FRIEND_REQUESTS_MUTUAL_GUILDS;
let PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_FRIENDS_DMS;
let PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_NON_FRIENDS_DMS;
let PARENTAL_CONTROLS_MESSAGE_REQUESTS;
let PARENTAL_CONTROLS_SENSITIVE_CONTENT_FILTERS;
let PINOT_MEMBER_SETTING;
let PINOT_MEMBER_SETTING_SAVE;
let PREMIUM;
let PREMIUM_GIFTING;
let PREMIUM_GUILD_BOOSTING;
let PREMIUM_MANAGE_PLAN;
let PREMIUM_MANAGE_SUBSCRIPTIONS;
let PREMIUM_PLAN_SELECT;
let PREMIUM_PROFILE_CUSTOMIZATION_TRY_IT_OUT;
let PREMIUM_RESTORE_SUBSCRIPTION;
let PROFILE_CUSTOMIZATION;
let PROFILE_PRIVACY;
let PROFILE_UPDATES_NOTIFICATIONS;
let QUEST_HOME;
let QUEST_PREVIEW_TOOL;
let REACTION_NOTIFICATIONS;
let REACT_COMPILER;
let REDESIGN_ANDROID_MESSAGE_NOTIFICATIONS;
let REDESIGN_ANDROID_NOTIFICATION_LIGHTS;
let REDESIGN_ANDROID_NOTIFICATION_SOUNDS;
let REDESIGN_ANDROID_NOTIFICATION_VIBRATIONS;
let REDESIGN_IN_APP_MESSAGE_SOUNDS;
let REDESIGN_IN_APP_NOTIFICATIONS;
let REDESIGN_IOS_NATIVE_PHONE_INTEGRATION;
let REDUCE_SATURATION;
let REQUEST_YOUR_DATA;
let ROLE_COLORS;
let SAFETY_GUILD_SETTING_DIRECT_MESSAGES;
let SAFETY_GUILD_SETTING_GUILD_SELECT;
let SAFETY_GUILD_SETTING_MESSAGE_REQUESTS;
let SAFETY_PRIVACY_POLICY;
let SAFETY_SEND_FRIEND_REQUESTS_EVERYONE;
let SAFETY_SEND_FRIEND_REQUESTS_MUTUAL_FRIENDS;
let SAFETY_SEND_FRIEND_REQUESTS_MUTUAL_GUILDS;
let SAFETY_TERMS_OF_SERVICE;
let SAME_AS_DEVICE_THEME;
let SAVE_CAMERA_UPLOADS_TO_DEVICE;
let SCAN_QR_CODE;
let SCREEN_DOWNTIME_REMINDER_NOTIFICATIONS;
let SCREEN_DOWNTIME_SCHEDULE_NOTIFICATIONS;
let SECURE_FRAMES_VERIFIED_DEVICES;
let SELECT_WEB_BROWSER;
let SEND_FRIEND_REQUESTS;
let SENSITIVE_CONTENT_FILTERS;
let SERVER_TRENDING_NOTIFICATIONS;
let SHOW_DEV_TOOLS;
let SHOW_DEV_WIDGET;
let SHOW_LINK_DECORATIONS;
let SHOW_ON_OFF_INDICATORS;
let SHOW_SPOILERS;
let SIDECHAIN_COMPRESSION;
let SOUNDBOARD_VOLUME;
let SPONSORED_CONTENT_PREFERENCES;
let STAFF_ONLY_FIND_YOUR_FRIENDS_DELETION;
let STICKER_AUTOCOMPLETE;
let STREAM_OUTPUT_VOLUME;
let SUMMARY_REMINDER_NOTIFICATIONS;
let SUPPORT;
let SWIPE_RIGHT_TO_LEFT;
let SYNC_CONTACTS;
let SYNC_CONTACTS_NAME;
let SYNC_PROFILE_COLORS;
let SYNC_REDUCED_MOTION_WITH_DEVICE;
let SYNC_THEME;
let SYSTEM_NOTIFICATIONS;
let TEXT_AND_MEDIA_SYNC;
let TIMESTAMP_HOUR_CYCLE;
let TOAST_DURATION;
let TYPING_INDICATOR;
let UPCOMING_SERVER_EVENT_NOTIFICATIONS;
let UPLOAD_DEBUG_LOGS;
let UPLOAD_INTL_DATA;
let USE_DATA_FOR_QUESTS;
let USE_DATA_FOR_QUESTS_3P;
let USE_DATA_FOR_QUESTS_3P_SPONSORED_CONTENT;
let USE_DATA_FOR_QUESTS_SPONSORED_CONTENT;
let USE_DATA_TO_CUSTOMIZE_DISCORD;
let USE_DATA_TO_IMPROVE_DISCORD;
let VIDEO_BACKGROUND;
let VIDEO_UPLOAD_QUALITY;
let VIEW_DEBUG_LOGS;
let VOICE;
let VOICE_ACTIVITY_NOTIFICATIONS;
let VOICE_SENSITIVITY;
let WEB_BROWSER;
let YOU_BAR_AVATAR_DECO_ACCESSSIBILITY;
let YOU_BAR_NAMEPLATE_ACCESSIBILITY;
const MobileUserSettings = SettingsConstants.MobileUserSettings;
const obj = { [PROFILE_CUSTOMIZATION]: ProfileCustomizationSettingDefault, [ACCOUNT]: AccountSettingDefault, [ACCOUNT_USERNAME]: AccountUsernameSettingDefault, [ACCOUNT_DISPLAY_NAME]: AccountDisplayNameSettingDefault, [ACCOUNT_EMAIL]: AccountEmailSettingDefault, [ACCOUNT_PHONE]: AccountPhoneSettingDefault, [ACCOUNT_AGE_GROUP]: AccountAgeGroupSettingDefault, [ACCOUNT_AGE_GROUP_ADULT]: AccountAgeGroupAdultSettingDefault, [ACCOUNT_AGE_GROUP_ASSIGNED_ADULT]: AccountAgeGroupAssignedAdultSettingDefault, [ACCOUNT_AGE_GROUP_NON_ADULT]: AccountAgeGroupNonAdultSettingDefault, [AGE_GROUP_CONFIRM]: AgeGroupConfirmSettingDefault, [AGE_GROUP_RESET]: AgeGroupResetSettingDefault, [AGE_GROUP_CONFIRM_ACCOUNT_STATUS]: AgeGroupConfirmAccountStatusSettingDefault, [ACCOUNT_STANDING]: AccountStandingSettingDefault, [ACCOUNT_CHANGE_PASSWORD]: AccountChangePasswordSettingDefault, [ACCOUNT_CONFIRM_PASSWORD]: AccountConfirmPasswordSettingDefault, [ACCOUNT_ENABLE_2FA]: AccountEnable2faSettingDefault, [ACCOUNT_REMOVE_2FA]: AccountRemove2faSettingDefault, [ACCOUNT_VIEW_BACKUP_CODES]: AccountViewBackupCodesSettingDefault, [ACCOUNT_SMS_BACKUP]: AccountSmsBackupSettingDefault, [ACCOUNT_WEB_AUTHN_VIEW]: AccountWebAuthnViewSettingDefault, [ACCOUNT_WEB_AUTHN_REGISTER]: AccountWebAuthnRegisterSettingDefault, [ACCOUNT_WEB_AUTHN_NAME]: AccountWebAuthnNameSettingDefault, [ACCOUNT_WEB_AUTHN_EDIT]: AccountWebAuthnEditSettingDefault, [ACCOUNT_WEB_AUTHN_SUCCESS]: AccountWebAuthnSuccessSettingDefault, [ACCOUNT_BLOCKED_USERS_V2]: AccountBlockedUsersSettingDefault, [ACCOUNT_IGNORED_USERS]: AccountIgnoredUsersSettingDefault, [ACCOUNT_DELETE]: AccountDeleteSettingDefault, [ACCOUNT_DISABLE]: AccountDisableSettingDefault, [SENSITIVE_CONTENT_FILTERS]: SensitiveContentFilterSettingDefault, [EXPLICIT_MEDIA_FILTERS_FRIENDS_DMS]: ExplicitMediaFiltersFriendsDMsSettingDefault, [EXPLICIT_MEDIA_FILTERS_NON_FRIENDS_DMS]: ExplicitMediaFiltersNonFriendsDMsSettingDefault, [EXPLICIT_MEDIA_FILTERS_GUILDS]: ExplicitMediaFiltersGuildsSettingDefault, [GORE_MEDIA_FILTERS_FRIENDS_DMS]: GoreMediaFiltersFriendsDMsSettingDefault, [GORE_MEDIA_FILTERS_NON_FRIENDS_DMS]: GoreMediaFiltersNonFriendsDMsSettingDefault, [GORE_MEDIA_FILTERS_GUILDS]: GoreMediaFiltersGuildsSettingDefault, [DIRECT_MESSAGE_SAFETY_ALERTS]: DirectMessageSafetyAlertsSettingDefault, [DIRECT_MESSAGE_SPAM_FILTER]: DirectMessageSpamFilterSettingDefault, [ANDROID_VIEW_NSFW_DM_COMMANDS_V2]: AndroidViewNsfwDmCommandsSettingDefault, [STAFF_ONLY_FIND_YOUR_FRIENDS_DELETION]: StaffOnlyFindYourFriendsDeletionSettingDefault, [SYNC_CONTACTS]: SyncContactsSettingDefault, [SYNC_CONTACTS_NAME]: SyncContactsNameSettingDefault, [DISCOVERY_BY_PHONE]: DiscoveryByPhoneSettingDefault, [DISCOVERY_BY_EMAIL]: DiscoveryByEmailSettingDefault, [IOS_CONVERSATION_SUGGESTIONS]: IOSConversationSuggestionsSettingDefault, [PROFILE_PRIVACY]: ProfilePrivacySettingDefault, [USE_DATA_TO_IMPROVE_DISCORD]: UseDataToImproveDiscordSettingDefault, [USE_DATA_TO_CUSTOMIZE_DISCORD]: UseDataToCustomizeDiscordSettingDefault, [REQUEST_YOUR_DATA]: RequestYourDataSettingDefault, [FAMILY_CENTER]: FamilyCenterSettingDefault, [FAMILY_CENTER_PARENTAL_CONTROLS_SETTINGS]: FamilyCenterSettingParentalControlsSettingDefault, [FAMILY_CENTER_SCHEDULE_DOWNTIME]: FamilyCenterScheduleDowntimeSettingDefault, [AUTHORIZED_APPS]: AuthorizedAppsSettingDefault, [AUTHORIZED_APP]: AuthorizedAppSettingDefault, [AUTHORIZED_APP_PERMISSIONS]: AuthorizedAppPermissionsSettingDefault, [DEVICES]: DevicesSettingDefault, [CONNECTIONS]: ConnectionsSettingDefault, [CLIPS]: ClipsSettingDefault, [CLIPS_OPT_OUT_OF_VOICE_RECORDING]: ClipsOptOutOfVoiceRecordingSettingDefault, [SEND_FRIEND_REQUESTS]: FriendRequestsEveryoneSettingDefault, [SAFETY_SEND_FRIEND_REQUESTS_EVERYONE]: FriendRequestsEveryoneSettingDefault, [SAFETY_SEND_FRIEND_REQUESTS_MUTUAL_FRIENDS]: FriendRequestsMutualFriendsSettingDefault, [SAFETY_SEND_FRIEND_REQUESTS_MUTUAL_GUILDS]: FriendRequestsMutualGuildsSettingDefault, [SCAN_QR_CODE]: ScanQrCodeSettingDefault, [PREMIUM]: PremiumSettingDefault, [PREMIUM_MANAGE_PLAN]: PremiumManagePlanSettingDefault, [PREMIUM_MANAGE_SUBSCRIPTIONS]: PremiumManageSubscriptionsSettingDefault, [PREMIUM_PLAN_SELECT]: PremiumPlanSelectSettingDefault, [PREMIUM_GUILD_BOOSTING]: PremiumGuildBoostingSettingDefault, [PREMIUM_GIFTING]: PremiumGiftingSettingDefault, [QUEST_HOME]: defs_QuestHomeSettingDefault, [QUEST_PREVIEW_TOOL]: QuestPreviewToolSettingDefault, [GUILD_ROLE_SUBSCRIPTIONS]: GuildRoleSubscriptionsSettingDefault, [GUILD_ROLE_SUBSCRIPTIONS_CANCEL]: GuildRoleSubscriptionsCancelSettingDefault, [PREMIUM_RESTORE_SUBSCRIPTION]: PremiumRestoreSubscriptionSettingDefault, [VOICE]: VoiceSettingDefault, [INPUT_MODE]: InputModeSettingDefault, [AUTO_VOICE_SENSITIVITY]: AutoVoiceSensitivitySettingDefault, [VOICE_SENSITIVITY]: VoiceSensitivitySettingDefault, [OUTPUT_VOLUME]: OutputVolumeSettingDefault, [STREAM_OUTPUT_VOLUME]: StreamOutputVolumeSettingDefault, [SOUNDBOARD_VOLUME]: SoundboardVolumeSettingDefault, [ANDROID_MOBILE_OVERLAY]: AndroidMobileOverlaySettingDefault, [NOISE_SUPPRESSION_KRISP]: NoiseSuppressionKrispSettingDefault, [NOISE_SUPPRESSION]: NoiseSuppressionSettingDefault, [ECHO_CANCELLATION]: EchoCancellationSettingDefault, [SIDECHAIN_COMPRESSION]: SidechainCompressionSettingDefault, [AUTOMATIC_GAIN_CONTROL]: AutomaticGainControlSettingDefault, [ADVANCED_VOICE_ACTIVITY]: AdvancedVoiceActivitySettingDefault, [APPEARANCE]: AppearanceSettingDefault, [APPEARANCE_THEME_PICKER]: AppearanceThemePickerSettingDefault, [SAME_AS_DEVICE_THEME]: SameAsDeviceThemeSettingDefault, [LIGHT_MODE_THEME_PICKER]: LightModeThemeSettingDefault, [DARK_MODE_THEME_PICKER]: DarkModeThemeSettingDefault, [SYNC_THEME]: SyncThemeSettingDefault, [DEFAULT_GUILD_THEME_PREFERENCE]: DefaultGuildThemePreferenceSettingDefault, [ANDROID_FONT_SCALE]: AndroidFontScaleSettingDefault, [ANDROID_CLASSIC_CHAT_FONT_SCALE]: AndroidClassicChatFontScaleSettingDefault, [DMS_MESSAGE_PREVIEWS]: DmsMessagePreviewsSettingDefault, [DMS_HAPPENING_NOW_CARDS]: DmsHappeningNowCardsSettingDefault, [EXACT_SEARCH_RESULT_COUNTS]: ExactSearchResultCountsSettingDefault, [GAME_MENTIONS_AUTOCOMPLETE]: GameMentionsAutocompleteSettingDefault, [FAVORITES_GUILD_TOGGLE]: FavoritesGuildToggleSettingDefault, [ACCESSIBILITY]: AccessibilitySettingDefault, [ROLE_COLORS]: RoleColorsSettingDefault, [OFFICIAL_MESSAGE_STYLE]: OfficialMessageStyleSettingDefault, [DISPLAY_NAME_STYLES_ROUTE]: DisplayNameStylesRouteSettingDefault, [TYPING_INDICATOR]: TypingIndicatorSettingDefault, [DISPLAY_NAME_STYLES_ACCESSIBILITY]: DisplayNameStylesAccessibilitySettingDefault, [YOU_BAR_NAMEPLATE_ACCESSIBILITY]: YouBarNameplateAccessibilitySettingDefault, [YOU_BAR_AVATAR_DECO_ACCESSSIBILITY]: YouBarAvatarDecoAccessibilitySettingDefault, [SHOW_LINK_DECORATIONS]: ShowLinkDecorationsSettingDefault, [SHOW_ON_OFF_INDICATORS]: EnableSwitchIconsSettingDefault, [CONTRAST_MODE]: ContrastModeSettingDefault, [REDUCE_SATURATION]: ReduceSaturationSettingDefault, [TOAST_DURATION]: ToastDurationSettingDefault, [SYNC_PROFILE_COLORS]: SyncProfileColorsSettingDefault, [ENABLE_REDUCED_MOTION]: EnableReducedMotionSettingDefault, [SYNC_REDUCED_MOTION_WITH_DEVICE]: SyncReducedMotionWithDeviceSettingDefault, [AUTOPLAY_GIF]: AutoplayGifSettingDefault, [ANIMATE_EMOJI]: AnimateEmojiSettingDefault, [ANIMATE_STICKERS]: AnimateStickersSettingDefault, [LANGUAGE]: LanguageSettingDefault, [CHAT]: ChatSettingDefault, [DISPLAY_MEDIA_LINKS]: DisplayMediaLinksSettingDefault, [DISPLAY_MEDIA_UPLOADS]: DisplayMediaUploadsSettingDefault, [IMAGE_DESCRIPTIONS]: ImageDescriptionsSettingDefault, [VIDEO_UPLOAD_QUALITY]: VideoUploadQualitySettingDefault, [DATA_SAVING_MODE]: DataSavingModeSettingDefault, [SAVE_CAMERA_UPLOADS_TO_DEVICE]: SaveCameraUploadsToDeviceSettingDefault, [EMBED_AND_LINK_PREVIEWS]: EmbedAndLinkPreviewsSettingDefault, [EMOJI_REACTIONS_ON_MESSAGES]: EmojiReactionsOnMessagesSettingDefault, [CHAT_EMOJI_EMOTICONS]: ChatEmojiEmoticonsSettingDefault, [STICKER_AUTOCOMPLETE]: StickerAutocompleteSettingDefault, [SHOW_SPOILERS]: ShowSpoilersSettingDefault, [INLINE_EMOJI_SUGGESTIONS]: InlineEmojiSuggestionsSettingDefault, [TEXT_AND_MEDIA_SYNC]: TextAndMediaSyncSettingDefault, [TIMESTAMP_HOUR_CYCLE]: TimestampHourCycleSettingDefault, [SWIPE_RIGHT_TO_LEFT]: SwipeRightToLeftSettingDefault, [CHAT_GESTURES]: ChatGestureSettingsDefault, [WEB_BROWSER]: WebBrowserSettingDefault, [SELECT_WEB_BROWSER]: SelectWebBrowserSettingDefault, [CLEAR_WEB_BROWSER_DATA]: ClearWebBrowserDataSettingDefault, [NOTIFICATIONS]: NotificationsSettingDefault, [IN_APP_NOTIFICATIONS]: InAppNotificationsSettingDefault, [SYSTEM_NOTIFICATIONS]: SystemNotificationsSettingDefault, [REACTION_NOTIFICATIONS]: ReactionNotificationsSettingsDefault, [CUSTOM_STATUS_NOTIFICATIONS]: CustomStatusNotificationSettingsDefault, [IOS_NATIVE_PHONE_INTEGRATION]: IOSNativePhoneIntegrationSettingDefault, [ANDROID_MESSAGE_NOTIFICATIONS]: AndroidMessageNotificationsSettingDefault, [ANDROID_NOTIFICATION_LIGHTS]: AndroidNotificationLightsSettingDefault, [ANDROID_NOTIFICATION_VIBRATIONS]: AndroidNotificationVibrationsSettingDefault, [ANDROID_NOTIFICATION_SOUNDS]: AndroidNotificationSoundsSettingDefault, [IN_APP_MESSAGE_SOUNDS]: InAppMessageSoundsSettingDefault, [REDESIGN_IN_APP_NOTIFICATIONS]: InAppNotificationsSetting.RedesignInAppNotificationsSetting, [REDESIGN_IN_APP_MESSAGE_SOUNDS]: InAppMessageSoundsSetting.RedesignInAppMessageSoundsSetting, [REDESIGN_ANDROID_MESSAGE_NOTIFICATIONS]: AndroidMessageNotificationsSetting.RedesignAndroidMessageNotificationsSetting, [REDESIGN_ANDROID_NOTIFICATION_LIGHTS]: AndroidNotificationLightsSetting.RedesignAndroidNotificationLightsSetting, [REDESIGN_ANDROID_NOTIFICATION_VIBRATIONS]: AndroidNotificationVibrationsSetting.RedesignAndroidNotificationVibrationsSetting, [REDESIGN_ANDROID_NOTIFICATION_SOUNDS]: AndroidNotificationSoundsSetting.RedesignAndroidNotificationSoundsSetting, [REDESIGN_IOS_NATIVE_PHONE_INTEGRATION]: IOSNativePhoneIntegrationSetting.RedesignIOSNativePhoneIntegrationSetting, [FRIEND_STREAM_NOTIFICATIONS]: FriendStreamNotificationsSettingDefault, [FRIEND_ANNIVERSARY_NOTIFICATIONS]: FriendAnniversaryNotificationSettingDefault, [VOICE_ACTIVITY_NOTIFICATIONS]: VoiceActivityNotificationSettingDefault, [FRIEND_ONLINE_NOTIFICATIONS]: FriendOnlineNotificationSettingDefault, [FRIEND_GAMING_ACTIVITY_NOTIFICATIONS]: FriendGamingActivityNotificationSettingDefault, [PROFILE_UPDATES_NOTIFICATIONS]: ProfileUpdatesNotificationSettingDefault, [SERVER_TRENDING_NOTIFICATIONS]: ServerTrendingNotificationSettingDefault, [UPCOMING_SERVER_EVENT_NOTIFICATIONS]: UpcomingServerEventNotificationSettingDefault, [SUMMARY_REMINDER_NOTIFICATIONS]: SummaryReminderNotificationSettingDefault, [SCREEN_DOWNTIME_REMINDER_NOTIFICATIONS]: ScreenDowntimeReminderSettingDefault, [SCREEN_DOWNTIME_SCHEDULE_NOTIFICATIONS]: ScreenDowntimeScheduleSettingDefault, [COMMUNITY_ACTIVITY_ALERTS]: CommunityActivityAlertsSettingDefault, [HIGHLIGHT_NOTIFICATIONS]: HighlightNotificationsSettingDefault, [APP_ICONS]: AppIconsSettingDefault, [ADVANCED]: AdvancedSettingDefault, [DEVELOPER_MODE]: DeveloperModeSettingDefault, [LAUNCHPAD]: LaunchpadSettingDefault, [CHANNEL_LIST_LAYOUT]: ChannelListLayoutSettingDefault, [ICYMI_TAB]: IcymiTabSettingDefault, [SUPPORT]: SupportSettingDefault, [UPLOAD_DEBUG_LOGS]: UploadDebugLogsSettingDefault, [UPLOAD_INTL_DATA]: UploadIntlDataSettingDefault, [ACKNOWLEDGEMENTS]: AcknowledgementsSettingDefault, [CHANGE_LOG]: ChangeLogSettingDefault, [LOGOUT]: LogoutSettingDefault, [APP_VERSION]: AppVersionSettingDefault, [DEVICE_INFO]: DeviceInfoSettingDefault, [VIEW_DEBUG_LOGS]: ViewDebugLogsSettingDefault, [COPY_CLIENT_INFO]: CopyClientInfoSettingDefault, [CACHE_ACTIONS]: CacheActionsSettingDefault, [SHOW_DEV_WIDGET]: ShowDevWidgetSettingDefault, [SHOW_DEV_TOOLS]: ShowDevToolsSettingDefault, [BUG_REPORTER]: BugReporterSettingDefault, [INTERNAL_BUILD_ACTIVE]: InternalBuildActiveSettingDefault, [INTERNAL_BUILD_UPDATE]: InternalBuildUpdateSettingDefault, [EXPERIMENT_OVERRIDE_ACTIVE]: ExperimentOverrideActiveSettingDefault, [BUILD_OVERRIDE_ACTIVE]: BuildOverrideActiveSettingDefault, [CREATE_BUG_REPORT]: CreateBugReportSettingDefault, [DESIGN_SYSTEMS]: DesignSystemsSettingDefault, [DESIGN_SYSTEMS_TEXT]: DesignSystemsTextSettingDefault, [DESIGN_SYSTEMS_BUTTON]: DesignSystemsButtonSettingDefault, [DESIGN_SYSTEMS_LEGACY_BUTTON]: DesignSystemsLegacyButtonSettingDefault, [DESIGN_SYSTEMS_BUTTON_GROUP]: DesignSystemsButtonGroupSettingDefault, [DESIGN_SYSTEMS_ROW_BUTTON]: DesignSystemsRowButtonSettingDefault, [DESIGN_SYSTEMS_EXPERIMENTAL_BUTTONS]: DesignSystemsExperimentalButtonsSettingDefault, [DESIGN_SYSTEMS_TABLE_ROW]: DesignSystemsTableRowSettingDefault, [DESIGN_SYSTEMS_ALERT_MODAL]: DesignSystemsAlertModalSettingDefault, [DESIGN_SYSTEMS_BACKGROUND_BLUR_VIEW]: DesignSystemsBackgroundBlurViewSettingDefault, [DESIGN_SYSTEMS_SHADOWS]: DesignSystemsShadowsSettingDefault, [DESIGN_SYSTEM_SEGMENTED_CONTROL]: DesignSystemSegmentedControlSettingDefault, [DESIGN_SYSTEMS_TABS]: DesignSystemsTabsSettingDefault, [DESIGN_SYSTEMS_CONTEXT_MENU]: DesignSystemsContextMenuSettingDefault, [DESIGN_SYSTEMS_TOAST]: DesignSystemsToastSettingDefault, [DESIGN_SYSTEMS_TEXT_INPUT]: DesignSystemsTextInputSettingDefault, [DESIGN_SYSTEMS_TOOLTIP]: DesignSystemsTooltipSettingDefault, [DESIGN_SYSTEMS_COACHMARK]: DesignSystemsCoachmarkSettingDefault, [DESIGN_SYSTEM_STACK]: DesignSystemStackSettingDefault, [DESIGN_SYSTEM_BACKDROP]: DesignSystemBackdropSettingDefault, [DESIGN_SYSTEMS_MODAL]: DesignSystemsModalSettingDefault, [DESIGN_SYSTEM_PILE]: DesignSystemPileSettingDefault, [DESIGN_SYSTEM_TAG_GROUP]: DesignSystemTagGroupSettingDefault, [DESIGN_SYSTEM_SHEETS]: DesignSystemSheetsSettingDefault, [DESIGN_SYSTEM_FORM_PRIMITIVES]: DesignSystemFormPrimitivesSettingDefault, [DESIGN_SYSTEM_HAPTICS]: DesignSystemHapticsSettingDefault, [DESIGN_SYSTEM_AI_LOADER]: DesignSystemAILoaderSettingDefault, [DESIGN_SYSTEM_AI_SHIMMER]: DesignSystemAIShimmerSettingDefault, [PREMIUM_PROFILE_CUSTOMIZATION_TRY_IT_OUT]: PremiumProfileCustomizationTryItOutSettingDefault, [COLLECTIBLES_SHOP]: CollectiblesShopSettingDefault, [COLLECTIBLES_SHOP_VIEW_ALL_CATEGORY_ITEMS]: CollectiblesShopViewAllCategoryItemsSettingDefault, [ENCRYPTION_VERIFIED_DEVICES]: EncryptionSettingDefault, [DATA_AND_PRIVACY_SECURE_FRAMES_PERSISTENT_CODES]: SecureFramesPersistentCodesSettingDefault, [SECURE_FRAMES_VERIFIED_DEVICES]: SecureFramesVerifiedDevicesSettingDefault, [USE_DATA_FOR_QUESTS]: UseDataForQuestsSettingDefault, [USE_DATA_FOR_QUESTS_3P]: UseDataForQuests3PSettingDefault, [PINOT_MEMBER_SETTING]: PinotSettingsLazy.PinotMemberSetting, [PINOT_MEMBER_SETTING_SAVE]: PinotSettingsLazy.PinotMemberSettingSave, [USE_DATA_FOR_QUESTS_SPONSORED_CONTENT]: UseDataForQuestsSetting.UseDataForQuestsSponsoredContentSetting, [USE_DATA_FOR_QUESTS_3P_SPONSORED_CONTENT]: UseDataForQuests3PSetting.UseDataForQuests3PSponsoredContentSetting, [SPONSORED_CONTENT_PREFERENCES]: SponsoredContentPreferencesSettingDefault, [MANAGE_SPONSORED_CONTENT]: ManageSponsoredContentSettingDefault, [DISABLE_STREAM_PREVIEWS]: DisableStreamPreviewsSettingDefault, [DATA_AND_PRIVACY]: DataAndPrivacySettingDefault, [CONTENT_AND_SOCIAL]: ContentAndSocialSettingDefault, [SAFETY_TERMS_OF_SERVICE]: SafetyTermsOfServiceSettingDefault, [SAFETY_PRIVACY_POLICY]: SafetyPrivacyPolicySettingDefault, [SAFETY_GUILD_SETTING_GUILD_SELECT]: SafetyGuildSettingGuildSelectDefault, [SAFETY_GUILD_SETTING_DIRECT_MESSAGES]: SafetyGuildSettingDirectMessagesDefault, [SAFETY_GUILD_SETTING_MESSAGE_REQUESTS]: SafetyGuildSettingMessageRequestsDefault, [GUILD_SETTING_ACTIVITY_STATUS]: GuildSettingActivityStatusDefault, [GUILD_SETTING_ACTIVITY_JOINING]: GuildSettingActivityJoiningDefault, [REACT_COMPILER]: ReactCompilerSettingDefault, [CONTENT_AND_SOCIAL_DISCORD]: ContentAndSocialDiscordRouteSettingDefault, [CONNECTED_GAMES]: ConnectedGamesRouteSettingDefault, [ALLOW_GAME_FRIEND_DMS]: AllowGameFriendDMsSettingDefault, [IN_GAME_DMS]: InGameDMsSettingDefault, [DOUBLE_TAP_EMOJI]: DoubleTapEmojiSettingDefault, [DOUBLE_TAP_TO_REACT_ENABLED]: DoubleTapToReactSettingDefault, [PARENTAL_CONTROLS_SENSITIVE_CONTENT_FILTERS]: ParentalControlsSensitiveContentFilterSettingDefault, [PARENTAL_CONTROLS_DIRECT_MESSAGES]: ParentalControlsDirectMessagesDefault, [PARENTAL_CONTROLS_MESSAGE_REQUESTS]: ParentalControlsMessageRequestsDefault, [PARENTAL_CONTROLS_FRIEND_REQUESTS_EVERYONE]: ParentalControlsFriendRequestsEveryoneSettingDefault, [PARENTAL_CONTROLS_FRIEND_REQUESTS_MUTUAL_FRIENDS]: ParentalControlsFriendRequestsMutualFriendsSettingDefault, [PARENTAL_CONTROLS_FRIEND_REQUESTS_MUTUAL_GUILDS]: ParentalControlsFriendRequestsMutualGuildsSettingDefault, [PARENTAL_CONTROLS_EXPLICIT_MEDIA_FILTERS_FRIENDS_DMS]: ParentalControlsExplicitMediaFiltersFriendsDMsSettingDefault, [PARENTAL_CONTROLS_EXPLICIT_MEDIA_FILTERS_NON_FRIENDS_DMS]: ParentalControlsExplicitMediaFiltersNonFriendsDMsSettingDefault, [PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_FRIENDS_DMS]: ParentalControlsGoreMediaFiltersFriendsDMsSettingDefault, [PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_NON_FRIENDS_DMS]: ParentalControlsGoreMediaFiltersNonFriendsDMsSettingDefault, [PARENTAL_CONTROLS_DATA_USAGE_STATISTICS]: ParentalControlsUseDataToImproveDiscordSettingDefault, [PARENTAL_CONTROLS_DATA_USAGE_PERSONALIZATION]: ParentalControlsUseDataToCustomizeDiscordSettingDefault, [PARENTAL_CONTROLS_DATA_USAGE_QUESTS]: ParentalControlsUseDataForQuestsSettingDefault, [PARENTAL_CONTROLS_DATA_USAGE_QUESTS_3P]: ParentalControlsUseDataForQuests3PSettingDefault, [ACTIVITY_PRIVACY_SHARE_MY_ACTIVITY]: ActivityPrivacyShareMyActivitySettingDefault, [ACTIVITY_PRIVACY_DEFAULT_SHARING]: ActivityPrivacyDefaultSharingSettingDefault, [FRIEND_REQUEST_NOTES]: FriendRequestsNotesSettingDefault, [NOTIFY_FRIENDS_ON_COME_ONLINE]: NotifyFriendsOnComeOnlineSettingDefault, [NOTIFY_FRIENDS_ON_PROFILE_UPDATE]: NotifyFriendsOnProfileUpdateSettingDefault, [NOTIFY_SERVER_MEMBERS_ON_GO_LIVE]: NotifyServerMembersOnGoLiveSettingDefault, [VIDEO_BACKGROUND]: VideoBackgroundSettingDefault };
({ PROFILE_CUSTOMIZATION, ACCOUNT, ACCOUNT_USERNAME, ACCOUNT_DISPLAY_NAME, ACCOUNT_EMAIL, ACCOUNT_PHONE, ACCOUNT_AGE_GROUP, ACCOUNT_AGE_GROUP_ADULT, ACCOUNT_AGE_GROUP_ASSIGNED_ADULT, ACCOUNT_AGE_GROUP_NON_ADULT, AGE_GROUP_CONFIRM, AGE_GROUP_RESET, AGE_GROUP_CONFIRM_ACCOUNT_STATUS, ACCOUNT_STANDING, ACCOUNT_CHANGE_PASSWORD, ACCOUNT_CONFIRM_PASSWORD, ACCOUNT_ENABLE_2FA, ACCOUNT_REMOVE_2FA, ACCOUNT_VIEW_BACKUP_CODES, ACCOUNT_SMS_BACKUP, ACCOUNT_WEB_AUTHN_VIEW, ACCOUNT_WEB_AUTHN_REGISTER, ACCOUNT_WEB_AUTHN_NAME, ACCOUNT_WEB_AUTHN_EDIT, ACCOUNT_WEB_AUTHN_SUCCESS, ACCOUNT_BLOCKED_USERS_V2, ACCOUNT_IGNORED_USERS, ACCOUNT_DELETE, ACCOUNT_DISABLE, SENSITIVE_CONTENT_FILTERS, EXPLICIT_MEDIA_FILTERS_FRIENDS_DMS, EXPLICIT_MEDIA_FILTERS_NON_FRIENDS_DMS, EXPLICIT_MEDIA_FILTERS_GUILDS, GORE_MEDIA_FILTERS_FRIENDS_DMS, GORE_MEDIA_FILTERS_NON_FRIENDS_DMS, GORE_MEDIA_FILTERS_GUILDS, DIRECT_MESSAGE_SAFETY_ALERTS, DIRECT_MESSAGE_SPAM_FILTER, ANDROID_VIEW_NSFW_DM_COMMANDS_V2, STAFF_ONLY_FIND_YOUR_FRIENDS_DELETION, SYNC_CONTACTS, SYNC_CONTACTS_NAME, DISCOVERY_BY_PHONE, DISCOVERY_BY_EMAIL, IOS_CONVERSATION_SUGGESTIONS, PROFILE_PRIVACY, USE_DATA_TO_IMPROVE_DISCORD, USE_DATA_TO_CUSTOMIZE_DISCORD, REQUEST_YOUR_DATA, FAMILY_CENTER, FAMILY_CENTER_PARENTAL_CONTROLS_SETTINGS, FAMILY_CENTER_SCHEDULE_DOWNTIME, AUTHORIZED_APPS, AUTHORIZED_APP, AUTHORIZED_APP_PERMISSIONS, DEVICES, CONNECTIONS, CLIPS, CLIPS_OPT_OUT_OF_VOICE_RECORDING, SEND_FRIEND_REQUESTS, SAFETY_SEND_FRIEND_REQUESTS_EVERYONE, SAFETY_SEND_FRIEND_REQUESTS_MUTUAL_FRIENDS, SAFETY_SEND_FRIEND_REQUESTS_MUTUAL_GUILDS, SCAN_QR_CODE, PREMIUM, PREMIUM_MANAGE_PLAN, PREMIUM_MANAGE_SUBSCRIPTIONS, PREMIUM_PLAN_SELECT, PREMIUM_GUILD_BOOSTING, PREMIUM_GIFTING, QUEST_HOME, QUEST_PREVIEW_TOOL, GUILD_ROLE_SUBSCRIPTIONS, GUILD_ROLE_SUBSCRIPTIONS_CANCEL, PREMIUM_RESTORE_SUBSCRIPTION, VOICE, INPUT_MODE, AUTO_VOICE_SENSITIVITY, VOICE_SENSITIVITY, OUTPUT_VOLUME, STREAM_OUTPUT_VOLUME, SOUNDBOARD_VOLUME, ANDROID_MOBILE_OVERLAY, NOISE_SUPPRESSION_KRISP, NOISE_SUPPRESSION, ECHO_CANCELLATION, SIDECHAIN_COMPRESSION, AUTOMATIC_GAIN_CONTROL, ADVANCED_VOICE_ACTIVITY, APPEARANCE, APPEARANCE_THEME_PICKER, SAME_AS_DEVICE_THEME, LIGHT_MODE_THEME_PICKER, DARK_MODE_THEME_PICKER, SYNC_THEME, DEFAULT_GUILD_THEME_PREFERENCE, ANDROID_FONT_SCALE, ANDROID_CLASSIC_CHAT_FONT_SCALE, DMS_MESSAGE_PREVIEWS, DMS_HAPPENING_NOW_CARDS, EXACT_SEARCH_RESULT_COUNTS, GAME_MENTIONS_AUTOCOMPLETE, FAVORITES_GUILD_TOGGLE, ACCESSIBILITY, ROLE_COLORS, OFFICIAL_MESSAGE_STYLE, DISPLAY_NAME_STYLES_ROUTE, TYPING_INDICATOR, DISPLAY_NAME_STYLES_ACCESSIBILITY, YOU_BAR_NAMEPLATE_ACCESSIBILITY, YOU_BAR_AVATAR_DECO_ACCESSSIBILITY, SHOW_LINK_DECORATIONS, SHOW_ON_OFF_INDICATORS, CONTRAST_MODE, REDUCE_SATURATION, TOAST_DURATION, SYNC_PROFILE_COLORS, ENABLE_REDUCED_MOTION, SYNC_REDUCED_MOTION_WITH_DEVICE, AUTOPLAY_GIF, ANIMATE_EMOJI, ANIMATE_STICKERS, LANGUAGE, CHAT, DISPLAY_MEDIA_LINKS, DISPLAY_MEDIA_UPLOADS, IMAGE_DESCRIPTIONS, VIDEO_UPLOAD_QUALITY, DATA_SAVING_MODE, SAVE_CAMERA_UPLOADS_TO_DEVICE, EMBED_AND_LINK_PREVIEWS, EMOJI_REACTIONS_ON_MESSAGES, CHAT_EMOJI_EMOTICONS, STICKER_AUTOCOMPLETE, SHOW_SPOILERS, INLINE_EMOJI_SUGGESTIONS, TEXT_AND_MEDIA_SYNC, TIMESTAMP_HOUR_CYCLE, SWIPE_RIGHT_TO_LEFT, CHAT_GESTURES, WEB_BROWSER, SELECT_WEB_BROWSER, CLEAR_WEB_BROWSER_DATA, NOTIFICATIONS, IN_APP_NOTIFICATIONS, SYSTEM_NOTIFICATIONS, REACTION_NOTIFICATIONS, CUSTOM_STATUS_NOTIFICATIONS, IOS_NATIVE_PHONE_INTEGRATION, ANDROID_MESSAGE_NOTIFICATIONS, ANDROID_NOTIFICATION_LIGHTS, ANDROID_NOTIFICATION_VIBRATIONS, ANDROID_NOTIFICATION_SOUNDS, IN_APP_MESSAGE_SOUNDS, REDESIGN_IN_APP_NOTIFICATIONS, REDESIGN_IN_APP_MESSAGE_SOUNDS, REDESIGN_ANDROID_MESSAGE_NOTIFICATIONS, REDESIGN_ANDROID_NOTIFICATION_LIGHTS, REDESIGN_ANDROID_NOTIFICATION_VIBRATIONS, REDESIGN_ANDROID_NOTIFICATION_SOUNDS, REDESIGN_IOS_NATIVE_PHONE_INTEGRATION, FRIEND_STREAM_NOTIFICATIONS, FRIEND_ANNIVERSARY_NOTIFICATIONS, VOICE_ACTIVITY_NOTIFICATIONS, FRIEND_ONLINE_NOTIFICATIONS, FRIEND_GAMING_ACTIVITY_NOTIFICATIONS, PROFILE_UPDATES_NOTIFICATIONS, SERVER_TRENDING_NOTIFICATIONS, UPCOMING_SERVER_EVENT_NOTIFICATIONS, SUMMARY_REMINDER_NOTIFICATIONS, SCREEN_DOWNTIME_REMINDER_NOTIFICATIONS, SCREEN_DOWNTIME_SCHEDULE_NOTIFICATIONS, COMMUNITY_ACTIVITY_ALERTS, HIGHLIGHT_NOTIFICATIONS, APP_ICONS, ADVANCED, DEVELOPER_MODE, LAUNCHPAD, CHANNEL_LIST_LAYOUT, ICYMI_TAB, SUPPORT, UPLOAD_DEBUG_LOGS, UPLOAD_INTL_DATA, ACKNOWLEDGEMENTS, CHANGE_LOG, LOGOUT, APP_VERSION, DEVICE_INFO, VIEW_DEBUG_LOGS, COPY_CLIENT_INFO, CACHE_ACTIONS, SHOW_DEV_WIDGET, SHOW_DEV_TOOLS, BUG_REPORTER, INTERNAL_BUILD_ACTIVE, INTERNAL_BUILD_UPDATE, EXPERIMENT_OVERRIDE_ACTIVE, BUILD_OVERRIDE_ACTIVE, CREATE_BUG_REPORT, DESIGN_SYSTEMS, DESIGN_SYSTEMS_TEXT, DESIGN_SYSTEMS_BUTTON, DESIGN_SYSTEMS_LEGACY_BUTTON, DESIGN_SYSTEMS_BUTTON_GROUP, DESIGN_SYSTEMS_ROW_BUTTON, DESIGN_SYSTEMS_EXPERIMENTAL_BUTTONS, DESIGN_SYSTEMS_TABLE_ROW, DESIGN_SYSTEMS_ALERT_MODAL, DESIGN_SYSTEMS_BACKGROUND_BLUR_VIEW, DESIGN_SYSTEMS_SHADOWS, DESIGN_SYSTEM_SEGMENTED_CONTROL, DESIGN_SYSTEMS_TABS, DESIGN_SYSTEMS_CONTEXT_MENU, DESIGN_SYSTEMS_TOAST, DESIGN_SYSTEMS_TEXT_INPUT, DESIGN_SYSTEMS_TOOLTIP, DESIGN_SYSTEMS_COACHMARK, DESIGN_SYSTEM_STACK, DESIGN_SYSTEM_BACKDROP, DESIGN_SYSTEMS_MODAL, DESIGN_SYSTEM_PILE, DESIGN_SYSTEM_TAG_GROUP, DESIGN_SYSTEM_SHEETS, DESIGN_SYSTEM_FORM_PRIMITIVES, DESIGN_SYSTEM_HAPTICS, DESIGN_SYSTEM_AI_LOADER, DESIGN_SYSTEM_AI_SHIMMER, PREMIUM_PROFILE_CUSTOMIZATION_TRY_IT_OUT, COLLECTIBLES_SHOP, COLLECTIBLES_SHOP_VIEW_ALL_CATEGORY_ITEMS, ENCRYPTION_VERIFIED_DEVICES, DATA_AND_PRIVACY_SECURE_FRAMES_PERSISTENT_CODES, SECURE_FRAMES_VERIFIED_DEVICES, USE_DATA_FOR_QUESTS, USE_DATA_FOR_QUESTS_3P, PINOT_MEMBER_SETTING, PINOT_MEMBER_SETTING_SAVE, USE_DATA_FOR_QUESTS_SPONSORED_CONTENT, USE_DATA_FOR_QUESTS_3P_SPONSORED_CONTENT, SPONSORED_CONTENT_PREFERENCES, MANAGE_SPONSORED_CONTENT, DISABLE_STREAM_PREVIEWS, DATA_AND_PRIVACY, CONTENT_AND_SOCIAL, SAFETY_TERMS_OF_SERVICE, SAFETY_PRIVACY_POLICY, SAFETY_GUILD_SETTING_GUILD_SELECT, SAFETY_GUILD_SETTING_DIRECT_MESSAGES, SAFETY_GUILD_SETTING_MESSAGE_REQUESTS, GUILD_SETTING_ACTIVITY_STATUS, GUILD_SETTING_ACTIVITY_JOINING, REACT_COMPILER, CONTENT_AND_SOCIAL_DISCORD, CONNECTED_GAMES, ALLOW_GAME_FRIEND_DMS, IN_GAME_DMS, DOUBLE_TAP_EMOJI, DOUBLE_TAP_TO_REACT_ENABLED, PARENTAL_CONTROLS_SENSITIVE_CONTENT_FILTERS, PARENTAL_CONTROLS_DIRECT_MESSAGES, PARENTAL_CONTROLS_MESSAGE_REQUESTS, PARENTAL_CONTROLS_FRIEND_REQUESTS_EVERYONE, PARENTAL_CONTROLS_FRIEND_REQUESTS_MUTUAL_FRIENDS, PARENTAL_CONTROLS_FRIEND_REQUESTS_MUTUAL_GUILDS, PARENTAL_CONTROLS_EXPLICIT_MEDIA_FILTERS_FRIENDS_DMS, PARENTAL_CONTROLS_EXPLICIT_MEDIA_FILTERS_NON_FRIENDS_DMS } = MobileUserSettings);
PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_FRIENDS_DMS = MobileUserSettings.PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_FRIENDS_DMS;
PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_NON_FRIENDS_DMS = MobileUserSettings.PARENTAL_CONTROLS_GORE_MEDIA_FILTERS_NON_FRIENDS_DMS;
PARENTAL_CONTROLS_DATA_USAGE_STATISTICS = MobileUserSettings.PARENTAL_CONTROLS_DATA_USAGE_STATISTICS;
PARENTAL_CONTROLS_DATA_USAGE_PERSONALIZATION = MobileUserSettings.PARENTAL_CONTROLS_DATA_USAGE_PERSONALIZATION;
PARENTAL_CONTROLS_DATA_USAGE_QUESTS = MobileUserSettings.PARENTAL_CONTROLS_DATA_USAGE_QUESTS;
PARENTAL_CONTROLS_DATA_USAGE_QUESTS_3P = MobileUserSettings.PARENTAL_CONTROLS_DATA_USAGE_QUESTS_3P;
ACTIVITY_PRIVACY_SHARE_MY_ACTIVITY = MobileUserSettings.ACTIVITY_PRIVACY_SHARE_MY_ACTIVITY;
ACTIVITY_PRIVACY_DEFAULT_SHARING = MobileUserSettings.ACTIVITY_PRIVACY_DEFAULT_SHARING;
FRIEND_REQUEST_NOTES = MobileUserSettings.FRIEND_REQUEST_NOTES;
NOTIFY_FRIENDS_ON_COME_ONLINE = MobileUserSettings.NOTIFY_FRIENDS_ON_COME_ONLINE;
NOTIFY_FRIENDS_ON_PROFILE_UPDATE = MobileUserSettings.NOTIFY_FRIENDS_ON_PROFILE_UPDATE;
NOTIFY_SERVER_MEMBERS_ON_GO_LIVE = MobileUserSettings.NOTIFY_SERVER_MEMBERS_ON_GO_LIVE;
VIDEO_BACKGROUND = MobileUserSettings.VIDEO_BACKGROUND;
const merged = Object.assign(MobileNotifSettingsRendererConfig.MOBILE_NOTIF_SETTINGS_RENDERER_CONFIG);
const freezeResult = freeze(obj);
const result = size.fileFinishedImporting("modules/user_settings/core/native/SettingsRendererConfig.tsx");

export const SETTING_RENDERER_CONFIG = freezeResult;
