// Module ID: 15422
// Function ID: 15423
// Name: QuestDockConstants
// Dependencies: [576, 2]

// Module 15422 (QuestDockConstants)
import nativeDefault from "native" /* 576 */;
import size from "module_2" /* 2 */;

const obj = { mass: 0.5, damping: 80, stiffness: 320 };
const obj2 = {};
const merged = Object.assign(obj);
obj2.overshootClamping = true;
const result = size.fileFinishedImporting("modules/quests/native/QuestDock/QuestDockConstants.tsx");

export const QUEST_DOCK_COLLAPSED_HEIGHT = 56;
export const QUEST_DOCK_CLOSED_HEIGHT = 22;
export const QUEST_DOCK_LANDSCAPE_MEDIA_EXPANDED_HEIGHT = 400;
export const QUEST_DOCK_PORTRAIT_MEDIA_EXPANDED_HEIGHT = 585;
export const QUEST_DOCK_COLLAPSED_HEADER_PADDING_RIGHT = nativeDefault.space.PX_16;
export const QUEST_DOCK_EXPANDED_PADDING_BOTTOM = nativeDefault.space.PX_16;
export const QUEST_DOCK_EXPANDED_PADDING_HORIZONTAL = nativeDefault.space.PX_12;
export const QUEST_DOCK_EXPANDED_ENROLLED_PADDING_TOP = nativeDefault.space.PX_8;
export const QUEST_DOCK_COLLAPSED_MAX_WIDTH = 600;
export const QUEST_DOCK_HORIZONTAL_EDGE_GUTTER_COLLAPSED = 8;
export const QUEST_DOCK_VERTICAL_EDGE_GUTTER_COLLAPSED = 8;
export const QUEST_DOCK_VERTICAL_EDGE_GUTTER_EXPANDED = 0;
export const QUEST_DOCK_VERTICAL_EDGE_GUTTER_CLOSED = 0;
export const QUEST_DOCK_UNENROLLED_HEADER_INSET_EXPANDED = 12;
export const QUEST_DOCK_GESTURE_VERTICAL_DELTA_MINIMUM = 15;
export const QUEST_DOCK_GESTURE_CLOSED_VERTICAL_DELTA_MINIMUM = 15;
export const QUEST_DOCK_GESTURE_MODE_TRANSITION_HEIGHT = 200;
export const QUEST_DOCK_GESTURE_MODE_CLOSED_TRANSITION_HEIGHT = 30;
export const QUEST_DOCK_GESTURE_MODE_TRANSITION_VELOCITY = 200;
export const QUEST_DOCK_GESTURE_TOUCH_MOVE_COUNT_THRESHOLD = 5;
export const QUEST_DOCK_GESTURE_CLOSED_Y_OFFSET_FACTOR = 0.8;
export const QUEST_DOCK_GESTURE_COLLAPSED_Y_OFFSET_FACTOR = 1.5;
export const QUEST_DOCK_GESTURE_EXPANDED_EXCESS_HEIGHT_FACTOR = 0.07;
export const QUEST_DOCK_EXTERNAL_SCROLL_DELTA_THRESHOLD = 4;
export const QUEST_DOCK_EXTERNAL_OFFSET_COLLAPSED = 64;
export const QUEST_DOCK_EXTERNAL_OFFSET_COLLAPSED_WITH_YOU_BAR = 56;
export const QUEST_DOCK_EXTERNAL_OFFSET_EXPANDED = 64;
export const QUEST_DOCK_EXTERNAL_OFFSET_EXPANDED_WITH_YOU_BAR = 56;
export const QUEST_DOCK_EXTERNAL_OFFSET_CLOSED = 22;
export const QUEST_DOCK_EXPANDED_CONTENT_PADDING_VERTICAL = 16;
export const QUEST_DOCK_MODE_CHANGE_PHYSICS = obj;
export const QUEST_DOCK_MODE_CHANGE_PHYSICS_CLAMPED = obj2;
export const QUEST_DOCK_CONTENT_BORDER_RADII = nativeDefault.radii.lg;
