// Module ID: 676
// Function ID: 677
// Name: debugSymbolicatorIntegration
// Dependencies: [677, 865, 881, 888, 975, 976, 977, 979, 980, 981, 990, 991, 992, 993, 994, 998, 999, 1017, 1027, 1029, 1030, 986, 1018, 1032, 1035, 1036, 1038, 1039, 1040, 1000]

// Module 676 (debugSymbolicatorIntegration)
import _mod677 from "module_677" /* 677 */;
import deviceContextIntegration from "deviceContextIntegration" /* 865 */;
import reactNativeErrorHandlersIntegration from "reactNativeErrorHandlersIntegration" /* 881 */;
import nativeLinkedErrorsIntegration from "nativeLinkedErrorsIntegration" /* 888 */;
import nativeReleaseIntegration from "nativeReleaseIntegration" /* 975 */;
import eventOriginIntegration from "eventOriginIntegration" /* 976 */;
import defaultSdkInfo from "defaultSdkInfo" /* 977 */;
import reactNativeInfoIntegration from "reactNativeInfoIntegration" /* 979 */;
import modulesLoaderIntegration from "modulesLoaderIntegration" /* 980 */;
import hermesProfilingIntegration from "hermesProfilingIntegration" /* 981 */;
import ANDROID_DEFAULT_BUNDLE_NAME from "ANDROID_DEFAULT_BUNDLE_NAME" /* 986 */;
import screenshotIntegration from "screenshotIntegration" /* 990 */;
import viewHierarchyIntegration from "viewHierarchyIntegration" /* 991 */;
import OTA_UPDATES_CONTEXT_KEY from "OTA_UPDATES_CONTEXT_KEY" /* 992 */;
import spotlightIntegration from "spotlightIntegration" /* 993 */;
import MOBILE_REPLAY_INTEGRATION_NAME from "MOBILE_REPLAY_INTEGRATION_NAME" /* 994 */;
import MOBILE_FEEDBACK_INTEGRATION_NAME from "MOBILE_FEEDBACK_INTEGRATION_NAME" /* 998 */;
import browserReplayIntegration from "browserReplayIntegration" /* 999 */;
import init from "init" /* 1000 */;
import captureAppStart from "captureAppStart" /* 1017 */;
import _mod1018 from "module_1018" /* 1018 */;
import _mod1027 from "module_1027" /* 1027 */;
import stallTrackingIntegration from "stallTrackingIntegration" /* 1029 */;
import userInteractionIntegration from "userInteractionIntegration" /* 1030 */;
import _mod1032 from "module_1032" /* 1032 */;
import _mod1035 from "module_1035" /* 1035 */;
import _mod1036 from "module_1036" /* 1036 */;
import logEnricherIntegration from "logEnricherIntegration" /* 1038 */;
import graphqlIntegration from "graphqlIntegration" /* 1039 */;
import supabaseIntegration from "supabaseIntegration" /* 1040 */;

const deviceContextIntegration_export = deviceContextIntegration.deviceContextIntegration;
const reactNativeErrorHandlersIntegration_export = reactNativeErrorHandlersIntegration.reactNativeErrorHandlersIntegration;
const nativeLinkedErrorsIntegration_export = nativeLinkedErrorsIntegration.nativeLinkedErrorsIntegration;
const nativeReleaseIntegration_export = nativeReleaseIntegration.nativeReleaseIntegration;
const eventOriginIntegration_export = eventOriginIntegration.eventOriginIntegration;
const reactNativeInfoIntegration_export = reactNativeInfoIntegration.reactNativeInfoIntegration;
const modulesLoaderIntegration_export = modulesLoaderIntegration.modulesLoaderIntegration;
const hermesProfilingIntegration_export = hermesProfilingIntegration.hermesProfilingIntegration;
const screenshotIntegration_export = screenshotIntegration.screenshotIntegration;
const viewHierarchyIntegration_export = viewHierarchyIntegration.viewHierarchyIntegration;
const spotlightIntegration_export = spotlightIntegration.spotlightIntegration;
const browserReplayIntegration_export = browserReplayIntegration.browserReplayIntegration;
const stallTrackingIntegration_export = stallTrackingIntegration.stallTrackingIntegration;
const userInteractionIntegration_export = userInteractionIntegration.userInteractionIntegration;
const logEnricherIntegration_export = logEnricherIntegration.logEnricherIntegration;
const graphqlIntegration_export = graphqlIntegration.graphqlIntegration;
const supabaseIntegration_export = supabaseIntegration.supabaseIntegration;

export const debugSymbolicatorIntegration = _mod677.debugSymbolicatorIntegration;
export { deviceContextIntegration_export as deviceContextIntegration };
export { reactNativeErrorHandlersIntegration_export as reactNativeErrorHandlersIntegration };
export { nativeLinkedErrorsIntegration_export as nativeLinkedErrorsIntegration };
export { nativeReleaseIntegration_export as nativeReleaseIntegration };
export { eventOriginIntegration_export as eventOriginIntegration };
export const sdkInfoIntegration = defaultSdkInfo.sdkInfoIntegration;
export { reactNativeInfoIntegration_export as reactNativeInfoIntegration };
export { modulesLoaderIntegration_export as modulesLoaderIntegration };
export { hermesProfilingIntegration_export as hermesProfilingIntegration };
export { screenshotIntegration_export as screenshotIntegration };
export { viewHierarchyIntegration_export as viewHierarchyIntegration };
export const expoContextIntegration = OTA_UPDATES_CONTEXT_KEY.expoContextIntegration;
export { spotlightIntegration_export as spotlightIntegration };
export const mobileReplayIntegration = MOBILE_REPLAY_INTEGRATION_NAME.mobileReplayIntegration;
export const feedbackIntegration = MOBILE_FEEDBACK_INTEGRATION_NAME.feedbackIntegration;
export { browserReplayIntegration_export as browserReplayIntegration };
export const appStartIntegration = captureAppStart.appStartIntegration;
export const nativeFramesIntegration = _mod1027.nativeFramesIntegration;
export const createNativeFramesIntegrations = _mod1027.createNativeFramesIntegrations;
export { stallTrackingIntegration_export as stallTrackingIntegration };
export { userInteractionIntegration_export as userInteractionIntegration };
export const createReactNativeRewriteFrames = ANDROID_DEFAULT_BUNDLE_NAME.createReactNativeRewriteFrames;
export const appRegistryIntegration = _mod1018.appRegistryIntegration;
export const timeToDisplayIntegration = _mod1032.timeToDisplayIntegration;
export const breadcrumbsIntegration = _mod1035.breadcrumbsIntegration;
export const primitiveTagIntegration = _mod1036.primitiveTagIntegration;
export { logEnricherIntegration_export as logEnricherIntegration };
export { graphqlIntegration_export as graphqlIntegration };
export { supabaseIntegration_export as supabaseIntegration };
export const browserApiErrorsIntegration = init.browserApiErrorsIntegration;
export const dedupeIntegration = init.dedupeIntegration;
export const functionToStringIntegration = init.functionToStringIntegration;
export const browserGlobalHandlersIntegration = init.globalHandlersIntegration;
export const httpClientIntegration = init.httpClientIntegration;
export const httpContextIntegration = init.httpContextIntegration;
export const inboundFiltersIntegration = init.inboundFiltersIntegration;
export const browserLinkedErrorsIntegration = init.linkedErrorsIntegration;
export const rewriteFramesIntegration = init.rewriteFramesIntegration;
export const extraErrorDataIntegration = init.extraErrorDataIntegration;
