// Module ID: 1642
// Function ID: 18339
// Name: BounceInData
// Dependencies: [1640]

// Module 1642 (BounceInData)
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";

obj = { BounceIn: obj, BounceInRight: obj, BounceInLeft: obj1, BounceInUp: obj2, BounceInDown: obj3 };
obj = { name: "BounceIn", style: null, duration: 0.6 };
const items = [{ scale: 0 }];
const items1 = [{ scale: 1.2 }];
const items2 = [{ scale: 0.9 }];
const items3 = [{ scale: 1.1 }];
const items4 = [{ scale: 1 }];
obj.style = { [0]: { transform: items }, [55]: { transform: items1 }, [70]: { transform: items2 }, [85]: { transform: items3 }, [100]: { transform: items4 } };
obj = { name: "BounceInRight", style: null, duration: 0.6 };
const items5 = [{ translateX: "100vw" }];
const items6 = [{ translateX: "-20px" }];
const items7 = [{ translateX: "10px" }];
const items8 = [{ translateX: "-10px" }];
const items9 = [{ translateX: "0px" }];
obj.style = { [0]: { transform: items5 }, [55]: { transform: items6 }, [70]: { transform: items7 }, [85]: { transform: items8 }, [100]: { transform: items9 } };
obj1 = { name: "BounceInLeft", style: null, duration: 0.6 };
const items10 = [{ translateX: "-100vw" }];
const items11 = [{ translateX: "20px" }];
const items12 = [{ translateX: "-10px" }];
const items13 = [{ translateX: "10px" }];
const items14 = [{ translateX: "0px" }];
obj1.style = { [0]: { transform: items10 }, [55]: { transform: items11 }, [70]: { transform: items12 }, [85]: { transform: items13 }, [100]: { transform: items14 } };
obj2 = { name: "BounceInUp", style: null, duration: 0.6 };
const items15 = [{ translateY: "-100vh" }];
const items16 = [{ translateY: "20px" }];
const items17 = [{ translateY: "-10px" }];
const items18 = [{ translateY: "10px" }];
const items19 = [{ translateY: "0px" }];
obj2.style = { [0]: { transform: items15 }, [55]: { transform: items16 }, [70]: { transform: items17 }, [85]: { transform: items18 }, [100]: { transform: items19 } };
obj3 = { name: "BounceInDown", style: null, duration: 0.6 };
const items20 = [{ translateY: "100vh" }];
const items21 = [{ translateY: "-20px" }];
const items22 = [{ translateY: "10px" }];
const items23 = [{ translateY: "-10px" }];
const items24 = [{ translateY: "0px" }];
obj3.style = { [0]: { transform: items20 }, [55]: { transform: items21 }, [70]: { transform: items22 }, [85]: { transform: items23 }, [100]: { transform: items24 } };
const obj4 = { BounceOut: obj5, BounceOutRight: obj6, BounceOutLeft: obj7, BounceOutUp: obj8, BounceOutDown: obj9 };
obj5 = { name: "BounceOut", style: null, duration: 0.6 };
const items25 = [{ scale: 1 }];
const items26 = [{ scale: 1.1 }];
const items27 = [{ scale: 0.9 }];
const items28 = [{ scale: 1.2 }];
const items29 = [{ scale: 0.1 }];
obj5.style = { [0]: { transform: items25 }, [15]: { transform: items26 }, [30]: { transform: items27 }, [45]: { transform: items28 }, [100]: { transform: items29 } };
obj6 = { name: "BounceOutRight", style: null, duration: 0.6 };
const items30 = [{ translateX: "0px" }];
const items31 = [{ translateX: "-10px" }];
const items32 = [{ translateX: "10px" }];
const items33 = [{ translateX: "-20px" }];
const items34 = [{ translateX: "100vh" }];
obj6.style = { [0]: { transform: items30 }, [15]: { transform: items31 }, [30]: { transform: items32 }, [45]: { transform: items33 }, [100]: { transform: items34 } };
obj7 = { name: "BounceOutLeft", style: null, duration: 0.6 };
const items35 = [{ translateX: "0px" }];
const items36 = [{ translateX: "10px" }];
const items37 = [{ translateX: "-10px" }];
const items38 = [{ translateX: "20px" }];
const items39 = [{ translateX: "-100vh" }];
obj7.style = { [0]: { transform: items35 }, [15]: { transform: items36 }, [30]: { transform: items37 }, [45]: { transform: items38 }, [100]: { transform: items39 } };
obj8 = { name: "BounceOutUp", style: null, duration: 0.6 };
const items40 = [{ translateY: "0px" }];
const items41 = [{ translateY: "10px" }];
const items42 = [{ translateY: "-10px" }];
const items43 = [{ translateY: "20px" }];
const items44 = [{ translateY: "-100vh" }];
obj8.style = { [0]: { transform: items40 }, [15]: { transform: items41 }, [30]: { transform: items42 }, [45]: { transform: items43 }, [100]: { transform: items44 } };
obj9 = { name: "BounceOutDown", style: null, duration: 0.6 };
const items45 = [{ translateY: "0px" }];
const items46 = [{ translateY: "-10px" }];
const items47 = [{ translateY: "10px" }];
const items48 = [{ translateY: "-20px" }];
const items49 = [{ translateY: "100vh" }];
obj9.style = { [0]: { transform: items45 }, [15]: { transform: items46 }, [30]: { transform: items47 }, [45]: { transform: items48 }, [100]: { transform: items49 } };
const obj10 = {};
const obj11 = {};
obj11.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.BounceIn);
obj11.duration = obj.BounceIn.duration;
obj10.BounceIn = obj11;
const obj12 = {};
obj12.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.BounceInRight);
obj12.duration = obj.BounceInRight.duration;
obj10.BounceInRight = obj12;
const obj13 = {};
obj13.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.BounceInLeft);
obj13.duration = obj.BounceInLeft.duration;
obj10.BounceInLeft = obj13;
const obj14 = {};
obj14.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.BounceInUp);
obj14.duration = obj.BounceInUp.duration;
obj10.BounceInUp = obj14;
const obj15 = {};
obj15.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.BounceInDown);
obj15.duration = obj.BounceInDown.duration;
obj10.BounceInDown = obj15;
const obj16 = {};
const obj17 = {};
obj17.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.BounceOut);
obj17.duration = obj4.BounceOut.duration;
obj16.BounceOut = obj17;
const obj18 = {};
obj18.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.BounceOutRight);
obj18.duration = obj4.BounceOutRight.duration;
obj16.BounceOutRight = obj18;
const obj19 = {};
obj19.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.BounceOutLeft);
obj19.duration = obj4.BounceOutLeft.duration;
obj16.BounceOutLeft = obj19;
const obj20 = {};
obj20.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.BounceOutUp);
obj20.duration = obj4.BounceOutUp.duration;
obj16.BounceOutUp = obj20;
const obj21 = {};
obj21.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj4.BounceOutDown);
obj21.duration = obj4.BounceOutDown.duration;
obj16.BounceOutDown = obj21;

export const BounceInData = obj;
export const BounceOutData = obj4;
export const BounceIn = obj10;
export const BounceOut = obj16;
