// Module ID: 1645
// Function ID: 18343
// Name: ZoomInData
// Dependencies: [1640]

// Module 1645 (ZoomInData)
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";
import convertAnimationObjectToKeyframes from "convertAnimationObjectToKeyframes";

obj = { ZoomIn: obj, ZoomInRotate: obj, ZoomInRight: obj1, ZoomInLeft: obj2, ZoomInUp: obj3, ZoomInDown: obj4, ZoomInEasyUp: obj5, ZoomInEasyDown: obj6 };
obj = { name: "ZoomIn", style: null, duration: 0.3 };
const items = [{ scale: 0 }];
const items1 = [{ scale: 1 }];
obj.style = { [0]: { transform: items }, [100]: { transform: items1 } };
obj = { name: "ZoomInRotate", style: null, duration: 0.3 };
const items2 = [{ scale: 0, rotate: "0.3rad" }];
const items3 = [{ scale: 1, rotate: "0deg" }];
obj.style = { [0]: { transform: items2 }, [100]: { transform: items3 } };
obj1 = { name: "ZoomInRight", style: null, duration: 0.3 };
const items4 = [{ translateX: "100vw", scale: 0 }];
const items5 = [{ translateX: "0%", scale: 1 }];
obj1.style = { [0]: { transform: items4 }, [100]: { transform: items5 } };
obj2 = { name: "ZoomInLeft", style: null, duration: 0.3 };
const items6 = [{ translateX: "-100vw", scale: 0 }];
const items7 = [{ translateX: "0%", scale: 1 }];
obj2.style = { [0]: { transform: items6 }, [100]: { transform: items7 } };
obj3 = { name: "ZoomInUp", style: null, duration: 0.3 };
const items8 = [{ translateY: "-100vh", scale: 0 }];
const items9 = [{ translateY: "0%", scale: 1 }];
obj3.style = { [0]: { transform: items8 }, [100]: { transform: items9 } };
obj4 = { name: "ZoomInDown", style: null, duration: 0.3 };
const items10 = [{ translateY: "100vh", scale: 0 }];
const items11 = [{ translateY: "0%", scale: 1 }];
obj4.style = { [0]: { transform: items10 }, [100]: { transform: items11 } };
obj5 = { name: "ZoomInEasyUp", style: null, duration: 0.3 };
const items12 = [{ translateY: "-100%", scale: 0 }];
const items13 = [{ translateY: "0%", scale: 1 }];
obj5.style = { [0]: { transform: items12 }, [100]: { transform: items13 } };
obj6 = { name: "ZoomInEasyDown", style: null, duration: 0.3 };
const items14 = [{ translateY: "100%", scale: 0 }];
const items15 = [{ translateY: "0%", scale: 1 }];
obj6.style = { [0]: { transform: items14 }, [100]: { transform: items15 } };
const obj7 = { ZoomOut: obj8, ZoomOutRotate: obj9, ZoomOutRight: obj10, ZoomOutLeft: obj11, ZoomOutUp: obj12, ZoomOutDown: obj13, ZoomOutEasyUp: obj14, ZoomOutEasyDown: obj15 };
obj8 = { name: "ZoomOut", style: null, duration: 0.3 };
const items16 = [{ scale: 1 }];
const items17 = [{ scale: 0 }];
obj8.style = { [0]: { transform: items16 }, [100]: { transform: items17 } };
obj9 = { name: "ZoomOutRotate", style: null, duration: 0.3 };
const items18 = [{ scale: 1, rotate: "0rad" }];
const items19 = [{ scale: 0, rotate: "0.3rad" }];
obj9.style = { [0]: { transform: items18 }, [100]: { transform: items19 } };
obj10 = { name: "ZoomOutRight", style: null, duration: 0.3 };
const items20 = [{ translateX: "0vw", scale: 1 }];
const items21 = [{ translateX: "100vw", scale: 0 }];
obj10.style = { [0]: { transform: items20 }, [100]: { transform: items21 } };
obj11 = { name: "ZoomOutLeft", style: null, duration: 0.3 };
const items22 = [{ translateX: "0vw", scale: 1 }];
const items23 = [{ translateX: "-100vw", scale: 0 }];
obj11.style = { [0]: { transform: items22 }, [100]: { transform: items23 } };
obj12 = { name: "ZoomOutUp", style: null, duration: 0.3 };
const items24 = [{ translateX: "0vh", scale: 1 }];
const items25 = [{ translateY: "-100vh", scale: 0 }];
obj12.style = { [0]: { transform: items24 }, [100]: { transform: items25 } };
obj13 = { name: "ZoomOutDown", style: null, duration: 0.3 };
const items26 = [{ translateX: "0vh", scale: 1 }];
const items27 = [{ translateY: "100vh", scale: 0 }];
obj13.style = { [0]: { transform: items26 }, [100]: { transform: items27 } };
obj14 = { name: "ZoomOutEasyUp", style: null, duration: 0.3 };
const items28 = [{ translateY: "0%", scale: 1 }];
const items29 = [{ translateY: "-100%", scale: 0 }];
obj14.style = { [0]: { transform: items28 }, [100]: { transform: items29 } };
obj15 = { name: "ZoomOutEasyDown", style: null, duration: 0.3 };
const items30 = [{ translateY: "0%", scale: 1 }];
const items31 = [{ translateY: "100%", scale: 0 }];
obj15.style = { [0]: { transform: items30 }, [100]: { transform: items31 } };
const obj16 = {};
const obj17 = {};
obj17.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomIn);
obj17.duration = obj.ZoomIn.duration;
obj16.ZoomIn = obj17;
const obj18 = {};
obj18.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInRotate);
obj18.duration = obj.ZoomInRotate.duration;
obj16.ZoomInRotate = obj18;
const obj19 = {};
obj19.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInRight);
obj19.duration = obj.ZoomInRight.duration;
obj16.ZoomInRight = obj19;
const obj20 = {};
obj20.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInLeft);
obj20.duration = obj.ZoomInLeft.duration;
obj16.ZoomInLeft = obj20;
const obj21 = {};
obj21.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInUp);
obj21.duration = obj.ZoomInUp.duration;
obj16.ZoomInUp = obj21;
const obj22 = {};
obj22.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInDown);
obj22.duration = obj.ZoomInDown.duration;
obj16.ZoomInDown = obj22;
const obj23 = {};
obj23.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInEasyUp);
obj23.duration = obj.ZoomInEasyUp.duration;
obj16.ZoomInEasyUp = obj23;
const obj24 = {};
obj24.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj.ZoomInEasyDown);
obj24.duration = obj.ZoomInEasyDown.duration;
obj16.ZoomInEasyDown = obj24;
const obj25 = {};
const obj26 = {};
obj26.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOut);
obj26.duration = obj7.ZoomOut.duration;
obj25.ZoomOut = obj26;
const obj27 = {};
obj27.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutRotate);
obj27.duration = obj7.ZoomOutRotate.duration;
obj25.ZoomOutRotate = obj27;
const obj28 = {};
obj28.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutRight);
obj28.duration = obj7.ZoomOutRight.duration;
obj25.ZoomOutRight = obj28;
const obj29 = {};
obj29.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutLeft);
obj29.duration = obj7.ZoomOutLeft.duration;
obj25.ZoomOutLeft = obj29;
const obj30 = {};
obj30.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutUp);
obj30.duration = obj7.ZoomOutUp.duration;
obj25.ZoomOutUp = obj30;
const obj31 = {};
obj31.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutDown);
obj31.duration = obj7.ZoomOutDown.duration;
obj25.ZoomOutDown = obj31;
const obj32 = {};
obj32.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutEasyUp);
obj32.duration = obj7.ZoomOutEasyUp.duration;
obj25.ZoomOutEasyUp = obj32;
const obj33 = {};
obj33.style = convertAnimationObjectToKeyframes.convertAnimationObjectToKeyframes(obj7.ZoomOutEasyDown);
obj33.duration = obj7.ZoomOutEasyDown.duration;
obj25.ZoomOutEasyDown = obj33;

export const ZoomInData = obj;
export const ZoomOutData = obj7;
export const ZoomIn = obj16;
export const ZoomOut = obj25;
