// Module ID: 3780
// Function ID: 3781
// Name: parsers
// Dependencies: [3781, 3783, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, 3795, 3797, 3798, 3799, 3801, 3802, 3803, 3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3813, 3814, 3815, 3816, 3817, 3818]

// Module 3780 (parsers)
import _typeof from "_typeof" /* 3781 */;
import _typeof2 from "_typeof" /* 3783 */;
import _typeof3 from "_typeof" /* 3786 */;
import _typeof4 from "_typeof" /* 3787 */;
import _typeof5 from "_typeof" /* 3788 */;
import _typeof6 from "_typeof" /* 3789 */;
import _typeof7 from "_typeof" /* 3790 */;
import _typeof8 from "_typeof" /* 3791 */;
import _typeof9 from "_typeof" /* 3792 */;
import _typeof10 from "_typeof" /* 3793 */;
import _typeof11 from "_typeof" /* 3795 */;
import _typeof12 from "_typeof" /* 3797 */;
import _typeof13 from "_typeof" /* 3798 */;
import _typeof14 from "_typeof" /* 3799 */;
import _typeof15 from "_typeof" /* 3801 */;
import _typeof16 from "_typeof" /* 3802 */;
import _typeof17 from "_typeof" /* 3803 */;
import _typeof18 from "_typeof" /* 3805 */;
import _typeof19 from "_typeof" /* 3806 */;
import _typeof20 from "_typeof" /* 3807 */;
import _typeof21 from "_typeof" /* 3808 */;
import _typeof22 from "_typeof" /* 3809 */;
import _typeof23 from "_typeof" /* 3810 */;
import _typeof24 from "_typeof" /* 3811 */;
import _typeof25 from "_typeof" /* 3812 */;
import _typeof26 from "_typeof" /* 3813 */;
import _typeof27 from "_typeof" /* 3814 */;
import _typeof28 from "_typeof" /* 3815 */;
import _typeof29 from "_typeof" /* 3816 */;
import _typeof30 from "_typeof" /* 3817 */;
import _typeof31 from "_typeof" /* 3818 */;

const obj = { G: null, y: null, Y: null, R: null, u: null, Q: null, q: null, M: null, L: null, w: null, I: null, d: null, D: null, E: null, e: null, c: null, i: null, a: null, b: null, B: null, h: null, H: null, K: null, k: null, m: null, s: null, S: null, X: null, x: null, t: null, T: null };
const eraParser = new _typeof.EraParser();
obj[0] = eraParser;
const yearParser = new _typeof2.YearParser();
obj[1] = yearParser;
const localWeekYearParser = new _typeof3.LocalWeekYearParser();
obj[2] = localWeekYearParser;
const iSOWeekYearParser = new _typeof4.ISOWeekYearParser();
obj[3] = iSOWeekYearParser;
const extendedYearParser = new _typeof5.ExtendedYearParser();
obj[4] = extendedYearParser;
const quarterParser = new _typeof6.QuarterParser();
obj[5] = quarterParser;
const standAloneQuarterParser = new _typeof7.StandAloneQuarterParser();
obj[6] = standAloneQuarterParser;
const monthParser = new _typeof8.MonthParser();
obj[7] = monthParser;
const standAloneMonthParser = new _typeof9.StandAloneMonthParser();
obj[8] = standAloneMonthParser;
const localWeekParser = new _typeof10.LocalWeekParser();
obj[9] = localWeekParser;
const iSOWeekParser = new _typeof11.ISOWeekParser();
obj[10] = iSOWeekParser;
const dateParser = new _typeof12.DateParser();
obj[11] = dateParser;
const dayOfYearParser = new _typeof13.DayOfYearParser();
obj[12] = dayOfYearParser;
const dayParser = new _typeof14.DayParser();
obj[13] = dayParser;
const localDayParser = new _typeof15.LocalDayParser();
obj[14] = localDayParser;
const standAloneLocalDayParser = new _typeof16.StandAloneLocalDayParser();
obj[15] = standAloneLocalDayParser;
const iSODayParser = new _typeof17.ISODayParser();
obj[16] = iSODayParser;
const aMPMParser = new _typeof18.AMPMParser();
obj[17] = aMPMParser;
const aMPMMidnightParser = new _typeof19.AMPMMidnightParser();
obj[18] = aMPMMidnightParser;
const dayPeriodParser = new _typeof20.DayPeriodParser();
obj[19] = dayPeriodParser;
const hour1to12Parser = new _typeof21.Hour1to12Parser();
obj[20] = hour1to12Parser;
const hour0to23Parser = new _typeof22.Hour0to23Parser();
obj[21] = hour0to23Parser;
const hour0To11Parser = new _typeof23.Hour0To11Parser();
obj[22] = hour0To11Parser;
const hour1To24Parser = new _typeof24.Hour1To24Parser();
obj[23] = hour1To24Parser;
const minuteParser = new _typeof25.MinuteParser();
obj[24] = minuteParser;
const secondParser = new _typeof26.SecondParser();
obj[25] = secondParser;
const fractionOfSecondParser = new _typeof27.FractionOfSecondParser();
obj[26] = fractionOfSecondParser;
const iSOTimezoneWithZParser = new _typeof28.ISOTimezoneWithZParser();
obj[27] = iSOTimezoneWithZParser;
const iSOTimezoneParser = new _typeof29.ISOTimezoneParser();
obj[28] = iSOTimezoneParser;
const timestampSecondsParser = new _typeof30.TimestampSecondsParser();
obj[29] = timestampSecondsParser;
const timestampMillisecondsParser = new _typeof31.TimestampMillisecondsParser();
obj[30] = timestampMillisecondsParser;

export const parsers = obj;
