// Module ID: 6610
// Function ID: 6611
// Name: Circle
// Dependencies: [6611, 6635, 6637, 6639, 6641, 6643, 6647, 6649, 6650, 6652, 6653, 6654, 6655, 6656, 6661, 6666, 6657, 6667, 6663, 6665, 6668, 6659, 6669, 6670, 6671, 6672, 6673, 6674, 6676, 6621, 6678, 6680, 6682, 6686, 6688, 6691, 6693, 6695, 6697, 6698, 6700, 6702, 6703, 6705, 6709, 6706, 6711]

// Module 6610 (Circle)
import _isNativeReflectConstructDefault from "_isNativeReflectConstruct" /* 6611 */;
import _isNativeReflectConstructDefault2 from "_isNativeReflectConstruct" /* 6621 */;
import _isNativeReflectConstructDefault3 from "_isNativeReflectConstruct" /* 6635 */;
import _isNativeReflectConstructDefault4 from "_isNativeReflectConstruct" /* 6637 */;
import _isNativeReflectConstructDefault5 from "_isNativeReflectConstruct" /* 6639 */;
import _isNativeReflectConstructDefault6 from "_isNativeReflectConstruct" /* 6641 */;
import _isNativeReflectConstructDefault7 from "_isNativeReflectConstruct" /* 6643 */;
import _isNativeReflectConstructDefault8 from "_isNativeReflectConstruct" /* 6647 */;
import _isNativeReflectConstructDefault9 from "_isNativeReflectConstruct" /* 6649 */;
import _isNativeReflectConstructDefault10 from "_isNativeReflectConstruct" /* 6650 */;
import _isNativeReflectConstructDefault11 from "_isNativeReflectConstruct" /* 6652 */;
import _isNativeReflectConstructDefault12 from "_isNativeReflectConstruct" /* 6653 */;
import _isNativeReflectConstructDefault13 from "_isNativeReflectConstruct" /* 6654 */;
import _isNativeReflectConstructDefault14 from "_isNativeReflectConstruct" /* 6655 */;
import _isNativeReflectConstructDefault15 from "_isNativeReflectConstruct" /* 6656 */;
import _isNativeReflectConstructDefault16 from "_isNativeReflectConstruct" /* 6657 */;
import _isNativeReflectConstructDefault17 from "_isNativeReflectConstruct" /* 6659 */;
import _isNativeReflectConstructDefault18 from "_isNativeReflectConstruct" /* 6661 */;
import _isNativeReflectConstructDefault19 from "_isNativeReflectConstruct" /* 6663 */;
import _isNativeReflectConstructDefault20 from "_isNativeReflectConstruct" /* 6665 */;
import _isNativeReflectConstructDefault21 from "_isNativeReflectConstruct" /* 6667 */;
import _isNativeReflectConstructDefault22 from "_isNativeReflectConstruct" /* 6668 */;
import _isNativeReflectConstructDefault23 from "_isNativeReflectConstruct" /* 6669 */;
import _isNativeReflectConstructDefault24 from "_isNativeReflectConstruct" /* 6670 */;
import _isNativeReflectConstructDefault25 from "_isNativeReflectConstruct" /* 6671 */;
import _isNativeReflectConstructDefault26 from "_isNativeReflectConstruct" /* 6672 */;
import _isNativeReflectConstructDefault27 from "_isNativeReflectConstruct" /* 6673 */;
import _isNativeReflectConstructDefault28 from "_isNativeReflectConstruct" /* 6674 */;
import _isNativeReflectConstructDefault29 from "_isNativeReflectConstruct" /* 6676 */;
import _isNativeReflectConstructDefault30 from "_isNativeReflectConstruct" /* 6678 */;
import _isNativeReflectConstructDefault31 from "_isNativeReflectConstruct" /* 6680 */;
import _isNativeReflectConstructDefault32 from "_isNativeReflectConstruct" /* 6682 */;
import _isNativeReflectConstructDefault33 from "_isNativeReflectConstruct" /* 6686 */;
import _isNativeReflectConstructDefault34 from "_isNativeReflectConstruct" /* 6688 */;
import _isNativeReflectConstructDefault35 from "_isNativeReflectConstruct" /* 6691 */;
import _isNativeReflectConstructDefault36 from "_isNativeReflectConstruct" /* 6693 */;
import _isNativeReflectConstructDefault37 from "_isNativeReflectConstruct" /* 6695 */;
import _isNativeReflectConstructDefault38 from "_isNativeReflectConstruct" /* 6697 */;
import _isNativeReflectConstructDefault39 from "_isNativeReflectConstruct" /* 6698 */;
import _isNativeReflectConstructDefault40 from "_isNativeReflectConstruct" /* 6700 */;
import _isNativeReflectConstructDefault41 from "_isNativeReflectConstruct" /* 6702 */;
import _isNativeReflectConstructDefault42 from "_isNativeReflectConstruct" /* 6703 */;
import _isNativeReflectConstructDefault43 from "_isNativeReflectConstruct" /* 6705 */;
import _isNativeReflectConstructDefault44 from "_isNativeReflectConstruct" /* 6706 */;
import _isNativeReflectConstructDefault45 from "_isNativeReflectConstruct" /* 6709 */;
import _isNativeReflectConstructDefault46 from "_isNativeReflectConstruct" /* 6711 */;


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;
