// Module ID: 7658
// Function ID: 7659
// Name: registerSpanErrorInstrumentation
// Dependencies: [7659, 7692, 7693, 7694, 7704, 7696, 7680, 7697, 7699, 7705, 7702, 7701, 7678, 7706, 7711, 7690, 7689, 7682, 7681, 7686, 7716, 7684, 7714, 7717, 7718, 7722, 7725, 7726, 7729, 7730, 7719, 7713, 7712, 7724, 7695, 7731, 7698, 7732, 7668, 7703, 7733, 7734, 7735, 7700, 7736, 7737, 7738, 7739, 7741, 7743, 7748, 7751, 7752, 7753, 7754, 7756, 7757, 7758, 7759, 7761, 7762, 7767, 7679, 7768, 7769, 7770, 7771, 7740, 7772, 7773, 7671, 7710, 7720, 7664, 7749, 7774, 7660, 7667, 7661, 7670, 7776, 7663, 7709, 7674, 7777, 7708, 7669, 7755, 7727, 7744, 7750, 7666, 7779, 7672, 7775, 7687, 7677, 7675, 7778, 7707, 7721, 7728, 7676, 7745, 7780, 7723, 7781, 7782, 7673, 7783, 7665, 7715, 7784, 7785, 7786, 7788, 7789, 7787, 7790, 7791]

// Module 7658 (registerSpanErrorInstrumentation)
import errorCallback from "errorCallback" /* 7659 */;
import instrumentError from "instrumentError" /* 7660 */;
import addHandler from "addHandler" /* 7661 */;
import consoleSandbox from "consoleSandbox" /* 7663 */;
import getGlobalSingleton from "getGlobalSingleton" /* 7664 */;
import _mod7665 from "module_7665" /* 7665 */;
import createStackParser from "createStackParser" /* 7666 */;
import instrumentUnhandledRejection from "instrumentUnhandledRejection" /* 7667 */;
import spanTimeInputToSeconds from "spanTimeInputToSeconds" /* 7668 */;
import addNonEnumerableProperty from "addNonEnumerableProperty" /* 7669 */;
import isInstanceOf from "isInstanceOf" /* 7670 */;
import _htmlElementAsString from "_htmlElementAsString" /* 7671 */;
import isMatchingPattern from "isMatchingPattern" /* 7672 */;
import generatePropagationContext from "generatePropagationContext" /* 7673 */;
import addContextToFrame from "addContextToFrame" /* 7674 */;
import regExp from "regExp" /* 7675 */;
import baggageHeaderToDynamicSamplingContext from "baggageHeaderToDynamicSamplingContext" /* 7676 */;
import _mod7678 from "module_7678" /* 7678 */;
import getMetricSummaryJsonForSpan from "getMetricSummaryJsonForSpan" /* 7679 */;
import getSpanStatusFromHttpCode from "getSpanStatusFromHttpCode" /* 7680 */;
import getMainCarrier from "getMainCarrier" /* 7681 */;
import getAsyncContextStrategy from "getAsyncContextStrategy" /* 7682 */;
import ScopeClass from "ScopeClass" /* 7684 */;
import updateSession from "updateSession" /* 7686 */;
import SyncPromise from "SyncPromise" /* 7687 */;
import getDefaultCurrentScope from "getDefaultCurrentScope" /* 7689 */;
import getClient from "getClient" /* 7690 */;
import getCapturedScopesOnSpan from "getCapturedScopesOnSpan" /* 7692 */;
import addTracingExtensions from "addTracingExtensions" /* 7693 */;
import TRACING_DEFAULTS from "TRACING_DEFAULTS" /* 7694 */;
import hasTracingEnabled from "hasTracingEnabled" /* 7695 */;
import SentryNonRecordingSpan from "SentryNonRecordingSpan" /* 7696 */;
import createChildOrRootSpan from "createChildOrRootSpan" /* 7697 */;
import handleCallbackErrors from "handleCallbackErrors" /* 7698 */;
import getDynamicSamplingContextFromSpan from "getDynamicSamplingContextFromSpan" /* 7699 */;
import _mod7700 from "module_7700" /* 7700 */;
import logSpanEnd from "logSpanEnd" /* 7701 */;
import sampleSpan from "sampleSpan" /* 7702 */;
import parseSampleRate from "parseSampleRate" /* 7703 */;
import isFullFinishedSpan from "isFullFinishedSpan" /* 7704 */;
import setMeasurement from "setMeasurement" /* 7705 */;
import createEventEnvelope from "createEventEnvelope" /* 7706 */;
import forEachEnvelopeItem from "forEachEnvelopeItem" /* 7707 */;
import normalize from "normalize" /* 7708 */;
import memoBuilder from "memoBuilder" /* 7709 */;
import dsnFromString from "dsnFromString" /* 7710 */;
import _flush from "_flush" /* 7711 */;
import applyClientOptions from "applyClientOptions" /* 7712 */;
import applyScopeDataToEvent from "applyScopeDataToEvent" /* 7713 */;
import notifyEventProcessors from "notifyEventProcessors" /* 7714 */;
import getFilenameToDebugIdMap from "getFilenameToDebugIdMap" /* 7715 */;
import SessionFlusher from "SessionFlusher" /* 7716 */;
import getEnvelopeEndpointWithUrlEncodedAuth from "getEnvelopeEndpointWithUrlEncodedAuth" /* 7717 */;
import isErrorEvent from "isErrorEvent" /* 7718 */;
import setupIntegration from "setupIntegration" /* 7719 */;
import _isNativeReflectConstruct from "_isNativeReflectConstruct" /* 7720 */;
import createClientReportEnvelope from "createClientReportEnvelope" /* 7721 */;
import _isNativeReflectConstruct2 from "_isNativeReflectConstruct" /* 7722 */;
import eventFromMessage from "eventFromMessage" /* 7723 */;
import createCheckInEnvelope from "createCheckInEnvelope" /* 7724 */;
import initAndBind from "initAndBind" /* 7725 */;
import createTransport from "createTransport" /* 7726 */;
import makePromiseBuffer from "makePromiseBuffer" /* 7727 */;
import parseRetryAfterHeader from "parseRetryAfterHeader" /* 7728 */;
import MIN_DELAY from "MIN_DELAY" /* 7729 */;
import eventFromEnvelope from "eventFromEnvelope" /* 7730 */;
import isSentryRequestUrl from "isSentryRequestUrl" /* 7731 */;
import parameterize from "parameterize" /* 7732 */;
import applySdkMetadata from "applySdkMetadata" /* 7733 */;
import getTraceData from "getTraceData" /* 7734 */;
import getTraceMetaTags from "getTraceMetaTags" /* 7735 */;
import addBreadcrumb from "addBreadcrumb" /* 7736 */;
import weakMap from "weakMap" /* 7737 */;
import _getEventFilterUrl from "_getEventFilterUrl" /* 7738 */;
import linkedErrorsIntegration from "linkedErrorsIntegration" /* 7739 */;
import aggregateExceptionsFromError from "aggregateExceptionsFromError" /* 7740 */;
import moduleMetadataIntegration from "moduleMetadataIntegration" /* 7741 */;
import requestDataIntegration from "requestDataIntegration" /* 7743 */;
import extractRequestData from "extractRequestData" /* 7744 */;
import getNumberOfUrlSegments from "getNumberOfUrlSegments" /* 7745 */;
import captureConsoleIntegration from "captureConsoleIntegration" /* 7748 */;
import instrumentConsole from "instrumentConsole" /* 7749 */;
import severityLevelFromString from "severityLevelFromString" /* 7750 */;
import debugIntegration from "debugIntegration" /* 7751 */;
import _shouldDropEvent from "_shouldDropEvent" /* 7752 */;
import extraErrorDataIntegration from "extraErrorDataIntegration" /* 7753 */;
import generateIteratee from "generateIteratee" /* 7754 */;
import resolve from "resolve" /* 7755 */;
import sessionTimingIntegration from "sessionTimingIntegration" /* 7756 */;
import flattenIssue from "flattenIssue" /* 7757 */;
import thirdPartyErrorFilterIntegration from "thirdPartyErrorFilterIntegration" /* 7758 */;
import addToMetricsAggregator from "addToMetricsAggregator" /* 7759 */;
import _mod7761 from "module_7761" /* 7761 */;
import addToMetricsAggregator2 from "addToMetricsAggregator" /* 7762 */;
import BrowserMetricsAggregator from "BrowserMetricsAggregator" /* 7767 */;
import _addTracingHeadersToFetchRequest from "_addTracingHeadersToFetchRequest" /* 7768 */;
import trpcMiddleware from "trpcMiddleware" /* 7769 */;
import captureFeedback from "captureFeedback" /* 7770 */;
import getCurrentHubShim from "getCurrentHubShim" /* 7771 */;
import flatten from "flatten" /* 7772 */;
import getBreadcrumbLogLevelFromHttpStatusCode from "getBreadcrumbLogLevelFromHttpStatusCode" /* 7773 */;
import _resolveResponse from "_resolveResponse" /* 7774 */;
import supportsFetch from "supportsFetch" /* 7775 */;
import isBrowser from "isBrowser" /* 7776 */;
import dynamicRequire from "dynamicRequire" /* 7777 */;
import getSDKSource from "getSDKSource" /* 7778 */;
import filenameIsInApp from "filenameIsInApp" /* 7779 */;
import makeFifoCache from "makeFifoCache" /* 7780 */;
import callFrameToStackFrame from "callFrameToStackFrame" /* 7781 */;
import LRUMap from "LRUMap" /* 7782 */;
import vercelWaitUntil from "vercelWaitUntil" /* 7783 */;
import escapeStringForRegex from "escapeStringForRegex" /* 7784 */;
import supportsHistory from "supportsHistory" /* 7785 */;
import _asyncNullishCoalesce2 from "_asyncNullishCoalesce2" /* 7786 */;
import _nullishCoalesce from "_nullishCoalesce" /* 7787 */;
import _asyncOptionalChain2 from "_asyncOptionalChain2" /* 7788 */;
import _asyncOptionalChainDelete2 from "_asyncOptionalChainDelete2" /* 7789 */;
import _optionalChain from "_optionalChain" /* 7790 */;
import _optionalChainDelete from "_optionalChainDelete" /* 7791 */;


export const registerSpanErrorInstrumentation = errorCallback.registerSpanErrorInstrumentation;
export const getCapturedScopesOnSpan = getCapturedScopesOnSpan.getCapturedScopesOnSpan;
export const setCapturedScopesOnSpan = getCapturedScopesOnSpan.setCapturedScopesOnSpan;
export const addTracingExtensions = addTracingExtensions.addTracingExtensions;
export const TRACING_DEFAULTS = TRACING_DEFAULTS.TRACING_DEFAULTS;
export const startIdleSpan = TRACING_DEFAULTS.startIdleSpan;
export const SentrySpan = isFullFinishedSpan.SentrySpan;
export const SentryNonRecordingSpan = SentryNonRecordingSpan.SentryNonRecordingSpan;
export const SPAN_STATUS_ERROR = getSpanStatusFromHttpCode.SPAN_STATUS_ERROR;
export const SPAN_STATUS_OK = getSpanStatusFromHttpCode.SPAN_STATUS_OK;
export const SPAN_STATUS_UNSET = getSpanStatusFromHttpCode.SPAN_STATUS_UNSET;
export const getSpanStatusFromHttpCode = getSpanStatusFromHttpCode.getSpanStatusFromHttpCode;
export const setHttpStatus = getSpanStatusFromHttpCode.setHttpStatus;
export const continueTrace = createChildOrRootSpan.continueTrace;
export const startInactiveSpan = createChildOrRootSpan.startInactiveSpan;
export const startNewTrace = createChildOrRootSpan.startNewTrace;
export const startSpan = createChildOrRootSpan.startSpan;
export const startSpanManual = createChildOrRootSpan.startSpanManual;
export const suppressTracing = createChildOrRootSpan.suppressTracing;
export const withActiveSpan = createChildOrRootSpan.withActiveSpan;
export const getDynamicSamplingContextFromClient = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromClient;
export const getDynamicSamplingContextFromScope = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromScope;
export const getDynamicSamplingContextFromSpan = getDynamicSamplingContextFromSpan.getDynamicSamplingContextFromSpan;
export const spanToBaggageHeader = getDynamicSamplingContextFromSpan.spanToBaggageHeader;
export const setMeasurement = setMeasurement.setMeasurement;
export const timedEventsToMeasurements = setMeasurement.timedEventsToMeasurements;
export const sampleSpan = sampleSpan.sampleSpan;
export const logSpanEnd = logSpanEnd.logSpanEnd;
export const logSpanStart = logSpanEnd.logSpanStart;
export const SEMANTIC_ATTRIBUTE_CACHE_HIT = _mod7678.SEMANTIC_ATTRIBUTE_CACHE_HIT;
export const SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE = _mod7678.SEMANTIC_ATTRIBUTE_CACHE_ITEM_SIZE;
export const SEMANTIC_ATTRIBUTE_CACHE_KEY = _mod7678.SEMANTIC_ATTRIBUTE_CACHE_KEY;
export const SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME = _mod7678.SEMANTIC_ATTRIBUTE_EXCLUSIVE_TIME;
export const SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD = _mod7678.SEMANTIC_ATTRIBUTE_HTTP_REQUEST_METHOD;
export const SEMANTIC_ATTRIBUTE_PROFILE_ID = _mod7678.SEMANTIC_ATTRIBUTE_PROFILE_ID;
export const SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_CUSTOM_SPAN_NAME;
export const SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_IDLE_SPAN_FINISH_REASON;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_UNIT;
export const SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_MEASUREMENT_VALUE;
export const SEMANTIC_ATTRIBUTE_SENTRY_OP = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_OP;
export const SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_ORIGIN;
export const SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_SAMPLE_RATE;
export const SEMANTIC_ATTRIBUTE_SENTRY_SOURCE = _mod7678.SEMANTIC_ATTRIBUTE_SENTRY_SOURCE;
export const SEMANTIC_ATTRIBUTE_URL_FULL = _mod7678.SEMANTIC_ATTRIBUTE_URL_FULL;
export const createEventEnvelope = createEventEnvelope.createEventEnvelope;
export const createSessionEnvelope = createEventEnvelope.createSessionEnvelope;
export const createSpanEnvelope = createEventEnvelope.createSpanEnvelope;
export const addEventProcessor = _flush.addEventProcessor;
export const captureCheckIn = _flush.captureCheckIn;
export const captureEvent = _flush.captureEvent;
export const captureException = _flush.captureException;
export const captureMessage = _flush.captureMessage;
export const captureSession = _flush.captureSession;
export const close = _flush.close;
export const endSession = _flush.endSession;
export const flush = _flush.flush;
export const isEnabled = _flush.isEnabled;
export const isInitialized = _flush.isInitialized;
export const lastEventId = _flush.lastEventId;
export const setContext = _flush.setContext;
export const setExtra = _flush.setExtra;
export const setExtras = _flush.setExtras;
export const setTag = _flush.setTag;
export const setTags = _flush.setTags;
export const setUser = _flush.setUser;
export const startSession = _flush.startSession;
export const withMonitor = _flush.withMonitor;
export const getClient = getClient.getClient;
export const getCurrentScope = getClient.getCurrentScope;
export const getGlobalScope = getClient.getGlobalScope;
export const getIsolationScope = getClient.getIsolationScope;
export const getTraceContextFromScope = getClient.getTraceContextFromScope;
export const withIsolationScope = getClient.withIsolationScope;
export const withScope = getClient.withScope;
export const getDefaultCurrentScope = getDefaultCurrentScope.getDefaultCurrentScope;
export const getDefaultIsolationScope = getDefaultCurrentScope.getDefaultIsolationScope;
export const setAsyncContextStrategy = getAsyncContextStrategy.setAsyncContextStrategy;
export const getMainCarrier = getMainCarrier.getMainCarrier;
export const closeSession = updateSession.closeSession;
export const makeSession = updateSession.makeSession;
export const updateSession = updateSession.updateSession;
export const SessionFlusher = SessionFlusher.SessionFlusher;
export const Scope = ScopeClass.Scope;
export const notifyEventProcessors = notifyEventProcessors.notifyEventProcessors;
export const getEnvelopeEndpointWithUrlEncodedAuth = getEnvelopeEndpointWithUrlEncodedAuth.getEnvelopeEndpointWithUrlEncodedAuth;
export const getReportDialogEndpoint = getEnvelopeEndpointWithUrlEncodedAuth.getReportDialogEndpoint;
export const BaseClient = isErrorEvent.BaseClient;
export const ServerRuntimeClient = _isNativeReflectConstruct2.ServerRuntimeClient;
export const initAndBind = initAndBind.initAndBind;
export const setCurrentClient = initAndBind.setCurrentClient;
export const createTransport = createTransport.createTransport;
export const makeOfflineTransport = MIN_DELAY.makeOfflineTransport;
export const makeMultiplexedTransport = eventFromEnvelope.makeMultiplexedTransport;
export const addIntegration = setupIntegration.addIntegration;
export const defineIntegration = setupIntegration.defineIntegration;
export const getIntegrationsToSetup = setupIntegration.getIntegrationsToSetup;
export const applyScopeDataToEvent = applyScopeDataToEvent.applyScopeDataToEvent;
export const mergeScopeData = applyScopeDataToEvent.mergeScopeData;
export const prepareEvent = applyClientOptions.prepareEvent;
export const createCheckInEnvelope = createCheckInEnvelope.createCheckInEnvelope;
export const hasTracingEnabled = hasTracingEnabled.hasTracingEnabled;
export const isSentryRequestUrl = isSentryRequestUrl.isSentryRequestUrl;
export const handleCallbackErrors = handleCallbackErrors.handleCallbackErrors;
export const parameterize = parameterize.parameterize;
export const addChildSpanToSpan = spanTimeInputToSeconds.addChildSpanToSpan;
export const getActiveSpan = spanTimeInputToSeconds.getActiveSpan;
export const getRootSpan = spanTimeInputToSeconds.getRootSpan;
export const getSpanDescendants = spanTimeInputToSeconds.getSpanDescendants;
export const getStatusMessage = spanTimeInputToSeconds.getStatusMessage;
export const spanIsSampled = spanTimeInputToSeconds.spanIsSampled;
export const spanTimeInputToSeconds = spanTimeInputToSeconds.spanTimeInputToSeconds;
export const spanToJSON = spanTimeInputToSeconds.spanToJSON;
export const spanToTraceContext = spanTimeInputToSeconds.spanToTraceContext;
export const spanToTraceHeader = spanTimeInputToSeconds.spanToTraceHeader;
export const updateSpanName = spanTimeInputToSeconds.updateSpanName;
export const parseSampleRate = parseSampleRate.parseSampleRate;
export const applySdkMetadata = applySdkMetadata.applySdkMetadata;
export const getTraceData = getTraceData.getTraceData;
export const getTraceMetaTags = getTraceMetaTags.getTraceMetaTags;
export const DEFAULT_ENVIRONMENT = _mod7700.DEFAULT_ENVIRONMENT;
export const addBreadcrumb = addBreadcrumb.addBreadcrumb;
export const functionToStringIntegration = weakMap.functionToStringIntegration;
export const inboundFiltersIntegration = _getEventFilterUrl.inboundFiltersIntegration;
export const linkedErrorsIntegration = linkedErrorsIntegration.linkedErrorsIntegration;
export const moduleMetadataIntegration = moduleMetadataIntegration.moduleMetadataIntegration;
export const requestDataIntegration = requestDataIntegration.requestDataIntegration;
export const captureConsoleIntegration = captureConsoleIntegration.captureConsoleIntegration;
export const debugIntegration = debugIntegration.debugIntegration;
export const dedupeIntegration = _shouldDropEvent.dedupeIntegration;
export const extraErrorDataIntegration = extraErrorDataIntegration.extraErrorDataIntegration;
export const rewriteFramesIntegration = generateIteratee.rewriteFramesIntegration;
export const sessionTimingIntegration = sessionTimingIntegration.sessionTimingIntegration;
export const zodErrorsIntegration = flattenIssue.zodErrorsIntegration;
export const thirdPartyErrorFilterIntegration = thirdPartyErrorFilterIntegration.thirdPartyErrorFilterIntegration;
export const metrics = addToMetricsAggregator.metrics;
export const profiler = _mod7761.profiler;
export const metricsDefault = addToMetricsAggregator2.metricsDefault;
export const BrowserMetricsAggregator = BrowserMetricsAggregator.BrowserMetricsAggregator;
export const getMetricSummaryJsonForSpan = getMetricSummaryJsonForSpan.getMetricSummaryJsonForSpan;
export const addTracingHeadersToFetchRequest = _addTracingHeadersToFetchRequest.addTracingHeadersToFetchRequest;
export const instrumentFetchRequest = _addTracingHeadersToFetchRequest.instrumentFetchRequest;
export const trpcMiddleware = trpcMiddleware.trpcMiddleware;
export const captureFeedback = captureFeedback.captureFeedback;
export const getCurrentHub = getCurrentHubShim.getCurrentHub;
export const getCurrentHubShim = getCurrentHubShim.getCurrentHubShim;
export const applyAggregateErrorsToEvent = aggregateExceptionsFromError.applyAggregateErrorsToEvent;
export const flatten = flatten.flatten;
export const getBreadcrumbLogLevelFromHttpStatusCode = getBreadcrumbLogLevelFromHttpStatusCode.getBreadcrumbLogLevelFromHttpStatusCode;
export const getComponentName = _htmlElementAsString.getComponentName;
export const getDomElement = _htmlElementAsString.getDomElement;
export const getLocationHref = _htmlElementAsString.getLocationHref;
export const htmlTreeAsString = _htmlElementAsString.htmlTreeAsString;
export const dsnFromString = dsnFromString.dsnFromString;
export const dsnToString = dsnFromString.dsnToString;
export const makeDsn = dsnFromString.makeDsn;
export const SentryError = _isNativeReflectConstruct.SentryError;
export const GLOBAL_OBJ = getGlobalSingleton.GLOBAL_OBJ;
export const getGlobalSingleton = getGlobalSingleton.getGlobalSingleton;
export const addConsoleInstrumentationHandler = instrumentConsole.addConsoleInstrumentationHandler;
export const addFetchEndInstrumentationHandler = _resolveResponse.addFetchEndInstrumentationHandler;
export const addFetchInstrumentationHandler = _resolveResponse.addFetchInstrumentationHandler;
export const addGlobalErrorInstrumentationHandler = instrumentError.addGlobalErrorInstrumentationHandler;
export const addGlobalUnhandledRejectionInstrumentationHandler = instrumentUnhandledRejection.addGlobalUnhandledRejectionInstrumentationHandler;
export const addHandler = addHandler.addHandler;
export const maybeInstrument = addHandler.maybeInstrument;
export const resetInstrumentationHandlers = addHandler.resetInstrumentationHandlers;
export const triggerHandlers = addHandler.triggerHandlers;
export const isDOMError = isInstanceOf.isDOMError;
export const isDOMException = isInstanceOf.isDOMException;
export const isElement = isInstanceOf.isElement;
export const isError = isInstanceOf.isError;
export const isErrorEvent = isInstanceOf.isErrorEvent;
export const isEvent = isInstanceOf.isEvent;
export const isInstanceOf = isInstanceOf.isInstanceOf;
export const isParameterizedString = isInstanceOf.isParameterizedString;
export const isPlainObject = isInstanceOf.isPlainObject;
export const isPrimitive = isInstanceOf.isPrimitive;
export const isRegExp = isInstanceOf.isRegExp;
export const isString = isInstanceOf.isString;
export const isSyntheticEvent = isInstanceOf.isSyntheticEvent;
export const isThenable = isInstanceOf.isThenable;
export const isVueViewModel = isInstanceOf.isVueViewModel;
export const isBrowser = isBrowser.isBrowser;
export const CONSOLE_LEVELS = consoleSandbox.CONSOLE_LEVELS;
export const consoleSandbox = consoleSandbox.consoleSandbox;
export const logger = consoleSandbox.logger;
export const originalConsoleMethods = consoleSandbox.originalConsoleMethods;
export const memoBuilder = memoBuilder.memoBuilder;
export const addContextToFrame = addContextToFrame.addContextToFrame;
export const addExceptionMechanism = addContextToFrame.addExceptionMechanism;
export const addExceptionTypeValue = addContextToFrame.addExceptionTypeValue;
export const arrayify = addContextToFrame.arrayify;
export const checkOrSetAlreadyCaught = addContextToFrame.checkOrSetAlreadyCaught;
export const getEventDescription = addContextToFrame.getEventDescription;
export const parseSemver = addContextToFrame.parseSemver;
export const uuid4 = addContextToFrame.uuid4;
export const dynamicRequire = dynamicRequire.dynamicRequire;
export const isNodeEnv = dynamicRequire.isNodeEnv;
export const loadModule = dynamicRequire.loadModule;
export const normalize = normalize.normalize;
export const normalizeToSize = normalize.normalizeToSize;
export const normalizeUrlToBase = normalize.normalizeUrlToBase;
export const addNonEnumerableProperty = addNonEnumerableProperty.addNonEnumerableProperty;
export const convertToPlainObject = addNonEnumerableProperty.convertToPlainObject;
export const dropUndefinedKeys = addNonEnumerableProperty.dropUndefinedKeys;
export const extractExceptionKeysForMessage = addNonEnumerableProperty.extractExceptionKeysForMessage;
export const fill = addNonEnumerableProperty.fill;
export const getOriginalFunction = addNonEnumerableProperty.getOriginalFunction;
export const markFunctionWrapped = addNonEnumerableProperty.markFunctionWrapped;
export const objectify = addNonEnumerableProperty.objectify;
export const urlEncode = addNonEnumerableProperty.urlEncode;
export const basename = resolve.basename;
export const dirname = resolve.dirname;
export const isAbsolute = resolve.isAbsolute;
export const join = resolve.join;
export const normalizePath = resolve.normalizePath;
export const relative = resolve.relative;
export const resolve = resolve.resolve;
export const makePromiseBuffer = makePromiseBuffer.makePromiseBuffer;
export const DEFAULT_USER_INCLUDES = extractRequestData.DEFAULT_USER_INCLUDES;
export const addNormalizedRequestDataToEvent = extractRequestData.addNormalizedRequestDataToEvent;
export const addRequestDataToEvent = extractRequestData.addRequestDataToEvent;
export const extractPathForTransaction = extractRequestData.extractPathForTransaction;
export const extractQueryParamsFromUrl = extractRequestData.extractQueryParamsFromUrl;
export const extractRequestData = extractRequestData.extractRequestData;
export const headersToDict = extractRequestData.headersToDict;
export const httpRequestToRequestData = extractRequestData.httpRequestToRequestData;
export const winterCGHeadersToDict = extractRequestData.winterCGHeadersToDict;
export const winterCGRequestToRequestData = extractRequestData.winterCGRequestToRequestData;
export const severityLevelFromString = severityLevelFromString.severityLevelFromString;
export const validSeverityLevels = severityLevelFromString.validSeverityLevels;
export const UNKNOWN_FUNCTION = createStackParser.UNKNOWN_FUNCTION;
export const createStackParser = createStackParser.createStackParser;
export const getFramesFromEvent = createStackParser.getFramesFromEvent;
export const getFunctionName = createStackParser.getFunctionName;
export const stackParserFromStackParserOptions = createStackParser.stackParserFromStackParserOptions;
export const stripSentryFramesAndReverse = createStackParser.stripSentryFramesAndReverse;
export const filenameIsInApp = filenameIsInApp.filenameIsInApp;
export const node = filenameIsInApp.node;
export const nodeStackLineParser = filenameIsInApp.nodeStackLineParser;
export const isMatchingPattern = isMatchingPattern.isMatchingPattern;
export const safeJoin = isMatchingPattern.safeJoin;
export const snipLine = isMatchingPattern.snipLine;
export const stringMatchesSomePattern = isMatchingPattern.stringMatchesSomePattern;
export const truncate = isMatchingPattern.truncate;
export const isNativeFunction = supportsFetch.isNativeFunction;
export const supportsDOMError = supportsFetch.supportsDOMError;
export const supportsDOMException = supportsFetch.supportsDOMException;
export const supportsErrorEvent = supportsFetch.supportsErrorEvent;
export const supportsFetch = supportsFetch.supportsFetch;
export const supportsNativeFetch = supportsFetch.supportsNativeFetch;
export const supportsReferrerPolicy = supportsFetch.supportsReferrerPolicy;
export const supportsReportingObserver = supportsFetch.supportsReportingObserver;
export const SyncPromise = SyncPromise.SyncPromise;
export const rejectedSyncPromise = SyncPromise.rejectedSyncPromise;
export const resolvedSyncPromise = SyncPromise.resolvedSyncPromise;
export const _browserPerformanceTimeOriginMode = require(7677) /* dateTimestampInSeconds */._browserPerformanceTimeOriginMode;
export const browserPerformanceTimeOrigin = require("dateTimestampInSeconds").browserPerformanceTimeOrigin;
export const dateTimestampInSeconds = require("dateTimestampInSeconds").dateTimestampInSeconds;
export const timestampInSeconds = require("dateTimestampInSeconds").timestampInSeconds;
export const TRACEPARENT_REGEXP = regExp.TRACEPARENT_REGEXP;
export const extractTraceparentData = regExp.extractTraceparentData;
export const generateSentryTraceHeader = regExp.generateSentryTraceHeader;
export const propagationContextFromHeaders = regExp.propagationContextFromHeaders;
export const getSDKSource = getSDKSource.getSDKSource;
export const isBrowserBundle = getSDKSource.isBrowserBundle;
export const addItemToEnvelope = forEachEnvelopeItem.addItemToEnvelope;
export const createAttachmentEnvelopeItem = forEachEnvelopeItem.createAttachmentEnvelopeItem;
export const createEnvelope = forEachEnvelopeItem.createEnvelope;
export const createEventEnvelopeHeaders = forEachEnvelopeItem.createEventEnvelopeHeaders;
export const createSpanEnvelopeItem = forEachEnvelopeItem.createSpanEnvelopeItem;
export const envelopeContainsItemType = forEachEnvelopeItem.envelopeContainsItemType;
export const envelopeItemTypeToDataCategory = forEachEnvelopeItem.envelopeItemTypeToDataCategory;
export const forEachEnvelopeItem = forEachEnvelopeItem.forEachEnvelopeItem;
export const getSdkMetadataForEnvelopeHeader = forEachEnvelopeItem.getSdkMetadataForEnvelopeHeader;
export const parseEnvelope = forEachEnvelopeItem.parseEnvelope;
export const serializeEnvelope = forEachEnvelopeItem.serializeEnvelope;
export const createClientReportEnvelope = createClientReportEnvelope.createClientReportEnvelope;
export const DEFAULT_RETRY_AFTER = parseRetryAfterHeader.DEFAULT_RETRY_AFTER;
export const disabledUntil = parseRetryAfterHeader.disabledUntil;
export const isRateLimited = parseRetryAfterHeader.isRateLimited;
export const parseRetryAfterHeader = parseRetryAfterHeader.parseRetryAfterHeader;
export const updateRateLimits = parseRetryAfterHeader.updateRateLimits;
export const BAGGAGE_HEADER_NAME = baggageHeaderToDynamicSamplingContext.BAGGAGE_HEADER_NAME;
export const MAX_BAGGAGE_STRING_LENGTH = baggageHeaderToDynamicSamplingContext.MAX_BAGGAGE_STRING_LENGTH;
export const SENTRY_BAGGAGE_KEY_PREFIX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX;
export const SENTRY_BAGGAGE_KEY_PREFIX_REGEX = baggageHeaderToDynamicSamplingContext.SENTRY_BAGGAGE_KEY_PREFIX_REGEX;
export const baggageHeaderToDynamicSamplingContext = baggageHeaderToDynamicSamplingContext.baggageHeaderToDynamicSamplingContext;
export const dynamicSamplingContextToSentryBaggageHeader = baggageHeaderToDynamicSamplingContext.dynamicSamplingContextToSentryBaggageHeader;
export const parseBaggageHeader = baggageHeaderToDynamicSamplingContext.parseBaggageHeader;
export const getNumberOfUrlSegments = getNumberOfUrlSegments.getNumberOfUrlSegments;
export const getSanitizedUrlString = getNumberOfUrlSegments.getSanitizedUrlString;
export const parseUrl = getNumberOfUrlSegments.parseUrl;
export const stripUrlQueryAndFragment = getNumberOfUrlSegments.stripUrlQueryAndFragment;
export const makeFifoCache = makeFifoCache.makeFifoCache;
export const eventFromMessage = eventFromMessage.eventFromMessage;
export const eventFromUnknownInput = eventFromMessage.eventFromUnknownInput;
export const exceptionFromError = eventFromMessage.exceptionFromError;
export const parseStackFrames = eventFromMessage.parseStackFrames;
export const callFrameToStackFrame = callFrameToStackFrame.callFrameToStackFrame;
export const watchdogTimer = callFrameToStackFrame.watchdogTimer;
export const LRUMap = LRUMap.LRUMap;
export const generatePropagationContext = generatePropagationContext.generatePropagationContext;
export const generateSpanId = generatePropagationContext.generateSpanId;
export const generateTraceId = generatePropagationContext.generateTraceId;
export const vercelWaitUntil = vercelWaitUntil.vercelWaitUntil;
export const SDK_VERSION = _mod7665.SDK_VERSION;
export const getDebugImagesForResources = getFilenameToDebugIdMap.getDebugImagesForResources;
export const getFilenameToDebugIdMap = getFilenameToDebugIdMap.getFilenameToDebugIdMap;
export const escapeStringForRegex = escapeStringForRegex.escapeStringForRegex;
export const supportsHistory = supportsHistory.supportsHistory;
export const _asyncNullishCoalesce = _asyncNullishCoalesce2._asyncNullishCoalesce;
export const _asyncOptionalChain = _asyncOptionalChain2._asyncOptionalChain;
export const _asyncOptionalChainDelete = _asyncOptionalChainDelete2._asyncOptionalChainDelete;
export const _nullishCoalesce = _nullishCoalesce._nullishCoalesce;
export const _optionalChain = _optionalChain._optionalChain;
export const _optionalChainDelete = _optionalChainDelete._optionalChainDelete;
