// Module ID: 5499
// Function ID: 5500
// Dependencies: []

// Module 5499
arg5.ActionType = { REANIMATED_WORKLET: 1, NATIVE_ANIMATED_EVENT: 2, JS_FUNCTION_OLD_API: 3, JS_FUNCTION_NEW_API: 4, NATIVE_DETECTOR: 5, VIRTUAL_DETECTOR: 6 };
