// Module ID: 16413
// Function ID: 16414
// Dependencies: []

// Module 16413
const obj = { VERIFIED: 0, [0]: "VERIFIED", SUPERVISED: 1, [1]: "SUPERVISED", SUPERVISED_APPROVAL_PENDING: 2, [2]: "SUPERVISED_APPROVAL_PENDING", SUPERVISED_APPROVAL_DENIED: 3, [3]: "SUPERVISED_APPROVAL_DENIED", UNKNOWN: 4, [4]: "UNKNOWN" };
arg5.PlayAgeRangeDeclarationUserStatus = obj;
arg5.PlayAgeRangeDeclarationUserStatusString = { [obj.VERIFIED]: "VERIFIED", [obj.SUPERVISED]: "SUPERVISED", [obj.SUPERVISED_APPROVAL_PENDING]: "SUPERVISED_APPROVAL_PENDING", [obj.SUPERVISED_APPROVAL_DENIED]: "SUPERVISED_APPROVAL_DENIED", [obj.UNKNOWN]: "UNKNOWN" };
