// Module ID: 8212
// Function ID: 64767
// Dependencies: [8202, 3955, 8198, 8213]

// Module 8212
import module_8202 from "module_8202";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";
import emptyFunction from "emptyFunction";

const items = ["phoneNumber", "link", "address", "calendarEvent", "none", "all"];
let obj = {};
obj.autoCapitalize = emptyFunction.oneOf(["none", "sentences", "words", "characters"]);
obj.autoCompleteType = emptyFunction.oneOf(["cc-csc", "cc-exp", "cc-exp-month", "cc-exp-year", "cc-number", "email", "name", "password", "postal-code", "street-address", "tel", "username", "off"]);
obj.autoCorrect = require("emptyFunction").bool;
obj.spellCheck = require("emptyFunction").bool;
obj.autoFocus = require("emptyFunction").bool;
obj.allowFontScaling = require("emptyFunction").bool;
obj.maxFontSizeMultiplier = require("emptyFunction").number;
obj.editable = require("emptyFunction").bool;
obj.keyboardType = emptyFunction.oneOf(["default", "email-address", "numeric", "phone-pad", "number-pad", "ascii-capable", "numbers-and-punctuation", "url", "name-phone-pad", "decimal-pad", "twitter", "web-search", "ascii-capable-number-pad", "visible-password"]);
obj.keyboardAppearance = emptyFunction.oneOf(["default", "light", "dark"]);
obj.returnKeyType = emptyFunction.oneOf(["done", "go", "next", "search", "send", "none", "previous", "default", "emergency-call", "google", "join", "route", "yahoo"]);
obj.returnKeyLabel = require("emptyFunction").string;
obj.maxLength = require("emptyFunction").number;
obj.numberOfLines = require("emptyFunction").number;
obj.disableFullscreenUI = require("emptyFunction").bool;
obj.enablesReturnKeyAutomatically = require("emptyFunction").bool;
obj.multiline = require("emptyFunction").bool;
obj.textBreakStrategy = emptyFunction.oneOf(["simple", "highQuality", "balanced"]);
obj.onBlur = require("emptyFunction").func;
obj.onFocus = require("emptyFunction").func;
obj.onChange = require("emptyFunction").func;
obj.onChangeText = require("emptyFunction").func;
obj.onContentSizeChange = require("emptyFunction").func;
obj.onTextInput = require("emptyFunction").func;
obj.onEndEditing = require("emptyFunction").func;
obj.onSelectionChange = require("emptyFunction").func;
obj.onSubmitEditing = require("emptyFunction").func;
obj.onKeyPress = require("emptyFunction").func;
obj.onLayout = require("emptyFunction").func;
obj.onScroll = require("emptyFunction").func;
obj.placeholder = require("emptyFunction").string;
obj.placeholderTextColor = require("colorPropType");
obj.scrollEnabled = require("emptyFunction").bool;
obj.secureTextEntry = require("emptyFunction").bool;
obj.selectionColor = require("colorPropType");
obj = { start: require("emptyFunction").number.isRequired, end: require("emptyFunction").number };
obj.selection = emptyFunction.shape(obj);
obj.value = require("emptyFunction").string;
obj.defaultValue = require("emptyFunction").string;
obj.clearButtonMode = emptyFunction.oneOf(["never", "while-editing", "unless-editing", "always"]);
obj.clearTextOnFocus = require("emptyFunction").bool;
obj.selectTextOnFocus = require("emptyFunction").bool;
obj.blurOnSubmit = require("emptyFunction").bool;
obj.style = require("module_8213").style;
obj.underlineColorAndroid = require("colorPropType");
obj.inlineImageLeft = require("emptyFunction").string;
obj.inlineImagePadding = require("emptyFunction").number;
obj.rejectResponderTermination = require("emptyFunction").bool;
const items1 = [emptyFunction.oneOf(items), ];
items1[1] = emptyFunction.arrayOf(emptyFunction.oneOf(items));
obj.dataDetectorTypes = emptyFunction.oneOfType(items1);
obj.caretHidden = require("emptyFunction").bool;
obj.contextMenuHidden = require("emptyFunction").bool;
obj.inputAccessoryViewID = require("emptyFunction").string;
obj.textContentType = emptyFunction.oneOf(["none", "URL", "addressCity", "addressCityAndState", "addressState", "countryName", "creditCardNumber", "emailAddress", "familyName", "fullStreetAddress", "givenName", "jobTitle", "location", "middleName", "name", "namePrefix", "nameSuffix", "nickname", "organizationName", "postalCode", "streetAddressLine1", "streetAddressLine2", "sublocality", "telephoneNumber", "username", "password", "newPassword", "oneTimeCode"]);
obj.showSoftInputOnFocus = require("emptyFunction").bool;

export default Object.assign({}, module_8202, obj);
