// Module ID: 4191
// Function ID: 36061
// Name: DesktopSources
// Dependencies: [2, 4192]

// Module 4191 (DesktopSources)
const result = require("set").fileFinishedImporting("../discord_common/js/packages/media-engine/Constants.tsx");

export const DesktopSources = require("_isNativeReflectConstruct").DesktopSources;
export const MediaEngineContextTypes = { DEFAULT: "default", STREAM: "stream" };
export const DeviceTypes = { AUDIO_INPUT: "audioinput", AUDIO_OUTPUT: "audiooutput", VIDEO_INPUT: "videoinput" };
export const InputModes = { PUSH_TO_TALK: "PUSH_TO_TALK", VOICE_ACTIVITY: "VOICE_ACTIVITY" };
export const ConnectionStates = { DISCONNECTED: "DISCONNECTED", CONNECTING: "CONNECTING", CONNECTED: "CONNECTED", NO_ROUTE: "NO_ROUTE", ICE_CHECKING: "ICE_CHECKING", DTLS_CONNECTING: "DTLS_CONNECTING" };
export const StatsFilter = { TRANSPORT: 1, [1]: "TRANSPORT", OUTBOUND: 2, [2]: "OUTBOUND", INBOUND: 4, [4]: "INBOUND", ALL: 7, [7]: "ALL" };
export const VideoToggleReason = { MANUAL_DISABLE: "video_manual_disable", MANUAL_ENABLE: "video_manual_enable", MANUAL_REENABLE: "video_manual_reenable", AUTO_DISABLE: "video_auto_disable", AUTO_ENABLE: "video_auto_enable", AUTO_DOWNGRADE: "video_auto_downgrade", AUTO_UPGRADE: "video_auto_upgrade," };
export const SimulcastOverrideQuality = { NO_OVERRIDE: "no_override", HIGH: "high", LOW: "low" };
export const DEFAULT_VOLUME = 100;
export const DEFAULT_STREAM_VOLUME = 18;
export const MAX_EMBEDDED_VOLUME_PERCEPTUAL = 200;
export const MAX_NON_EMBEDDED_VOLUME_PERCEPTUAL = 100;
export const DEFAULT_VOICE_BITRATE = 64000;
export const DEFAULT_SOUNDSHARE_VOICE_BITRATE = 128000;
export const DEFAULT_DEVICE_ID = "default";
export const DEFAULT_DEVICE_REGEX = /^Default/;
export const DISABLED_DEVICE_ID = "disabled";
export const DEFAULT_PAN = 50;
export const DEFAULT_PRIORITY_SPEAKER_DUCKING = 0.1;
export const SIDECHAIN_COMPRESSION_MIN_THRESHOLD = -40;
export const SIDECHAIN_COMPRESSION_MAX_THRESHOLD = -25;
export const SIDECHAIN_COMPRESSION_MIN_RATIO = 0.06666666666666667;
export const SIDECHAIN_COMPRESSION_MAX_RATIO = 0.8;
export const DEFAULT_CALL_BITRATE = 600000;
export const DEFAULT_CALL_MIN_BITRATE = 16000;
export const DEFAULT_CALL_MAX_BITRATE = 10000000;
export const PING_INTERVAL = 5000;
export const VIDEO_QUALITY_LOW_WIDTH = 640;
export const VIDEO_QUALITY_LOW_HEIGHT = 360;
export const VIDEO_QUALITY_LOW_MIN_BITRATE = 100000;
export const VIDEO_QUALITY_LOW_MAX_BITRATE = 625000;
export const VIDEO_QUALITY_FRAMRATE_NOT_SPEAKING_TIMEOUT = 15000;
export const VIDEO_QUALITY_FRAMERATE = 30;
export const VIDEO_QUALITY_FRAMERATE_MUTED = 20;
export const VIDEO_QUALITY_FRAMERATE_MUTED_2 = 12;
export const VIDEO_CAPTURE_FRAMERATE = 30;
export const SIMULCAST_HQ_QUALITY = 100;
export const SIMULCAST_LQ_QUALITY = 50;
export const VIDEO_QUALITY_GOLIVE_LQ_WIDTH = 1280;
export const VIDEO_QUALITY_GOLIVE_LQ_HEIGHT = 720;
export const VIDEO_QUALITY_GOLIVE_LQ_FRAMERATE = 30;
export const DESKTOP_LOW_QUALITY_STREAM_MAX_BITRATE = 1500000;
export const DESKTOP_LOW_QUALITY_STREAM_MIN_BITRATE = 500000;
export const DESKTOP_BITRATE = 3500000;
export const DESKTOP_BITRATE_ENHANCED = 9000000;
export const MEDIA_SINK_WANTS_PROPERTIES = ["remoteSinkWantsPixelCount", "remoteSinkWantsMaxFramerate", "encodingVideoMinBitRate", "encodingVideoMaxBitRate", "encodingVideoBitRate", "streamParameters"];
export const defaultVideoQualityOptions = { videoBudget: { width: 1280, height: 720, framerate: 30 }, videoCapture: { width: 1280, height: 720, framerate: 30 }, videoBitrate: { min: 150000, max: 2500000 }, desktopBitrate: { min: 500000, max: 3500000, target: 600000 }, videoBitrateFloor: 150000 };
export const BIT_FLOOR_PER_PIXEL = 0.02;
export const VideoHealthManagerConfig = { featureEnabled: true, windowLength: 5, allowedPoorFpsRatio: 1, fpsThreshold: 5, backoffTimeSec: 15 };
export const VIEWERSIDE_CLIP_KFI_MS = 60000;
export const DARWIN_H265_VERSION = ">=22.0.0";
export const QUEUE_METRICS_INTERVAL_MS = 900000;
export const Features = { AUTO_ENABLE: "AUTO_ENABLE", ATTENUATION: "ATTENUATION", AUDIO_INPUT_DEVICE: "AUDIO_INPUT_DEVICE", AUDIO_OUTPUT_DEVICE: "AUDIO_OUTPUT_DEVICE", VOICE_PROCESSING: "VOICE_PROCESSING", QOS: "QOS", NATIVE_PING: "NATIVE_PING", LEGACY_AUDIO_SUBSYSTEM: "LEGACY_AUDIO_SUBSYSTEM", EXPERIMENTAL_AUDIO_SUBSYSTEM: "EXPERIMENTAL_AUDIO_SUBSYSTEM", AUTOMATIC_AUDIO_SUBSYSTEM: "AUTOMATIC_AUDIO_SUBSYSTEM", AUDIO_SUBSYSTEM_DEFERRED_SWITCH: "AUDIO_SUBSYSTEM_DEFERRED_SWITCH", AUDIO_BYPASS_SYSTEM_INPUT_PROCESSING: "AUDIO_BYPASS_SYSTEM_INPUT_PROCESSING", DEBUG_LOGGING: "DEBUG_LOGGING", AUTOMATIC_VAD: "AUTOMATIC_VAD", VOICE_PANNING: "VOICE_PANNING", DIAGNOSTICS: "DIAGNOSTICS", VIDEO: "VIDEO", DESKTOP_CAPTURE: "DESKTOP_CAPTURE", DESKTOP_CAPTURE_FORMAT: "DESKTOP_CAPTURE_FORMAT", DESKTOP_CAPTURE_APPLICATIONS: "DESKTOP_CAPTURE_APPLICATIONS", SOUNDSHARE: "SOUNDSHARE", LOOPBACK: "LOOPBACK", VIDEO_HOOK: "VIDEO_HOOK", EXPERIMENTAL_SOUNDSHARE: "EXPERIMENTAL_SOUNDSHARE", WUMPUS_VIDEO: "WUMPUS_VIDEO", ELEVATED_HOOK: "ELEVATED_HOOK", HYBRID_VIDEO: "HYBRID_VIDEO", REMOTE_LOCUS_NETWORK_CONTROL: "REMOTE_LOCUS_NETWORK_CONTROL", SCREEN_PREVIEWS: "SCREEN_PREVIEWS", WINDOW_PREVIEWS: "WINDOW_PREVIEWS", AUDIO_DEBUG_STATE: "AUDIO_DEBUG_STATE", AEC_DUMP: "AEC_DUMP", DISABLE_VIDEO: "DISABLE_VIDEO", CONNECTION_REPLAY: "CONNECTION_REPLAY", SIMULCAST: "SIMULCAST", RTC_REGION_RANKING: "RTC_REGION_RANKING", ELECTRON_VIDEO: "ELECTRON_VIDEO", MEDIAPIPE: "MEDIAPIPE", FIXED_KEYFRAME_INTERVAL: "FIXED_KEYFRAME_INTERVAL", SAMPLE_PLAYBACK: "SAMPLE_PLAYBACK", FIRST_FRAME_CALLBACK: "FIRST_FRAME_CALLBACK", REMOTE_USER_MULTI_STREAM: "REMOTE_USER_MULTI_STREAM", NOISE_SUPPRESSION: "NOISE_SUPPRESSION", NOISE_CANCELLATION: "NOISE_CANCELLATION", AUTOMATIC_GAIN_CONTROL: "AUTOMATIC_GAIN_CONTROL", CLIPS: "CLIPS", CLIPS_RECORDING_READY_EVENTS: "CLIPS_RECORDING_READY_EVENTS", SPEED_TEST: "SPEED_TEST", IMAGE_QUALITY_MEASUREMENT: "IMAGE_QUALITY_MEASUREMENT", GO_LIVE_HARDWARE: "GO_LIVE_HARDWARE", SCREEN_CAPTURE_KIT: "SCREEN_CAPTURE_KIT", SCREEN_SOUNDSHARE: "SCREEN_SOUNDSHARE", NATIVE_SCREENSHARE_PICKER: "NATIVE_SCREENSHARE_PICKER", MLS_PAIRWISE_FINGERPRINTS: "MLS_PAIRWISE_FINGERPRINTS", OFFLOAD_ADM_CONTROLS: "OFFLOAD_ADM_CONTROLS", SIDECHAIN_COMPRESSION: "SIDECHAIN_COMPRESSION", VAAPI: "VAAPI", GAMESCOPE_CAPTURE: "GAMESCOPE_CAPTURE", ASYNC_VIDEO_INPUT_DEVICE_INIT: "ASYNC_VIDEO_INPUT_DEVICE_INIT", PORT_AWARE_LATENCY_TESTING: "PORT_AWARE_LATENCY_TESTING", SPATIAL_AUDIO: "SPATIAL_AUDIO", KRISP_NATIVE_ERROR: "KRISP_NATIVE_ERROR" };
export const MediaEngineImplementations = { NATIVE: "NATIVE", WEBRTC: "WEBRTC", DUMMY: "DUMMY" };
export const AudioSubsystems = { LEGACY: "legacy", STANDARD: "standard", EXPERIMENTAL: "experimental", AUTOMATIC: "automatic" };
export const Codecs = { OPUS: "opus", VP8: "VP8", VP9: "VP9", H264: "H264", H265: "H265", RTX: "rtx", TEST: "TEST" };
export const SpeakingFlags = { NONE: 0, [0]: "NONE", VOICE: 1, [1]: "VOICE", SOUNDSHARE: 2, [2]: "SOUNDSHARE", PRIORITY: 4, [4]: "PRIORITY", HIDDEN: 8, [8]: "HIDDEN" };
export const MediaTypes = { AUDIO: "audio", VIDEO: "video", SCREEN: "screen", TEST: "test" };
export const VideoStates = { PLAYING: "playing", PAUSED: "paused" };
export const ResolutionTypes = { FIXED: "fixed", SOURCE: "source" };
export const RTCPMessageTypes = { REMB: "remb" };
export const ExperimentFlags = { VIDEOTOOLBOX_RATE_CONTROL: "videotoolbox_rate_control", SIGNAL_AV1_ENCODE: "signal_av1_encode", SIGNAL_AV1_DECODE: "signal_av1_decode", SIGNAL_AV1_HARDWARE_DECODE: "signal_av1_hardware_decode", VIEWER_CLIP: "viewer_clip", RESET_DECODER_ON_ERRORS: "reset_decoder_on_errors", SOFTWARE_FALLBACK_ON_ERRORS: "software_fallback_on_errors", SOFTWARE_FALLBACK_ON_CONSECUTIVE_ERRORS: "software_fallback_on_consecutive_errors", BROWSER_HEVC: "browser_hevc", LOW_LATENCY_RATE_CONTROL: "low_latency_rate_control", H265_DISABLE_ENCODE: "h265_disable_encode", H265_HARDWARE_ONLY: "h265_hardware_only", H265_HARDWARE_DECODE_AVAILABLE: "h265_hardware_decode_available", WMF_GPU_ENCODE: "wmf_gpu_encode", USE_LIBOPENH264_DECODER: "use_libopenh264_decoder", SWALLOW_VOLUME_ONLY_SPEAKING_EVENTS: "swallow_volume_only_speaking_events", BROWSER_TRANSCEIVER_PADDING_REMOVAL: "browser_transceiver_padding_removal", INTEL_GPU_DISABLE: "intel_gpu_disable" };
export const VideoQualityMode = { AUTO: 1, [1]: "AUTO", FULL: 2, [2]: "FULL" };
export const NoiseCancellerError = { KRISP_CPU_OVERUSE: 1, [1]: "KRISP_CPU_OVERUSE", KRISP_FAILED: 2, [2]: "KRISP_FAILED", KRISP_VAD_CPU_OVERUSE: 3, [3]: "KRISP_VAD_CPU_OVERUSE", KRISP_INIT_ERROR: 4, [4]: "KRISP_INIT_ERROR", KRISP_INIT_ERROR_NATIVE: 5, [5]: "KRISP_INIT_ERROR_NATIVE", KRISP_INIT_ERROR_SSE4_NOT_SUPPORTED: -1, [-1]: "KRISP_INIT_ERROR_SSE4_NOT_SUPPORTED", KRISP_INIT_ERROR_AVX2_NOT_SUPPORTED: -2, [-2]: "KRISP_INIT_ERROR_AVX2_NOT_SUPPORTED", KRISP_INIT_ERROR_UNSIGNED: -3, [-3]: "KRISP_INIT_ERROR_UNSIGNED", KRISP_INIT_ERROR_GLOBAL_INIT: -4, [-4]: "KRISP_INIT_ERROR_GLOBAL_INIT", KRISP_INIT_ERROR_WEIGHT_8K: -5, [-5]: "KRISP_INIT_ERROR_WEIGHT_8K", KRISP_INIT_ERROR_WEIGHT_16K: -6, [-6]: "KRISP_INIT_ERROR_WEIGHT_16K", KRISP_INIT_ERROR_WEIGHT_32K: -7, [-7]: "KRISP_INIT_ERROR_WEIGHT_32K", KRISP_INIT_ERROR_WEIGHT_VAD: -8, [-8]: "KRISP_INIT_ERROR_WEIGHT_VAD" };
export const VideoFilterError = { INIT_FAILED: 1, [1]: "INIT_FAILED", UNSUPPORTED: 2, [2]: "UNSUPPORTED" };
export const VideoFilterTarget = { LIVE: 0, [0]: "LIVE", PREVIEW: 1, [1]: "PREVIEW" };
export const ProcessPriority = { LOW: 2, [2]: "LOW", BELOW_NORMAL: 1, [1]: "BELOW_NORMAL", NORMAL: 0, [0]: "NORMAL", ABOVE_NORMAL: -1, [-1]: "ABOVE_NORMAL", HIGH: -2, [-2]: "HIGH" };
